In [1]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.7.4"
    },
    "colab": {
      "name": "hyperparameter_Tuning_with_Python Mbuthia Project",
      "provenance": [],
      "collapsed_sections": [],
      "toc_visible": true
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "IcGUDoSkBiT4"
      },
      "source": [
        "# <font color='#2F4F4F'>1. Defining the Question</font>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "6sg3Sq-kBiT5"
      },
      "source": [
        "### a) Specifying the Data Analysis Question\n",
        "\n",
        "What is your research question? What problem is it that you are trying to solve?\n",
        "\n",
        "- Airbnb has tasked you to create to create a model that predicts their rental prices in Amsterdam City \n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "54AGppS1BiT6"
      },
      "source": [
        "### b) Defining the Metric for Success\n",
        "\n",
        "What will convince you that your project has succeeded?\n",
        "\n",
        "The solution will have satisfied the research question when the model can make optimal predictions for Airbnb rental prices \n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "In67Zlg2BiT7"
      },
      "source": [
        "### c) Understanding the Context \n",
        "\n",
        "The background information surrounding the problem or research question.\n",
        "\n",
        "Airbnb is an American vacation rental online marketplace company based in San\n",
        "Francisco, California, United States. Airbnb offers arrangement for lodging, primarily\n",
        "homestays, or tourism experiences. The company does not own any of the real estate\n",
        "listings, nor does it host events; it acts as a broker, receiving commissions from each\n",
        "booking.\n",
        "\n",
        "As a Data Scientist working for Airbnb, you have been tasked to create a model that\n",
        "predicts Airbnb rental prices for the city of Amsterdam. Popularity for Airbnbs in\n",
        "Amsterdam has grown over the past years and you are required to build a solution the\n",
        "would make optimal predictions.\n",
        "In this project, you will be required to perform feature engineering on your features and\n",
        "later hyperparameter tuning techniques to your most accurate model in an effort to\n",
        "achieve optimal predictions"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "VME7R5U9BiT8"
      },
      "source": [
        "### d) Recording the Experimental Design\n",
        "\n",
        "The steps you will take from the beginning to the end of this project.\n",
        "\n",
        "Defining the Research Question\n",
        "\n",
        "- Data Importation\n",
        "- Data Exploration\n",
        "- Data Cleaning\n",
        " Data Analysis (Univariate and Bivariate)\n",
        "- Data Preparation\n",
        "- Data Modeling\n",
        "- Model Evaluation\n",
        "- Challenging your Solution\n",
        "- Recommendations / Conclusion"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Ox4_7p-dBiT8"
      },
      "source": [
        "### e) Data Relevance\n",
        "\n",
        "The data provided was relevant to answering the research question."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "C8P0JbeUBiT9"
      },
      "source": [
        "# <font color='#2F4F4F'>2. Data Cleaning & Preparation</font>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 2.1 Data Preparation"
      ],
      "metadata": {
        "id": "jbPB9fonR1mI"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7i0Z1TaoBiT-"
      },
      "source": [
        "# loading libraries\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "pd.set_option('display.max.columns', None)\n",
        "pd.set_option('display.max_colwidth', None)\n",
        "%matplotlib inline"
      ],
      "execution_count": 62,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "scrolled": true,
        "id": "hrt1AegqBiUD",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 398
        },
        "outputId": "156495b9-e9c8-47d0-ee83-c19ea21c2dc9"
      },
      "source": [
        "# loading and previewing dataset\n",
        "\n",
        "df = pd.read_csv('https://bit.ly/31fkomB')\n",
        "df.sample(3)"
      ],
      "execution_count": 66,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-bba4df2b-7ad3-4149-84c5-6733650baf45\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id</th>\n",
              "      <th>name</th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood_group</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>reviews_per_month</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>10318</th>\n",
              "      <td>19704631</td>\n",
              "      <td>Romantic floating room 2</td>\n",
              "      <td>135998516</td>\n",
              "      <td>Ilonk</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.37167</td>\n",
              "      <td>4.88122</td>\n",
              "      <td>Private room</td>\n",
              "      <td>135</td>\n",
              "      <td>4</td>\n",
              "      <td>39</td>\n",
              "      <td>2019-11-01</td>\n",
              "      <td>1.26</td>\n",
              "      <td>2</td>\n",
              "      <td>107</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>18730</th>\n",
              "      <td>41636925</td>\n",
              "      <td>Spacious 4br design family house, central &amp; quiet</td>\n",
              "      <td>10426536</td>\n",
              "      <td>Michiel</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Geuzenveld - Slotermeer</td>\n",
              "      <td>52.38340</td>\n",
              "      <td>4.83122</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>175</td>\n",
              "      <td>4</td>\n",
              "      <td>0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>1</td>\n",
              "      <td>54</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>15943</th>\n",
              "      <td>33555115</td>\n",
              "      <td>Cozy sailboat in Amsterdam - sleep and sail</td>\n",
              "      <td>54965636</td>\n",
              "      <td>Karlijn</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Oostelijk Havengebied - Indische Buurt</td>\n",
              "      <td>52.37062</td>\n",
              "      <td>4.94348</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>95</td>\n",
              "      <td>2</td>\n",
              "      <td>8</td>\n",
              "      <td>2019-05-26</td>\n",
              "      <td>0.65</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-bba4df2b-7ad3-4149-84c5-6733650baf45')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-bba4df2b-7ad3-4149-84c5-6733650baf45 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-bba4df2b-7ad3-4149-84c5-6733650baf45');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "             id                                               name    host_id  \\\n",
              "10318  19704631                           Romantic floating room 2  135998516   \n",
              "18730  41636925  Spacious 4br design family house, central & quiet   10426536   \n",
              "15943  33555115        Cozy sailboat in Amsterdam - sleep and sail   54965636   \n",
              "\n",
              "      host_name  neighbourhood_group                           neighbourhood  \\\n",
              "10318     Ilonk                  NaN                            Centrum-West   \n",
              "18730   Michiel                  NaN                 Geuzenveld - Slotermeer   \n",
              "15943   Karlijn                  NaN  Oostelijk Havengebied - Indische Buurt   \n",
              "\n",
              "       latitude  longitude        room_type  price  minimum_nights  \\\n",
              "10318  52.37167    4.88122     Private room    135               4   \n",
              "18730  52.38340    4.83122  Entire home/apt    175               4   \n",
              "15943  52.37062    4.94348  Entire home/apt     95               2   \n",
              "\n",
              "       number_of_reviews last_review  reviews_per_month  \\\n",
              "10318                 39  2019-11-01               1.26   \n",
              "18730                  0         NaN                NaN   \n",
              "15943                  8  2019-05-26               0.65   \n",
              "\n",
              "       calculated_host_listings_count  availability_365  \n",
              "10318                               2               107  \n",
              "18730                               1                54  \n",
              "15943                               1                 0  "
            ]
          },
          "metadata": {},
          "execution_count": 66
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "8nHmaa4tBiUL",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 206
        },
        "outputId": "afe24a1b-9440-47e0-d19f-0d6927a81d7f"
      },
      "source": [
        "# loading glossary\n",
        "# glossary = pd.read_csv('Glossary - Sheet1 (1).csv', header = None)\n",
        "variables_definition = pd.read_csv('https://bit.ly/3klxdEn', header = None)\n",
        "variables_definition.head()"
      ],
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-67784f05-0905-4b5d-ae23-72d5fc7446d5\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>room_id: A unique number identifying an Airbnb listing.</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>host_id: A unique number identifying an Airbnb host.</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>neighborhood: A subregion of the city or search area for which the survey is carried out. For some cities there is no neighbourhood information.</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>room_type: One of “Entire home/apt”, “Private room”, or “Shared room”.</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>host_response_rate: The rate at which the particular host responds to the customers.</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-67784f05-0905-4b5d-ae23-72d5fc7446d5')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-67784f05-0905-4b5d-ae23-72d5fc7446d5 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-67784f05-0905-4b5d-ae23-72d5fc7446d5');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "                                                                                                                                                  0\n",
              "0                                                                                           room_id: A unique number identifying an Airbnb listing.\n",
              "1                                                                                              host_id: A unique number identifying an Airbnb host.\n",
              "2  neighborhood: A subregion of the city or search area for which the survey is carried out. For some cities there is no neighbourhood information.\n",
              "3                                                                            room_type: One of “Entire home/apt”, “Private room”, or “Shared room”.\n",
              "4                                                              host_response_rate: The rate at which the particular host responds to the customers."
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "xwI6XbOtBiUO"
      },
      "source": [
        "df.drop(columns = ['name'], inplace = True)"
      ],
      "execution_count": 67,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Name column wont be necessary for our analysis"
      ],
      "metadata": {
        "id": "cngynoVzPRLa"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6YLlPK34BiUS",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "0ac73aec-102a-48a9-ee9d-34c9a99f3511"
      },
      "source": [
        "# checking dataset shape\n",
        "df.shape"
      ],
      "execution_count": 68,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(19362, 15)"
            ]
          },
          "metadata": {},
          "execution_count": 68
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "There are 19,362 records and 15 columns "
      ],
      "metadata": {
        "id": "gYmleT7JPL83"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "wSszt42KBiUX",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "8314c76c-c840-4dbf-bc52-927517a201f8"
      },
      "source": [
        "# checking data types\n",
        "df.dtypes"
      ],
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "id                                  int64\n",
              "host_id                             int64\n",
              "host_name                          object\n",
              "neighbourhood_group               float64\n",
              "neighbourhood                      object\n",
              "latitude                          float64\n",
              "longitude                         float64\n",
              "room_type                          object\n",
              "price                               int64\n",
              "minimum_nights                      int64\n",
              "number_of_reviews                   int64\n",
              "last_review                        object\n",
              "reviews_per_month                 float64\n",
              "calculated_host_listings_count      int64\n",
              "availability_365                    int64\n",
              "dtype: object"
            ]
          },
          "metadata": {},
          "execution_count": 6
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "sE9Pjh1gBiUd",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "e9b41806-c2ef-4849-dc38-50494e70afe6"
      },
      "source": [
        "# dropping duplicates, if any\n",
        "df.drop_duplicates(inplace = True)\n",
        "df.shape"
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(19362, 15)"
            ]
          },
          "metadata": {},
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "No duplicates found"
      ],
      "metadata": {
        "id": "Is1YxBXy88Cw"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "TSntRcwDBiUg",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "76761d1d-c4c9-4714-ea01-96fd6de893f6"
      },
      "source": [
        "# checking for missing data\n",
        "df.isna().sum()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "id                                    0\n",
              "host_id                               0\n",
              "host_name                             4\n",
              "neighbourhood_group               19362\n",
              "neighbourhood                         0\n",
              "latitude                              0\n",
              "longitude                             0\n",
              "room_type                             0\n",
              "price                                 0\n",
              "minimum_nights                        0\n",
              "number_of_reviews                     0\n",
              "last_review                        2284\n",
              "reviews_per_month                  2284\n",
              "calculated_host_listings_count        0\n",
              "availability_365                      0\n",
              "dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Neighbourhood group has 100% missing values\n",
        "There are missing records for last review and reviews per month\n",
        "\n",
        "These columns will be dropped  "
      ],
      "metadata": {
        "id": "F8PE1oHePdLk"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7-sCZwtIBiUj",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "297fc335-1439-494b-b44e-4493e05e133a"
      },
      "source": [
        "df.drop(columns = ['neighbourhood_group'], inplace = True)\n",
        "df.dropna(inplace = True)\n",
        "\n",
        "# confirming there are no null values\n",
        "df.isnull().sum()"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "id                                0\n",
              "host_id                           0\n",
              "host_name                         0\n",
              "neighbourhood                     0\n",
              "latitude                          0\n",
              "longitude                         0\n",
              "room_type                         0\n",
              "price                             0\n",
              "minimum_nights                    0\n",
              "number_of_reviews                 0\n",
              "last_review                       0\n",
              "reviews_per_month                 0\n",
              "calculated_host_listings_count    0\n",
              "availability_365                  0\n",
              "dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 8
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "w0ZinlPpBiUo",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "fda54f20-0be7-4d02-b346-296b11962c30"
      },
      "source": [
        "df.shape"
      ],
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(17075, 14)"
            ]
          },
          "metadata": {},
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "17,075 variables and 14 columns remaining "
      ],
      "metadata": {
        "id": "8BGRDA3OQJLt"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Biqt5CGbBiUs",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "71cbae4c-def6-43e5-e6c0-248d3428550f"
      },
      "source": [
        "# get the unique value of each variable to ensure there are no anomalies\n",
        "cols = df.columns.to_list()\n",
        "\n",
        "for col in cols:\n",
        "    print(\"Variable:\", col)\n",
        "    print(\"Number of unique variables:\", df[col].nunique())\n",
        "    print('First Five unique values:',df[col].unique()[:5])\n",
        "    print()"
      ],
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Variable: id\n",
            "Number of unique variables: 17075\n",
            "First Five unique values: [ 2818 20168 25428 27886 28871]\n",
            "\n",
            "Variable: host_id\n",
            "Number of unique variables: 15182\n",
            "First Five unique values: [  3159  59484  56142  97647 124245]\n",
            "\n",
            "Variable: host_name\n",
            "Number of unique variables: 5382\n",
            "First Five unique values: ['Daniel' 'Alexander' 'Joan' 'Flip' 'Edwin']\n",
            "\n",
            "Variable: neighbourhood\n",
            "Number of unique variables: 22\n",
            "First Five unique values: ['Oostelijk Havengebied - Indische Buurt' 'Centrum-Oost' 'Centrum-West'\n",
            " 'Zuid' 'De Pijp - Rivierenbuurt']\n",
            "\n",
            "Variable: latitude\n",
            "Number of unique variables: 5720\n",
            "First Five unique values: [52.36575 52.36509 52.37297 52.38761 52.36719]\n",
            "\n",
            "Variable: longitude\n",
            "Number of unique variables: 9193\n",
            "First Five unique values: [4.94142 4.89354 4.88339 4.89188 4.89092]\n",
            "\n",
            "Variable: room_type\n",
            "Number of unique variables: 4\n",
            "First Five unique values: ['Private room' 'Entire home/apt' 'Hotel room' 'Shared room']\n",
            "\n",
            "Variable: price\n",
            "Number of unique variables: 422\n",
            "First Five unique values: [ 59 100 125 155  75]\n",
            "\n",
            "Variable: minimum_nights\n",
            "Number of unique variables: 60\n",
            "First Five unique values: [ 3  1 14  2  4]\n",
            "\n",
            "Variable: number_of_reviews\n",
            "Number of unique variables: 422\n",
            "First Five unique values: [278 340   5 217 332]\n",
            "\n",
            "Variable: last_review\n",
            "Number of unique variables: 1590\n",
            "First Five unique values: ['2020-02-14' '2020-04-09' '2020-02-09' '2020-03-02' '2020-03-16']\n",
            "\n",
            "Variable: reviews_per_month\n",
            "Number of unique variables: 703\n",
            "First Five unique values: [2.06 2.76 0.18 2.15 2.82]\n",
            "\n",
            "Variable: calculated_host_listings_count\n",
            "Number of unique variables: 23\n",
            "First Five unique values: [1 2 3 5 9]\n",
            "\n",
            "Variable: availability_365\n",
            "Number of unique variables: 366\n",
            "First Five unique values: [169 106 132 172 210]\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "There are no missing values"
      ],
      "metadata": {
        "id": "2YefU5HWQbja"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "For our analysis, we will check the assumptions of multiple linear regression which include:\n",
        "\n",
        "1. There must be a linear relationship between the independent variables and the target variable.\n",
        "2. Few or no outliers.\n",
        "3. Little to no multicollinearity.\n",
        "4. Homoscedasticity - variance of error terms must be similar across the independent variables.\n",
        "5. All residuals must be normally distributed."
      ],
      "metadata": {
        "id": "Jgk6yc-WQxqk"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 2.2 Checking linearity"
      ],
      "metadata": {
        "id": "33wVli64Q6cs"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "numerical_train = df.select_dtypes(include = ['int','float'])\n",
        "numerical_train.head(2)\n",
        "\n",
        "null_series = numerical_train.isnull().sum()\n",
        "print(null_series.shape)\n",
        "\n",
        "full_cols_series = null_series[null_series == 0]\n",
        "print(full_cols_series.shape)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5UDuKS-fRAEC",
        "outputId": "8ec0f587-454b-4980-92b0-1331eff4bdea"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "(10,)\n",
            "(10,)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.head(1)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 179
        },
        "id": "AGhFebOsRG_E",
        "outputId": "69ee636d-970b-465d-81fd-688864c0f340"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-323a6a8f-75c8-478a-81fa-553a71a32da9\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id</th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>reviews_per_month</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>2818</td>\n",
              "      <td>3159</td>\n",
              "      <td>Daniel</td>\n",
              "      <td>Oostelijk Havengebied - Indische Buurt</td>\n",
              "      <td>52.36575</td>\n",
              "      <td>4.94142</td>\n",
              "      <td>Private room</td>\n",
              "      <td>59</td>\n",
              "      <td>3</td>\n",
              "      <td>278</td>\n",
              "      <td>2020-02-14</td>\n",
              "      <td>2.06</td>\n",
              "      <td>1</td>\n",
              "      <td>169</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-323a6a8f-75c8-478a-81fa-553a71a32da9')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-323a6a8f-75c8-478a-81fa-553a71a32da9 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-323a6a8f-75c8-478a-81fa-553a71a32da9');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "     id  host_id host_name                           neighbourhood  latitude  \\\n",
              "0  2818     3159    Daniel  Oostelijk Havengebied - Indische Buurt  52.36575   \n",
              "\n",
              "   longitude     room_type  price  minimum_nights  number_of_reviews  \\\n",
              "0    4.94142  Private room     59               3                278   \n",
              "\n",
              "  last_review  reviews_per_month  calculated_host_listings_count  \\\n",
              "0  2020-02-14               2.06                               1   \n",
              "\n",
              "   availability_365  \n",
              "0               169  "
            ]
          },
          "metadata": {},
          "execution_count": 12
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# create list to store column names to test against 'price'\n",
        "train_subset = df[full_cols_series.index]\n",
        "\n",
        "corr = train_subset.corr()\n",
        "\n",
        "SalePrice_corr = corr ['price']\n",
        "SalePrice_corr\n",
        "\n",
        "# '''\n",
        "# Select just the Price column from the resulting data frame, compute the absolute value of each term, \n",
        "# sort the resulting Series by the correlation values, and assign to sorted_corrs.\n",
        "# '''\n",
        "\n",
        "ab = SalePrice_corr.abs()\n",
        "\n",
        "sorted_corrs = ab.sort_values(ascending=False)\n",
        "print(sorted_corrs)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "oo-b-knhRDu9",
        "outputId": "0e0df5e9-5319-4d27-f71e-951e35e8c3c7"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "price                             1.000000\n",
            "availability_365                  0.132741\n",
            "minimum_nights                    0.035343\n",
            "id                                0.025537\n",
            "calculated_host_listings_count    0.025464\n",
            "number_of_reviews                 0.024397\n",
            "latitude                          0.019567\n",
            "host_id                           0.019220\n",
            "reviews_per_month                 0.015244\n",
            "longitude                         0.013304\n",
            "Name: price, dtype: float64\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "There is a poor relationship between price and the rest of the features"
      ],
      "metadata": {
        "id": "ATSXY-D5RSt9"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 2.2 Checking for outliers"
      ],
      "metadata": {
        "id": "O6JK9ItWRo7p"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# # looking for outliers\n",
        "\n",
        "df.drop(columns = ['id'], inplace = True)\n",
        "plt.figure(figsize = (14, 6))\n",
        "df.boxplot()\n",
        "plt.xticks(rotation = 45)\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 490
        },
        "id": "uIesPeDPSDdp",
        "outputId": "3955aab8-0de4-427a-c9c1-a721a1401431"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAzIAAAHZCAYAAABdKQ5FAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nOzdd5xdVbXA8d+C0CQIIhIRkKjgs2AliqhPJiAaQZqiwlMUFSMqxfYoFlBs2CsWFAQbEcVCE1BMFBRLQEEUCypSVEB4okEBA+v9sffAdZyQSTJnzuzJ7/v5zCe3nLmzs+bOuXudvffakZlIkiRJUktW6bsBkiRJkrSsTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNafXRCYijouIayPikjEce9+ImB8RP4mIiyNix4looyRJkqTJp+8RmeOBOWM89g3ASZn5KGBP4KNdNUqSJEnS5NZrIpOZ3wVuGHwsIh4QEWdGxAURcW5EPGj4cODu9fa6wB8nsKmSJEmSJpFpfTdgFMcA+2XmbyJia8rIy3bAm4CzI+IAYG3gyf01UZIkSVKfJlUiExHTgccDX4qI4YfXqP/uBRyfme+NiG2Az0bElpl5ew9NlSRJktSjSZXIUKa6/TUzHznKcy+mrqfJzPMjYk1gA+DaCWyfJEmSpEmg78X+/yYz/wb8PiKeBRDFI+rTVwDb18cfDKwJXNdLQyVJkiT1KjKzvx8ecSIwRBlZuQY4Avg28DFgI2A1YF5mHhkRDwE+CUynLPw/ODPP7qPdkiRJkvrVayIjSZIkSctjUk0tkyRJkqSx6G2x/wYbbJAzZ87s68cvs5tuuom1116772ZMOca1O8a2O8a2O8a2O8a2G8a1O8a2Oy3F9oILLvhLZt5rtOd6S2RmzpzJwoUL+/rxy2zBggUMDQ313Ywpx7h2x9h2x9h2x9h2x9h2w7h2x9h2p6XYRsQflvScU8skSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzlprIRMSaEfGjiLgoIn4eEW8e5Zh9IuK6iPhp/dq3m+ZKkiRJ0tiqlt0CbJeZiyJiNeC8iPhGZv5gxHFfzMz9x7+JkiRJkvTvlprIZGYCi+rd1epXdtkoSZIkSborUfKUpRwUsSpwAbA5cHRmHjLi+X2AdwDXAb8GXpWZV47yOnOBuQAzZszYat68eSva/gmzaNEipk+f3nczphzj2h1j2x1j2x1j2x1j2w3j2h1j252WYjt79uwLMnPWaM+NKZG54+CI9YCvAgdk5iUDj98TWJSZt0TES4HnZOZ2d/Vas2bNSjfElHHtjrHtjrHtjrHtjrHthnHtjrHtTkuxjYglJjLLVLUsM/8KzAfmjHj8+sy8pd79FLDV8jRUkiRJksZiLFXL7lVHYoiItYAdgF+OOGajgbu7AJeOZyP7dOKJJ7Lllluy/fbbs+WWW3LiiSf23SRJkiRppTeWqmUbASfUdTKrACdl5mkRcSSwMDNPAQ6MiF2AxcANwD5dNXginXjiiRx00EGsvfbaZCY33XQTBx10EAB77bVXz62TJEmSVl5jqVp2MfCoUR4/fOD2YcBh49u0/h188MHceOONXHfddQBcfvnlrL766hx88MEmMpIkSVKPxjIis9K66qqrAFhllVW4/fbbWWWVVbj11lvveFySJElSP5Zpsf/K6vbbb/+3fyVJkiT1y0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1x0RGkiRJUnNMZCRJkiQ1Z6mJTESsGRE/ioiLIuLnEfHmUY5ZIyK+GBGXRcQPI2JmF42VJEmSJBjbiMwtwHaZ+QjgkcCciHjciGNeDPxfZm4OvB945/g2U5IkSZLutNREJotF9e5q9StHHLYrcEK9/WVg+4iIcWulJEmSJA2IzJE5ySgHRawKXABsDhydmYeMeP4SYE5mXlXv/xbYOjP/MuK4ucBcgBkzZmw1b968cflPdGX27NlLfG7+/PkT2JKpa9GiRUyfPr3vZkxJxrY7xrY7xrY7xrYbxrU7xrY7LcV29uzZF2TmrNGeG1Mic8fBEesBXwUOyMxLBh4fUyIzaNasWblw4cIx/+w+3NWg0rLETUu2YMEChoaG+m7GlGRsu2Nsu2Nsu2Nsu2Fcu2Nsu9NSbCNiiYnMMlUty8y/AvOBOSOeuhrYtP6wacC6wPXL3lRJkiRJWrqxVC27Vx2JISLWAnYAfjnisFOAF9TbewDfTocsJEmSJHVk2hiO2Qg4oa6TWQU4KTNPi4gjgYWZeQpwLPDZiLgMuAHYs7MWS5IkSVrpLTWRycyLgUeN8vjhA7dvBp41vk2TJEmSpNEt0xoZSZIkSZoMTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNWepiUxEbBoR8yPiFxHx84g4aJRjhiLixoj4af06vJvmSpIkSRJMG8Mxi4HXZOaFEbEOcEFEfDMzfzHiuHMz8+nj30RJkiRJ+ndLHZHJzD9l5oX19t+BS4GNu26YJEmSJC3JMq2RiYiZwKOAH47y9DYRcVFEfCMiHjoObZMkSZKkUUVmju3AiOnAd4C3ZeZXRjx3d+D2zFwUETsCH8zMLUZ5jbnAXIAZM2ZsNW/evBVtf6dmz569xOfmz58/gS2ZuhYtWsT06dP7bsaUZGy7Y2y7Y2y7Y2y7YVy7Y2y701JsZ8+efUFmzhrtuTElMhGxGnAacFZmvm8Mx18OzMrMvyzpmFmzZuXChQuX+rP7FBFLfG6sCaDu2oIFCxgaGuq7GVOSse2Ose2Ose2Ose2Gce2Ose1OS7GNiCUmMmOpWhbAscClS0piIuLe9Tgi4rH1da9f/iZLkiRJ0pKNpWrZE4C9gZ9FxE/rY68D7guQmR8H9gBeFhGLgX8Ce6ZDFpIkSZI6stREJjPPA5Y8x6oc8xHgI+PVKEmSJEm6K8tUtUySJEmSJgMTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1JylJjIRsWlEzI+IX0TEzyPioFGOiYj4UERcFhEXR8Sju2muJEmSJMG0MRyzGHhNZl4YEesAF0TENzPzFwPHPA3Yon5tDXys/itJkiRJ426pIzKZ+afMvLDe/jtwKbDxiMN2BT6TxQ+A9SJio3FvrSRJkiQBkZljPzhiJvBdYMvM/NvA46cBR2XmefX+OcAhmblwxPfPBeYCzJgxY6t58+ataPs7NXv27CU+N3/+/AlsydS1aNEipk+f3nczpiRj2x1j2x1j2x1j2w3j2h1j252WYjt79uwLMnPWaM+NZWoZABExHTgZeOVgErMsMvMY4BiAWbNm5dDQ0PK8zKTQctsnkwULFhjLjhjb7hjb7hjb7hjbbhjX7hjb7kyV2I6pallErEZJYj6fmV8Z5ZCrgU0H7m9SH5MkSZKkcTeWqmUBHAtcmpnvW8JhpwDPr9XLHgfcmJl/Gsd2SpIkSdIdxjK17AnA3sDPIuKn9bHXAfcFyMyPA2cAOwKXAf8AXjj+TZUkSZKkYqmJTF3AH0s5JoFXjFejJEmSJOmujGmNjCRJkiRNJiYykiRJkppjIiNJkiSpOSYykiRJkppjIiNJkiSpOSYykiRJkppjIiNJkiSpOSYykiRJkppjIiNJkiSpOSYykiRJkpozre8G9CkiOvnezFzu15UkSZK0dCt1IrO0hMNkRZIkSZqcnFp2FzbddNNlelySJEnSxDCRuQtXXHHFfyQtm266KVdccUVPLZIkSZIEJjJLdcUVV5CZbHbIaWSmSYwkSZI0CZjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWrOUhOZiDguIq6NiEuW8PxQRNwYET+tX4ePfzMlSZIk6U7TxnDM8cBHgM/cxTHnZubTx6VFkiRJkrQUSx2RyczvAjdMQFskSZIkaUwiM5d+UMRM4LTM3HKU54aAk4GrgD8Cr83Mny/hdeYCcwFmzJix1bx585a33RNunzNv4vg5a/fdjCln0aJFTJ8+ve9mTEnGtjvGtjvGtjvGthvGtTvGtjstxXb27NkXZOas0Z4by9SypbkQ2CwzF0XEjsDXgC1GOzAzjwGOAZg1a1YODQ2Nw4+fIGeeTlPtbcSCBQuMa0eMbXeMbXeMbXeMbTeMa3eMbXemSmxXuGpZZv4tMxfV22cAq0XEBivcMkmSJElaghVOZCLi3hER9fZj62tev6KvK0mSJElLstSpZRFxIjAEbBARVwFHAKsBZObHgT2Al0XEYuCfwJ45loU3kiRJkrSclprIZOZeS3n+I5TyzJIkSZI0IVZ4apkkSZIkTTQTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNMZGRJEmS1BwTGUmSJEnNWWoiExHHRcS1EXHJEp6PiPhQRFwWERdHxKPHv5mSJEmSdKexjMgcD8y5i+efBmxRv+YCH1vxZkmSJEnSki01kcnM7wI33MUhuwKfyeIHwHoRsdF4NVCSJEmSRorMXPpBETOB0zJzy1GeOw04KjPPq/fPAQ7JzIWjHDuXMmrDjBkztpo3b94KNX4i7XPmTRw/Z+2+mzHlLFq0iOnTp/fdjCnJ2HbH2HbH2HbH2HbDuHbH2HanpdjOnj37gsycNdpz0yayIZl5DHAMwKxZs3JoaGgif/yKOfN0mmpvIxYsWGBcO2Jsu2Nsu2Nsu2Nsu2Fcu2NsuzNVYjseVcuuBjYduL9JfUySJEmSOjEeicwpwPNr9bLHATdm5p/G4XUlSZIkaVRLnVoWEScCQ8AGEXEVcASwGkBmfhw4A9gRuAz4B/DCrhorSZIkSTCGRCYz91rK8wm8YtxaJEmSJElLMR5TyyRJkiRpQpnISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWqOiYwkSZKk5pjISJIkSWrOtL4bMN4e8eazufGf/+rktWceevq4vt66a63GRUc8ZVxfU5IkSVoZTLlE5sZ//ovLj9pp3F93wYIFDA0NjetrjndiJEmSJK0snFomSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaM6ZEJiLmRMSvIuKyiDh0lOf3iYjrIuKn9Wvf8W+qJEmSJBXTlnZARKwKHA3sAFwF/DgiTsnMX4w49IuZuX8HbZQkSZKkfzOWEZnHApdl5u8y81ZgHrBrt82SJEmSpCWLzLzrAyL2AOZk5r71/t7A1oOjLxGxD/AO4Drg18CrMvPKUV5rLjAXYMaMGVvNmzdvnP4bd9rnzJs4fs7a4/66ixYtYvr06eP6ml21tSVdxFWFse2Ose2Ose2Ose2Gce2Ose1OS7GdPXv2BZk5a7Tnljq1bIxOBU7MzFsi4qXACcB2Iw/KzGOAYwBmzZqVQ0ND4/TjB5x5Ol287oIFC8b/dTtqa0s6iasAY9slY9sdY9sdY9sN49odY9udqRLbsUwtuxrYdOD+JvWxO2Tm9Zl5S737KWCr8WmeJEmSJP2nsSQyPwa2iIj7RcTqwJ7AKYMHRMRGA3d3AS4dvyZKkiRJ0r9b6tSyzFwcEfsDZwGrAsdl5s8j4khgYWaeAhwYEbsAi4EbgH06bLMkSZKkldyY1shk5hnAGSMeO3zg9mHAYePbNEmSJEka3Zg2xJQkSZKkycRERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzTGQkSZIkNcdERpIkSVJzpvXdgPG2zoMP5WEnHNrNi58wvi+3zoMBdhrfF5UkSZJWAlMukfn7pUdx+VHjnxwsWLCAoaGhcX3NmYeePq6vJ0mSJK0snFomSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaYyIjSZIkqTkmMpIkSZKaM63vBnRh5qGnd/PCZ47v66671mrj+nqSJEnSymLKJTKXH7VTJ68789DTO3ttSZIkScvGqWWSJEmSmmMiI0mSJKk5JjKSJEmSmjOmNTIRMQf4ILAq8KnMPGrE82sAnwG2Aq4HnpOZl49vUzWVRMR/PJaZPbRk6jG23TG23TG23TG23TCu3TG23ZlqsV3qiExErAocDTwNeAiwV0Q8ZMRhLwb+LzM3B94PvHO8G6qpY7Q/ort6XGNnbLtjbLtjbLtjbLthXLtjbLszFWM7lqlljwUuy8zfZeatwDxg1xHH7AqcUG9/Gdg+Wo6KJkRmMn/+/KavBExWxrY7xrY7xrY7xrYbxrU7xrY7Uym2sbT/RETsAczJzH3r/b2BrTNz/4FjLqnHXFXv/7Ye85cRrzUXmAswY8aMrebNmzee/5dlNnv27E5ed/78+Z28bt8O+MMBfTdhmXx4sw/33YQxM7bdaC2uYGy7ZGy70Upcwdh2pbW4grHt0njHdvbs2Rdk5qzRnpvQRGbQrFmzcuHChcv8n+nLggULGBoa6rsZU8LwYF1m3hHXwce0/Ixtd4xtd4xtd4xtN4xrd4xtd1qNbUQsMZEZy2L/q4FNB+5vUh8b7ZirImIasC5l0b+0RM4+7I6x7Y6x7Y6x7Y6x7YZx7Y6x7c5Uiu1Y1sj8GNgiIu4XEasDewKnjDjmFOAF9fYewLdzMqd26tWS3hq+ZVacse2Ose2Ose2Ose2Gce2Ose3OVIztUhOZzFwM7A+cBVwKnJSZP4+IIyNil3rYscA9I+Iy4NXAoV01WFNDZv7bYrOW/4gmG2PbHWPbHWPbHWPbDePaHWPbnakW2zHtI5OZZwBnjHjs8IHbNwPPGt+mSZIkSdLoxjK1TJIkSZImFRMZSZIkSc0xkZEkSZLUHBMZSZIkSc0xkZEkSZLUHBMZSZIkSc0xkZEkSZLUHBMZSZIkSc0xkZEkSZLUnMjMfn5wxHXAH3r54ctnA+AvfTdiCjKu3TG23TG23TG23TG23TCu3TG23Wkptptl5r1Ge6K3RKY1EbEwM2f13Y6pxrh2x9h2x9h2x9h2x9h2w7h2x9h2Z6rE1qllkiRJkppjIiNJkiSpOSYyY3dM3w2Yooxrd4xtd4xtd4xtd4xtN4xrd4xtd6ZEbF0jI0mSJKk5jshIkiRJao6JjCRJkqTmmMhIkiRJao6JzDiIiE0j4vC+2zEVRUT03YaVifGW1JWIsM+hlZafr93wpDI+VgN2i4i39N2QqSQiIms1ioh4cE0YPRF0YCCu03ptSIOGYxcR60bEWn23R3dt4Pe1ft9tmeoGYv3oiFg1M2/vu01TlZ+Nk1NErDZwd43eGjKBIuIBETE0Ue9JE5kVVDvbvwNeRUlmXtd3m6aKgSRmf+ATwP8C53jCHl/DCWNEPAX4dES8MiKe3Xe7WlFjtxtwHPCZiPifiFi373bpPw28158KvDci7uP5pDs11jsCXwC2Hn7cmI+fiFgb7oi1cZ1EImJV4LkR8fiI2Bb4XESsMZV/TxHxX8ApwEYDfbhO/78mMitg4ENxV0oi8yPKm/aonpvWtIi428DtpwK7AzsBfwMW99Wuqaq+h7cH3gN8GngisHNErN5vy9oQEY8BDgNeAtwKvAD4V6+N0qjqe3074CPAJzPzj8Cqw89P5Q5GHyLiQcD7gGdl5vcjYuOIWD/d92G5RcQGEfGEensnysWTUyLiXsZ1csnM24ALgW8AnwGOysxbpurvKSI2A04GPpqZJ0bEKjWZW7PLn2sisxwiYr2IuHv9ULw7cCjwgcx8MbAHsE1EvLHfVrapZvOvrv8C/JUyGrMv8Fjg6QOjB1pOEXHviLj/wEP3B14E3AxsBrwuM2+NiE16aWBbNqUkgP9NieNLM/MfEXGffpslKOsyRiQoTwGOAn4UEXsDJ0fEkXDnKLBWXI15Ui7wrR8RbwVOAr4TEVv22rhGRcQ0ynl6r/refR3wQeCPwJci4oF9tk93imKVzLwY+Bpl2va96nODF0+mUj98G+Ba4Nw6K+HjlM/G99dZC52YSgGcEBGxDqVTvU6d8/s34P+Aq+shvwY+Cxww/OGoZbIhcG9g94i4H/AP4GPAczPzKbVzvQ+wr9N3VshrgA9ExBb1/u3AF4EPADtm5pURMQfYIyJWinm9YzUw73842b4G2Bl4PfA/mXl5RDwD+NDwtA/1IyLWBIbKzXh6RDwdOAd4J3AGJfE8HtgxIh7QVzunktqB25IS319TRicPAn5B+V2cBczurYGNqjNAFlOSwWuAxwMXZuZ3M3M/4AfAx+oomHo0PFsH2Cwi7paZLwB2AY6OiOdl5m0R8YiIuPdUWDcWETNq0jaPMiLzKmA+ZRbNJ4DvAy+ofbpxZyKzjDLz75QhwtuB/Wqn5ofAiXWU5jZKUvNZ4Oz+WtqW4c5hZp4L/BZ4NOXK028pU3XuExHPi4jXAwcCR2bmjX21t1UDcf5f4AbgtRExE/gKcD7wo8y8LiKeCLwf+FVm3tJTcyedgemkc4BTayL4S8pVqO8A96tTl94MHJ+ZN/XYXJWpfkPAt4D3Av/IzG8COwD7ZuabgZ8CtwH/7KuRU8HAuSUz8xLKaPohmfnizHxGZn4BeAgwB/hJj01tTk3IH1fv3kJJCq8BHhgRTwbIzEOBnwHHDk7P1sQa8RlxBnBmRLyE8p5/PvCWepH7G8AWd/FSTYiIB1P6DjsAZObRlOl0X8/M12bm94DTKefiTqZchyPpYzeQZRMRe1KmKHyfspDxdcCzKcNoLwf2yszzBr9HSxcRB1Km5/0Y2IrSAfkoMIsS7wSOzcxf9tbIKSAingS8EngkcBUwF7gnsA/wUEqi/s7MPLWvNk4mdfT1tnr7oZTRq5fVxJuI2JgSw82AuwEnZObp/v33Z6BD8QDKB+lllHPLbZn5r3rMLsC7KR3ur/XX2qkhylq7AymFWdahrG38ZmaeHxGzKevw3pyZp/TYzOZExH0pV/SfBDyMso5xdeCllEpYZ2fm/Hrsf2Xmr/pqq+5YN3kw8EZgc8rv7heUaYBbAtsBP83M7/TWyHEQERtQkrVPZeYxdVTm9vrcKtTrGhHxcEoxnP/JzF+Pezv8jF1+EfEsyonlksz8RP1QXBO4bvikorGrfxSfoawxuLJ+8D2HcuXpQ5l5fa8NnCLqPOqvAntSRhM+QSkhfnhm/r7+HjIzr7cjDnWtyxMoV5hurSfl/TLz5XXO+qqZeUtErJaZ/6ojs38zdv2JiGmZuTjKGsZFwMaUtYxrAG+r7/MNgU2ADTLzbH9fy2fEBb4nUZL8z1MujNwMLMzMY+vzD83MnxvrZVcv8r0P+Exmvqg+tgXlPL4+8A3fx/2qo5LTKcVEHp2ZD6uPPw3YjXIx5fjMvK6/Vo6fOr3/7Zn5ivpZeBhwE/B74Iz6ubg78CbgDV1dGHVq2XIYGEL/EnAe8JCIOAD4TmaeZBKzfDLzL5SqZM+q9+cDFwDPA/aJiNWHY69lMyJuNwO/A27IzH/VD8VNgZMi4oGZ+ZfhpNEPRADuQ7matnYdefk7sFNEPDUzF9eT9VOA/evxfwdj14eI2KxekV4cETtTpm8cQVl7dyBlpPHgiNiXsgj9msw8G/x9La96xXXriNgtM79LSWK+Rys7ea8AACAASURBVFngvANl3cb/1GN/Pvw9vTW4ISPO258GXgj8OSKOjIh7ZOZvKO/xvwGXg7Ht2RZ1+cEHgRujVrDNzG8ApwEPBqbSusm7A0+sI7EfpZxnN6SsgduvHvNgSvGgU7vqv5nI3IUYqCYxeLueuIeTmS9SPhAfBKw34Y2cAiLiGRHxwXr308C9IuKZ9f41lGlmn83MWz1JL5/6nn1SRAxl5hWU+euzImL4PfthSlUVzwkD6tXNhZSCHh8E9gKuB14NHBIRc+tc6HdRrrbZkejXzsAZUUri7wMcTSmv/AJge8qH6xXAY4BXZubVS3gdLZv1KMVDngdcSUkaz6FchPosJeZaRvW8/dSIeAOwR2Z+FjiVMgLz8nqlfw5wTBdTdjQ2USojrgZ8OyI+lJkXAgcA942ItwHU0YiDM/PyHpu6wiJiw4i4b0RskJlXUtbSvhy4W2YeQFlm8UPgAQCZ+faup1k7tWwJ6uK6R1AWzz2IMmXs/MFfxIgh9Y0y80+9NLZxUUr8fo0y3ekEYFdKhySBmcAzM/MXvTVwioiIFwPvoMzPXY9ywrmQktQ8C3h1loV5GlBHWx4G/AF4OuUkfTZwP0p1lj8DX83M05zW0b+IOAh4BeXix1si4t7AMyjn8W9l5ikD0wD9fS2HgfVHj6GMcl1PKZbwWkoisx+lw30osEZm3mysx24gvo8G5gHHUopWXJOZ+0TE1pSLKrsBB3Q1ZUdjM3A+mUFZN/3lzDwkIh5JmVb168w8uPW/gSiVOk+iXLzfibJ2+XbK3/tBlGT7nCgFKF4NPBe4MTuuzGYiswQRsRHlJLEtpTb2nMy8dJTj7qjUMrjQSUsXEY+gvMkvr1N2vgScSdnjYTql83iZV02Xz8CH4RpZK49FxIsoCczOlBPQkymL+7+emWf119rJqXYkXgzMy8xz6xD6PpQqLZ/OzH8OHNv0h1TLBt7rwx2KN1GuiD4xMy+NiHtRRgc2B96SmX/us70tG4j1TsBbKRefXkLZluCXlItPb6FUKHtcZl7bV1tbFhGPpVS5+l6WzQXXBr4M/DkzX1iP2SQzr/Lc05+IeBjlvT4/M6+Nssb0IspapsPqZ8jtmfnTXhu6gqJsdnkG8L7MPDYijga+kJnfq6NRr6BMffwypeLsKzLzjIlo27SJ+CEtysw/RcQfKcnM5yhXXUezSpaa4OsCL4mIowc7N7pTRKw1HJv6x78vcEVEzMuyuH8PygjBxpn5Uko5Wy2j4Q+12tl4BGXPnXdl5pWZeVyUzbi+AjwvM48e6Jj4Yci/ddQC+BSlbOT76+PnRMTtlPUw0yLimMy8GZxS1peB39fjgSMjYu/MfFNE3Ap8LiKen2WB+eeBtUxilk9ErAXcWj/vNqDsRTUH2BG4EfhdZv4fZRrm0yPiESYxK2RjylqDv0fE1zPzpjrl+hsR8ZXMfAZ1/zrPPb16DGV04vaIWJBl+4I9KRu/3pylxPtUMJOyYP+rtQ+xI3C3etHoNZn5gYj4DqXIx1mZ+aOJapjz4UcYHmGJiFmUBb67UqaUHBh1N+KIWC8iVqsjMMNJzGnA901iRhcR04GnRlkUuidlFGABsBHwzIjYLDP/SNkJ9pERcc/+Wtuu2tl4YL39IMqGopsBr46IjesJ6HOUD8CTI+Ie1POAH4ZF7RQ/kdJJ+zDlxPy04fhkKULxUUpxj5v7a6nqOTjr9L99KO/9c6JsNPd2yrScr0SplnVtZv6hz/a2qiYuB1JKKkM5r/yK0pl5MbBPZl4TETvW8w6ZeVEvjW3UQN/j/hGxPmW69YsoG1/OiYg1M/MflPPSO8Bzdh8Gfk/3raNknwY+SbnoPVQ/Y2+kVC47v7eGjr/v1SQmgJdRStrPpfR9z46yvOInmfmtiUxiwKllo4pSRvkI4FWZ+d2IeBxlj5i/UK42/Xd97pooi6W/TKmNf25vjZ7EImLDOuS6M3AkZX3GwzJzUZRFuU+ijA7+H2UjzFdkWUSmZVBPMJtQPvzWpsxPfTil03E88EfKyXUjYHfKXicX99LYSWjElf1jKaODV1H+3jenbML6kT7bqCIi1s662WiUedtnUNYMLAQ+Rtk8cE4dWX89Jek8r7cGN652zmZSKh5ukZkLIuJTlJg/qI6oPxH4ALD3aNOwtXRRFu8fCfwGWBc4pP57JKWz/DUvnvQvSoGXo4CLKX8XzwAeRZkKOI1Srn+vOu1qys10iBFrwiPiBMqUs34uXmSmXwNfwP0p8xvvX+9vUr82p5xUzgN2r8+tBXwd2Lbvdk/WL0opvpMolYMeSlkI+kVg+4FjHk9ZLPYVYMu+29ziV43zy+rtQyg76L5p4Pl1KJ3z4yid8537bvNk/AIeC8ynzO2n/t2/glJS9o+UCxa9t3Nl/qKU/PwgsH69f29KZax1Bo45i9LJWLvv9rb+Rdknafj2wZQNoLehVCX6BPBNylTLi4Bd+m5vq1+1n/GzGtsZlCTxIsqI+q7AucCMvtu5sn/V9/3FlAtcqwNvoGxnsF7tPz6Zsjav97ZOUDweX9+3D+qrDY7IjBARj6JctX4z5Q35cMobdtvMXBh1s7t67EaUD8rLemtwA+q0sq0pmy6eAzwTeApwemaeXK+oXg4szrp7upZNXVB4E6V60OaUxYdbU9YZfTsz/xwR61B+B+tl5u+m4pWiFRURO1AKTrwxM99eFzHuCGxFmUKwcXplv1f1fDKdUklyS8rv63Tgk5n55XrMbpQrplcDT/Z9vmLq+eXgzNwzIg6jdLq/RKng9xJK5cMrsozUeF5ZBgMjwRtRNn5+1sBzR1I22P7wyKvg6ked9v6ezHxhndp6e0R8CLgyM9/dd/smSp3G/gTK9OvX5AQt7B/NSr/Yf+AksjFwbWb+JCJOp5RV/XSWknmvBbaNiAsGkpjwpLJkEbFeZv613l2fMnr1PuDAzJxX1xU9vXY4NqIMw06J3W77kJkXRsQalM7bbZn52oi4gVJW+aYo5cS3Bg7LzBvq99jZGCEzvxkRzwDeGxG/z1It6K+UssvvzbIjvB21HmWZkvoPyjSOF1NGyg4DToiy0/mtlPf98ylzuNeldLS1jIbf68Pnlzp97F2UC33PpGxgfPTgBSj/NsZm4DyyHmVa9Z+BGRHxgcx8ZT3sb5SkEcqeappgA33EJ1F+V98BHhURL8vMj9XDLuPO9WNTRgxUPF2CzYGXZ8+bwK/0iUx9g86hrIm5rK4zeG2WhaLU+fIvokzbycHv66XBDYiIacAuEbEpZRrT1pQa4wcD764nhk9ExG8pa49eaRKzYiJi88y8LCK+CDwnIt4MvK0+vQNlHdKbl3JSEpCZX49SmezzUaoE3U6Zpndjfd6//R4MdChWy8x/AcfX8/XbKInMMylTcDYHXkop0rAVFrVZEWsC/6xx/h5ldOu8gfPL8yhFcW7osY1Nqu/lnYC3R8RZlCmtu1OKsHyBMsr4AspFVdKtHXpRf087U5L3wzLzxoh4AWWB+8aUzV5fROnfTBlRKp4+lyX8vzLznxFxXGbeWo9fta8ZNSv91LKIeCBwCmV4/BpK5YlnUjrYa1E2afzfzDytt0Y2KCLuRplHenfgv7KU5Rye8nEE8I7MPKnHJjZvoGP3QOBDwI8y8/A6DeQFlM7FuykLdDes08scTRijWvTjSODzmfnu2pkzkelR/Z3sDVwLfDRLWeUXURbbfiAzv1WPexJlTdjumXlJbw1uVH2vzwS+RenI/Iiy4eX3KdNITq0XrO6Xmb/praENi7J54jsp1ck2pBS6OZeyVvQwyjrHhZn5jd4aKSLi7pQ1km/NzB9GxOqZeWuU6nzPoST7C3KK7cMWZe+tbwGHZ+bXR3l+WmYurlPMyB4r9q6Uicxg5hhlk583ZOZLBuY7fpByAvnswJVuO4BLMRij+sf/QcrV0fMz8+CB43an7Pq6E/B347r8amJ4AGVawn0osX5dlLVe+1GmLLyxXsHWMopS1vc4ypTIr/TdnpVZ7Th8ilKVbBNKueXnZObFEfFSSjKzN2Wd2P0pm9D9tqfmNmng4sjwvzsCT6XsafJNylSyB+Do7gqJUgn14ZTqnQdEKYP/5Pp1fmYeP3CsfY8eRVlbehZwSJZNkYc78PcYvkA7FQz0f9egnDv/FRF7A/fMskfMHRu+D/eho1TtPZ5ycaO3c+1KlchExDqZ+fd6ezZlz4E/UDoqr8/MT9fnjqR0sN/tSWRsRiQxmwF/rUOw6wAnA7/OzP0jYogy7/eXWWriazlFWfR8KmUq5AURsTXwcsrGdG+OiMcA/8jMn/fa0MZFKQDw28z8Xd9tWVnVaQ5volxgelt97ADKfgbPzbK2cZPMvKrHZjZtIHnZiTIj4Sbgc5n5/Trq+0HgHsB/Uap6TplO3ESqo4UnUCqe7kfZo2p+vfi3M2UTzLekex5NGlHWSa8FzMvM30TEE4DXUdbg/bHlPuLwCFO9vTXlIvMPKPv83QKcCOw0fG4dSGLWpcxYelNmfreXxlcrzRqZOtXp9CjVJS6iVCb7FWV+71eAt0XEhpT67bsArwSnkSzNyOk2EfEa7tzx9bTMfFtEvBg4MSK+S9nfZA+TmHExjTKsvVq9/zPK3ifPj4ibMvM9vbVsCsnMb/bdBnElEMBWUas3ZanktAZlw8uHm8SsmJrE7EBZC/AS4DWU9RtPzcxf15H0h1PKMZvELIcoxSgOBeZmKSxyCXBMRLwkS8W3U4FzMvPP/bZUI3yf0q85NiLmU9aOHJiZV/fbrBVTp4fOiYjFlH0St6HsybU6ZTPhQylrDPeOiHcCDCQxpwOH5iSo4rmyjcjsTvnF3ED5BVwUEc+jTEO4N3Av4FLKWgPXxIzB8DBrvf1i4PmZuW1EHE2Z+vGBzHx97XC8gHKSdrrHchi4Ynpf4JrMvKVOqdmNso7rkigbqu0K3A14W2b+qs82SytqYMrDPSjrXn4DvH+4sxcRm3n1esXVTs0zKPHdmHLFea/M/ENE3Ccz/9hrAxtXL/rtQllz9AtKAaHFdY3XOyix/nafbdSS1TVNjwI2oIzQn99zk1ZIRKxbZ808lLIP16bAk7JuZhtlre2DgX0plVCfXB9flTJqc/5kSGJgJUtk4I5pIicBb69Tx6ZRhtG3BK6jdLzvmCPcZ1snu4jYgLKT9qMz84aI2J7yIbgbMERZsHge8IXMPKi3hk4BA0nM0ygLRK+j7PT8U8pUhEMo+5zsS9lIbT/KYujv99RkadwMJDP3pKyR+TPlHO6V63EQEU8FtqMUBtmZUq76uZn5p7pOZmvgqD4X9E4FUfal2p4S48spJd1vj4i5lOnXC3ps3kpr4PN1mda9tNhPrAn1GpR1P8+hrHv7JmUq6ccz83OjfM9ZwCmZeXS9Pz0zF01cq+/aSleWsk4TeSGwT0TsVUcTvghcApw1/KZs7c3Zh8z8C2Wh+fkRsX5mnkNZ/7ItpSrZryibpj0uItbvsanNqyfZx1D2zXguJWkZomzW+gXKe/rXwBxKtZuHUkpfS00Znq46qHb2VsnM6ynrwDaj7OmgFVTXv7yS0ok5gpLM/KkmMU+m7P/1PZOYFZel6Mp8SidyE+D19X19TJ1a9h/vfXVrIInZBZgXZWPSJR37b8sxGu0nrpmZN1NmbmxAGYV5FGWU5dkRsT+Uke4oBVagvGfXH1hKMGmSGFiJ1sgMysyvRcStwFvqQqcTKJ1BLaMsZTgXAz+OiMfUkZnLgT0iYjtKWck9sm7CqOUTpTrIqyg7y/8M+FlE3EypcrMmZdRrfl2s9w5gn8y8or8WS8tm4OrmmpRSv//2eE1mVs3Mv0TEs4YXqGr51XWhb6WUyR9ea7cz8NWImEfpbL86M8/uqYlNi1H21qhTgs+i9L92oJS5/l19rsWOcdNqErM98BbK2qU/RdlA+rYcqPZZf5eL6xTXXXOgslwrakGJb0fEIZl5TkRsCXw5Il6UmcdHxEeBAyPi4cBDgJdHKSq0IWWD+En5/lzpppYNqhn4UZTO4J/TDaeWW53y9BHgkZTynMPTy/ZP93FYLiOHraNUfHsncFpmvqU+tifwFOCIzLwyIjYBFjvlRi2KUjHrYMpC0ouy7s0w+LcQd5Y/XQ2Y5kjBiomIp1NGdM8ATh9Ye7QOsFZmXttn+1oVZaPtbSkVUf+jb1HXja5rfPtX15quRtn09eGU9bzfAj5bP1cHK3WdSvm87XU3+2UVEWtm5s0R8Qpgf+Dl9eLnNsCZwEE1mXkkpRrkVzPzzPq9a+QkLre+UicyUDb9SXeVHxd1LvU7gf/OzL9GxFp2MpbPwHD3tpT1WzdTSh0+lLJr+c8z8x312HubuKh1NQn/IKWjMAO4H3B21v176rSGVfLO/QveQ9kDzPf+GIw8H49IDnenLPT/JvCtdGH/ComIh1Au7L0yMy9ewjEj9+xpbr1F6+qC9ksp1brmAltQCorcDjwCeHfWsvv1nPMlyh5Kk2KR+1jVtYVHUM6Xf4uIFwJvAPatyczjKeXAj8jMjw583x17x0xmK90amZFMYsZPZp4BvBGYHxGrUGqQaxnVK84ZZa+jE4CknGQPAm4DPg48ISLeWL/lmn5aKq2Y4TnXUfaJ2R64pE7Z+BylkMgOEfGc4cMHroqeTNnjxCRmDGrH+ugolZeAO6bUDM95/yrwZUpVrTl1tEvLISLuDRwIrEtdpzhy7Uu9wp+1c/zuiFjNJGZiDJxz/gv4AGWN9Hcpn7G71I78tynJzTr12LtR1okc2VoSA1DXFr4X2CAits6yZ+JbgU9FxOwsRYGeAbwrIu4bpTIZLSQxYCKjcZaZX6OMyNzeyh/BZBER94tSEnFxnaO7G/DWemLdhXJS3bmeSN8FnAbOq1a7amduO8oozFOAV0bE/bPsz3A6ZW+kp0bZO+b2msQMXzlc0FvDGxIRa1Hm/x8H/K2OfAH/kcx8nbL53QWDawO0dIOJSk2uv0ipSrZ3RNxzMM7x77uin0ypBmW8J0j9XexK+Xs4h7K33amUNTFX16mWXwUOz8yL6rfdSimPfW4vjV4B9aIyWUrU7w28J8p65uFk5mMRsUP9v22SmVeMXNc12a30U8ukySJKhaAvUXfNjoj/Be5L2Tn3+nql7zRgR+dVayqIUhXnfZT3+I+ibLr2ZEqBkN9HxH0oGzBeGaVi0NGUkZjmOhR9iojPUPaJWBXYc+TUMac1Lb+BqWE7AY+nFKs4AngS8FTgl8CXshSpuKPMLyXZeYvv5YlVRxu+AJyQmWfUiyPvBO4D7EGZUrZ6Zn6vJp/R6kXZgffbHUsoIuLllIplb6zn3LnA6yl75NxYk+ymzgeOyEiTRGZ+i7IHzAVx5865awBD9erdOpTpes2cYKSRRkyzeQxlQ+KnAWTmIcDZwFl1ZOaPmXllfW4xcJgdv7EbiPUnKXvBMJzEDE8fqY9lTRSJiLXr2gGNQY3dDsCbKCNaO1I2bD0D+A7waGCvgSnDa1CmTr7d93IvVqFUjNuw3r+J8nubCXyCUmTke1B+ty0mMRExMyL2qO+3HYHTIuIzdTr6p4CvAUdExDaZeQzwhMy8YXgkpqUkBkxkpEklS5WQ/YEfUqYmfJ2yN8zJlN133+e6LrWsfrj+d0Tsl5mfBd4M3LcuQCUzDwNOoVwhBe7skKdl3MdsxFXVqygjBKtGxFcA6pXXVeuxw6Vl16N0cixtvWyeRKn0tBlwA/B2gCyFKr4OfLsm4lCmMu3n1MiJMTCl76ERsUmdxvch4I0RsePA72U+cDdKtdXWPQD4QEQcDOwDHEoZAbwbZUPhjwPnA2+qF02v7qmd42Kl3EdGmszqcHdQFjs/NjNPj1Lv/ZbM/E1rw77SKG4GDo+I2zLzk3Ue97ZRynx+PDNfO3iw7/dlMzClZLjq4T8z87iIeCLw/YiYl5l71mRm2kAS8yXKujxL5i+bW4DXUDYY3KdOi/wf4B5Zd0MfVpNxE/IJMPB38GTKSMSvI+IHwPHAfsBnIuJkykL3nSmbTTe/0W6WPWJeSFlL+4cslcmmUTZ+PxJ4fGa+NSK2yMwbe23sOHBERpqEMvN0ygfjZRGxfmZekpm/qc/ZqVOTImJ6vfr/Y0oBi9dGxNzM/DzlCuHWg4vRtXxq52246mEAL42Io4DNMnMb4JEDIzOLo+wZcyqlKtN3emt4QyJiVkQ8tq7z+hxlc8uT6sWmx1HK2/6q10au5OrfwTbAsyjTVw+mlFbej9KpfxxlpsN/U9Y2bQdc2E9rV9yIohPfpEx33D4inpeZi+uC/8WUixsAl018K8efi/2lSawuIP1HNrb5ljRSRDyQsqj2SODiOhrwWMr89Ldm5qcj4j4jF6Jr2dTOzCrA+4Gf1pGYe1M6cWTmq+txTxheC1BHD35TE0wtwYiRrhMpUyC3oyzuv4SS0FwMbE5ZA3Nqb41dSUXETEqxkPfUUYjjKBURN6lJ+1aU0Zd7Asdl5k8i4qGUCl5vyjsrlTVl4L35GOAewO9rUv10yrngeMr6wxOAl02lCxYmMlIDnE6mFo1839aqZA+gJDOXZua/IuJYygLpWVnKLmscRMSrKQuY35SZN0TExpT1Gs/IzCvqMcOdnyY2vpsMomweuCvwjcxcUEdkvkNZi/A9ypX96Zn5O8/bEy8ipgMPAa7OUk55XUo55esy8zn1mMdQRoQ/n5m/rN8zLTP/2lvDV8DA9NCnUTYVPhY4BHh2Zn4rInahxOA84PXZ4F44d8WpZVID/DBUi4bnp0fEqyJiVpaqZBdSrmA/LiKeWg/dziRm3F1EKbe8bUTcnbLQ95/AP4YPGD6vmMQsk5fUrzUBMvOXlM0UdwP+npnXZt0N3vP2xIk790tZlJk/Ak6KiGPrGpDdgWkR8bl6zI+Bd9ckJur3NJfERMRGcMf00AcDb6NcFPoJ5W/94xGxW2aeQikadOhUS2LAERlJUkci4hHA54EfUMqG/yIz3x8RBwEPo+y78bosG+lqOS3pyn9E7AtsBWxBKd/+rsw8eaLbN9VExCcp+/LsmZl/jYg9gBcCu2emFd8mWC1pvVtmfjHKBrszKZU+zwR+lJkH1ZGZE4FFmfnsqTBaFhELgJsyc6d6/0HA+sCHM3OriDgA+ADwtMw8u7+WdstERpI0bgamK21IuQp4fZbKe3OApwO/BT5U18hsmJnXToVORR8GYn3PzLx+5OP19gbAvSg7l//aWC+/Wqjitnr7RMoUpq8DjwWOyVJuWT2IsoH0AcCNlPLW36uV+M4Gzs3M19T798/MZhf0Awz/vdf1cD8ELs/MZ9fn9gG2ycyXRsSTKKPfb8jM8/trcbdMZCRJ4yoidgbeCEyndCJeGhGrAbMpFYSupCyuTTvVKyYinkLZmXtXys7cwwnMkkZpXA+zAkYkM8cATwT2ysyLBp/TxBh+P0fEPSjFF+4JbDn8Hq+Pfxc4LzNf1mNTx0U9j84DDsnMy2oy8xPgV5n5nLr+52DgGsqeOC+ZykkMmMhIksZRnU72DuB/KYnM54F3ZOaxtYrQDpS9DX7RYzOnhIh4CGXqyOsyc+FoycvAQuBpeefmf7oLAyNd6422dmJEMnMCcH9gTmbeNNFtXZkN/J62oSQw5wKvo3Tg98jMKyPibsBtwKMy8wf9tXb8RMRa3Dm18cj62E+ASzJz7yj7RQ0BC7Nssj2ludhfkrTcIv6/vTsP13yu/zj+fM1gGDGWkT1EiQpZo35qSIxt7JmS7RoJP7sIZRtKlJS97EKyT/Z9yzJ+ERqJsqWMhsZuTGNevz8+n1M3BrOd83Xf5/W4LtfMnPM91/V2zz3nfN/fz3vRgio7Sqh16NsBiwH/sH0PsD2wr6SdXXYZXJ0kZtrVm5l1KL1Gi8O7m8vrDXfXssvraplZvI+Wm+P1geFq2WtUn35TyyL71t9vAzwKDGgk4F6q5e9pXcrDkrG2X6oDRW4CLpa0FeXvZuFOSWIAbL9BGeTxbUkH1I99Dlha0kW277B9uO1rut6znSwnMhERMdXq6NJFKGVNz6jsZDgQeBo4pvbADKLsMfgi8EzKyaZOy81bf2Ac0A/YHfgkcLbtW7quA/rUG+45gN9Q9prc0kzk7UXSmpTdG8Nsj3xHz1FXKVPf+vr2AdayfW2jQfcSkuazPbr+fmHKWOHtbT+ospdqAUqJ2fbAMsA1tq9qLODppOXf/lwALiPVPwlcBpxve3i97iFgG+D+3vJ9NolMRERMk3rj/Bugn+0Na3nZNpQRoMfZHi1pTttjGw20A0gaQnlt+1GW/T0IrAcsCVxs+4aWa+cELgQOtX17A+G2JUlHAC8DJ1JG934JeJ4yvtYtScwASjP5bvX0MbqZyt6po13GXiPpWGAg8AKlxG888IjtAyXNbHtcuw+4aEliNgJ2BER5cHGepMUpydwI299rNNCGpLQsIiKmWGvJQr1J2A54XdK5Ltuxz6SMAt1L0kyUG8OYBrUXYD/KzcxoYHfbjwGXAE8BQ7ue2NaTgiMoJzFJYiaDpKUlbUFpDl+DUqK0KGUy1OzA/PVEpuuk6xJg7yQx3a/rfQ0MA8ZLOrV+DzofGEu5md+Msrl+dgDb4+qvbZvEwH/2ca1FOeneGngcOErSLrb/Svn/3kLSEvXffa+SE5mIiJgqdWLWisDLto+vfRvnAK/b3lrScsCbtv/UaKAdQtImwEzABGAv4Bu2n6gnAwBz2X6i5fqP2H61gVDbUk1ilgN+TOl5ke3HJa1ASczXt/2UpNko5UsHJUnsfi2Tuh4Ejq4fvge40fYeLdetThl+cZDtK3o80G5Sk5O1KQ+D5qY8zDgZOAQ41fYPJc1Se2d6nV6XuUVExNTreuInaRXgBOAVYDdJp9QfpFsBc0u6wPYfksRMvUk06r5C2Sq/G/D1msRsSrnJHt+axEDZct4jgbY5ScvWPq7Lgc9QJl49ATwt6SuUp/77236qfsm8wD5JYnqG7X8DhwGfp5xCvg6sAqwo73UzqgAAEA1JREFU6RQASYtR/m0cZvuKTmlyl/QJYDhwAyWR+wawh+1zKCeHa0tasLcmMZATmYiImAyS5gEm2B4raRngW8C9ts+SNCtwH+UJ6c71ZGYpt/niuabUAQrjbY+vJSVLUuriT6QmLZQnzwsAP6H0bnTME+ieJGl24CLK9LcdgBcpr/OOtu+StB5le/ot9eZYzh6eHtUyYOHTlPf9TfUUoj9wFWXJ7jBggO0X270nppWkL1EGFwyz/W9JJwCmJN17UhK3jpnINjVyIhMREe+rJiZDKWUNAPMDywLLS1rAZX/GCsBGkk61/UaSmKlTy5Z+BawjaTXgFMqo1aHAqZQpZWOBPYCdgH076Ql0T1LZkP4yZXnrk5STro9TGvu3lNQPuKpr2puLJDE9rCYxfWyPorzv15C0fz2ZWY9yira0686fTkhi6vcBbN8KzEY5/YbyvcGUEruTensSAzmRiYiIyVCbm2eh3OwdDqxMeQp6BeUJ6XP1JGGF+sM3ppKk7YCvU5p677Z9Rv34b4Extrevf5693ojHFJI0H+V9/DTwW2BWYHngAcrgis2BJWw/21iQ8TbvOJn5MXCP7UO6Pt50fNOLpCUo32dH2T6lvlcPBo4HHq7N//PW77kdc/o0tXIiExER70l18R/wOvApYCKwP3A3ZRHdYGBw3e/wqu1bczowdbr6j2ri8gvKIIVlaxIJsAkwXy3zg9IzE5Op631ZE8DRlIbpx4FfUk68BlJujrelJORJYnqYpD7v9f3jHScz+wGrS1q8E5KYlvfmIsDngAuAYZKGA1vUy5buSlpsP1d/7dVJDCSRiYiI91FHzW5M2ROzMSWh+RdwEHAzpb9gHVp+nuSH65SrT1Yn1hHAc9i+ENiXMkVrTUnzU25wFqOUmuV1nkItuzjOlvRrYHHKNKydKa/r/pTdPACPwSQHLkQ3kTQzMKj8VutLGvrOa1qSmQeBIXX8cNur780NKb0vWwIbAvtQxqovQBm5/hNJA3rjiOX3k9KyiIh4l66ShXoacCYlkZmJ0qMxgpLMLELZbfAR22OairVT1AlZZwF3UG6kj6ZMajoIeI3Su3Gh7UsbC7KNSVqJUp4zuP46N2VC2SuS5qWMuH3S9m0Nhtlr1Rv0Q4EvUvrwdrJ983tcO4PtCfXEeGK7J/WSPg8cB6wPfIXSG3cGcLztP0vamrw3JymJTERETFIdsbw8MND28Pqxr1HKOq6j3Fj/1vafm4uyvbUkjAMoU4iuBt6knH7NSamNXw74EbCN7T+lLn7y1DKddWx3jejdlFI+Nhr4Lv8dYb2Q7WdaejDy+vawltf+48BllJOIzSiTEt9q/TuR1Nf/XUq6J/Bj221dZilpIUryNield+vrlAb//sAOth+p1+W9+Q45noqIiP9oqdVeDTib8oRwQ0mDJM1o+wLgp5TSh8uTxEybmsQMptxYfwl41vYfKCUm/6IkMA8Ag1138uRGZrL1AX5fm6UB/kbpMzqQ/yYxmwDHqiwPnQh5fXtaS1nlypRpiOtRks3jgI/Vy+au13YlMQMoCc/N7Z7EANh+xva9lO8B59r+C6UHcUZKX2LXdXlvvkMSmYiI+I96Y70KpcRjM9vrAddQbgBXq8nMOcCath9rMtZOUF/rw4E/Um7WDgSo46uvBMYA89l+obEg25TLUssHgAskHWF7JGXM8u+AxSStQXmfn+ksD21MS3/IGcDztv8G7ELZnfRdScOAkZIWazmJuQT4nuto7A7yEGWM/T7At4G9bT/acEwfaikti4iIt5H0VcqiuX1tHyNpRuB7wMLAOe9Vtx5TRtKilNOtP9g+tI6vvhZ40PZO9ZqMWJ5Kkj5FaZR+jtJzcDFwErA3ZQJfP+As21emZKc59d/B+cA3bD8u6bOU5P16Sd+hDGW42vbldSDApcAPbN/eWNDdRGVB68aUE+/TbV/ZcEgfeklkIiLiXSQNAX4AHGH7PEkzAIdRyh5GNRtd+6s3ZDNTXtMVKE9e75Y0K3AncK/tYU3G2M5q8r0f0LcmiZ8GTgN+bfvYes3stl9OEtOsevN+KqXn7nVK4rIAMML2EZL62X6z5fqF66lNx2oZZpD35gdIIhMREZMkaV1gOHCc7TMbDqdjSFqM0tS/PvB3ypjV+SklTiNrMrOs7TsbDLNttTSOf5YyHnxX29dJWory5P8q2weowxYptouWARcfB2agJDBLUCYink0p/VsVWN3291u+rq/tt5qIuaclgZl8SWQiIuI91dr1IykjQZ/rLTcS3U3SIZQSko2AsZRdJp8ETrZ9d4OhtbV68rIScJPtpyVtCywKHGl7nKSlgQG272owzF6v7vPZDxhP6Qu5xfZF9XODKCWX37N9RXNRRjuYoekAIiLiw8v2CEl3ZU/MtJP0CeBF22NsHyJpHHAFZaHoKcD/Amk6nzbLAUsDe0raGzDlaf9swDjbDzcZXICkeYDvANtTTmO+DKwh6UXgr5QTyoNtX5GTifggOZGJiIjoJi1lNKKMVB4FHGv7ufr5MygLANcE/mF7QnPRtp+W13dlYEHgkfrfZpRRthMpCeLJtnduLtLoIuljlMEL69oeI2kgZXrcKNsnSprb9gtJYmJyZPxyREREN6k32V8GNqU0my8PbNuy2+Q64DFgkSQxU66+vhsAp1NOY84Dhtq+kDJI4STKBL5LmosyACTNCWD7aeB2YD9J89h+Hrgf+ETtW3qhXpckJj5QSssiIiKms5aTglWAE4E/A49Sbti+CvSvpWWbA9+0PSpPoKdcbeBfG1gD+AwwBLipfnqs7X9K2rA2/+f17UGS5gWWt311HRyyh6TXKb0xF1P+3i6TdDplf9IOGb4QUyqlZREREd2gljsdRtnH86CkrYBFgP7AOMoek3ttX95gmG2nJUlcjdJbdBtllPXSlNOYJ+uN86O2/5IEpudJ6gtsBQymnL5sStlF9TVgDsq45UcpiWd/4CHbNzYTbbSzlJZFRER0jzko097Wqn/+NfAEJYF5GTioLvlTQ/G1pZaTruHAvsDNlF08369JzKqUqVdzdV3fWLC9VJ1ueEP97/PA47bvtL07paF/R2BJ27+wfWySmJhaSWQiIiK6ge3rgE2A7SUNrT0wFwD3Add3ldHkRnuqDKBMu1qc0gNzJzCslimdRlkwOrK58ML234ErgbuAz0ratH78MEpCv3tX30zE1EppWURERDdqWSz6c9tnNR1Pp6i7SI6iTCW7HlgRWBh4wvb9KSn7cKhTyTalDLq4xval9eNL2P5Lo8FF20uzf0RERDeyfZWkGYAjJV0PjE5T87SzfZmkCZSFrQNtnwfc2/L5JDE9RNIstt+YVPJo+3lJIyijsDeR1Nf2RUliYnrIiUxEREQPqKNms1h0OpM0BPghpR8pSWIPkzQ7pYTscNvXvtdJmKQFKM39d9h+qKfjjM6URCYiIiLaWpLEZknaBtgd2NX2794nmZnF9hv1932SdMa0SrN/REREtLUkMc1ombj3f8DDwEmSvlAny+kd1/at5WczAySJiekhiUxERERETLGasKxLWXB5G3A3JZkZ1JrM1CTmLUlzACMkLdZg2NFBUloWEREREVNF0qHAk7bPqEMtvgnsCuxm+w5JM9ieIGkAcAlwiO3bm4w5OkdOZCIiIiJiskxigesMlEEL1F1JNwKvAb+QNFdNYuYARgAHJ4mJ6SknMhERERHxgbqa+CWtDgwEXqIsI70WGGl7H0mrANsCJ9j+o6Q+wL7AXbZvbSr26ExJZCIiIiJiskhaHzgUOJEyqewnwHWUE5cngRWAPWyPaPmaWW2/1vPRRqfLQsyIiIiIeF+S+gIzAdsAg4E1gFeBG2w/W09iPgr0t/14VwmaiyQx0S2SyERERETEu0jqB/S1/Towl+0xkl4Ddga+DGxr+++SNgKetX1P19dOao9MxPSWRCYiIiIi3qaeqHwV+KikcZQ+l2WBUcD3gXVtPyrpC8APgK0aCzZ6rSQyEREREfE2tan/JuBWYFFgh/qpk4CZgV9KugjYCNjP9n2NBBq9Wpr9IyIiIuJtWiaU7QZsTGnoPx14vi63XAcYD7xqe2TX9U3GHL1PEpmIiIiIAN6WwCwFvAy8AAg4H3gEOABYlXIPeUdzkUYkkYmIiIgI3pbEbAgcBPwReJEyankMcCYwGtgM2Nr2lU3FGgFJZCIiIiJ6NUn9gYm2x0laEfgZMAQYBmwH3Aj8HHgaWAl4xfZ9KSeLpvVpOoCIiIiIaIakOYEjgLUlzQj8G9iNsthyc0qT/0DgR8DKtm9NY398WCSRiYiIiOilbI+llI+tS1lyOcr274HVgINt3wbcB7xEKStr/dqcxkSjkshERERE9EKS+gLYPhR4ENgSWEtSH+BV4GRJm1F2xJxi+5HGgo2YhOyRiYiIiOiF6hjlTwPL2D5B0i7A14AJto+uCc0QYH/bv2s02IhJSCITERER0cvUJAXKKOVVJb3VksxsKWlG2z+S1M/2m2nsjw+jJDIRERERvc8A22MlXQC8BawuqU9NZvYChkoaaft5SD9MfDglkYmIiIjoRSQtAFwvaXfbN0i6COhLSV4m2D5G0iJdSUzEh1Wa/SMiIiI6nCTVX+cF/gkcAxwlaZDtV4DTgNmA9STNb/up5qKNmDxJZCIiIiI6nG1L2gD4FfAx26dRllweK2kQsAQwATjG9rMNhhox2VJaFhEREdHhJK0EHALsYvtxANtnShoPnEAZt3yk7YeaizJiyii9WxERERGdRdJHgaHASbbHS1ofWMP2XpJmAd4EsD1R0kCgr+3nMp0s2klKyyIiIiI6zzLAssCekmaiJC6fA7D9hu2JlLHLg20/b/u5+rkkMdE2kshEREREdJ5bgQuBhYBdbV8PvCDpOknLSFoPOJt6MhPRjlJaFhEREdGBJM0IDAI2Ax6oO2KOAQYACwI/s311kzFGTIskMhEREREdoKu/RdIXgVmBl2zfLWlNYEvgfkrPjCXNbvvlRgOOmEYpLYuIiIjoADVB2RA4HvgMMFzSt23fCJwLrAIcUHfKvNpgqBHTRcYvR0RERHQASQsBOwEbAGsAcwEbS5rF9k8l9QVG14b+lORE20siExEREdGmWsrJ/ocyqWwXSv/LnsAQSkJzsKQZbR/VYKgR011KyyIiIiLaVE1iNgB+Bjxcl13OD5xr+yngJeBi4JbmoozoHjmRiYiIiGhTkj4CbA/sbPvulk99S9JE4DvA5rZHNhJgRDdKIhMRERHRvgzMA8wOIKmP7UslLQmMAb5p+/YmA4zoLikti4iIiGhTtl8DLgBWk7SU7YmSVgVWA26uizAjOlL2yERERES0MUkLAjtSll/eAWwB7Gr7qkYDi+hmSWQiIiIi2pykWYGVgHmBJ23f03BIEd0uiUxERERERLSd9MhERERERETbSSITERERERFtJ4lMRERERES0nSQyERERERHRdpLIRERERERE20kiExERERERbSeJTEREREREtJ3/B78uP0V1sexwAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 1008x432 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Host id has the most outliers in the dataset"
      ],
      "metadata": {
        "id": "jNQUSnweUOOW"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# getting the records with outliers\n",
        "q1 = df.quantile(0.25)\n",
        "q3 = df.quantile(0.75)\n",
        "iqr = q3 - q1\n",
        "\n",
        "outliers_df = df[((df < (q1 - 1.5 * iqr)) | (df > (q3 + 1.5 * iqr))).any(axis = 1)]\n",
        "print(outliers_df.shape)\n",
        "outliers_df.sample(3)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 278
        },
        "id": "7_w3pt_OUNMr",
        "outputId": "117f7a17-7766-4d3c-a276-5507d81b4bb5"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "(8544, 13)\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-3b1a23a4-c575-4d25-9a7a-adfe66f9b55d\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>reviews_per_month</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>14267</th>\n",
              "      <td>212839622</td>\n",
              "      <td>Alex</td>\n",
              "      <td>Bijlmer-Oost</td>\n",
              "      <td>52.32337</td>\n",
              "      <td>4.97229</td>\n",
              "      <td>Private room</td>\n",
              "      <td>35</td>\n",
              "      <td>1</td>\n",
              "      <td>74</td>\n",
              "      <td>2020-03-08</td>\n",
              "      <td>3.76</td>\n",
              "      <td>1</td>\n",
              "      <td>187</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2736</th>\n",
              "      <td>8810466</td>\n",
              "      <td>Barbe</td>\n",
              "      <td>Bos en Lommer</td>\n",
              "      <td>52.37870</td>\n",
              "      <td>4.85117</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>145</td>\n",
              "      <td>2</td>\n",
              "      <td>21</td>\n",
              "      <td>2019-08-01</td>\n",
              "      <td>0.35</td>\n",
              "      <td>1</td>\n",
              "      <td>144</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4676</th>\n",
              "      <td>49264788</td>\n",
              "      <td>Job</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.37186</td>\n",
              "      <td>4.87838</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>449</td>\n",
              "      <td>4</td>\n",
              "      <td>50</td>\n",
              "      <td>2019-12-31</td>\n",
              "      <td>0.94</td>\n",
              "      <td>1</td>\n",
              "      <td>174</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-3b1a23a4-c575-4d25-9a7a-adfe66f9b55d')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-3b1a23a4-c575-4d25-9a7a-adfe66f9b55d button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-3b1a23a4-c575-4d25-9a7a-adfe66f9b55d');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "         host_id host_name  neighbourhood  latitude  longitude  \\\n",
              "14267  212839622      Alex   Bijlmer-Oost  52.32337    4.97229   \n",
              "2736     8810466     Barbe  Bos en Lommer  52.37870    4.85117   \n",
              "4676    49264788       Job   Centrum-West  52.37186    4.87838   \n",
              "\n",
              "             room_type  price  minimum_nights  number_of_reviews last_review  \\\n",
              "14267     Private room     35               1                 74  2020-03-08   \n",
              "2736   Entire home/apt    145               2                 21  2019-08-01   \n",
              "4676   Entire home/apt    449               4                 50  2019-12-31   \n",
              "\n",
              "       reviews_per_month  calculated_host_listings_count  availability_365  \n",
              "14267               3.76                               1               187  \n",
              "2736                0.35                               1               144  \n",
              "4676                0.94                               1               174  "
            ]
          },
          "metadata": {},
          "execution_count": 24
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# calculating percentage of outliers\n",
        "round((outliers_df.shape[0] / df.shape[0]) * 100, 2)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KIEAav1tUbze",
        "outputId": "e5dcd02f-e5bc-42aa-d97f-b1edc93c11b5"
      },
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "50.04"
            ]
          },
          "metadata": {},
          "execution_count": 26
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "50.04% is a fairly large number of records to drop, so we will not drop our outliers."
      ],
      "metadata": {
        "id": "YFLuGFSdUhVx"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 2.3 Checking multicollinearity "
      ],
      "metadata": {
        "id": "gBSNFcLDUsul"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# checking the correlations between the numerical variables\n",
        "cor = df.corr()\n",
        "cor"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 395
        },
        "id": "FGwMsRJuU0du",
        "outputId": "2937ee68-d9a4-49af-9d85-319440c591ec"
      },
      "execution_count": 28,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-7e4f6686-f27b-45b7-9774-ab770099586f\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>host_id</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>reviews_per_month</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>host_id</th>\n",
              "      <td>1.000000</td>\n",
              "      <td>-0.011259</td>\n",
              "      <td>0.027041</td>\n",
              "      <td>0.019220</td>\n",
              "      <td>-0.012490</td>\n",
              "      <td>-0.107797</td>\n",
              "      <td>0.126118</td>\n",
              "      <td>0.024235</td>\n",
              "      <td>0.102491</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>latitude</th>\n",
              "      <td>-0.011259</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>-0.143365</td>\n",
              "      <td>0.019567</td>\n",
              "      <td>-0.017351</td>\n",
              "      <td>0.036669</td>\n",
              "      <td>0.030088</td>\n",
              "      <td>0.022713</td>\n",
              "      <td>0.040589</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>longitude</th>\n",
              "      <td>0.027041</td>\n",
              "      <td>-0.143365</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.013304</td>\n",
              "      <td>-0.002961</td>\n",
              "      <td>0.003264</td>\n",
              "      <td>0.012546</td>\n",
              "      <td>0.012186</td>\n",
              "      <td>0.021006</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>price</th>\n",
              "      <td>0.019220</td>\n",
              "      <td>0.019567</td>\n",
              "      <td>0.013304</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.035343</td>\n",
              "      <td>-0.024397</td>\n",
              "      <td>-0.015244</td>\n",
              "      <td>0.025464</td>\n",
              "      <td>0.132741</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>minimum_nights</th>\n",
              "      <td>-0.012490</td>\n",
              "      <td>-0.017351</td>\n",
              "      <td>-0.002961</td>\n",
              "      <td>0.035343</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>-0.017258</td>\n",
              "      <td>-0.024594</td>\n",
              "      <td>-0.007350</td>\n",
              "      <td>0.041135</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>number_of_reviews</th>\n",
              "      <td>-0.107797</td>\n",
              "      <td>0.036669</td>\n",
              "      <td>0.003264</td>\n",
              "      <td>-0.024397</td>\n",
              "      <td>-0.017258</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.738433</td>\n",
              "      <td>0.002123</td>\n",
              "      <td>0.306629</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>reviews_per_month</th>\n",
              "      <td>0.126118</td>\n",
              "      <td>0.030088</td>\n",
              "      <td>0.012546</td>\n",
              "      <td>-0.015244</td>\n",
              "      <td>-0.024594</td>\n",
              "      <td>0.738433</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.039661</td>\n",
              "      <td>0.325249</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <td>0.024235</td>\n",
              "      <td>0.022713</td>\n",
              "      <td>0.012186</td>\n",
              "      <td>0.025464</td>\n",
              "      <td>-0.007350</td>\n",
              "      <td>0.002123</td>\n",
              "      <td>0.039661</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.126483</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>availability_365</th>\n",
              "      <td>0.102491</td>\n",
              "      <td>0.040589</td>\n",
              "      <td>0.021006</td>\n",
              "      <td>0.132741</td>\n",
              "      <td>0.041135</td>\n",
              "      <td>0.306629</td>\n",
              "      <td>0.325249</td>\n",
              "      <td>0.126483</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-7e4f6686-f27b-45b7-9774-ab770099586f')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-7e4f6686-f27b-45b7-9774-ab770099586f button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-7e4f6686-f27b-45b7-9774-ab770099586f');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "                                 host_id  latitude  longitude     price  \\\n",
              "host_id                         1.000000 -0.011259   0.027041  0.019220   \n",
              "latitude                       -0.011259  1.000000  -0.143365  0.019567   \n",
              "longitude                       0.027041 -0.143365   1.000000  0.013304   \n",
              "price                           0.019220  0.019567   0.013304  1.000000   \n",
              "minimum_nights                 -0.012490 -0.017351  -0.002961  0.035343   \n",
              "number_of_reviews              -0.107797  0.036669   0.003264 -0.024397   \n",
              "reviews_per_month               0.126118  0.030088   0.012546 -0.015244   \n",
              "calculated_host_listings_count  0.024235  0.022713   0.012186  0.025464   \n",
              "availability_365                0.102491  0.040589   0.021006  0.132741   \n",
              "\n",
              "                                minimum_nights  number_of_reviews  \\\n",
              "host_id                              -0.012490          -0.107797   \n",
              "latitude                             -0.017351           0.036669   \n",
              "longitude                            -0.002961           0.003264   \n",
              "price                                 0.035343          -0.024397   \n",
              "minimum_nights                        1.000000          -0.017258   \n",
              "number_of_reviews                    -0.017258           1.000000   \n",
              "reviews_per_month                    -0.024594           0.738433   \n",
              "calculated_host_listings_count       -0.007350           0.002123   \n",
              "availability_365                      0.041135           0.306629   \n",
              "\n",
              "                                reviews_per_month  \\\n",
              "host_id                                  0.126118   \n",
              "latitude                                 0.030088   \n",
              "longitude                                0.012546   \n",
              "price                                   -0.015244   \n",
              "minimum_nights                          -0.024594   \n",
              "number_of_reviews                        0.738433   \n",
              "reviews_per_month                        1.000000   \n",
              "calculated_host_listings_count           0.039661   \n",
              "availability_365                         0.325249   \n",
              "\n",
              "                                calculated_host_listings_count  \\\n",
              "host_id                                               0.024235   \n",
              "latitude                                              0.022713   \n",
              "longitude                                             0.012186   \n",
              "price                                                 0.025464   \n",
              "minimum_nights                                       -0.007350   \n",
              "number_of_reviews                                     0.002123   \n",
              "reviews_per_month                                     0.039661   \n",
              "calculated_host_listings_count                        1.000000   \n",
              "availability_365                                      0.126483   \n",
              "\n",
              "                                availability_365  \n",
              "host_id                                 0.102491  \n",
              "latitude                                0.040589  \n",
              "longitude                               0.021006  \n",
              "price                                   0.132741  \n",
              "minimum_nights                          0.041135  \n",
              "number_of_reviews                       0.306629  \n",
              "reviews_per_month                       0.325249  \n",
              "calculated_host_listings_count          0.126483  \n",
              "availability_365                        1.000000  "
            ]
          },
          "metadata": {},
          "execution_count": 28
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# plotting the correlations onto a heatmap\n",
        "plt.figure(figsize=(12,10))\n",
        "cor = df.corr()\n",
        "sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 738
        },
        "id": "kYPqmTnGU6vn",
        "outputId": "77f8ef1f-e0fb-4dee-cd92-6de15eb82d2f"
      },
      "execution_count": 29,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAxgAAALRCAYAAADY7QWsAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nOzde5xN9f7H8dfXMG4zbsPMECqX6mBKCOV+i9SJOjrVcUoXiVAnaujmGhGDhGEkuihSvzguRakY9ztRJw1FxAwzNC5lZvZ8f3/sbcyeGfc9aw/zfnrsx2P2Xt+19vdjfdd37+/6rO/axlqLiIiIiIiILxTwdwVEREREROTqoQGGiIiIiIj4jAYYIiIiIiLiMxpgiIiIiIiIz2iAISIiIiIiPqMBhoiIiIiI+IwGGCIiIiIi+ZQx5l1jTIIxZvtZlhtjzHhjTJwxZpsxps75tqkBhoiIiIhI/jUDaHeO5XcB1T2PbkD0+TaoAYaIiIiISD5lrV0OJJ2jSAfgfeu2BihljCl/rm1qgCEiIiIiImdzDfBbpuf7PK+dVcFcrY7IJepuSlh/18Ep0XvX+LsKzvrzuL9r4JwCAf6ugbMKF/V3DRxjSpT1dxUc5dr8jb+r4JgC11T1dxUcZQ/t83cVHFXgjvuMv+vg9HecKRx7GvelTafFWGtjcvM9NcAQEREREblKeQYTlzOg2A9UyvS8oue1s9IlUiIiIiIicjb/BR713E2qIfCHtfbAuVZQBkNERERExCF57ey+MeZjoDlQ1hizDxgIFAKw1k4GFgHtgTjgJPD4+bapAYaIiIiISD5lrX34PMst0PNitqkBhoiIiIiIQwoYv88zz3V5LUsjIiIiIiJXMGUwREREREQckh/O7ueHGEVERERExCHKYIiIiIiIOKTA1T8FQxkMERERERHxHWUwREREREQckh/O7ueHGEVERERExCHKYIiIiIiIOES/gyEiIiIiInIRlMEQEREREXFIfji7nx9iFBERERERh2iAISIiIiIiPqNLpEREREREHKIf2hMREREREbkIymCIiIiIiDgkP5zdzw8xioiIiIiIQ5TBEBERERFxiNEP7YmIiIiIiFw4ZTBERERERBySH87ua4AhAjwybSIR97TjWMIhhkY09Hd1Lom1lmETp7F83UaKFC7MG5G9qVm9arZy23fu4qU3x3MqJYWm9evySs8nMcbw5bKVTHh/Nrv27uOTCW8ScWM1AI78kcxzQ0ax/ac4OrZtwYDe3ZwOLUexG7cxbOoHpKen06lNc7o98Hev5SmpqfQbM4Udu36hVHAQYyJ7UTGsHCs3f0/Ue5+QmpZGoYIFiXz8IRreUpPjJ//k3/1fz1j/4OEk7m3RiJef+rfToWUTu2Erw2Led8d6Zwu6/fNer+Upqan0i4pmR5wn1v7PUjGsHEeSj/Hc8LfY/vMuOrZuyoAej2ess2j5aibPnkt6ejrNb6vDC0887HRYZ5VbbXnlxi1EvfMBqalpFCpUkMhuXWh4681Oh3dW1lqGRb3FslVrKFKkMCMGvEzNm27MVm7spBjmLlpM8rFjbF62JOP19Zu2MHzseH6K282Y1wfSrlULJ6t/0WK3/8wbn3yBK93SqXEdnmrXxGv5hp2/8sYnX7Jzfzyju3aibd2aAOxPPMqz0bNIt5Y0l4vOLRrwULPb/BHCOcVu3MqwGE8fdWdzuj2Qw3E7ZrLnuA1mTL9MfdSM2Wf6qCcepuEtNb3W7TEkin0HDzF/0ggnQ7oksd//xPCP5pOebunU9Daeuru51/L1P+3mjY8WsHPfQaK6P0zb2yL8U1HxqfwwiJJMjDHXGWO2X+Y2mhtj7jhPme7GmEdz4/1zw+oZM3m73f3+rsZlWb5uE3v2/87i9yYx5PkeDH5rSo7lBr81maF9nmHxe5PYs/93YtdvAqD6dZUZP6gf9SJqeJUvHBjIc489TOTTXXI9hgvlcqUzZPJ7TB30IgsmjmTh8tXE7d3vVebTJcsoEVScJTFRdOnQjqgZswEoXSKY6Nf6MH/CG4x4vhuRY9z/T0HFijJ3/LCMR4XQsrS5vZ7jsWXlcqUzJHo6UwdHsiB6FAuXryJu7z6vMp8u/s4d6ztj6dLxLqKmfwxA4cBCPPdIJyKf7OxV/kjyMUa9+xEzhr/CguhRHDp6lNVb8s5hmVttuXSJEkQPfYX577zFiMhniRzxVq7HcjGWr1rDr7/tY8lnHzP0pUgGjYzKsVyLJo2YMyP7/0n58DDeGPAy99zZOreretlc6em8/vFCpvT+N/MH9WTR+u+J+z3Bq0z5MiUZ/lhH7q7v/YWzXMkgPu7Xlc9f68Gs/k/xzuIVJBxNdrL65+U+bt9zH7eT3mThsjU59FHfUaJ4cZZMHePpo2YBnj5qQF/mTxzBiOefJjJqstd6S1atp1jRIo7Fcjlc6ekM/WAeMc8/zvxhz7Nw7Rbi9sd7lakQUoo3uj7A3Q1v8VMtnVfAOPvwS4z+eVu5wjUHzjnAsNZOtta+70x1Ll9c7CpOJh3xdzUuy9JV6+jQpgXGGGrXuJHk4ydISEzyKpOQmMTxk39Su8aNGGPo0KYFX69cB0DVaytRpdI12bZbrGgR6kbUIDAw0JE4LsS2n3dRuXwYlcJDCSxUkPZNG7J07UavMkvXbqJjq8YAtG1Un9Vbd2CtpUbV6wgLKQ1A9coVOZWSQkpqqte6v+w/QNIfydSrmf3ssdO27YyjcoUwKpUP88R6O0vXZI11Ax1buc/+tm3cgNVbt2OtpViRItSteROBhQp5ld93MIFrK4RTpmQJAO6oXYslnnaQF+RWW65RvQphZcsA7kHIqZQUUlJSs5Xzl6XLV9CxfTt33BE1ST52nITDh7OVqx1Rk9CyZbO9XrFCeW6qXo0CV8CveH3/y34qh5ahUrkyBBYsyF31avHN1v95lbmmbGlurBhOgSwTYgMLFiSwkPsCjNQ0F+np1rF6X6htO3Poo7Iet2s2ZTpuz9JHXevdR5348y9mzP2CHg92dDagS7Rt929UDg2hUmgIgQUL0r7+LXyz+QevMteULcONlcpn289yZdMAI38KMMZMNcbsMMYsMcYUNcbUNsasMcZsM8Z8bowpDWCMedYY84Pn9VnGmOuA7sDzxpgtxpgmOb2BMWaQMeYFz991jTFbjTFbgZ4OxZjvxB9OpHy5kIzn4eVCiD+clKVMEuFls5ZJdKyOvhKfeITyni+KAOEhZYhP9B4gJiQmUd4Ta8GAAIKLF+No8nGvMotXradG1euyfQFftHwNdzVukCfu9OGONdM+K1uG+Gxfto9k7PuCAQEEFyvG0eRjZ91m5fJh/LLvAPviD5HmcvH16g0cyEPtwIm2vDh2NTWqVSEwsND5CzskPuEQ4WGhGc/DQ8sRn5B9gHE1iD+aTHjpkhnPw0uXJOHo2dtsVgeS/qDjkEm07D+Grm0bEVqqRG5U85LFJx6hfLlMfVTZnPqoM2XOHLdZ+qiV3n3U+A8/5fGOd1GkcN454XMuCUeSCS9zZj+HlSlJ/JG8lW3yhwIOP/xBA4z8qTow0VpbEzgK/AN4H+hnrb0Z+B4Y6CnbH7jV83p3a+2vwGRgrLW2trU29gLebzrQ21qbf/Kfkuf9vGcfUTNmM7jn49mWLYpdw93NbvdDrZxRMjiIgT0fp8+I8XSOHMw1YeUIKJB/Pg5+/nUvUVPfZ/Dz3f1dFblE5cuUZO6AZ/jy9WeZt2Yrh7N8Mb8auPuoWQzu9QQAP+7ew94D8bS5I+/NNxHJSpO886dfrLVbPH9vBKoCpay1yzyvvQfM8fy9DZhpjJkLzL3YNzLGlPJse7nnpQ+Au85SthvQDaAJhanBlXGGxp9mzlvEnEVfARBxQzUOHDpzBvfgocSMy0FOCytbhoOHs5YJ4UoTFlKaA5nOaB9MTMq4pOC00JAyHDicSHjZMqS5XBw7cZJSJYLc5Q8n0Wv4W4x8/mkqlw/zWu9/v+whzZVOrWrX534gF8Ada6Z9djiJsBDv/RoaUpoDhxIJLxvijvXkSUqVCD7ndls2qEvLBnUBmP3FUr8PMJxqywcPHabXwBGM7PcclSuU91HtL93MOf/HJ3PnAxBR4yYOxp+Zh3Aw4RBhodkvhboahJUqwcEjf2Q8P3jkD0JLnbvN5iS0VAmqVQhl4897MiaB5wVhIaU5cChTH3U4pz7KXcb7uD3dRyXSa9g4RvbpntFHbfnfz2yP+4WWT/wHl8tF0h/JPNL/dT4Y8apzgV2k0NIlOJh0Zj/HJ/1BWOm8lW3yh/xwOVj+OWUlmZ3K9LcLKHWOsncDE4E6wHpjTK4NSq21MdbaetbaehpcXJjOHdozd8pY5k4ZS6tGDZj31bdYa9nyw08EFy9GaLYvomUIKlaULT/8hLWWeV99S6s76vup9pcuonoV9vx+kH0HE0hJTWPR8jW0rF/Hq0zLBrcyd+kKABavXEfDm2tgjCH5+AmeHjyavl3+SZ0aN2Tb9sJla7i7ad65k1jEDVXZsz9zrKszBgantWxQl7lL3cnExSvW0vDmmue9vCvxqPtD/49jx/l44dd0auvfOw450ZaTj5/g6VeG0bfrI9Sp9bfcDOeCdX7gfubNnM68mdNp3awJcxd96Y77+x0EBwXlONfialDrugrsSUhi3+EjpKSl8cWG7bS45aYLWvfgkT/4yzN35o8Tf7Ipbi/Xh+et/6eIG3Looxpk7aPqZDpus/RRg6Lo+9iDXn3Uw+1bE/v+BL55dxwz3xzAdRXK5+nBBUDE9RXZk5DIvkNJpKSlsWjdVlrcWuP8K8oVz1ib9yZHSe7xzKFYYK2t5Xn+AhAE3Af0stbGGmMGASWBvkBla+2vxphCwB6gBvAkUMJaOzD7O2S8zyDguLV2tDFmG/CMtXaFMWYkcPfp9z+b7qaEow3zyY/e5YbmjQkqG0JyfALzBw5n1bsfOPLe0XvX+GQ71lqGvh1D7PrNFClcmOEv9s64PWfHp59n7pSxAHz/UxwvjxrPX6dSaFK/Dq/1egpjDF+tWMPrE94h6Y8/KFG8ODdVvZ5pI927uGXnbpw4+SepqWkEBxVn2siBVLu20qVV9E/fXMqwbMMWhk+dSXp6Ov9o3ZTuD3Zg/IefUav69bRsUIdTKSlEjpnMj7v3UDIoiDGRPakUHkr07LnEzJnPtRXCM7Y1bUgkIaXc1wm37tqHmIEvUKVShcuvZIGAy98GsGz9ZoZ7bnf5jzbN6f5QR8Z/MIda1avQsmFdd6yjJ7ljDS7OmMjeVPKc9Wz5+LPufZeWRnDx4kx7vT/VKlekz8i3+emXvQA88/B93N3snPdtuDCFi17+Nsi9thz94RxiZn3GtdecyVxMGzGQkNLnOseSM1PC919orbUMGTWW2NVrKVqkCMNfe4mIGu4v3R06P868mdMBeHP8JBYs+ZqEQ4cJLVeWB+69h97dnmDbDz/SK/IVkpOPUTgwkLIhZVg42zf9mGvzNz7ZTmbLvt/JiE++JD09nfsa3Ur39s14+7/fUPPaCrS85Sa+/3U/z0bPIvnknwQWKkjZEkHMH9SLVT/s4s1PF2MMWAv/al6ffzb13R3fClyT/ZbIl2LZ+i0Mn/qh57ht5umjPvX0UZ7jNmoyP+7+1d1H9evl7qNmne6jzmRXpw3tl9FHAeyLP0SPwVE+uU2tPbTv/IUuw7Kt/+ONjxeQnp7O/U3q0f3vLRn/+RJqXVeRlrfW4Pvdv9F7wgckn/iTwEKFKFsyiAXD+uRafQrccZ/f0wfDipRx9DvOK38lOR6zBhj5zDkGGHNxz60oBuwGHgeOA9/iHmwY4ENr7QhjzA3Ap0A67rkV2eZhZBlg1AXeBSywBGif1wYY/uSrAcYVw0cDjCuCjwYYVwwfDTCuBLkxwMjLcmOAkVf5aoBxpcjtAUZeowGGMzQHI5/xTNKulen56EyLc7oupHEO29gJnPPXqay1gzL9vRHIPME78sJqKyIiIiJXGg0wREREREQccgX8VM1l0wBDLosx5hXggSwvz7HWDvNHfURERETEvzTAkMviGUhoMCEiIiJyAfLDLVzzQ4wiIiIiIuIQZTBERERERBxSgKt/EoYyGCIiIiIi4jPKYIiIiIiIOCQ/3EVKGQwREREREfEZZTBERERERBySH87u54cYRURERETEIcpgiIiIiIg4RHMwRERERERELoIyGCIiIiIiDtHvYIiIiIiIiFwEZTBERERERByiORgiIiIiIiIXQQMMERERERHxGV0iJSIiIiLikPxwdj8/xCgiIiIiIg5RBkNERERExCGa5C0iIiIiInIRlMEQEREREXGIfmhPRERERETkIiiDISIiIiLiEM3BEBERERERuQjKYEieFL13jb+r4JgelRv6uwqOmnziN39XwTH29zh/V8FZJh+clvNIP7DL31VwVIEKVfxdBcktpUL9XYN8Jz/0lMpgiIiIiIiIzyiDISIiIiLiEM3BEBERERERuQjKYIiIiIiIOES/gyEiIiIiInIRlMEQEREREXGI5mCIiIiIiIhcBA0wRERERETEZ3SJlIiIiIiIQ/LD2f38EKOIiIiIiDhEGQwREREREYfkgzneymCIiIiIiIjvKIMhIiIiIuKQAubqz2EogyEiIiIiIj6jDIaIiIiIiEOu/vyFMhgiIiIiIuJDymCIiIiIiDhEGQwREREREZGLoAyGiIiIiIhDlMEQERERERG5CMpgiIiIiIg4xOh3MERERERERC6cMhgiIiIiIg65+vMXymCIiIiIiIgPaYAhIiIiIiI+o0uk8gljzHFrbdA5lpcC/mWtneR5XgEYb63tZIypDVSw1i66yPccBBy31o6+jKpfFmstwyZOY/m6jRQpXJg3IntTs3rVbOW279zFS2+O51RKCk3r1+WVnk9ijOHLZSuZ8P5sdu3dxycT3iTixmoAHPkjmeeGjGL7T3F0bNuCAb27OR3aZXlk2kQi7mnHsYRDDI1o6O/qXDZrLcPejGLZylUUKVKEEYMHUPNvN2UrN3bCJOYuWERy8jE2r1qWbfnir7/h2Rf78+mHM4ioWcOJql+02A1bGRbzPunp6XS6swXd/nmv1/KU1FT6RUWzI+4XSgUHMab/s1QMK8fKzd8TNf1jUtNcFCoYQOSTnWl4S00/RXFu7uP2HZavPX3cPkvNG3I6buPcx+2pFJo2qMsrPbueOW7fm+U+bieOyjhu53+9jGmffJ6x/k+79/B/k6P4W7UqjsWWVeymbQyf+pF7f7ZpylOd7vFanpKaSr+xU/lh16/u/fliD64JK8e2nbsZOGk6ANZCz4c60ub2uvyy7wB9Rk/KWP+3g4fo/a/76HJvW0fjuhCxG7cxbOoHntib0+2Bv3stT0lNpd+YKezY5WnLkb2oGFaObTt3MWDCu4C7rfT61/20ub2eP0I4p9iNWxkW44nvzuZ0eyCHY3XMZM+xGsyYfr3OHKszZpOalkahggWJfOLhjGO164CRHEr6A1e6i7o1bmRAj8cICMgb54pjN33P8GkfkZ5u6dS6CU/9426v5SmpqfR76x1+2LWHUsHFGfNCD64JLZux/PdDifz92Vfp+WAHnujYDoBX3n6X7zZspUzJEswfP9TReHJT3thjuSs/xCgXphTwzOkn1trfrbWdPE9rA+39UqvLtHzdJvbs/53F701iyPM9GPzWlBzLDX5rMkP7PMPi9yaxZ//vxK7fBED16yozflA/6kV4f9ksHBjIc489TOTTXXI9htywesZM3m53v7+r4TPLV6zi172/sWTeZwx99SUGDR+ZY7kWTZsw54MZOS47fuIE7380i1siauViTS+Py5XOkOjpTB0cyYLoUSxcvoq4vfu8yny6+DtKBBVnyTtj6dLxLqKmfwxA6RLBRA98kfmTRjKiTw8ioybl9BZ5wvJ1G9mz7wCL349mSJ9nGPzW5BzLDR43haF9erL4/Wj27DtA7LpMx+3g/tS72fu4/XvrZsyNGcfcmHGM7P8fKoaH+nVw4XKlM3TKB8QM7MP8CcNZGLuWuL37vcp8+tVySgYVY/GUN3n03jsZ/d4cAKpfew1zogbx+bihxAzsy6DoGaS5XFxfsTyfjxvK5+OG8mnUYIoWDqR1w7r+CO+cXK50hkx+j6mDXmTBxJEsXL46e+xLlrnbckwUXTq0I2rGbACqV67Ip2OHMHf8MKYOjmTgxHdJc7n8EcZZuY/V99zH6qQ3WbhsTQ7xfUeJ4sVZMnWMJ75ZgOdYHdCX+RNHMOL5p4mMOtP+x/XvzbwJw5k/cQRJycf4csVaR+M6G5crnaExHxLz2vPMH/86C1esJe63LPF+HUvJ4sVZHD2CR/9+J6Pfn+O1fOT0WTS5NcLrtY4tGxEzoE+u1198TwOMfMYYE2SMWWqM2WSM+d4Y08GzaARQ1RizxRgzyhhznTFmuzEmEBgCPOhZ9qAxZpAx5oVM29xujLnO8/crxpidxpgVwI2ZylQ1xnxpjNlojIk1xmQ/vZwLlq5aR4c2LTDGULvGjSQfP0FCYpJXmYTEJI6f/JPaNW7EGEOHNi34euU6AKpeW4kqla7Jtt1iRYtQN6IGgYGBToThc3GxqziZdMTf1fCZpcuW0/Ge9u79fHMEyceOkXDocLZytW+OILRc2Ry2AG9NmsJTjz9K4Ty8T7ftjKNyhTAqlQ8jsFBB2je9naVrNnqVWbp2Ax1bNQGgbeMGrN66HWstNapeR1hIaQCqX1uRU6dSSElNdTyGC7F05To63Nn8Ao7bk2eO2zub8/VK95etsx23mS38Jpb2LZrkWgwXYtvPu6kcHkal8FD3/mzSgG/WbfYq883azXRo2RiAto1uY822H7DWUrRwYQoGBADuM8Mmh2mja7b9QKXwUK+zxHnFtp93Ubl8ptibNmTp2qxteRMdW52OvT6rt+5wx14kU+wpKXnylp/bduYQX9Zjdc2mTMfqmfiyHaspZ47VoGLFAEhzuUhNTcszsW/7eTeVy4eeibdxA75Zt8WrzDfrNtOhxR0AtL2jHmu2/Yi1FoCv126iYmg5qlWu4LXObTVvpFRwcWeCcJAxzj78QQOM/Ocv4D5rbR2gBRBl3D1Uf2CXtba2tfbF04WttSnAAGC2Z9nss23YGFMXeIgzGY/bMi2OAXpba+sCLwCOnD6NP5xI+XIhGc/Dy4UQfzgpS5kkwstmLZPoRPXER+ITEggPD8t4Hh4WSnxCwgWvv+PH/3HwYDzNmzTOjer5THziEcpnbqtlyxCf7Yv3kYw2XzAggOBixTiafMyrzOKV66hR9ToCCxXK/UpfgvjDSZTPNBA863Gb+dgum73MuXzx3QrubunfAUZC4hHCy5bJeB4WUpr4RO+Bf3zSEcp7yhQMCCC4eFGOHjsOwNafdnFPr5fp8OyrDOzRJeNL92mLYtdyd9O8eQmkuy2fiT08pEy22BMSkzLauzv2YhxNPh17HPc80597e7/MoGcezxa7v8UnHqF8uUzxlc0pvjNlzhyrx73KLF65Ptux+uRrI2nU+RmKFytC20b1czGKC5eQdPT8bTnxqHdbLuZuyyf+/It3/u8LnnnQ+xIyubJpgJH/GGC4MWYb8DVwDRB27lUuWBPgc2vtSWttMvBfcGdNgDuAOcaYLcAUoLyP3lPksqSnpzMiahz9+j7n76o44uc9+4ia/jGDe3f1d1X8ZuuPOylSpDA3XH+tv6tyWW65sSoLJgznk9EDmfrZAk6lpGQsS0lN45t1m2nb6LZzbOHKdcuN1VgwaQRzxgwmZs58r9ivFj/v2UfUjFkM7vWE1+vThvYj9oMJpKSmsWbbDj/Vzncmzp5Hl3vbULxoEX9XxTHG4X/+oEne+U9noBxQ11qbaoz5FbjYozoN78Hp+dYvABy11tY+VyFjTDegG8DkNwbSrfM/L7JabjPnLWLOoq8AiLihGgcOnclGHDyUSFimsywAYWXLcPBw1jIhSN42c/YcPvm/uQBE1KzBwYPxGcsOxicQFhp6Qds5ceIkO3ft4tGuPQA4lJhIj/+8QPS40XluondYSGkOZG6rh5MIC/Fuz6EhpTlwKJHwsiGkuVwcO3mSUiWCPeUT6fX6GEb27UHl8r46r+AbM+cuYs6iJQBE3FidA5kucTvrcZv52D6cvczZLPo2lrv9fHkUuPfVwUxZl/jEIxmXxpwWVqY0Bw4nEV62jHt/nviTUsHe9+uoWqkCxYoU4ec9+6lV/XrAPXm8RtVrKVuqZO4HcgncbflM7AcTk7LFHhpShgOHEzPFfpJSJbLGfg3FihZm5559RFT333yarMJCSnPgUKb4DucUn7uM97Ea5CmfSK9h4xjZp3uOx2rhwEBaNajD0jWbaJRl3oI/hJYpdf62HFLKuy2fdLflbTt3s3jVBka/N4djJ05SoEABCgcWonP7Vk6HkW8ZY9oBbwEBwDvW2hFZllcG3sM9XzcA6H++G/8og5H/lAQSPIOLFsDpU3jHgOCzrJN12a9AHQBjTB3ges/ry4GOxpiixphg4O8AnmzGL8aYBzzrGGPMLVnfxFobY62tZ62td6mDC4DOHdozd8pY5k4ZS6tGDZj31bdYa9nyw08EFy9GaLYvZGUIKlaULT/8hLWWeV99S6s78kbaWc6u84MPMG/2TObNnknrFs2Yu2CRez9v+57goKCzzrXIKjg4iLXffsU3i+bxzaJ51I6olScHFwARN1Rlz/6D7DuYQEpqGouWr6ZlA+8JvC0b1GXu0lgAFq9YS8Oba2KMIfn4CZ4eNIq+jz1EnRo35rR5v+rcsX3GBOxWjRowb8l3mY7b4mc5boudOW6XfEerC7hcJD09nS++W5knBhgR1a9nz4F49sUfcu/P2LW0qH+rV5kW9Wsz75sVgPtymYY3/w1jDPviD2VMbN6fcJjd+w5wTdiZNr9w+RrubpI3L48CiKhehT2/Z27La2hZv45XmZYNbmXu0tOxr6PhzTXcsR9MyBZ7xdByjsdwLhE35BBfg6zx1cl0rJ6Jz32sRtH3sQepU+OGjPIn/vyLBM/cuTSXi2UbtlClYt64GCBbW16xlha3eZ9TbHFbbeZ9uwqAxas20DDiJowxfDj8JZbGjGJpzCge/Xsbuv3j7qt+cGEcfpyzLsYEABOBu4AawHpAhccAACAASURBVMPGmKwfgK8Cn1hrb8V9Kfx5L3NXBiP/mQnMN8Z8D2wA/gdgrU00xqw0xmwHvsDd2E77FujvubzpDeAz4FFjzA5gLbDTs41NxpjZwFYgAVifaRudgWhjzKtAIWCWp1yuatagLsvXbeTOR3tQpHBhhr/YO2NZx6efZ+6UsQAMePZpXh41nr9OpdCkfh2aej7ovlqxhtcnvEPSH3/Q/ZXXuanq9UwbORCAlp27ceLkn6SmprF05TqmjRxItWsr5XZIPvHkR+9yQ/PGBJUN4Y3ffmT+wOGsevcDf1frkjVr3IhlK1bR5t77KVqkCMMHvZaxrMODnZk3eyYAb44bz4IvlvDnX3/RtO09PHDfvfTufuXcYrhgQACv9XiMJ18bQXp6Ov9o05zq11Zk/AdzqFW9Ci0b1qXTnc2JHD2JO7s+T8ng4oyJdLf5mQuWsPf3eCZ9/DmTPnbfqnXa6/0JyYNnuJs1qMvytRu585HuFClSmOEvPpuxrGO3/zA3ZhwAA557mpffHM9fp07RpH5dmtZ3D7a+WrGG19+e6j5uXx7KTdWuZ9rIQQCs37aD8qFlqVQh3PG4sioYEMCr3f5N10GjSU9P5/5WTahe+RrGz/w/alW7npYNbqVTm6b0GxtD26cjKRlcnKgX3Jm2jT/sZOpnCylUMABjCjCg+yOU9mSqTv51ilVbdzD4mcf8GN25FQwI4LXuj/LkwFHutty6qbstf/gZtapfT8sGdejUphmRYyZzZ7e+lAwKYkxkT8AT+6cLKFgwgALGMLB7F0qXPNv5Mf9wx9eFJwe86TlWm3ni+9QTX1063dmMyKjJ3PlUH3d8/XoBMHPBV+w9kOVYHdoPa+GZoWNISU3Dplvq3/w3HsojX8QLBgTw6lP/puvgMZ623Njdlj/6nFrVrqNl/Vvp1Lop/cZNpW2P/pQMKk5U36fPu92+UZNZt+MnjiYfp3nXvvR6qAOdWjd1IKJ8pT4QZ63dDWCMmQV0AH7IVMYCJTx/lwR+P99GzekZ/CJ5if3th3zTMHtUzrtnGXPD5BO/+bsKjrG/x/m7Cs4qUszfNXCMPX7U31VwlCmQtyZR56o8cmcmp9jUq2/+yrkUqNHI7zt4QUh5R7/j3JN44KwxG2M6Ae2stV09zx8BGlhre2UqUx5YApQGigOtrbUbc9reabpESkRERETkKmWM6WaM2ZDpcbGp+4eBGdbairjvEvqBMeacYwhdIiUiIiIi4pACDudQrLUxuH8uICf7gczXd1f0vJbZk0A7z7ZWG2OKAGVxXw6fI2UwRERERETyp/VAdWPM9Z4fV34Iz88MZLIXaAVgjPkb7ruHHjrXRpXBEBERERFxiL9+myIn1to0Y0wvYDHuW9C+a63dYYwZAmyw1v4X6AtMNcY8j3vC92P2PJO4NcAQEREREcmnPL9psSjLawMy/f0D0OhitqkBhoiIiIiIQ/JO/iL3aA6GiIiIiIj4jDIYIiIiIiIOyQ8/taIMhoiIiIiI+IwGGCIiIiIi4jO6REpERERExCH54AopZTBERERERMR3lMEQEREREXFIgXyQw1AGQ0REREREfEYZDBERERERh1z9+QtlMERERERExIeUwRARERERcYh+aE9EREREROQiKIMhIiIiIuKQfJDAUAZDRERERER8RxkMERERERGHmHyQw1AGQ0REREREfEYZDBERERERhxS4+hMYymCIiIiIiIjvKIMhIiIiIuKQfJDA0ABD8qg/j/u7Bo6ZfOI3f1fBUd2LV/J3FRwTHfedv6vgrHSXv2vgGFM0yN9VcFY+2rf5jTG6mEV8T61KRERERER8RhkMERERERGH5IdLpJTBEBERERERn1EGQ0RERETEIfqhPRERERERkYugDIaIiIiIiEPM1Z/AUAZDRERERER8RxkMERERERGH5Iez+/khRhERERERcYgyGCIiIiIiDskHUzCUwRAREREREd9RBkNERERExCEmH9xGShkMERERERHxGWUwREREREQccvXnL5TBEBERERERH1IGQ0RERETEIcpgiIiIiIiIXAQNMERERERExGd0iZSIiIiIiEN0m1oREREREZGLoAyGiIiIiIhDClz9CQxlMERERERExHeUwRARERERcYjJBykMZTBERERERMRnlMEQEREREXFIPriJlAYYVwNjzHFrbZCPt3kvUMNaO8IY0xHYaa394SK38R3wgrV2gy/rdqFiN25j2NQPSE9Pp1Ob5nR74O9ey1NSU+k3Zgo7dv1CqeAgxkT2omJYOVZu/p6o9z4hNS2NQgULEvn4QzS8pSbHT/7Jv/u/nrH+wcNJ3NuiES8/9W+nQzsvay3D3oxi2cpVFClShBGDB1DzbzdlKzd2wiTmLlhEcvIxNq9alm354q+/4dkX+/PphzOIqFnDiar73CPTJhJxTzuOJRxiaERDf1fnksRu2MKwKe+723LbFnT7Zwev5SmpqfQbPYkdcZ62/NJzVAwrx5HkYzw3fBzbd+6iY+tmDHjm8Yx1ur72BoeSjuJyuahb8yYGPPMEAQF5I6ltrWXYpHdZvm4TRQoH8saLvalZvUq2ctt37uKlURM4lZJC0/p1eOWZJzDGcDT5GH2GjWH/wQSuCQ9l7Kt9KRkcxNJV63hrxscUMAUICAjg5Wcep26tvzkeX+z6zQyLnu7en+1a0e2h+7yWp6Sk0m/U2+z4ebd7f77Sh4rhoQBM+fj/+GzxNxQoUIBXnnmCJvVqcyolhX/3HUBKaioul4s7m9zOs48+CMArUZPY/vMurLVcd00F3nixJ8WLFnU85tNiN2xhWPQMT+wt6fZgR6/lKSmp9Bs90R17iWB3Ww4Pdbfl18e423Kb5gzo+UTGOl1fGc6hpCO4XOnUrXUTA3o+mSfasq9j/fOvU/xn2Fj2HognoEABWjSsS98n/uWP0HIUu2Erw2I8/dSdLej2z3u9lqekptIvKvpMP9X/2TOfudM/JjXNRaGCAUQ+2ZmGt9QEYOx7s5n3TSzJx0+w6bPp/ghLLpH/j0DJk6y1/7XWjvA87QhcUd8uXa50hkx+j6mDXmTBxJEsXL6auL37vcp8umQZJYKKsyQmii4d2hE1YzYApUsEE/1aH+ZPeIMRz3cjcswUAIKKFWXu+GEZjwqhZWlzez3HY7sQy1es4te9v7Fk3mcMffUlBg0fmWO5Fk2bMOeDGTkuO37iBO9/NItbImrlYk1z3+oZM3m73f3+rsYlc7nSGTJpOlOH9GPB5NEsXLaKuL37vMp8uvhbd1ueNo4u97Un6t2PACgcWIjnHnmAyCc7Z9vuuJeeY97EkcyPHkXSH8f4csUaR+K5EMvXbWLP/gMsnjGBIf/pweDxMTmWGzw+hqHP92DxjAns2X+A2PWbAZg6+3Ma3hrB4vcm0vDWCKbO+hyAhrdGMG/KGOZOiWL4C8/w6phJjsV0msvlYsiEd5g67BUWTB3Lwu9WELfnN68yn3651L0/Z0ygy/33EDXtQwDi9vzGomUrWRAzlneGvcKQt6ficrkILFSIGW8OZN7kKD6PHs2K9ZvZ8uNOAF7q/hjzJkfx3yljKB9alpnzvnQ85tNcrnSGTHyXqa+/xIKYMSz8biVxe7K25W/csU8fn70tP/ogkU89km27417+D/OiRzF/ymiS/kjmy9jVjsRzLrkV6+Od7uGLd8byfxNHsmnHTyz3tHl/c7nSGRI9namDI1kQPYqFy3Pqp75zx/vOWLp0vIuo6R8Dns/cgS8yf9JIRvTpQWTUmeOyRYM6fDJ2qKOxOMEYZx/+oAHGVcS4jTLGbDfGfG+MedDzenNjzHfGmE+NMf8zxsw0nl95Mca097y20Rgz3hizwPP6Y8aYCcaYO4B7gVHGmC3GmKqebdXzlCtrjPnV83dRY8wsY8yPxpjPgaKZ6nanMWa1MWaTMWaOMcanGZestv28i8rlw6gUHkpgoYK0b9qQpWs3epVZunYTHVs1BqBto/qs3roDay01ql5HWEhpAKpXrsiplBRSUlO91v1l/wGS/kimXs0bczOMS7Z02XI63tMeYwy1b44g+dgxEg4dzlau9s0RhJYrm+M23po0hacef5TCgYG5Xd1cFRe7ipNJR/xdjUu2bWcclSuEU6l8mKct387S1d5JwaVrNtKxdVMA2jZuwOqt27HWUqxIEerWvInAHPZhULFiAKS5XKSmpWHIOzn7pavX06F1M3f7rXEDycdPkJDovQ8TEo9w/ORJate4AWMMHVo34+tV69zrr1pPxzYtAOjYpkXG68WLFs34gauTf53yS8zbfsq8PwvRvlkjlq5a71Vm6er1dGzTHIC2TW9n9ebvsdaydNV62jdrRGBgISqWD6NyhXC2/RSHMSYjK5GW5iLN5cqILKi4ez9bazmVkuLXSzO2/RTn7pdPt+Vmd7B0ddbYN9CxdTMA2jZpyOotmdpyrZsILFQo23ZPx5jRlvPA9Se5EWvRIoVpeIv7hE9goYLUqHY9Bw8nORPQebj7qTDvfmpN1s/cDXRs1QTw7qe8PnOvrcipU2c+c2vfVJ3QMqWdDUZ8QgOMq8v9QG3gFqA17kFBec+yW4H/4M5EVAEaGWOKAFOAu6y1dYFyWTdorV0F/Bd40Vpb21q76xzv3wM4aa39GzAQqAvuQQjwKtDaWlsH2AD0udxgzyU+8Qjly5bJeB4eUob4bF9QkihfNgSAggEBBBcvxtHk415lFq9aT42q12Xr6BctX8NdjRvkiQ+ynMQnJBAeHpbxPDwslPiEhAtef8eP/+PgwXiaN2mcG9WTi+BuyyEZz8PLhuTclstlasvFinE0+dh5t/3kq2/Q6F/dKV60CG0bN/BtxS9D/OEkyoeeGfiGlw0h/nBiljKJhGf+fykXQrzny1bikaOEer6wlCtTisQjRzPKfbViLXc90Zvurw5n2As9czOMHMUfTqJ8pkF9eLkQ4hO9vyQmZCpzpm86RnxilnXLnonZ5XLRsfsLNPrnk9xR52Zu+dsNGeVeGj2Rxg92Zfdv+/l3h/a5Gd45xWdqp3CBbbn4Bbbll4fR6KFuFC9alLaN/X8pZG7GCpB8/ATfrt3I7bXzRoY5ez9VJnu7Tjxy3n5q8cp1OX7mXm2MMY4+/EEDjKtLY+Bja63LWhsPLANu8yxbZ63dZ61NB7YA1wE3Abuttb94ynx8me/fFPgQwFq7Ddjmeb0h7oHNSmPMFqALcO1lvleu+3nPPqJmzGZwz8ezLVsUu4a7m93uh1rlvvT0dEZEjaNf3+f8XRXJZdNef4nYDyeRkprGmq3b/V2dXJH1A7ZN4wZ88e7bTBgUyfgZl9vl5R0BAQHMnTya7z6awraf4tj5y96MZW+80JPlH8dQtVJFFi1b6cda5p5pw18h9qPJpKSmXrVt+bQ0l4u+I8bzSId2VCofdv4VrhA/79lH1PSPGdy7q7+rIj6gAUb+cSrT3y4ub4J/GmfaTpELKG+ArzwZkNrW2hrW2iezFTKmmzFmgzFmQ8zszy+jehAWUpoDmVLHBxOTMlKwp4WGlOGA56xomsvFsRMnKVXCfeXWwcNJ9Br+FiOff5rKWTrw//2yhzRXOrWqXX9ZdfS1mbPn0OHBznR4sDPlypbl4MH4jGUH4xMICw29oO2cOHGSnbt28WjXHrRs34Et32+nx39e4PsdFzXHX3zE3ZbPnL0/eDgx57Z8KFNbPnmSUiWCL2j7hQMDaXV73WyXMzht5rwv6Ph0Xzo+3ZfQMqU5kHDmkr6DhxMJy3R2FCCsbAgHM/+/HEokzJO1DCldKuOSqoTEI5QpVTLb+912c01+OxDPkT+ScyOcsworW4YDmS5XPHgokbCQMl5lQjOVOdM3BRMWkmXdw2diPq1EUHEa3FKL2A3e1+YHBATQvnkjlvhxrk1YpnYKF9iWT1xsW66X7RJCf8jNWAe8FcO1FcLpct/dvq30ZcjeTyVlb9chpc/aTx08nEiv18cwsm+PbJ+5VyPNwZArTSzwoDEmwBhTDndGYd05yv8EVDHGXOd5/uBZyh0DMvd6v+K5/AnolOn15cC/AIwxtYCbPa+vwX1JVjXPsuLGmBvIwlobY62tZ62t1+3B+7IuvigR1auw5/eD7DuYQEpqGouWr6Fl/TpeZVo2uJW5S1cA7rRsw5trYIwh+fgJnh48mr5d/kmdGtmqycJla7i7qf9T8Fl1fvAB5s2eybzZM2ndohlzFyzCWsuWbd8THBR01rkWWQUHB7H226/4ZtE8vlk0j9oRtYgeN/qKvYvUlS7ihqpZ2vJqWjas61WmZYO6zP16OQCLV6yl4c01z5kWP/HnXyR45qWkuVwsW7eZKpUq5F4QF6Bzh7uYOyWKuVOiaNWoPvO+XuZuvz/sJLh4sYxLnk4LDSlNULFibPlhJ9Za5n29jFa3uxO2LW+vx9yvvgVg7lff0uoO9+t79h/AWgvAjp93k5KadsFfXn0l4sZq7Nl/gH0H4klJTWXRspW0vP02rzLu+n8HwOLlq2lYuxbGGFrefhuLlq0kJSWVfQfi2bP/ADffWI2ko3+QfPwEAH+dOsWqTVupUukarLXs2X8AcM/B+GbNeqpUusbReDOLuDFLW162ipYNvW+U0bJhPeZ+7b6j3eLYNTS85QLacmLeasuQO7ECjJsxi2MnTvJy9y65VvdLEXFDVfbsz9JPNcihn1oaC3j3U8nHT/D0oFH0fewh6tTIm/Ma5eKZ052tXLlO36bWM3H7TeAuwAKvW2tnG2Oa475d7D2e8hOADdbaGcaYvwOjgBPAeiDYWtvZGPMYUM9a28sY0wiYijsL0gkoBHyCOxOyEPi3tfY6Y0xRYDruOSA/AtcAPa21G4wxLYGRQGFPtV+11v73bDHZnesuu2Eu27CF4VNnkp6ezj9aN6X7gx0Y/+Fn1Kp+PS0b1OFUSgqRYybz4+49lAwKYkxkTyqFhxI9ey4xc+ZzbYXwjG1NGxJJiOcsaOuufYgZ+ILPPsRMRd93qNZahowYReyq1RQtUoThg17LGCB0eLAz82bPBODNceNZ8MUSEg4dIrRcOR647156d+/mta1HunYn8vlnfTbA6F68kk+2c6Ge/OhdbmjemKCyISTHJzB/4HBWvfuBI+8dHfedT7azbP1mhntuU/uPO5vT/aH7GP/BHHdbbljP3ZZHT+LHXb9SMjiIMf16Z1w60fKx3pw4+SepaWkEFy/OtGEvUSo4iO6DRpGSmoq1lvo31+Clbo9SMCDg8ipayDc3BLDWMvTtd4jdsJkihQsz/IWeRNxYDYCOT/dl7pQoAL7/KY6XR0/gr1MpNLntVl7r1RVjDEeSj/H80CgOJByiQlg5xr7al1Ilgpk663Pmff0dBQMKUrhwIJHdHr3029RexmfnsnWbGO65Te0/2rak+7/+wfj3ZlHrhqq0vP029/4cOf7M/nz5+Yz9Ofmjz/hs8Tfu2+x2f4ym9evw0+5f6T9qAq70dGy6pV2zO+j57wdIT0+nc5/XOH7yT7CWG6tcy6Bnu2VMir4o6a5Ljtc79s0Mn/Lembb88P2Mf/8TalWvQsvbPW35zQlnYn/puTNt+dFenDh50t2Wg4ozbdgrlCoRRPcBI0lJTcPadOrfUpOXnu5y+W3ZB3wda1CxojR/5BmqVKqQMUeh89/b8sBdrS6voi4f7dv1mxke4741/D/aNKf7Qx09/VQVWjase6af2r2HksHFGRPp7qeiZ31OzCf/9f7Mfb0/IaVKMurdj1jw3SoSko4QWqY0ndo2p3fnTueoxfmZanX9PnlyR5Uqjn75rrl7t+Mxa4CRzxljgqy1xz2Dk4nAz9basf6uly8GGFeK3Bhg5GVODzD8yVcDjCuGjwYYV4T89tnpowGG5EE+GmBcKTTAcIYukZKnPBOvdwAlcd9VSkRERETkkuiXvPM5T7bC7xkLERERkfwgj97h3qeUwRAREREREZ9RBkNERERExCEF8kEKQxkMERERERHxGWUwREREREQckg8SGMpgiIiIiIiI7yiDISIiIiLikPP9YvvVQBkMERERERHxGWUwREREREQcYvLB6f18EKKIiIiIiDhFGQwREREREYdoDoaIiIiIiMhFUAZDRERERMQh+SCBoQyGiIiIiIj4jjIYIiIiIiIO0RwMERERERGRi6ABhoiIiIiI+IwukRIRERERcUg+uEJKGQwREREREfEdZTBERERERBxSIB+kMJTBEBERERERn1EGQ0RERETEIfkggaEMhoiIiIiI+I4yGCIiIiIiDtEP7YmIiIiIiFwEZTAkbyoQ4O8aOMb+HufvKjgqOu47f1fBMT2qNfd3FRw16cfF/q6CY0xwGX9XwVk23d81cM6fx/1dA0el7/vZ31VwVEC1uv6uguZgiIiIiIiIXAxlMEREREREHKIMhoiIiIiIyEVQBkNERERExCGmwNWfwlAGQ0REREQknzLGtDPG/GSMiTPG9D9LmX8aY34wxuwwxnx0vm0qgyEiIiIi4pC8NAfDGBMATATaAPuA9caY/1prf8hUpjrwEtDIWnvEGBN6vu0qgyEiIiIikj/VB+KstbuttSnALKBDljJPAROttUcArLUJ59uoBhgiIiIiIvnTNcBvmZ7v87yW2Q3ADcaYlcaYNcaYdufbqC6REhERERFxSAGHr5EyxnQDumV6KcZaG3MRmygIVAeaAxWB5caYCGvt0XOtICIiIiIiVyHPYOJsA4r9QKVMzyt6XstsH7DWWpsK/GKM2Yl7wLH+bO+pS6RERERERBxijLOP81gPVDfGXG+MCQQeAv6bpcxc3NkLjDFlcV8ytftcG9UAQ0REREQkH7LWpgG9gMXAj8An1todxpghxph7PcUWA4nGmB+Ab4EXrbWJ59quLpESEREREXGIyUv3qQWstYuARVleG5Dpbwv08TwuiDIYIiIiIiLiM8pgiIiIiIg4JI8lMHKFMhgiIiIiIuIzymCIiIiIiDgkr83ByA3KYIiIiIiIiM8ogyEiIiIi4pB8kMBQBkNERERERHxHGQwREREREYdoDoaIiIiIiMhFUAZDRERERMQhJh+c3s8HIYqIiIiIiFM0wBAREREREZ/RJVJy2YwxQ4Dl1tqv/V2XzGI3bGVYzPukp6fT6c4WdPvnvV7LU1JT6RcVzY64XygVHMSY/s9SMawcR5KP8dzwt9j+8y46tm7KgB6PZ6yzaPlqJs+eS3p6Os1vq8MLTzzsdFgX5FJjX7n5e6Kmf0xqmotCBQOIfLIzDW+p6acozi12wxaGTfHE2LYF3f7ZwWt5Smoq/UZPOhPjS89l2r/j2L5zFx1bN2PAM2f2b9fX3uBQ0lFcLhd1a97EgGeeICDgyjoP88i0iUTc045jCYcYGtHQ39W5JLGbtjF86kfufdumKU91usdreUpqKv3GTuWHXb+69+2LPbgmrBzbdu5m4KTpAFgLPR/qSJvb6wLQ6qm+FC9alIAChoACAXw6ZpDTYeXIWsuwCVNZvnYDRYoU5o3I/1DzhqrZym3fGcdLI9/i1KlTNG1Qj1d6PYUxhjcnT+fb1esoVKgglcuXZ3i/ZykRFJSx3u/xh7jn8Z707PIwTz54n5Oh5chay7CJ77B87UaKFC7MG5HPnj3eN8dz6lQKTRvU5ZWeXTHG8OWylUx4bxa79u7jk4mjiLixGgD7DsZz9+O9ub5SBQBu+duNDH6+h6OxZRW7cSvDYj7w9MPN6fZADv3wmMmePiqYMf16nemHZ8wmNS2NQgULEvnEwxn98CP9X+fQkaMUCQwEYNrQfoSUKul4bOcTuyOONz75Eld6Op0a1eGpdo29lm/4eQ9vfPIlO/fHM/rJTrStWwOA/YlHeXbybNKtJc2VTucW9XmoaT1/hJCrNMlb5DyMMQHW2gF5bXDhcqUzJHo6UwdHsiB6FAuXryJu7z6vMp8u/o4SQcVZ8s5YunS8i6jpHwNQOLAQzz3SicgnO3uVP5J8jFHvfsSM4a+wIHoUh44eZfWW7Y7FdKEuJ/bSJYKJHvgi8yeNZESfHkRGTfJHCOflcqUzZNJ0pg7px4LJo1m4LKcYv3XHOG0cXe5rT9S7HwGn9+8D2fYvwLiXnmPexJHMjx5F0h/H+HLFGkfi8aXVM2bydrv7/V2NS+ZypTN0ygfEDOzD/AnDWRi7lri9+73KfPrVckoGFWPxlDd59N47Gf3eHACqX3sNc6IG8fm4ocQM7Mug6BmkuVwZ6733ej8+Hzc0zwwuAJav3cie/b+z+IMpDOnTk8HjonMsN3hsNEP79mTxB1PYs/93YtdtAuCOurWZ/+4E/vvO21xXqQIxH33qtd6I6Gk0qV8n1+O4UMvXbWTPvgMsfj+aIX2eYfBbk3MsN3jcFIb26cni96PZs+9ARrzVr6vM+MH9qXdzjWzrVK4QztyYccyNGef3wYW7H37P3Q9PepOFy9Zkb8dLvqNE8eIsmTqGLh3aETVjFuDphwf0Zf7EEYx4/mkio7z/j0a98Axz3x7O3LeH58nBhSs9ndc/XsSUXp2ZP7Ani9ZvJ+73Q15lypcuyfAuHbn7tgiv18uVDObjyCf5/NXuzOrXlXe+XEHC0WNOVl98RAMMOStjzHXGmP8ZY2YaY340xnxqjClmjPnVGDPSGLMJeMAYM8MY08mzzm3GmFXGmK3GmHXGmGBjTIAxZpQxZr0xZpsx5uncrvu2nXFUrhBGpfJhBBYqSPumt7N0zUavMkvXbqBjqyYAtG3cgNVbt2OtpViRItSteROBhQp5ld93MIFrK4RTpmQJAO6oXYslK9fldigX7XJir1H1OsJCSgNQ/dqKnDqVQkpqquMxnI87xnDvGFdv8CqzdM1GOrZuCpxl/3rOAGYWVKwYAGkuF6lpaRiuvLNMcbGrOJl0xN/V+H/27js+imr94/jnSeiEmpBCE6Qp0rtSpOu1gcpVf7bLtaAComJBwAsizQJSBQFRLFjAElTQSO9NRFBQqiI1FGEI9wAAIABJREFUgdCLBJLz+2OXJaEltNkI3/frxYudmWdmz7OTPbtnzjmz52z5mvUUj46iWHSk79zWr820RUvTxExbuJQWjX1XRG+oW5MFy1finCNn9uxkCQ0FfFeH/wnnb+q8hbRo1ggzo0r5q9i7/wAJiTvTxCQk7mT/wYNUKX8VZkaLZo2YMtfX+K1Xs2og58pXl2Pb9sTAflPmLKBodBSlSxT3LqF0TJ27iBbNG/rzLZdOvuV8+TZvyJS5CwEodUUxrixWJBhFPyvLV6+jeEyqv+MGdU6uhxf8lKoersX8ZStOXQ8nZc56+HR++XMzxSMLUqxQAbJlCeVfNa9h2vLf08QUichPuaJRhJxwJT9bllCyZfUNrjly9CgpznlWbk+FmLf/gpFiUJ5V/knKAcOcc1cDe4G2/vWJzrlqzrlPjwWaWTbgM+Ap51xloClwCHgY2OOcqwnUBB41s5IXs9DxibuIiQgPLEdHFCT+pA+xXcQU8sVkCQ0lT65c7N57+islxWOi+GPTVjbFb+docjJT5v/I1h2Jp40PlguVe9zcRZQvVeKkhlZmcHKO4cQnpv1SnZC486zO7zEPv9SXuvc+Tu6cObihXu0LW3BJV0LiLqIjCgaWo8ILnHRu43fuIsYfkyU0lDy5c7J7334Alq1axy3tu9Ciw0t0f+I/gS/fhvFw937c2bE74+JmeJNMBsTvSCQmslBgObpQOPEn1CvxOxKJLhSRKibipBiAL76bQgN/b8WBQ4cY9ekXtPvPPRep5OcmfsdOYtLkEk78jp0nxUQXOuH9fULMqWzaFs/tjz3D/c905cflKy5coc9BfOIuYgod/zv21cMn1lHHY47XUfvTxMTNXXxSPdxl4EhaPtmFYZ98hcuEX8Djd+0jukDewHJ0/rwk7Mp4L8TWnXto2XM4jTsP4JEb6hKZP8/FKKZcZJqDIenZ6Jyb63/8EdDB//izU8SWA7Y65xYDOOf2AphZc6DSsV4OIB9QBvgj9c5m1gZoA/B2zy60uSdzDfPIlyeM7u3+S8dXB2MhRtWry7Jxa3ywi3VRrNmwif7vfcLoXp2DXRTPje7VmcNJSTz3+lssWPYrdatVCnaR5CxULleKb4f2Yd3GLXQeNIoG1SuSPVs2xr7alajwAiTu3svD3d+gZNEYal5TLtjFvWDe/mgcWUJDubVpQwCGjvmE1q1akDtnzuAWzCORBQsy7eNRFMiXl19Xr6V9t758O3oIYblzBbto52zNhk30H/Mpo3t2Cqzr91xboiIKsv/gITr0HcSEaXMCvSCXipiC+Yj93xMk7N7Hk8M/pXm18kTkDUt/x3+Sy2AOhhoYkp4TL48cWz5wFscw4EnnXNwZn8i5kcBIALd2yXldlokKL5Cmd2Hbjp1EhRdMExMZXoCt2xOJjgjnaHIy+w4eJH/eM18paVy7Oo1r+yaNfvbdVEJDMl8n4Pnmvm1HIu17vclrzz5B8ZgoT8ueUSfnmBgYUnBMZHjBsz6/x2TPlo0m11Zn6oIlamB4LDK8ANtSXa2OT9x10rmNKliArTt2Eh1R0HduDxwif560X0BKFStMrhw5WLNhMxXKlAwcIzx/XprWqcYvq9cHrYExNnYi4yf+AEDFcmXYmnB8fPq27YlEpeqdA4iKCGfb9h2pYnakifny+6lMX7CYMf16BSaPLv99NXGz5vHGiDHs23+AkBAje7as3H972gnzXhgbO4nxk1LlmyaXRKIi0tZPUREF0wz12rbj5JgTZcuWlWzZfFf5K5QtTbHC0fyxaUtgErjXosILsHX78b9jXz18Yh3li0lbR4X54xNp33sgr3V8PE09fOx1CMuVk1uuv47lq9dnugZGVIE8bNu1N7C8bfdeIgucfS9EZP48lC4SyZI1fwUmgcs/R+b7diSZTXEzu9b/+F5gzhliVwExZlYTwD//IgsQBzxhZln968uaWe6LWeiKZUuxYfM2Nm1LIOnIUSbNmh9oGBzTuHZ1YqfOBiBuzkLqVLom3Ts7JO7eA8Ceffv5ZOIUWt3Q6OIkcB7OJ/e9+w/w2Mtv8Gzre6hWPvNe3a1YthQbtpyQY51T5DhlFpCx83vg0N8k+OcuHE1OZuaipVzpvyONeKdimZJs2BrPpvjtvnM7eyGNalVNE9OoVhUmTPNVRXFzF1On0tWYWWD4IsDmhB2s37SVIlERHPz7MAcOHgLg4N+Hmbt0BWWuCN44/vta3kzsqEHEjhpEk3q1mTB5Os45fl75O3ly5yLypAsCBQnLlYufV/6Oc44Jk6fT5Drf8L3Zi5Yw+rMvGd7rJXLmyB7YZ+ygV5n2yTtM++QdHrzzVtrc+++gNC4A7mt5U2DydZO6tZnwwwx/vqvIkzv3GfJd5cv3hxk0qVvrjM+xc/cekv3nfuOWbWzYtJViQbxAUrHslSfUUQtoXDvtZPvGtaulqocXUadS+VT1cH+ebX031cqXDcQfTU5m1x7fUKMjR48yY9FSyl5R1LukMqjCFUXYkJDIph27SDqazHeLV9CoUsY+T7bt2svfSb75JnsOHOKntX9RMjo8nb3+eczM039ByTEzjt+TzMHMSgDfAz8C1YGVwAP+/2s453b448YA3zrnPvc3LoYAOfHNv2gKHAR6Abfi683YDrR0zu053XOfbw8GwMzFS+njv0Xgnc0a8vg9LRn84XgqlLmSxnWqczgpiRf6DeO39RvIlyc3b77wZOADqfF/O3Dg4CGOHD1Knty5Gd3rRUoXL0rH14aw6o+/AGj7f7dz8/XXnW8xL4pzzX34p18xctzXXFE4OnCs0b1evLB3KrlAld3MxUvp479N7Z3NG/L4Pbf7cyxJ4zo1jue47k/y5QnjzU6pzm/rJ9Oe396dyZ8njMdffoOkI0dwzlGrUnk6t3kwMIb/XDxRuuEFyfVsPPzxu5RtWI+wiHD2xifwTfc+zHv3Q0+ee9hvZ+ykzLCZPy6j72jfbWrvaFKfx++6jcFjv6RC6ZI0rl2Vw0lJdBowkt/W/0W+PLnp/9wTFIuOZML0uYz6YiJZs4RiFkLbu2+jaZ3qbNyWwJN9hwC+L2m3NKjD4yfcuvlsWZ4zX1HPKOccPQePYPain8iRIzt9XuhAxXJlAGj56FPEjhoEwC+r1tDltUH8fTiJ+rWq8b8Oj2FmNL+/DUlHjgZ65yqXL0ePZ9qmeY4hYz4mV86c53ebWpdy7vumPoxz9Bw8ktmL/fk+3yHQy9CyzdPEjhwIwC+r1tLl9cH8ffgw9WtV539P+m7LO3nOAnoNGcXOPXvImzs3V5UuyejXXiZu1jyGjPmELFlCCbEQ2v/nHhpfd+ZGyWkd2p9+TAbMXPwzfUZ95K+Hr+fxu1sw+KPPfXVUbX893P9tflv/J/nCwnizU3uKRUcy/NNYRo7/hisKH28gje7ZiZw5snN/p14cTU4mJSWFaytfw4uP3H/et9JO2bTmfFM9ycxf1vDq+O9JSXHcfl0VHr+pAUO+ns41VxSmceVy/PLnZjq8/Rl7D/5NtqxZiMgbxjfd2zJv5Tpe/+IHDMPhuLdhLe6qXz39JzwLoY3uDfr4pL2Nq3r65TvvtKWe56wGhpyWv4HxrXOugtfPfSEaGJJJXQZjT48JRgMjmC5UA+Of4EI1MP4xLlAD4x/hAjUw/ikuRgMjM8sUDYym1bxtYEz5yfOcNURKREREREQuGE3yltNyzv0JeN57ISIiInLJugx68tWDISIiIiIiF4x6MEREREREPGJB+nVtL6kHQ0RERERELhj1YIiIiIiIeEVzMERERERERDJODQwREREREblgNERKRERERMQjmuQtIiIiIiJyFtSDISIiIiLiFU3yFhERERERyTj1YIiIiIiIeEVzMERERERERDJOPRgiIiIiIh4xzcEQERERERHJOPVgiIiIiIh4RXMwREREREREMk49GCIiIiIiXtEcDBERERERkYxTD4aIiIiIiEfsMri8fxmkKCIiIiIiXlEPhoiIiIiIVzQHQ0REREREJOPUwBARERERkQtGQ6Qkc8qeM9gl8M5l0FWaRkpysEvgmWG/xQW7CJ5qe/UNwS6CZ4ZvXBjsInjrcpiVekz2XMEugacs6opgF+GyY/qhPRERERERkYxTD4aIiIiIiFcug5EL6sEQEREREZELRj0YIiIiIiJe0RwMERERERGRjFMPhoiIiIiIR0xzMERERERERDJOPRgiIiIiIl7RHAwREREREZGMUw+GiIiIiIhXNAdDREREREQk49SDISIiIiLiEd1FSkRERERE5CyoB0NERERExCu6i5SIiIiIiEjGqYEhIiIiIiIXjIZIiYiIiIh4RJO8RUREREREzoJ6MEREREREvKJJ3iIiIiIiIhmnHgwREREREa9oDoaIiIiIiEjGqQdDRERERMQjpjkYIiIiIiIiGaceDBERERERr1wGczDUwLhIzOw2oLxz7tUzxBQGBjvnWnlXsowzsxrAg865DmeIKQF865yrcIptrYEfnHNbLlYZ0+Oco/dbo5m1aAk5smen7wtPck2ZUifF/bp6HZ1fH8zhpCQa1KpO13YPY2Z8P3MuQz/4jHV/bWLc0NepWK40AHOX/Ez/dz7kyJGjZM2ahRfa/Ic6VSt5nV4avlzfYdbCY7l24Jqyp8p1rS/Xw0k0qF2dru0eOZ7r+5/6cn3rjUCu30yZyehxXwX2X7V+A1++3Z+rS1/pWW6n4pyj97B3mbXoJ3Jkz0bf55/kmjInl+nX1evo/MZQ/7mtRte2D2Fm7N67j46932TztgSKREcy4KVnyZcnjKnzFjFozCeEWAihoaF0aftfqle4OggZHjf7p+X0GfUxKSkptGrWgEdb3ZJme9KRI3QaMIqV6/4kf54w3nz+CYpEFWL56vV0H/YeAM5Bu3ta0uza6gA0efRZcufMSWiIERoSyudvvux1WuftgdFvUfGWG9mXsJ2eFesEuzjn5LJ83w4dxayFP5IjR3b6vvD06fN9bRCHDx+mQe0adG3/KGbG62+/x/T5i8iaNQvFY2Lo06kDecPC2LQtnptbt6NksSIAVC5fjh7PtPU6PX+9NNpfL2Wn7/PtT/+Z88aQVPXSw6nqpf5s3radItGFGPDSc+TLE8bocbF8M3UWAMkpyaz7azPzxr9H/rx5fOuSk2nV7gUiIwoyoldXT3M+ZvZPv9Bn9MekpDhaNa3Po3fenGZ70pEjdBr0DivXbSB/nty8+dwTFImMCGzfsj2RWzu8RLu7W/BQyxsB6DrkXWb8uIyC+fLyzeCenuYj50dDpC4S59zXZ2pc+GO2ZNbGBYBz7sczNS4yoDVQ+AIV55zMWvQTGzZvIe79YbzyzBP0GDTilHE9Br1Nz45tiXt/GBs2b2H24p8AKFOiOINf7kSNiuXTxBfIm5fhPbvyzTuDePWFDrzw6qCLnkt6Zi1awoZNW4n7YDivdGxLj0FvnzKux8AR9OzYjrgPhrNh01ZmL0qVa48XqVEpba63Nr2e2JEDiR05kNdefJqi0ZFB/5ICx87tVuLGDOWVp5+gx+CRp4zrMXgkPZ95grgxQ9mweSuzFy8FYNRnX1GnakXi3n+LOlUrMupT35exOlUrMmHEm8SO6E+f59ry0pvDPMvpVJKTU+g54kNGdu/IN0P7MHH2Qtb+tTlNzOeTZ5EvLBdxI17nwdua0+/98QCUuaII4/u/zFcDezKy+7O8PHwMR5OTA/u936sTXw3s+Y9sXADMHzOWITfeEexinJfL7n27cImvTv5wBK90bEePgcNPGddjwHB6PtuOuA9H+Opkf77XVa/CN+8O5et3hlCiWGFGfvx5YJ/ihaOJHTWI2FGDgtK4gNT10lu88vTjZ6iXRvjrpbdOUS9V8tdLlRj16ZcAPHxXS2JHvEnsiDd55qH7qVmpfKBxAfDBVxO5snjRi5/gaSQnp9Bz5EeM/N8zfDO4FxPnLGTtxhPqqSmzyZc7N3HDX+XBW5vT74Pxaba/9t6n1K9aMc26lo3rMrJbx4tefs+FmLf/gpFiUJ71H87MSpjZ72Y2xsxWm9lYM2tqZnPNbI2Z1TKz1mY21B8/xswGm9k8M1tvZq1SHedX/+PWZhZrZpPN7E8za29mHc1sqZktMLOC/rgZ/p4FzCzCzP48m/1Pk88MM3vNzBb586nvX9/QzL71Py7kP/YKM3vHzDaY2bFLD6FmNsq/7Qczy+nPsQYw1sx+9q971cxWmtlyM+t3Mc7NiabOW0SLZo0wM6qUL8fe/QdISNyZJiYhcSf7Dx6iSvlymBktmjViytxFAJS6ohhX+q+IpVa+zJVERfhe0jIlinM4KYmkpCMXP6EzmDp3ES2aN8xArgeP59q8IVPmLgROn2tqE6fN5qZG9S9aDmdj6vzFtGh6vT/fsv58d6WJSUjc5c+3rC/fptczZZ7v3E6dt5iWzRoB0LJZo8D63DlzYv7u64N/H8YIblf28jXrKR4dRbHoSLJlzcJN9WszbdHSNDHTFi6lReN6ANxQtyYLlq/EOUfO7NnJEhoK+K4eBjuXC23t7Hkc3Lkr/cBM7LJ7385bmKpOviqdfK9KVScvAKBezaqBv+nKV5dj2/ZEz3M4k6nzF9GiaUbOZ6rPnKYNmTLPdz6nzltEy2YNAWjZrGGgXkpt4vQ53JzqfG7bvoOZC5fw7381vXiJpWP5mvUUj4k8Xk/Vq820RT+niZm2aCktGl0HwA3X1WDB8t9wzgEwZeFPFI0sROniaa9J1rymHPnz5PYmCbmg1MA4d6WB/sBV/n/3AvWA54Aup4iP8W+/BThdz0YF4A6gJtAbOOicqwrMBx7MQJnOZ/8szrlawNNA91Ns7w5Mc85dA3wOFE+1rQzwln/bbuBO59znwI/Afc65KkAu4HbgGudcJaBXBvI5b/E7EokpFB5Yji4UTvyOnSfE7CQ64sSYjH9oxc2eT/nSV5ItW9bzL/B5iN+xk5hCx7ubT5tr6tcj4uSYM/luxhxubpw5vqjE79hJTKrudV8uiSfEJJ7i3PryTdy1m8jwAgAUKpifxF27A3GT5yzkXw89yeMv9aH3c+0uZhrpSkjcRXTE8esDUeEFiD+hIRW/cxcx/pgsoaHkyZ2T3fv2A7Bs1Tpuad+FFh1eovsT/wl8OTOMh7v3486O3RkXN8ObZOQkl9/7NpGYyEKB5VPVt/E7EolO85pEnLJO/uK7KTSoVS2wvGlbPLe3eYr7n+7Mj8tXXITSp+/U9VJGPnNS10u+93KhggXS1EsAh/4+zJwfl9K83vEhgX2Gv8tzjz4Y1DsTJezcnX49lbg7bT2Vy1dPHTj0N+98+R1t777N0zIHk5l5+i8YNAfj3P3hnPsFwMxWAFOdc87MfgFKnCI+1jmXAqw0s6jTHHO6c24fsM/M9gDf+Nf/AmRkgP/57P+l//8lpyl/PXwNBJxz35tZ6prjD+fcsUsVp9t/D/A3MNrfK/JtOuX5R1jz51/0H/UBo187VZvs0rLst9XkyJGdsiWvCHZRLrgTK+Fm9WrTrF5tFi9fweAxn/De6y8Hr3DnqXK5Unw7tA/rNm6h86BRNKhekezZsjH21a5EhRcgcfdeHu7+BiWLxlDzmnLBLq5cYJfq+/btj8aRJTSUW5s2BCCyYEGmfTKaAvny8uvqtbT/Xx++fXcoYblzBbeg5+FUXw6nL1hM1WuuCgyPmr7gR8Lz56NC2VIsXPZrMIp53t76bAL/ua0ZuXPmCHZR5AJSA+PcHU71OCXVcgqnfl1Tx5+uOZmRYx7leM/Tie/Gsy3TqfZNzkDs6fY9tn/OEwOcc0fNrBbQBGgFtAcap44xszZAG4C3+3anzX13nWUxfMZOmMT4SZMBqFi2NFtTdaFv254YGNp0TFREQbbtODEmnPRs276D9t1f5bVOT1G8cMw5lfV8jY2dxPhJPwBQsVwZtm7fkap8p8k19eux4+SY05k0fXaabvlgGDvhO8ZPmgJAxXKl2ZqQKt8dJ5+3qIjwU5xbX77hBfKTkLiLyPACJCTuomD+fCc9X81K17Bx61B27dlLgXx5L0ZK6YoML8C2VFdA4xN3EeXveTkmqmABtu7YSXREQY4mJ7PvwCHy5wlLE1OqWGFy5cjBmg2bqVCmZOAY4fnz0rRONX5ZvV4NDI9cdu/b2ImMn5gq34TtgW2nqm+jIsLZluY12ZEm5svvpzJ9wWLG9OsV+AKeLVvWQC9yhbKlKVY4mj82baZiuTIXLa9jfPWS/zPnlPVSRj5zUtdLO4kML0hC4s6T6qVJM+Zwc6N6geWfVvzOtPmLmbnoJ5KSjrD/4EGef3Ugb7z49AXP80wiC+ZPv54Kz5+2njroq6eWr15P3Lwf6ff+ePYdOEhISAjZs2XlvpuaeJqDp/Q7GJIJ/QlU9z/2coL4XOAuADNrDhQ4czgA+4A8/n3CgHzOuUnAM0DlE4OdcyOdczWcczXOtXEBcF+Lm4gdMYDYEQNoUrc2EyZPxznHzytXkSd3rkD38zGR4QUJy5WTn1euwjnHhMnTaXJdrTM+x979B3isa2+efeQBqgXxDkP3tbwpMJGzSd3aTPhhRqpcc58m11zHc/1hBk3qnjlXgJSUFL6bMTfoX1Tua/EvYkf0J3ZEf5rUrcWEKTP9+a72n9u0f5aR4QX8+a725TtlJk2urQlA42trEDt5OgCxk6fT5Drf+g2btwbGBa9Ys56kI0fTTKb0WsUyJdmwNZ5N8dtJOnKUSbMX0qhW1TQxjWpVYcK0OQDEzV1MnUpXY2Zsit8emNS9OWEH6zdtpUhUBAf/PsyBg4cA3zyTuUtXUOaKM4/jlwvnsnvftrw5MPm6Sb3UdfLvZ6iTc/Hzyt9T1cm1AZi9aAmjP/uS4b1eImeO7IF9du7eQ7L/b33jlm1s2LSFYjHR3uTX4l+BCdi+emnG2X3mTJlBk2t957PxtTWJnTwDgNjJM9J8Fu07cIDFy1cGYgGeffh+Zn7yDtM+GkH/rh2pXaWi540LOEU9NWchjWpWSRPTqGYVJkyfB0DcvB+pU9E3x+ajPp2ZOvINpo58gwdvbUabO2++tBsXlwn1YPzz9APG+a/2T/TweXsAn5jZA/jmdGzD14AIO8M+Y4C3zewQ8C9ggpnlwNeD48ltIa6vXZ1Zi5bQ/MEnyJE9O32efzKwreVjzxA7YgAA3To8Rpc3BvP34STq16oWGNc7ec4Ceg19h5179vB4115cVaoko1/rztjYSfy1ZSvDPhrHsI/GATD61e6EF8jvRVqndH3t6sxauITmDzxOjhzZ6fP88RuAtWzzNLEjBwLQ7anH6PL6YP4+fJj6tarToJavvTp5zgJ6DRnly7VLT64qXZLRr70MwOLlK4iJjKBYYW8+sDPi+lrVmLXwJ5r/p53v3KaaK9HysWeJHdEfgG5PPkqXfkN957Zm1cC5ffSeO3imZ3+++G4qhaMKMeClZwH4YfYCJkyZQZbQLGTPno0BL3UM2hhW8I1VfqnN/Tzycj9SUlK4o0l9yhQvwuCxX1KhdEka165Kq2YN6DRgJDc89gL58uSm/3NPALBk5WpGfTGRrFlCMQuh2+MPUCBvHjZuS+DJvkMAOJqczC0N6lC/WnBvs3wuHv74Xco2rEdYRDh9N/7GN937MO/dD4NdrLNy2b1va9fw5Xv/Y758X0iV76NPETvKd0e+bk8/TpfXBh2vk2v78u05eARJR47y0PPdgOO3o128fAVD3htLlixZCDHj5WfaBuXCwPW1qvvrpbb+eqn98fwe60jsiDd9+T3Zhi79hvjrpWon1Ev9TqqXwDc3rG71yuTKhEOJsoSG8tKj9/NIjzf99VQ9Xz318VdUKF2CxrWq0qppAzoNHMUNT7xIvrDc9H/2sXSP+2z/t1m0YhW79+6n4SPP0v6eFrRq2sCDjC6yy+B3MOzYlTqRMzGz7ECyf6jTtcBw/+Tti8JtXHn5/GFeBhVNGinJ6cdcItzBfcEugqfaXn1DsIvgmeEbFwa7CN6yy2jAQ/LRYJfAU27/7vSDLiEh5esG/UP36JO3evodJ8uQbzzPWT0YklHF8fWchABJwKNBLo+IiIiIZEJqYFxGzOwtoO4Jqwc5595Lb1/n3BqganpxIiIiInIGl8HIBTUwLiPOueDe0F9ERERELnlqYIiIiIiIeOUy6MG4jGZtiYiIiIjIxaYGhoiIiIiIV0JCvP2XDjO70cxWmdlaM3vxDHF3mpkzsxrppniWL4mIiIiIiFwCzCwUeAvf75WVB/7PzMqfIi4P8BSQoXt0q4EhIiIiIuIVM2//nVktYK1zbr1zLgn4FGhxiriewGvA3xlJUQ0MEREREZHLUxFgY6rlTf51AWZWDSjmnJuY0YPqLlIiIiIiIl7x+C5SZtYGaJNq1Ujn3MgM7hsCvAm0PpvnVANDREREROQS5W9MnK5BsRkolmq5qH/dMXmACsAM8zWMooGvzew259yPp3tONTBERERERLySuX4HYzFQxsxK4mtY3APce2yjc24PEHFs2cxmAM+dqXEBmoMhIiIiInJZcs4dBdoDccBvwDjn3Aoze8XMbjvX46oHQ0RERETEKxn4bQovOecmAZNOWNftNLENM3LMzJWhiIiIiIj8o6kHQ0RERETEK5lrDsZFoR4MERERERG5YNTAEBERERGRC0ZDpEREREREvKIhUiIiIiIiIhmnHgwREREREa+oB0NERERERCTj1IMhIiIiIuKVTPZDexfDpZ+hiIiIiIh4Rj0YIiIiIiJe0RwMERERERGRjFMPhmRKljci2EXwTMrWdcEugqcsZ1iwi+AZy1Mw2EXw1PCNC4NdBM88Uax2sIvgqQci8wW7CJ65btGkYBfBU+77z4JdBG+VrxvsEqgHQ0RERERE5GyoB0NERERExCvqwRAREREREck49WCIiIiIiHjE9DsYIiIiIiIiGaceDBERERERr2gOhoiIiIiISMapgSEiIiIiIheMhkiJiIjacOb3AAAgAElEQVSIiHhFQ6REREREREQyTj0YIiIiIiJeUQ+GiIiIiIhIxqkHQ0RERETEK/qhPRERERERkYxTD4aIiIiIiFc0B0NERERERCTj1IMhIiIiIuIV9WCIiIiIiIhknHowRERERES8oh4MERERERGRjFMPhoiIiIiIV/Q7GCIiIiIiIhmnHgwREREREa9oDoaIiIiIiEjGqQdDLhvOOXr3H8TMeQvIkSM7r3brwjVXlTspbsCwkcROimPvvn0snflDYP3in36mz4DBrFq7njd7defGJo28LH66Zv+0nD6jPiYlJYVWzRrwaKtb0mxPOnKETgNGsXLdn+TPE8abzz9BkahCLF+9nu7D3gPAOWh3T0uaXVudPzZtpWO/YYH9N27bzpP33s5/brvB07yOmb14Kb2Hv+fL78YmtLnn9jTbk5KO0OmNIaxYs96XX9eOFI2OBGDEJ1/yRdw0QkJC6Nr2IerXqMLhpCTuf7YbSUeOkJycTPP619LhwbsB6Np/GL+uWYdzjhJFCtP3+XbkzpnT85yPcc7Re+goZi38kRw5stP3hae5pmypk+J+Xb2Wzq8N4vDhwzSoXYOu7R/FzHj97feYPn8RWbNmoXhMDH06dSBvWFhgvy3x27nlv+1o95//4+G7bz/puF5zztH7rXeYtXAJObJnp+8LHU6f7+uDOXw4iQa1q9O13SOYGd/PnMvQ9z9l3V+bGPfWG1QsVxqAb6bMZPS4rwL7r1q/gS/f7s/Vpa/0LLfz8cDot6h4y43sS9hOz4p1gl2c85a/UUOu7PUyhIYSP/YTNg8ZlmZ7yVe6k7futQCE5sxJ1ohwFpatENgeGhZG1dnT2PldHOu7/M/Dkp/eha6ntibsoNMbQ0jctQczuOumZjx4+80AfD9rHkM/HMe6vzYzbkhfKpYt7Xm+p1XiakIa3gEhIbhf5uMWT0mz2SrVxarUh5QUOHKYlMmfwc5tkCMXIbc+DFHFcSsX4qZ9Hpzyy3lTD8ZFYGYzzKyGh8/3hpmtMLM3LtLxXzGzphfj2F6aNW8Bf27cxA9ffELPzi/w8mv9TxnXqH5dxo8ZcdL6mOgo+nbrwi3NM99LkZycQs8RHzKye0e+GdqHibMXsvavzWliPp88i3xhuYgb8ToP3tacfu+PB6DMFUUY3/9lvhrYk5Hdn+Xl4WM4mpxMyaIxfDWwJ18N7Mnn/XuQM3s2mtapHoz0SE5O5pWh7zCqd1e+HTWAiTPmsHbDxjQxn38/lbxhuflhzFD+c8ct9B/9EQBrN2xk0sy5fDtyAO/07sorQ0aRnJxMtqxZGfN6dya83Z+vhvdjzuKl/PzbagA6P96aCW/35+sRbxITGcHYCd97nnNqsxYuYcPmLcR9OIJXOrajx8Dhp4zrMWA4PZ9tR9yHI9iweQuzF/0EwHXVq/DNu0P5+p0hlChWmJEfp/3QfnX4aOrXqnbR88ioWYuWsGHTVuI+GM4rHdvSY9Dbp4zrMXAEPTu2I+6D4WzYtDWQb5kSxRnc40VqVCqfJv7WptcTO3IgsSMH8tqLT1M0OvIf07gAmD9mLENuvCPYxbgwQkK48tVerLj3QZbWb0yh21uQs2yZNCF/dOvBsiY3sqzJjWwd/R6Jk9K+D4u/+Bx7Fyz0stRndDHqqdDQUDq1+Q8T3xnIp4P6Mvbr7wPHLFOiOIO7PU+Nild7nusZmRHS+N+kfPU2KWP6YFdVh4LRaULc70tI+eBVUj56nZTFUwlp6G+IHT1KytyJuFmx3pfbS2be/gsCNTAyGTM7l16lNkAl59zzF+P4zrluzrkp6UdmblNnzaHlTTdiZlSpeA179+0nYceOk+KqVLyGyIiIk9YXLRzDVWVKExKS+cZOLl+znuLRURSLjiRb1izcVL820xYtTRMzbeFSWjSuB8ANdWuyYPlKnHPkzJ6dLKGhgK+Xwzg5vwXLV1IsOpIikSe/Ll5YvmotxQtHUywmimxZs3LT9XWZOm9xmpip8xfTsllDAG5ocC3zl/6Cc46p8xZz0/V1yZYtK0VjoiheOJrlq9ZiZoFeiaNHkzmanBzIPCx3LsB3Jf1wUlLQh8tOnbeQFs0a+f52y1/F3v0HSEjcmSYmIXEn+w8epEr5qzAzWjRrxJS5CwCoV7Nq4BxXvroc27YnBvabMmcBRaOjKF2iuHcJpWPq3EW0aN7Qn2+5dPIt58u3eUOmzPV92Sx1RTGuLFbkjM8xcdpsbmpU/6LlcDGsnT2Pgzt3BbsYF0SealX4+48/ObzhL9yRI2yP/ZqCNzY/bXzE7S3Y/uWEwHLuShXJWqgQu2fM8qK4GXIx6qnI8AJcU8bXCA7LlZNSxYsQv8P3XihVvGi6f+dBEX0F7N4OexIhJRn3+09YqYppY5L+Djy0rNl83ecAR5Ngy3o4esTDAsvFcFk3MMyshJn9Zmaj/D0AP5hZztQ9EGYWYWZ/+h+3NrNYM5tsZn+aWXsz62hmS81sgZkVTHX4B8zsZzP71cxq+ffPbWbvmtki/z4tUh33azObBkw9TVnN31Pxq5n9YmZ3+9d/DYQBS46tO8W+Y8zsbTNbCLxuZqXM7HszW2Jms83sKjPLZ2YbzCwkVVk3mllW//6t/Ourm9lM/75xZhZjZpFmtsS/vbKZOTMr7l9eZ2a5zOzf/rIvM7OgfCLEJ2wnOioysBwdWYj4hJMbGP9ECYm7iI44/ucXFV6A+MS0X0Tid+4ixh+TJTSUPLlzsnvffgCWrVrHLe270KLDS3R/4j+BL6PHTJq9kJsbBG9IRvyOncQUOt64iS4UTvyJXzhTxfjyy8XuvfuITzxh34jwwAd0cnIyLR9/jrp3Pcx11SpR+eqygbjO/d6i3t2PsH7jZu5vcdPFTC9d8TsSiYksFFiOLhRO/I7Ek2Ki07xGESfFAHzx3RQa+HsrDhw6xKhPv6Ddf+65SCU/N6c83zt2nhQTXSj8eEzEyTFn8t2MOdzc+J/VwLiUZIuOJmnLlsBy0patZI+OPmVs9qJFyFG8GHvmzPWtMKPky//jz5d7elHUDLtY9dQxm7Yl8NvaP6l8VdqenkwnLD9u3+7jy/t3Q558J4VZ5fqEPNQNa9CClOlfeFjATCAkxNt/wUgxKM+auZQB3nLOXQPsBu5MJ74CcAdQE+gNHHTOVQXmAw+misvlnKsCtAXe9a/rCkxzztUCGgFvmFlu/7ZqQCvn3PWned47gCpAZaCpf98Y59xtwCHnXBXn3GdnKHdR4DrnXEdgJPCkc6468BwwzDm3B/gZOPb8twBxzrnAZQQzywoM8Zezuj+v3s65BCCHmeUF6gM/AvXN7AogwTl3EOgG3OCcqwzcdoZyShBULleKb4f2YVy/7oz64lsOJyUFtiUdOcq0RUu5oW7NIJbw4ggNDSX27X7M+HgEy1etZfUffwW29X2uHbM+GUmpYkWZNHNuEEt54bz90TiyhIZya9OGAAwd8wmtW7UI6vySYFj222py5MhO2ZJXBLsokgERLW9jx7eTfOP1gej/PsiuqdNI2rotyCXzzoFDh+jwSj86P9E60MP6T+eWzSbl3Vdws7/Gap++90r+mTTJG/5wzv3sf7wEKJFO/HTn3D5gn5ntAb7xr/8FqJQq7hMA59wsM8trZvmB5sBtZvacPyYHcGxcwmTn3Jkuv9UDPnHOJQPxZjYTXyPn63Qz9BnvnEs2szDgOmC8HR/3kd3//2fA3cB04B5g2AnHKIevgTXZv28osNW/bR5QF2gA9AFuBAyY7d8+FxhjZuOAL09VQDNrg2+4FyMGvkGb1g+eKuysjB3/JeNifaeoYvmr2BafENi2LWE7UUEa8nOhRYYXYFuqq13xibuICi+QJiaqYAG27thJdERBjiYns+/AIfLnCUsTU6pYYXLlyMGaDZupUKYk4Js8Xr7UFUTkP/kKlFeiIgqydfvx3qZt2xOJCi+YJibSHxNdKNyf30Hy581DVPgJ++5IJCoi7b55w3JTu3IFZv+4lLIljw8VCg0N5aaGdXlnfCx33tD4ImV3amNjJzJ+ou8mAxXLlWFrwvbAtm3bE4mKCE8THxURzrY0r9GONDFffj+V6QsWM6ZfL46995f/vpq4WfN4Y8QY9u0/QEiIkT1bVu6/Pe0NArwwNnYS4yelyvfE833COYuKKJhmqNepzuvpTJo+m5v/YcOjLjVJ27aRrXDhwHK2wjEc3nbqBkNEy9tY/+JLgeW8NaqTt3Ytols/SGju3Fi2rCQfPMCGXq9e9HKfycWqp44cPUqHV/pxa+P6NK/3D5jcv383lic/7thyWH7Yt+e04e73nwhpchcubqwnxcsUgj3u1gPqwYDDqR4n42t0HeX4a5PjDPEpqZZTSNtgc6Tl8H3hvtPf21DFOVfcOfebf/uBcyx/Rh07fgiwO1UZqjjnjs0Q+xq40T/Uqzow7YRjGLAi1X4VnXPHLjvMwtd7cQUwAV9PSz38DQzn3OPAS0AxfMO5wk84Ns65kc65Gs65GheicQFw37/vYMLY95gw9j2aXl+f2Enf45zj519WkCcs7JRzLf6JKpYpyYat8WyK307SkaNMmr2QRrWqpolpVKsKE6bNASBu7mLqVLoaM2NT/HaOJicDsDlhB+s3baVI1PHXZeKsBdxcP7gfahXLlWbD5q1s2hpP0pEjTJo5l8bXpu1RaXxtDWInzwAgbtZ86lSpgJnR+NqaTJo5l6SkI2zaGs+GzVupVK40O3fvYe9+39vi78OHmffTMq4sVgTnHBs2+9rNzjmmLVgclHHO97W8mdhRg4gdNYgm9WozYfJ039/uyt/JkzsXkSd+cQkvSFiuXPy88necc0yYPJ0m19UGYPaiJYz+7EuG93qJnDmyB/YZO+hVpn3yDtM+eYcH77yVNvf+OyiNC4D7Wt4UmIDdpG5tJvwww5/vKvLkzn2GfFf58v1hBk3q1kr3eVJSUvhuxlw1MIJs39Jl5LyyBNmLF8OyZqVQy9vYGTf5pLicpUuRJV8+9v24JLBuddsO/Fi9DktqXsefPXqxfdwXQW9cwMWpp5xzvPTmMEoVL8p/W90ahKzOwba/IH8hyFsQQkKxq6rh1v+SNib/8SGfXHkN7NqOXFrUg3Fqf+L7gr0IaHWOx7gbmG5m9YA9zrk9ZhYHPGlmTzrnnJlVdc4tTec4x8wGHjOz94GC+HoK0p3UfSLn3F4z+8PM/u2cG2++S5mVnHPLnHP7zWwxMAj41t9bktoqoJCZXeucm+8fMlXWObfCX77ewCznXIqZ7QRuAjoDmFkp59xCYKGZ/QtfQ+PkAeIX0fV1r2XmvAU0u+MecubIQZ//dQ5sa3Hff5kw1ner1tcHD+PbH6Zw6O+/aXDLHfz7tlt4ss1DLF/5G+1f6MrevfuYPnseQ0a+y8TPPvQyhdPKEhrKS23u55GX+5GSksIdTepTpngRBo/9kgqlS9K4dlVaNWtApwEjueGxF8iXJzf9n3sCgCUrVzPqi4lkzRKKWQjdHn+AAnnzAHDw78PMW7aCHm1bBzE7X37/a/8ID3fpRUpKCnfe0JgyJYox+P1PqVC2FI2vrUmrG5vwwmuDad66PfnyhPFml2cAKFOiGP9qcB03P/o0oaGhdGv/CKGhoWzfuYsX3xhKckoKLsVx4/XX0ahODVJSUnjxjaHsP3gInKPclVfwcoc2Qc3/+to1mLVwCc3vf4wcObLT54UOgW0tH32K2FGDAOj29ON0eW0Qfx9Oon6tajSo7bvrV8/BI0g6cpSHnu8GQOXy5ejxTFvvE8mg62tX9+X7wOO+fJ9PlW+bp4kdORCAbk89RpfXB/P34cPUr1WdBrV8+U6es4BeQ0axc88eHu/Sk6tKl2T0ay8DsHj5CmIiIyhW+NTj/TOzhz9+l7IN6xEWEU7fjb/xTfc+zHs3c9RBZy05mfWd/8c1n34EoaEkfPIZh1atpvgLz7J/2fJAYyOi5W3smJDRjvrguhj11JJff2PClFmULVmclo/7Bj8889C9XF+rGpPnLKTXsNHs3LOXx1/qy1WlSjC6bya4Xa9LIWX654Tc2RYsBPfrAkjchl13E27bX7D+V6xKfax4OUhJhsOHSIn7KLB7yMPdIXsOCMmClapEyhfDfLewvZRcBj0Y5tyJF9ovH2ZWAt8X6Qr+5efwTZj+FBiHr0djInC/c66EmbUGajjn2vvj//Qv70i9zcxmcHw+Q1bgIefcIjPLCQzEN0QpBN/wrFtOPO5pymrA68C/8PWG9Do258LM9jvnws6w7xh/np/7l0sCw4EYf/k+dc694t/WChgPNHTOzTxxfzOrAgwG8uFroA50zo3yx20EejrnRppZF+Ae51wl/7Yv8c13MXwT2Z92Z/rj25Nw2fxhpmxdF+wieMpynvZP9dKTJVuwS+AtlxLsEnjmiWK1g10ETz0QGbwhkl67btGkYBfBUylfjAp2ETwV2nFw0L/dJw982tPvOKFPD/Q858u6gSGZmBoYlyw1MC5hamBcstTAuHSpgeG95EHPeNvAeGqA5zlrDoaIiIiIiFwwmoORyZhZReDEQbWHnXPpXi4zs67Av09YPd451/tClU9EREREzkOQfpvCS2pgZDLOuV/w/d7FuezbG99EaxERERGRoFADQ0RERETEK5fBXaQu/T4aERERERHxjHowRERERES8oh4MERERERGRjFMDQ0RERERELhgNkRIRERER8Ypd+tf3L/0MRURERETEM+rBEBERERHxSogmeYuIiIiIiGSYejBERERERLyiORgiIiIiIiIZpx4MERERERGv6If2REREREREMk49GCIiIiIiXgm59K/vX/oZioiIiIiIZ9SDISIiIiLiFc3BEBERERERyTj1YIiIiIiIeEW/gyEiIiIiIpJx6sEQEREREfGK5mCIiIiIiIhknBoYIiIiIiJywWiIlGRKyUunBbsIngkpfGWwi+CtlORgl8A7LiXYJfDWZTBx8ZgHIvMFuwie+jBhT7CL4JlrD+0PdhG8lZQU7BJcfvRDeyIiIiIiIhmnHgwREREREa9okreIiIiIiEjGqQdDRERERMQrl8F8tUs/QxERERER8Yx6MEREREREvBKiORgiIiIiIiIZph4MERERERGvaA6GiIiIiIhIxqkHQ0RERETEK/odDBERERERkYxTD4aIiIiIiFc0B0NERERERCTj1IMhIiIiIuIV/Q6GiIiIiIhcqszsRjNbZWZrzezFU2zvaGYrzWy5mU01syvSO6YaGCIiIiIilyEzCwXeAv4FlAf+z8zKnxC2FKjhnKsEfA68nt5x1cAQEREREfGKmbf/zqwWsNY5t945lwR8CrRIHeCcm+6cO+hfXAAUTe+gamCIiIiIiFyizKyNmf2Y6l+bVJuLABtTLW/yrzudh4Hv0ntOTfIWEREREfGKx7epdc6NBEae73HM7H6gBnB9erFqYIiIiIiIXJ42A8VSLRf1r0vDzJoCXYHrnXOH0zuoGhgiIiIiIl7JXLepXQyUMbOS+BoW9wD3pg4ws6rACOBG51xCRg6qORgiIiIiIpch59xRoD0QB/wGjHPOrTCzV8zsNn/YG0AYMN7Mfjazr9M7rnowRERERES84vEcjPQ45yYBk05Y1y3V46Zne8zMlaGIiIiIiPyjqQdDRERERMQr6f82xT+eGhjnyMwKA4Odc62CXZbMxsyqAIX9XW6Y2cvAfudcv2CWa/ava+g77juSUxyt6lXj0Rvrp9n+4+o/6Tvue1ZvjqffI624ofo1AGxO3E2H4Z+S4hxHk5O5r1Ft7rm+ZjBSyLDZS5bTe9SHpKSk0KpZQ9r8+9Y025OOHKHTmyNYse4P8ucJ480X2lM0qhDLV6+j29B3AXDO0f7eO2h2bY1gpJCu2T/+TO/hY3w53tiYNne3TLM9KekInfq9xYo168mfNw9vdn6KotGR7Nq7j6d6vcmvq9fRsllDurV7KLDPI137sH3nLpKTU6he4Sq6tXuY0NDgd/Q65+j91jvMWriEHNmz0/eFDlxTttRJcb+uXkvn1wdz+HASDWpXp2u7RzAzvp85l6Hvf8q6vzYx7q03qFiuNACbtsVz83+fpGSxwgBUvrocPZ55wtPcTsU5R++ho5i18Edy5MhO3xeePn2+rw3i8OHDNKhdg67tH8XMeP3t95g+fxFZs2aheEwMfTp1IG9YmC/f1u0oWcx3i/fK5cvR45m2Xqd3WvkbNeTKXi9DaCjxYz9h85BhabaXfKU7eeteC0BozpxkjQhnYdkKge2hYWFUnT2Nnd/Fsb7L/zws+YX3wOi3qHjLjexL2E7PinWCXZzzNvun5fQZ9bG/Tm7Ao61uSbM96cgROg0Yxcp1f/rq5OefoEhUocD2LdsTubV9F9rd05KHbv+X18U/eyXLE9L0LggJwS2bi1sQl2azVamPVWsILgWSDpPy/VhI3AoxJQi58T5/kJEy51tY/bP35ZfzpgaGn5kZYM65lIzEO+e2AP+IxoWZZfFP4vFKFXz3SZ6UXqBXklNS6PXJRN55+kGiCuTl7r4jaVSpHKULRwZiYgrmo0/rlrw3eV6afQvlC+OTTo+QLWsWDvx9mBavDKNx5XJE5s/rdRoZkpycwitvv8+7PTsRFV6Qf3fsRuPa1Shd/Pjv5nz+w0zyhuXmh5H9mThrPv3HfMaATu0pU7wonw94hSyhoSTs3E3LDl1oVKsqWUJDg5jRyZKTU3jlrXd5t09XoiLC+XeHzjSuU4PSVxz/cdHP46b5cnxvMBNnzKX/ux8zoMvTZM+WlacevJs1Gzay+s+NaY47sMvThOXOhXOODr3e5PvZ87m5YV2v0zvJrEVL2LBpK3EfDGfZb6vpMehtxr31xklxPQaOoGfHdlS+uixtOvdk9qKfaFC7OmVKFGdwjxfpPmDYSfsULxxN7MiBXqSRYbMWLmHD5i3EfTiCZb+tosfA4YwbdvL1iR4DhtPz2XZUvrocbTr3COR7XfUqdHz0QbKEhtJv5BhGfvw5z7VpDfjzHTXI44wyICSEK1/txYq77iVpy1Yqx33LzrjJHFq9JhDyR7cegccxD7cmd8UKaQ5R/MXn2LtgoVclvqjmjxnLjKEjaf3BiGAX5bwlJ6fQc8SHjO7xPFHhBbnruR40qlU1bZ08eRb5wnIRN+J1Js5aQL/3xzPgheON39dGf0L9ahWDUfyzZ0ZI8/8j5dNBsG8XIa0749Ys9zUg/NzKxbifZ/sWSlcipEkrUsYNge2bSRnT19fwyJ2XkIdeImXNct/ypSSTzcG4GC79DM/AzEqY2Soz+wD4FfifmS02s+Vm1sMf86qZtUu1z8tm9px/31/960LN7I1U+z7mX//WsRn4ZvaVmb3rf/yQmfU2s9xmNtHMlpnZr2Z29xnK+qeZvW5mv5jZIjMr7V9fyMy+8D/3YjOrm6qcH5rZXODD0xyztZnFmtlk//Hbm1lHM1tqZgvMrKA/rop/ebk/jwL+9TPM7DV/eVabWX0zywa8Atztv9PAsZzK++PXm1mHcz1n5+qXPzZTPLIgxQoVJFuWLPyrRgWmLfs9TUyRiAKUKxpNyAldl9myZCFbVl9b/MjRZFJSnGflPhfL16yjeEwUxaIjyZY1Czc1qMPUhUvSxExd+BMtm9QD4Ia6tZi/bAXOOXLmyB5oTCQlJWGZtBt3+aq1vhxjonw5Xn8dU+cvThMzdf6PtGzq+y2gG+rXYf7Pv+KcI1eOHFSvcBXZsmY96bhhuXMBcDQ5mSNHj2aa/KfOXUSL5g0xM6qUL8fe/QdISNyZJiYhcSf7Dx6kSvlymBktmjdkylzfl81SVxTjymJn+mHWzGXqvIW0aNbIn+9V6eR7lS/fZo2YMncBAPVqHm8UV766HNu2J3qew9nKU60Kf//xJ4c3/IU7coTtsV9T8Mbmp42PuL0F27+cEFjOXakiWQsVYveMWV4U96JbO3seB3fuCnYxLojla9ZTPDpVnVy/NtMWLU0TM23hUlo0PlYn12TB8pU45/usmbJgCUWjItI0SDK1mBKwKwH27ICUZNzKxViZSmljkv4OPLSs2cCfK0ePHG9MZDm5jpZ/jsu6geFXBhgGPIPvp9Fr4bsCX93MGgCfAXelir/Lvy61h4E9zrmaQE3gUf/9hGcDx8bhFAHK+x/XB2YBNwJbnHOVnXMVgO/TKese51xFYChw7JLjIGCA/7nvBN5JFV8eaOqc+78zHLMCcIe/3L2Bg865qsB84EF/zAdAJ+dcJeAXoHuq/bM452oBTwPdnXNJQDfgM+dcFefcsdfqKuAGfK9vdzPztOaI372X6AL5AsvRBfKRsHtfhvffunMPLV8ZRuMX3+SRG+pm2t4LgPjEXcREFAwsR4cXJD4x7Qd1QuJOYiLCAcgSGkqe3LnYvXc/AMtWreWWti9y25NdeLntfzNd7wVAfOJOYgqFB5ajI8JPnWOhE3NM/5w/3KU3de9pQ+6cObmhXuYYmhG/YycxhSICy9GFwonfsfOkmOgTX5MTYk5l07Z4bn/sGe5/pis/Ll9x4Qp9HuJ3JBITeXx4iC/fxJNiotO8JhEnxQB88d0UGtSqFljetC2e29s8xf1Pd840+QJki44macuWwHLSlq1kj44+ZWz2okXIUbwYe+bM9a2w/2fvvuOjqtI/jn+eJBSpIUBCBwvqIojSEVFABbu4y66uujasqKxt7b1gBRWsIIodywouoKJSFESQogJ2figKEnovhmSe3x/3JiQhkKCZmTD5vl+vvDJz77l3npO5M7nnPueca+x9x638fMfdsQhVdtPyVWuol+87OaN2rR2+r5at3v69HXxf7cXaDRvZtGUrz779Lv1OL9gFtEyrXgvfkK9+G9ZC9Vo7FLM2R5J08d1Y978S+eiN7SvqNyOp720k9b2VyPhXEy97AcF9MGL5EwfqIgWL3H26mT0M9ARyLytUA5q7+3AzSw/HXNQF1rj7r2bWLN8+egIHm1lul6maBJoUFBUAACAASURBVA2XKcCVZtYC+AaoZWb1gc5Af6A+MNDMHgDGuvuUYmJ9Ld/vR8LHRxNkB3LL1DCzauHj/7n7lmL2OcndNwAbzGwdMCZcPi+sU00g1d0/Dpe/ALyZb/u3w9+zgWa7eJ1x4Z0ffzez5UAGsLiY2MqM+mk1GX1bP5avXc8VT42kZ9uDqFOjWvEb7oFaH7AfY5+8n//7dQk3PDKUI9oeTKWKFeMdVswMH3Azv2dlce0DQ5j+1Xy6tDm4+I32UOlpaUx8dRi1atZg/g8LuPy2+xg7fEheJmdP9/TLb5CSnMxJR3cDwvq+Nnx7fW8dwNjnHt/j6lun98msHPsuRIITr3rnnc2aCRPJWpoZ58iktD0xcjTnnNyLqntVjncopc7nfIzP+Rhr0R477Dh83AvBiqU/Exl+F9SuR9IJ5xL5v/mQE8te3lIa1MCATeFvA+5z96I6fL5JMN6iHjtmL3K3vcLdx++wwiyVIFPxCZBGkAHZmO+kvg1wPHCPmU1w97t2EasX8TgJ6OTuW/MXDBscmyhe/tu9R/I9j1Cy4yO3fE4x5fO/TpFlzewi4CKAp66+gAtPOqoEL18yGak1yFyzLu955pp1pKdW3+39pKfWYL8G6cz+cVHeIPCyJqN2LZbmu3KduWo1GbULXj1Kr53G0pWrqFcnjeycHDZs2kxqoQbTvo0bUmWvSvywaDGtmu8Tk9hLKqN2GkvzdXvJXLmq6DquWEW9urXz1bFk73mlihU5qnM7Jnw2K24NjFdGv8ub734AQKsDmrN0xcq8dZkrVpGR74ooQEadtAJdgTJX7limsIoVK1CxYpBMbLn/fjRuUI+fFv+WNwg8ll4ZPY43x+Wr7/IVeeuC+tYuUD6jTm0yC/xNVhYo8/b7E5g0fSYjHr4nr6tb0fVdQqsDmketXiWVlZlJxQYN8p5XbFCf3zOLbjDU6X0yC2+4Je95jXZtqdGxA/XOPZvkqlWxihXI2byJRffcH/W4pXjptWuRme87edmqNTt8X2WkBd/b27+Tt5BavRpzf1jI+GkzefiF19mwaTNJlkSlihU484Tdvi1B7GxYg1Wvtf2EpXoqbNh5dzf/ZhZJPc/AeaHgilWZsG0r1G0Amb9ELdy40BiMcmU8cH7u1X8za2hmuSOAXye4dXofCl69z7/tpbndfsxsfzOrGq6bTtB96BOCjMa14e/cmag2u/vLBHdJbFN4x4Wclu/3Z+HjD4ArcguEMziVGndfB6wxs9yuXv8CPt7FJgAbgN0+e3f3oe7ezt3blWbjAqBlswYsWr6axSvXkJWdzXuz5tO99YEl2jZzzTq2Zm0DYN2mLcxZ8At716tTzFbx06r5Piz6LZPFmcvJ2pbNu59Mp0eHgodWj46HMnrCVADGf/o5nQ5ugZmxOHM52Tk5ACxZvpKFi5fSKF9XlbKi1QH7Fqzjx9Po0angbFc9OrVj9EfBoTp+ynQ6tT5ol2MqNm3ZyvKw20J2Tg4ff/4F+zRusNPy0XZm7+MZPfRRRg99lKO6dOSdDybj7nz5zfdUr1qV9NoFGw/ptdOoVqUKX37zPe7OOx9M5qguHXb5GqvXriMnfL9//S2TRYuX0rh+RtTqtCtn9j6B0cMeY/Swxzjq8I688+GksL7fUb1qlV3U97ugvh9O4qjDOgIw5fPZDH/9bZ665xb2qlwpb5sd6/sbjesX3Q0p1jZ88RV77dOMSk0aYxUqULf3yawe/+EO5fbab19SatZkw6zt46p+6NefWW07Mbv9Yfx85z2seOO/alyUIa2a782ipctYvGxF8H01ZQbdOxxaoEz3DofwzsTc7+SZdDr4L5gZL993ExOGDWTCsIGcfVJPLupzYtluXAAsXQRp6VCzNiQlYy3a4wvmFixTa/sEK+zXMhizAcE2uSffNdIgrR6sK/tjqGRHymCE3P0DM/sL8Fl4ErIROAtYHt4yvTqwxN2XFrH5swTdg+aEs1GtAHI7TE4Berr7AjNbRJDFyO0K1Qp4yMwiwDaguPkha5nZXIJsQO64iv7AE+HyFIKGzCW7V/tinQM8bWZVgIXAecWUnwTcYGZfAveVcix/SEpyMjeffjwXPhZM3Xpql0Np3iCdIf+byEFNG9Cj9YHM+3kJ/Z8ayfrNW5g093seHzOJMXdczsKlK3nwrfGYBePQzjvmMPZvGJ+TsJJISU7m1kvOpu/tDxGJRPjb0UfQvGkjBr/8X1o235seHdvQ55gjuW7Q0/S86BpqVqvGoOuCeQxmf/MDw94aS0pKMklm3H7JOdSqufuZnmhLSU7m1n7n0/fmAUEde3ajebPGDH7xDVo234cendvR59juXPfg4/Q8rz81q1dj0I3/ztu+x9mXs2nzZrZlZzPhs5kMv/dmUmtUo98dD5K1LRv3CB1aH8TpJxwTx1pud2THtnwyYzY9/3UJlStXYsB/ts+T0PuiK/Nmgbrt3xdz04OD2fr773Tt0JYjOrQF4MOp07lnyDBWr1vHJTfdzYH77c3wB+5g5tyvGTLitfD9TuKOKy8pcZYnmo7s2C6o71kXB/W9Ll99L/x33ixQt115CTc98Bhbf8+ia4c2HNExqO/dg58ha1s25/8nuBFt7nS0M+d+zZDnXyElJYUkM+64ql+ZqC8AOTksvPFWDhr5MiQns/y119ny/Q80ue4aNn41N6+xUaf3yax8539xDjb6+r76HPt3O5xqdWpz36/fMub2AUx7rsj5Ssq8lORkbrnoLC6442EikQh/PaorzZs0ZPArb9Nyv73p0fFQ+hxzBNc/MpReF19HzepVGXht/KeL/sM8QuSD10k6rT9YEj53GqxcinU9CV+6CBbMxdp2w5oeCJEc2LqZyLgRAFij/bBOvYLl7kQ+eA22lKQzhpQ1ljtLgZRtZvYz0M7dVxZXNhHkTB5Zbg7MpAZlq/tR1FUoP+M5qFCp+DKJpByk/XNNa1PGryKXspeWryu+UIJ48tsdejsnNB/9QvGFEkjyDU/HfXrAnHFDY3qOk3zCRTGvc/n5byAiIiIiIlGnLlJljJmNAvYutPh6d2/2J/bZC3ig0OKf3P3UP7pPEREREfkDkhL/+r4aGGVMNE76w9mtylfOV0RERETiQg0MEREREZFY2cWMhoki8XM0IiIiIiISM8pgiIiIiIjESjmYcS/xaygiIiIiIjGjDIaIiIiISKxoDIaIiIiIiEjJKYMhIiIiIhIr5eA+GIlfQxERERERiRllMEREREREYkVjMEREREREREpOGQwRERERkVjRfTBERERERERKTg0MEREREREpNeoiJSIiIiISKxrkLSIiIiIiUnLKYIiIiIiIxIoGeYuIiIiIiJScMhgiIiIiIrGSpDEYIiIiIiIiJaYMhoiIiIhIrGgMhoiIiIiISMkpgyEiIiIiEivl4D4YamBImZTUcN94hyDy523ZGO8IYqtSlXhHEDOHff5uvEOIqc7l6Fju95de8Q4hpp6YNDTeIUgCUgNDRERERCRWNAZDRERERESk5JTBEBERERGJESsHYzCUwRARERERkVKjDIaIiIiISKxoDIaIiIiIiEjJqYEhIiIiIiKlRl2kRERERERiRV2kRERERERESk4ZDBERERGRWEnSNLUiIiIiIiIlpgyGiIiIiEisaAyGiIiIiIhIySmDISIiIiISK6YxGCIiIiIiIiWmDIaIiIiISKxoDIaIiIiIiEjJKYMhIiIiIhIrGoMhIiIiIiJScspgiIiIiIjEisZgiIiIiIiIlJwyGCIiIiIisZKkMRgiIiIiIiIlpgyGiIiIiEisaAyGiIiIiIhIySmDIQltyuyvuHfoS0QiEfr07MZFfz+5wPqsbdu4ftDTfL3gJ1KrV2fQ9ZfTKKMun34xj4EjXmdbdjYVUlK47vx/0qn1QQW2vfSugSzOXMGYJ++PZZV2Khp1veC2B1ixeh05kRzatjiA2y49l+TksnFdYsqsL7n3qRFBfY/twUWn9S6wPitrG9c//ARf/7iQ1BrVGXTjv2lUL5016zfw73sGMf+H/6P3Md247bLzAdiy9XeuvPcRflm6jOSkJLp3ass1558Rj6rtIBrv7b9uuIcVa9ZSuWJFAIbffT21U2vGvG653J17nxzOJ5/PoXKlStz3n8s5qPm+O5Sb/8P/ceNDQ/g9K4sjOrTh5n59MTPWrt/A1fcOZEnmChrWq8sjt1xLzerVGP7GaMZM+ASAnEgO//fLEqa9+TypNaoHy3Jy6HPZdaTXSeOZe26OSV2nzPyCe596Pjx2j+Ki008tsD4raxvXPzQkOHarV2PQzVfTqF46AM+89jb/HT+RpKQkbu53Pl3bHcLS5Su5/qEhrFqzDjP4x/HHcPapJwDw/ifTePylN/i/X5bwxpD7aLX/fjGpY0lMmTOXAcNeDf4OxxzBhX1OLLA+a9s2rn9kGN/838/B3+E/l9Iwo27e+t9WrOKky2/istN7c/6px8U6/FL1r+FP0OrEY9mwfAV3t+oU73D+tCnzf+S+N94jJ+L0ObwNFx7btcD6WT/8zH1vvM8PS5bx8AV96NU2+F5asmot/Z8aScSd7JwczuzekdOPbB+PKsifVKpnCmZ2rpk9/ge3HWFmfUqw/wa7ud9mZja/mH3+oZh3NzYzm2xm7cLH75pZ6i7KXmlmVfI932X5PUXhekVTTk6Eu556gWF3XsfYJx9k3MfTWfDLkgJl3vpgMjWqVuWDYYM455RjGThiJAC1alTnqduuYcwT93P/VRdz3cCnC2z3wbSZVNmrciyqUSLRquujN1zBO48PYMwT97N6/QbenzojpvXamZycCHc98RzD7rmRsUMHMW7ypyxYtLhAmbfGT6RGtap88Pxgzjn1eAY+9yoAlSpW4N9nn8Z1F/5rh/2e1+dE3nv2Ed5+4gHmfP09n8z8Iib12ZVoHscPXduP0UMGMHrIgLg2LgA++XwOi5YsZfyIJ7jryku4c/DQIsvdOfgZ7r7qUsaPeIJFS5YyJXyPhr0+ik6HHsz4F56g06EHM2zk2wD0/UdvRj8ziNHPDOKq88+i/cEt8hoXAC+OGsc+TRpFv4KhnJwc7nr8WYbdezNjhz3CuMlTWbDo1wJl3np/QnDsjnicc/56IgOHvwzAgkW/8u7HnzJ26CM8e+/N3DVkGDk5OSQnJ3P9Recw7tlHGfnYfbzyv/fz9tm8WRMG3/Yf2rX6S8zqWBI5ORHufuYlht5+NWMeH8C4KTN2PK4//ISa1aow/pkHOfvknjz8wpsF1j8w/DW6tmkVy7Cj5rMRrzDk2L/GO4xSkROJcM9r43jmirMYc8dlvDtzHgt+W16gTP20mgw4tzcndCj4/tWtWY3Xrr+AUbdeysgbLuTZ8VNZvnZ9LMOPDbPY/sRB2bgUWXLnArvVwIihc9mN2Nz9eHdfu4siVwJVdqP8nqJAvaJp7g//R5P6GTSul07FCikcf0QnJkyfXaDMhOlz6H1UcGWl1+Ed+Oyrr3F3WuzbjIzatQBo3rQRv2dlkbVtGwCbtmxlxOj3uLTQFfN4ilZdq1UJ3qrsnBy2bcvGysjdR+d+vyCob/2MoL5HHsaEz2YWKDPhs1n0PvpIAHp17cRnX87H3alSuTJtWx5IxQoVCpTfq3IlOrVuCUDFCim02G9vMleujk2FdiFa721ZM+Gzzznl6G6YGYe0OID1GzexfFXBv//yVavZuHkLh7Q4ADPjlKO78dG0oNE7Ydrn9D6mGwC9j+nGR9M+3+E1xk2aygndt19JzVyxko9nzObvxx0dvYoVMvf7BTRpUC88ditw/JFdmDCt8LE7M68uvY7ozGdfzMPdmTBtJscf2YWKFSvQqH4GTRrUY+73C0ivXYuDmu8DQLUqe7Fvk4YsC4/dfZs0Yp/GDWNWv5Ka++NCmtTLd1x37cjEzws26CfO+IJTehwOQK8u7Zk+9xvcHYCPps+mUUYd9mtS9ur2RyyYMo3Nq9fEO4xSMe+nJTRJT6Nx3TQqpqRwXLuWTPzquwJlGtapxQGN6pFU6H9KxZQUKlYIOtdsy84hEvGYxS2lq0QNDDM728zmmtlXZvaSmZ1kZjPM7Asz+8jMMorYJsPMRoXbfGVmhxXOJpjZtWZ2RxHb3mZmM81svpkNtUAfoB3wipl9aWZ7mVlbM/vYzGab2Xgzqx9u3zb3dYHLSlDFBmb2vpn9aGYP5ovjn2Y2L4zjgXBZcphtmR+uu6qo2ErwN/3ZzOqYWVUzGxfGO9/MTjOz/gSNlUlmNqlQ+WZm9q2ZDTOzr83sg9zXM7P24fv0pZk9lPu3NrODzOzzcPlcM2u+i7gKvNfhsmZmNjFcPsHMmoTLC2SdzGxj+LtbmK15y8y+M7NXwvdwh3pF07JVa6hfNy3veb06aSxbVfALfHm+MinJyVSvUoW16zcWKDP+05m02LdZ3gnp4Jff4rzex1G5UsUo16DkolVXgL63PkCXM/tRtUplenXpEMValNyyVaupX7d23vN6dWoXUd/tZVKSk6letQpr128o0f7Xb9zEpBmz6XxIy9IL+g+K5nt706ND6X3FTTz52qi8E7d4WbZyNfXT6+Q9r1endt5Jcv4y9erke9/rbi+zas1a0msHf4O6abVYtabg9ZgtW39n6qwv6Hn49u4nA556jmsvPBuL4ZSRy1aupn7dfPWsW5tlhRtS+crkP3aD437Xf6PFmcv5dsHPtD5wp1/zZcLyVWuoV2f7cZ1Ru9YOx/Wy1WuoXyffcV11L9Zu2MimLVt59u136Xd62bnII9stW7ueerW2Z0Tr1arJ8rUl++4FWLp6Hb3vepIeNwzigl5dSE+tEY0w48uSYvsTB8W+qpkdBNwC9HD31sC/galAJ3c/FBgJXFfEpoOBj8Nt2gBf70Zcj7t7e3dvCewFnOjubwGzgDPd/RAgGxgC9HH3tsBzwL3h9s8DV4SvXRKHAKcBrYDTzKxx2N3pAaBHuL69mfUOHzd095bu3gp4vnBs7r5lN+p6LPCbu7cO6/u+uw8GfgO6u3v3IrZpDjzh7gcBa4G/5av3xeHfJydf+UuAx8Ll7YCCfUlCO3mvIfg7v+DuBwOvELy3xTmUIFvRAtgH6FKCepU5Py5azMARI7nz8qCf/rcLF/HL0mUcc1ji9QktXNdcw+++nikvPU7Wtmymz92dj/GeKTsnh2vuH8y/TjmWxvV3uHayRyrqvX342n6MeeJ+Xn7gVmZ98z3vTJwaxwhLl5ntkG2bNH0mhx50YF73qEnTZ1E7tSYt999xnMeeatOWLfS/62FuvPRcqlWNSaI4Lp4YOZpzTu5F1TLUTVVKT/20moy+rR/v39Ofd6Z/xcpCF0tkz1CSZk0P4E13Xwng7quBRsB4M5sH/Ac4aCfbPRVuk+Pu63Yjru5hhmReuJ+i9n8A0BL40My+JDgxbhSOU0h190/Cci+V4PUmuPs6d98KfAM0BdoDk919hbtnE5xYHwEsBPYxsyFmdizwZzsHzgOOMbMHzKxrCf9OP7n7l+Hj2UCzsN7V3f2zcPmr+cp/BtxkZtcDTXfRACrqvQbonG9/LwGHlyDGz919sbtHgC+BZsVtYGYXmdksM5s1dOSoErzErmXUrsXSFduv7mWuXJ3XXSRXer4y2Tk5bNi8mdQa1cLyq7j83kd54OpLaBKeaH753Y/MX/ATPc6/kjOvu4uff1vKv26450/H+mdFo675VapYkaM6tmHC9DlRrEXJZdROY+mKVXnPM1euKqK+28tk5+SwYdPmAn3vd+a2x4bStEE9zgkHycZbtN7bjPDKcLUqe3HikYcx94eF0a7KDl555z16X3w1vS++mvS0WixdvjJvXebKVXkx5sqok0bmynzv+4rtZWrXSs3rUrV81WrSCo0peXfyVE7ovv2ra87X3zHxs5n0OOtirrl3EDO+nMd/7n+01OtYWEadNJauyFfPFavIqF2wnun5yuQ/doPjvui/0bbsbPrf9TAn9ehaIEtTVqXXrlWgC+KyVWt2OK4z0mqxdGW+43rTFlKrV2PuDwt5+IXXOerCa3hxzAcMfWssr4z7KKbxy85lpNYgc832U5nMNetITy3+u7ew9NQa7Ncgndk/LirN8MoGjcHYqSEEWYZWwMVASS8jZBd6zR22M7PKwJMEmYlWwLCd7N+Ar8OMwSHu3srde+5OJfL5Pd/jHHYxu5a7rwFaA5MJMgPP/sHXzN3fDwQZnnnAPWZ2Wwk2K3G84Wu8CpwMbAHeNbMefzDcwvLeTzNLAvL3GdqtGMM4h7p7O3dvV3hWlT+i1f77sOi3TBZnLidrWzbvfjKdHh3bFCjTo2MbRk+YAsD4qZ/T6eAWmBnrN27i4jsGcs25p9Gmxf555f95/NFMefFxJj73KK88eBvNGtTnpftv+dOx/lnRqOumLVtZHvYJzs7J4eNZX7JPo/qxq9QutDpg34L1/XgaPTq1K1CmR6d2jP7oYwDGT5lOp9YHFTuG5NERI9mwaTM3XXJO1GLfXdF4b7NzclizLuiysC07m8mff8H+TWM30DnXmacclzcA+6guHXjno8m4O19+8z3Vq1bJ6/KUK712GtWq7MWX33yPu/POR5M5qnPQba9H5/aM/nAyAKM/nMxRh23vzrdh0yZmzv0mryzANX3P4uPXnmXiy88w8Oar6XhIKx664cqo17nVAfuxaMlSFi9dRta2bbz78af06FwwI9qjc7u8uoz/5DM6HdISM6NH5/a8+/GnZGVtY/HSZSxaspSDD9gPd+eWQU+yb5NGnNfnpKjXoTS0ar43i5YuY/GyFcFxPWUG3TscWqBM9w6H5GXWxn86k04H/wUz4+X7bmLCsIFMGDaQs0/qyUV9TuTME2I3jkZ2rWWzBixavprFK9eQlZ3Ne7Pm0731gSXaNnPNOrZmBePE1m3awpwFv7B3vTrFbCVlUUmmqZ0IjDKzQe6+yszSgJpA7nQPO/tPPAG4FHjUzJKBasAyIN3MagMbgROB9wttl9uYWGlm1YA+wFvhsg1AbjP4e6CumXV298/MrAKwv7t/bWZrzexwd58KnFmCOhblc2CwmdUB1gD/BIaEz7Pc/b9m9j3wchGxlVjYFWu1u79sZmuBCwrtb+VON87H3dea2QYz6+juM4DT873GPsBCdx8cjp84mOB9LWyH9zrMYkwL9/cSwd9zSlj+Z6At8AZBA6bCjrvcwW7V689ISU7m1kvOoe9tDxKJRPjbMUfSvGkjBr/8Fi2b702Pjm3p0/NIrhv4ND0vvJqa1aox6PrLAXhl7If8snQZT742iidfC7Ip8Z7Gc1eiUVd36Hf3ILK2ZeMRp8PBf+H044+KZzXzpCQnc2u/8+l784Cgvj270bxZYwa/+AYtm+9Dj87t6HNsd6578HF6ntefmtWrMejGf+dt3+Psy9m0eTPbsrOZ8NlMht97M9Wq7MXTI0exT+MG/PXyGwA486Re/P24+NY5Gu/tXpUr0fe2B8jOySESidC59UH8vVd8ey0e2aEtn8yYQ89z+lG5UiUGXHt53rreF1/N6GcGAXDbFRdx08ND2Pp7Fl3bt+GIDkFj68LT/8pVdz/Mf9+bQIOMujxyyzV52384dQZd2rYuEzO/pSQnc+vlF9D3pnuC97NXj+DYfWEkLffflx6d29Pn2KO47oHB9Dz38uDYvekqAJo3a8xxRxzGCRdeSXJyMrddfgHJycnMnv8t73z0Cfvv3YTel1wLwFXnn8GRHdrw4dQZ3PPkcFavW88lt9zHgfs2Y/h9t8bzTwAEf4dbLjqLC+54mEgkwl+P6krzJg0Z/MrbtNxvb3p0PJQ+xxzB9Y8MpdfF11GzelUGXntpvMOOmr6vPsf+3Q6nWp3a3Pfrt4y5fQDTnitJB4yyJyU5mZtPP54LHwum1j61y6E0b5DOkP9N5KCmDejR+kDm/byE/k+NZP3mLUya+z2Pj5nEmDsuZ+HSlTz41njMwB3OO+Yw9m+YGF1VCygHN9qzkgzsM7NzCLpC5QBfAKOARwhOvCcC7d29m5mdC7Rz98stGPg9lKD/fQ5wadgQ6E/Qt38JQXejn939DjMbAYx197fM7B6CE/pM4AdgUVjmb8AAgivxnQm6SQ0maPCkAI+6+zAzyx2T4cAHwPHh+Iai6pYXc/h8LPCwu082s38CNxFkS8a5+/Vm1ppgrEPu0XGju79XOLaiuiGZ2WTgWnefZWY/E4yHaAs8BESAbeHfaZaZXQFcTjA+o3u+8tXCv1PLcJ/XAtXCv09HgoxPBPg4rFcXM7sB+Fe4/0zgjHzdnwrHWOC9dvdzzaxpWOc6wArgPHf/JXyP3yEYJ/M+cJm7VzOzbmE9Twz3+Tgwy91HFK5XUTEA+I8zNXVEokopSTs0QWSXzRmboqZS4vb734FH4h1BTPmW8tMPvt9fesU7hJh6YlLRU0InquRup8d9OsTIN5/G9BwnqUWXmNe5RA0M2TOYWTV3z53J6Qagvrv/u5jNyiQ1MBKYGhiJSw2MhKUGRuJSAyP2It99FtsGxoGdY15n3ck7sZxgZjcSvK+LCO7NISIiIiISM+WmgWFmvQimnc3vJ3f/86OJd3ytUcDehRZf7+7jS/u18nP314HXiysXjoGZUMSqo9x9VRHLRURERKQUFDfhSCIoNw2M8OQ+qif4+V6r1BstpSlsRBwS7zhEREREJPGUmwaGiIiIiEjclYNZpBK/hiIiIiIiEjPKYIiIiIiIxEo5GIOhDIaIiIiIiJQaNTBERERERKTUqIuUiIiIiEisaJC3iIiIiIhIySmDISIiIiISKxrkLSIiIiIiUnLKYIiIiIiIxEpS4l/fT/waioiIiIhIzKiBISIiIiISK2ax/Sk2HDvWzL43swVmdkMR6yuZ2evh+hlm1qy4faqBISIiIiJSDplZMvAEcBzQAvinmbUoVKwvsMbd9wMeAR4obr9qYIiIiIiIxIolxfZn1zoAC9x9obtnASOBUwqVOQV4IXz88rClVQAAIABJREFUFnCU2a5TI2pgiIiIiIiUTw2BX/M9XxwuK7KMu2cD64Dau9qpZpESEREREYmVGN8Hw8wuAi7Kt2iouw+N5muqgSEiIiIikqDCxsTOGhRLgMb5njcKlxVVZrGZpQA1gVW7ek11kRIRERERiRmL8c8uzQSam9neZlYROB34X6Ey/wPOCR/3ASa6u+9qp8pgiIiIiIiUQ+6ebWaXA+OBZOA5d//azO4CZrn7/4DhwEtmtgBYTdAI2SU1MEREREREYiXGYzCK4+7vAu8WWnZbvsdbgb/vzj7VRUpEREREREqNGhgiIiIiIlJq1EVKyiRfsTjeIcROanq8I4gpK/6mPwkjsvjHeIcQU5bRNN4hxIy//3q8Q4itrKx4RxAzT0yK6uydZc5l3S8qvlACedqLHT4QfWWsi1Q0lJ//9CIiIiIiEnXKYIiIiIiIxIwyGCIiIiIiIiWmDIaIiIiISKxoDIaIiIiIiEjJKYMhIiIiIhIriZ/AUAZDRERERERKjzIYIiIiIiIxk/gpDGUwRERERESk1CiDISIiIiISK5pFSkREREREpOSUwRARERERiRVlMEREREREREpOGQwRERERkZhRBkNERERERKTE1MAQEREREZFSoy5SIiIiIiKxokHeIiIiIiIiJacMhoiIiIhIzCiDISIiIiIiUmLKYIiIiIiIxIrGYIiIiIiIiJScMhgiIiIiIrGiDIaIiIiIiEjJKYMhIiIiIhIziZ/BUAOjDDGzd4Ez3H2tmW1092q7KNsMGOvuLYtY9ywwyN2/MbOfgXbuvtLMprn7YeG2h7n7q38gxlOAu4EIkA1c6e5Tw3VNgGeBxoADx7v7z2Y2AjgSWBfu5lx3/3J3X7s0TZn3PQNeHUMk4vQ5oj0XntCtwPqZ3y/kvlfH8sPiTAZe8k96tW8Vn0B3w5Q58xgw/NWgTkd35cK/nVBgfda2bVz/2LN883+LSK1elUHXXkrD9Dp5639bsYqT+t/CZaedwvm9jwXg5iHPMXnWV6TVrMGYwXfHtD7FmTLrK+4d+iKRSIQ+Pbtz0T9OLrA+a9s2rh/4FF8v+InU6tUYdEN/GmXU5dMv5jHw+dfYlp1DhZRkrut7Jp1aHwTAIy+8zjsTp7B+4ybm/Pf5eFSrWFO+XsB9b7xPTiRCny5tuPDYwwusn/XjIu57431+WLKMh/v2oVfbFgAsWbWW/k+/TsSd7JwIZ3bvwOlHtItHFYpV3o7lPM3+QlK3v0JSEj7vM3zmRwVW28FdsEO6QiQC234n8uHrsDoTKlch6aS+kNEE/2YGPvGt+MS/u/ZuQdLR/wjq+9Wn+PTxBVbbIV2xNt3AI5D1O5H3X4FVS6F+M5KOPTMsZESmjoUf4vovpVhT5v/IfW+8R07E6XN4Gy48tmuB9bN++Hn75/aCPvRqG3wnLVm1lv5PjQw/tzmc2b0jpx/ZPh5VKDX/Gv4ErU48lg3LV3B3q07xDkeiRF2kyhB3P97d15bCfi5w92+KWH5Y+LAZcMYf3P0EoLW7HwKcT9CgyPUi8JC7/wXoACzPt+4/7n5I+BPX/wQ5kQh3v/QOQ686jzH3XsW4GV+yYMmyAmUa1E7lvgv+zgmdWscpyt2TkxPh7qEvM/TWqxgz+B7GTZ3Bgl+XFCjz1kdTqFm1KuOfup+zT+rJwy++WWD9A8+PpOuhBRtSvXt0YehtV0c9/t2VkxPhrqeeZ9id1zH2qYcY98k0FvyyuECZt8ZPpka1qnzw7COc0/s4Bj7/GgC1alTnqdv/w5gnH+D+qy/luoFP5m3TvWMb3nikjJ58Ehy797z2Ls9cfiZjbr+Md2fOZ8FvKwqUqV+rJgPO6c0JhRrFdWtW57Xr+jLqlksYef0FPPv+VJav3RDL8EukvB3LecxI6vF3IqOeJjJiAHZgW0irV6CIfzebyIv3E3n5QSIzJ5DU7dRgRXY2kU/H4Z+Mjn3cf5QZST3/SeSNx4kMuxNr0R5q1y9QxL+ZSeS5u4k8fy+RGR+QdFSfYMWKJURG3Bcsf30wSb3OACu7pzPB53Ycz1xxFmPuuIx3Z85jwW/LC5Spn1aTAef25oQOhT+31Xjt+gsYdeuljLzhQp4dP5Xla9fHMvxS99mIVxhy7F/jHUZcmVlMf+Kh7H4i9zBmNtrMZpvZ12Z2kZldYmYP5Vt/rpk9XlTZfGV+NrM6hfZbzcwmmNkcM5sXZhBypZjZK2b2rZm9ZWZVwm0mm9kOlybNbGP48H6gq5l9aWZXmdknZnZIvnJTzazIM2t33+juHj6tSpCpwMxaACnu/mG+cptL+veLpbkLf6VJem0ap9emYkoKx3dozcQvCrbHGtZJ44DG9UnaQwZizf1xIU3qp9O4XjoVK6Rw/OEdmfh5wXbcxM+/4JTuQRuz12HtmD73W3Lfyo9mzKFRel32a9KgwDbtDzqA1OpVY1OJ3TD3hwU0aZBB4/oZQX2P6MyE6bMLlJkwYxa9jwquEvY6vCOffTUfd6fFvs3IqF0LgOZNG/H771lkbdsGwCEHNic9rVZsK7Mb5v28hCbpaTSuW4uKKckc1/4gJs79rkCZhnVSOaBRxg7HbsWUZCpWCJLW27KzieR9jMuW8nYs56nXFNaugHWrIJKDfzcH27dQ5jRra95Dq1ARct/D7Cz4bSFkb4thwH9S/WawZjmsWxnU95uZWPODC5bZaX23BVkNgJQKsYn3T5j3U+7nNo2KKSkc164lE78q/LmtxQGN6hXxuU3J97nNIRIpm5/b3bFgyjQ2r14T7zAkytTAKD3nu3tboB3QHxgFnJpv/WnAyKLKmlntXex3K3Cqu7cBugMDbXtz9ADgyTBjsB7oV8JYbwCmhNmER4DhwLkAZrY/UNndv9rZxmZ2qpl9B4wjyGIA7A+sNbO3zewLM3vIzJLzbXavmc01s0fMrFIJ44yK5WvWUy+tZt7zjLSaLFuzZ18RWr56LfXqpOU9z6hdi2WrCn6BL1u1lvphmZTkZKpX2Yu1GzayactWnn37PfqdVrCLUVm2bNUa6tfZ/rGpVyeNZatWFyizfNUa6tcNygT1rcLa9QWv2I//9HNa7NuMihXK/kkKwLI1G6hXq0be83qpNVi+puRZiKWr19H77qfoceMjXNCrC+mp1aMR5p9S3o7lPNVS8Q35Etgb10L1mjsUs9ZdSTr/NuyIU4hM+m8MAyxl1WvhG/K9rxvWQvUdG/fW5kiSLr4b6/5XIh+9sX1F/WYk9b2NpL63Ehn/6vYGRxm0bO166tXa/l7Wq1Vzt7KHS1evo/ddT9LjhkHh57ZG8RtJ2WYW2584UAOj9PQ3s6+A6QRjEPYGFppZp7ABcSDw6U7KNt/Ffg0YYGZzgY+AhkBGuO5Xd8/d58vA4UVsXxJvAieaWQWCBsOIXRV291HufiDQm2A8BgTjeboC1wLtgX0IGy3AjQT1bw+kAdcXtd8w8zPLzGYNfeeDP1gV2V1PvP4O55x8DFX3qhzvUGLqx0WLGfj8a9x5xQXxDiVm6qfVZPStl/L+3f1557OvWLl+Y/Eb7UHKw7HsX00h8txd+JT/YR17xjucqPM5HxN55lZ88ijssOO2r1j6M5HhdxF54X6SOh0LyYk7pLR+Wk1G39aP9+/pzzvTE+9zK4kpcT+RMWRm3YCjgc7uvtnMJgOVCTIW/wC+A0a5u++i7M6cCdQF2rr7tnDQdm75wrnSP5Q7DeP4EDgljLdtCbf7xMz2Cbt1LQa+dPeFEHQDAzoBw919abjJ72b2PEEjpKj9DQWGAkSmjYpaHji9Vg0yV6/Le75s9Toyau3ZV4TS01LJXLn9Cv6yVWvyugHlyqidytKVq6lXJ43snBw2bN5CavVqzP1hIeOnzeLhF95kw6bNJCUlUaliBc48/qhYV6PEMmrXYunKVXnPM1euJqN2WoEy6bVrsXTFKurVqR3WdzOpNaqH5Vdx+T2DeOCaS2lSP4M9RUat6mTmy7Zlrl1Peq3dz0Kkp1Znv4bpzP7xl7xB4GVFeTuW82xci1VP3f4lXi0VNqzbaXH/bg5JR/0DH/9KTMIrdRvWYNVrba9v9VTYsPNuM/7NLJJ6noHzQsEVqzJh21ao2wAyf4lauH9GRmoNMtdsfy8z16z7Q9nD9NQa7Ncgndk/LsobBC57qj2j+/WfoQxG6agJrAlP1A8kOLGGoJvUKcA/2d49amdld7Xv5WHjojvQNN+6JmbWOXx8BjC1hPFuAAp/uz0LDAZmuvtOv+XNbL/cLlpm1gaoBKwCZgKpZlY3LNoD+CYsVz/8bQRZj/kljDMqWu3diEXLV7F4xWqysrN59/Ov6H5o2TrJ2l2tmu/NoqXLWLxsBVnbsnl36gy6tz+kQJnu7Q/hnUnTABg/bRadWh2ImfHygBuZMPQhJgx9iLNPOoaL/nZCmT8ha7X/vixaksnizOVBfT/5jB4dC7aLe3Rsy+gJUwAYP3UGnQ4+CDNj/cZNXHzHQ1xz7um0aXFAPML/w1o2bRgcuyvXkJWdw3szv6b7wSWrQ+aa9WzNCvror9u0hTkLfmHvervqnRkf5e1YzpP5C6TWhRppkJSMHdgGXzivYJnUutsf73MQrCk4wH+PsnQRpKVDzdpBfVu0xxfMLVimVvr2x/u1DMZsQLBN7qDuGmnBYPh1qyirWjZrwKLlq8PPbTbvzZpP99YHlmjbzDXrivjc1ilmK5H4UwajdLwPXGJm3wLfE3R9wt3XhMtauPvnuyq7C68AY8xsHjCLIBuS63vgMjN7juBk/qkSxjsXyAm7aY1w90fcfbaZrQeKm5vzb8DZZrYN2AKcFg76zjGza4EJYUNiNjAstw5hw8OAL4FLShhnVKQkJ3PLmSdzwcDniEQi/LVrO5o3zGDwqA9o2awRPQ5twbyFv3LF4y+xftMWJn35HUNGf8jYe8vuDDQpycnccuFZXHDnoKBORx1O8yYNGfzqKFru14weHQ6lz9FHcP2jw+h16Q3UrFaVgddcXOx+rxn4NJ9//T1r12+k2wXXcPnpp9Dn6CNiUKNdS0lO5tZLz6XvrfcTiUT42zHdaN60EYNfepOWzfehR6e29OnZjesefpKeF1xFzepVGXTdFQC8MvYDfvltGU++NoonXxsFwPB7bqB2ak0eeu5Vxk6expbfszjy7Mvp06sbV5zZJ55VLSAlOYmbTzueCwe/TCTinHrYITRvkM6Q/03ioKYN6NH6AOb9vIT+T7/O+s1bmTTvBx4fO5kxt/dj4dIVPPjfDzAMxznvmMPYv2HZy96Ut2M5j0eITHqLpL/1A0vC50+HVZnYYcfjmb/AwvnBtK1NDoBIDvy+hcj4l/M2T+p7O1SqDEkp2L4HE/nvk8EUtmWVR4h88DpJp/UP6jt3GqxcinU9CV+6CBbMxdp2w5oeGNR362Yi40YAYI32wzr1Cpa7E/ngNdiyKb712YWU5GRuPv14LnzsJSKRCKd2OTT83E4MP7cHBp/bp0ayfvMWJs39nsfHTGLMHZezcOlKHnxrPGbBGPey+rndHX1ffY79ux1OtTq1ue/Xbxlz+wCmPfdSvMOSUmZeRmcSkdgyswbAZOBA9/iPlotmF6kyJzW9+DIJxCombv/4wiK/fh/vEGLKMpoWXyhB+PuvxzuE2MrKincEsdOpW7wjiKnLul9UfKEE8rSvj3//pNW/xfYcJ61BzOusLlKCmZ0NzABuLguNCxERERHZc6mLlODuLxLcJC+PmZ0H/LtQ0U/d/bKYBSYiIiKSaPaQe2z9GWpgSJHc/XmKH48hIiIiIlKAGhgiIiIiIjGT+BkMjcEQEREREZFSowyGiIiIiEislIMxGMpgiIiIiIhIqVEGQ0REREQkVhI/gaEMhoiIiIiIlB5lMEREREREYibxUxjKYIiIiIiISKlRBkNEREREJFY0i5SIiIiIiEjJKYMhIiIiIhIrymCIiIiIiIiUnBoYIiIiIiJSatRFSkREREQkZtRFSkREREREpMSUwRARERERiRUN8hYRERERESk5ZTBERERERGJFGQwREREREZGSUwZDRERERCRmlMEQEREREREpMWUwRERERERiRWMwRERERERESs7cPd4xiJQZZnaRuw+NdxyxUp7qW57qCuWrvuWprlC+6lue6grlq77lqa7lkTIYIgVdFO8AYqw81bc81RXKV33LU12hfNW3PNUVyld9y1Ndyx01MEREREREpNSogSEiIiIiIqVGDQyRgspbf9DyVN/yVFcoX/UtT3WF8lXf8lRXKF/1LU91LXc0yFtEREREREqNMhgiIiIiIlJq1MAQEREREZFSowaGiIiIiIiUGjUwRMoZM9vfzCaY2fzw+cFmdku844oGM6tiZrea2bDweXMzOzHecUWTmTU1s6PDx3uZWfV4xxQNZvagmdUwswrh8bzCzM6Kd1yxYGa1zOzgeMcRbWaWbGYNzKxJ7k+8Y4oGM5tQkmV7svzHa/iZvcXM/mdmA8ysSjxjk+hQA0PKLTObZ2Zzd/YT7/iiaBhwI7ANwN3nAqfHNaLoeR74HegcPl8C3BO/cKLLzC4E3gKeCRc1AkbHL6Ko6unu64ETgZ+B/YD/xDWiKDKzyWGDKg2YAwwzs0HxjitazOwKYBnwITAu/Bkb16BKmZlVDt/POmGjMS38aQY0jG90pW5Evsf3E3xeBwJ7AU/HIyCJrpR4ByASR7lXsi8Lf78U/j4zDrHEUhV3/9zM8i/LjlcwUbavu59mZv8EcPfNVqjiCeYyoAMwA8DdfzSz9PiGFDUVwt8nAG+6+7rEfmup6e7rzewC4EV3vz3BL4T8GzjA3VfFO5Aouhi4EmgAzAZyD+D1wOPxCipK8n84jwLau/s2M/sE+CpOMUkUqYEh5Za7LwIws2Pc/dB8q24wsznADfGJLOpWmtm+gAOYWR9gaXxDiposM9uL7XXdlyCjkah+d/es3BNtM0shrHsCGmNm3wFbgEvNrC6wNc4xRVOKmdUH/gHcHO9gYuBXYF28g4gmd38MeMzMrnD3IfGOJ8pqmtmpBD1nKrl7bgbdzSxRv6PKNTUwRMDMrIu7fxo+OYzE7j54GcENjg40syXAT0Ci9l2/HXgfaGxmrwBdgHPjGlF0fWxmNwF7mdkxQD9gTJxjipbbgQeBde6eY2abgZPjHFM03QWMB6a6+0wz2wf4Mc4xlTozuzp8uBCYbGbjyHdRwN0TrluYuw8J/+80I995mbu/GLegSt/HbP98TjezDHdfZmb1gJVxjEuiRDfak3LPzNoCzwE1CdK4a4Dz3X1OXAOLMjOrCiS5+4Z4xxJNZlYb6ETw3k5394T9Z2ZmSUBfoCdBfccDz3oCftGb2Rx3b1PcskRhZpXdPZEzNACY2e27WO3uflfMgokRM3sJ2Bf4EsgJF7u7949fVCJ/jhoYIiEzqwng7gmZls93ZbBIiXRl0Mx2eZKZqI3HsNG41d1zwufJBN0RNsc3stITXvFsCLwMnMH2vt01gKfd/cB4xRZNZraAYNDzlPBnaqJ+VwGY2d/d/c3iliUCM/sWaJGIFwJyhTOALXf3reE4uHOBNsA3wDB3T9RxgOWWGhhSbpnZWe7+8s5OvBPphBsKXBk8AGgP/C98fhLwubsnTDcpM5sUPqwMtCMYRGjAwcAsd++8s233ZGY2HTja3TeGz6sBH7j7YfGNrPSY2TkEJyftgFn5Vm0ARrj72/GIKxbCk7SuBF39jgfWuvsh8Y0qOspThsrM3gT6u3uijoUjnBa9QzjRxgMEGZvRQA8Adz8/nvFJ6dMYDCnPqoa/E/I+AYW5+50A4awdbXK7RpnZHQRTQCYMd+8OYGZvE9R1Xvi8JXBHHEOLtsq5jQsAd9+YaHPMu/sLwAtm9jd3/2+844kVM2tE0LDoCrQGvgamxjWoKDCz4wgaTw3NbHC+VTVI3Nnu6gDfmNnnFBxvkkhjipLyZVKPJphFKgK8bGaaRSoBqYEh5Za7PxP+vnNX5czsRne/LzZRxUQGkJXveVa4LBEdkNu4AHD3+Wb2l3gGFGWbzKxNbhewcHzRljjHFC1jzewMdhwYm3B99EO/ADOBAe5+SbyDiaLfCDJTJxNM3ZprA3BVXCKKvjviHUAM/GpmPdx9IsF9axoDi8IxcpKA1EVKpBiJlpY3s5sJprocFS7qDbzh7gPiF1V0mNlrwCaC/voQ3OOkmrv/M35RRY+ZtQdGEpykGVAPOM3dZ+9ywz2Qmb1PMI3pbLYPjMXdB8YtqCgys9bA4cARQBOCGaQ+dvfhcQ0sSsysQu5UprLnM7PGwItAMsHn9nCCQe2pwLXunlB3Lhc1MESKZWZfFLpPxh4vHATdNXz6ibt/Ec94osXMKgOXEpyUAXwCPJXIs/GYWQWCcTYA3yfqSZqZzXf3lvGOI5bCMTWHE3x2zwJw96ZxDSpKzKwLwZX9pgQZKiOYWWmfeMYVDWa2ge33q6lIcBPJTe5eI35RRUeYQd6f4D1dDMwMu0pJglEDQ6QYCZjBaFLUcnf/JdaxSOnI7XpgZn8tan0iDnw2s6HAkPxd4BKZmc0CKgHTCGeSyr1ZaCIKb6J4FTtmqBL5zt6EMyydAnRy90S92SsAZpbm7qvjHYdEhxoYIsVItAyGmc1j+9WyvYC9Ca50HxS/qKLDzH6iiDtZJ9pVUDO7091vN7Pni1jtiTRDS77jNwVoTnBDtt/ZfoX74DiGFzVmVtfdV8Q7jlgxsxnu3jHeccRLAv7f6QI8C0SA84F7gH0IMjb/cPfP4hieRIEGeUu5l/8u3jtZllDzrrt7q/zPw+5S/eIUTrS1y/e4MvB3IC1OsURN2LhIAt5z9zfiHU+UnRjvAOIkycyGAw3c/TgzawF0TtQxGMAkM3sIeJuCMysl3D1sCmUekwi+txKtG+cjBGP/qhHMWtjb3aeG/3+GEMyQJglEGQwp98rTfOs7Y2bzCjc8EpWZzXb3tvGOIxrMbJa7tyu+5J7PzIpqKG5I4DEn7wHPAze7e2szSwG+SNTPbb572eTn7t4j5sFEWaHMYzbBLEvD3H15fCIqffkzMmb2rbv/Jd+6cvX/trxQBkPKLTPrDBwG1C10s70aBDNdJKRCdU0iuJvqb3EKJ6oK3dE798pgIn/vfWRm1wKvE8yeBUCC9nOeQzDV5RqC7lGpQKaZLQMuTMCZs+q4+xtmdiOAu2ebWU5xG+2pcu9lUx64+3nxjiEGkvI9vrHQuoqxDERiI5H/0YoUpyJBujaFgjfbWw/0iUtEsZG/rtkE6epEvWFZ/ilLs4GfCNL0ieo0gvEJhbu8JdSYk9CHwFvuPh7AzHoCfyO4yv8kkGj99zeF9wxwADPrRDDdZ0Iys5rA7WyfAe5j4C53T7g6hzdRzN9NaArwb3dfHL+oSt2tZlbF3Te7++jchWa2L8H0tZJg1EVKyj0za5o7G0vYj72au6+Pc1hRY2Z/d/c3i1uWCMxsH3dfWGjZ3u7+U7xiiiYz24ugcXE4wYnoFOBpd0+4m+0V1a3PzOa6+8Fm9qW7HxKv2KIhX1/1lsB8oC7Qx93nxjWwKDGz/xLU84Vw0b+A1u5e5ExpezIz+xB4FXgpXHQWcKa7HxO/qOLDzIa4+xXxjkP+PDUwpNwzs1eBSwimQpxJ0EXqMXd/KK6BRUl5GnOyk7om8hiMNwgycK+Ei84Aarp7wmVtzOwDYALBjQUhyN4cAxxLMLd+Ih7PKQT3ODES+B4nAEU1EhOx4Qjlq67FSdT/ReWRukiJQAt3X29mZwLvATcQzL2eUA0MMzsOOB5oaGaD862qQdB9KGGY2YHAQUDNQjO01CCYTSpRtXT3FvmeTzKzb+IWTXSdQdCFJre7xafhsmQSqBvcLu5xsr+ZJeQ9TkJbzOxwd58KedOcJlwmLrTKzM4CXguf/xNI6Pt9SOJTA0MEKoR3P+4NPO7u28wsEVN7vwGzgJMJGlC5NhDc0CqRHEAwnWkqcFK+5RuAC+MSUWzMMbNO7j4dwMw6ErznCcfdVwI760qxIJaxRNmRwEQKHse5nGAa10R0KfBCOBbDgNXAuXGNKHrOJ+j+9gjBezoNKA8DvyWBqYuUlHtm1h+4HvgKOAFoArzs7l3jGliUmFmKuydUxmJnzKxzebqBk5l9S9C4yr0rexPge4IMVULchM7MHnX3K81sDEXfRPHkOIQVdWaW7O4JO2vUzphZDYBEHhcn2yXaDQbLMzUwRIqQiCfhZvaGu/+j0J288yTCyWcuM7vO3R80syEUXdf+cQgr6sys6a7W505msCczs7buPtvMjixqvbt/HOuYYsHMfgHeJ5iCeKIn+D9vM0sFzgaaka+3RSJ+ds3sBYJZo9aGz2sBA939/PhGVvrMrJW7z9vF+nPdfUQMQ5IoUQNDyr3yMh2imdV396U7OwlNhJPPXGZ2kruPMbNzilrv7i8UtVykrDKzKgTd/k4nuHfNWGBk7hiFRGNm04DpwDwgkrv8/9u78yi7y/qO4+/PICXGEAKCAlIRFaFQw6JhE62oVJSlhRiwtcpitS4VUEtRaK21uKDVI6UbdS2IRSiglCKINAUpIJIQiSy2yNKyKLKFCLLJp3/8fte5M50khbn3PnOf+3mdM+fm95vhnM+cTJj7/T3P8/3W+G93qqf2tT7Jl/QdYB3gy8Cptf2ejXEpMGLkjVI7RABJx9s+ek33Imay9tDvh4HNaZ5wi2YbWI0zPyZon3CfQNPKtMqhoKPUTUjS94FX2r6vvd4AuLjiKe1b0pw7WQRcCXzJ9oVlU0WvpcCIkTdqLQJX0br1mpq2SHWsYp/+CpqDzyfZfnjwqaIXJN1A05xgCU2LaQBsV9t9p90WdhBNK96rgK/ZrnJIpqT3Aj+jWal5pHO/xqn0kt4CHAN0ZhEtAj5q+5RV/1fDTdJaNI1V/oqmtbaAYyruijZy0kUqYkTaIUp6J80QtudL6h7OtS5Ni88a3UQzkKzT/vEgmk5SLwI+R7NaFcM0DJJfAAAWpElEQVRphe1vlg4xKJJuAa4GTgeOsv1g2UR99yhNq/BjGX9IYCqcSm/7ZElXAa9qbx1g+5ftpSWt31ndGHaS5tN0yNobuBDY1/ZSSZsCl1NvV7SRkxWMGHmStqfZHrVee+s+4ODaJuS2Z03WBz5OM+ujY2WNTwUBJH3P9oKp7km61va2pbLF9Ej6BM3Mi7OY+IR7abFQfSRp7ih1UpJ0E7BT2454pNW0XUzSxcDngX+2/fNJn3tzzas2oyYrGBFwPfBJ4AU0cxNW0CzdVlVgtIfpVtAMcULSs2iGzs2RNMf2f6/uvx9ScyQ9t/O9SXouMKf93KPlYkUP7Ny+vrTrnhl/ClybjSWdDTzb9q+3T4L3s31c6WB9ciPwUOkQM4RKB+ihsycXEZKOsH1Ciou6pMCIgG8A9wNLgdsLZ+k7SfsCnwE2Be6iOSR7Pc3k69q8H7hU0o9ofklvAbxL0jMYP9QfQ8j2Hqv7vKSDK+s49DngKOAkANvXSPoqUGuB8SCwTNJiJq5QVdem9v+hpq0mbwE+O+neITRNC6IiKTAiYDPbe5UOMUDHAbsA37a9g6Q9gN8rnKkvbJ/XdizZur31w66D3ZN/yUVdjqCuInK27SulCQ+zq5rVM8nX24+ogKTfAX4X2ELSOV2fWpdmSntUJgVGBFy2puE/lXnM9j2SxiSN2V4sqeY32y9hfFjXdpKwfXLZSDEANW0rAbhb0gton2ZLegNwZ9lI/bOm1SdJZ9peOKg8hdXws3wZzc/rhsCnu+6vpLLtyNFIgREjq2ui9dOAQ9tDhY8w3k+/uratrfslzQEuAU6VdBfNdoTqSDqF5mzNMsZbmRpIgVG/mraVALwb+Adga0m3AzcDbyobqahqukm1heNtth+R9EpgPnByZ7I38Opi4XqkHeR6K7Br6SwxGOkiFSNrVROtO2qabN2tPX/wME0h9Saa7lmn1jg/QNL1wDbO/+hGTk2TkNuZAcfb/qP23++Y7ZWlc5VUWWelZTTNCp4HnEdzLnBb268vmauXJF1qe3dJK5lY/Hce6M0tFC36JCsYMbJqLSDWZFL//Jr2qE/lB8DGVLyVJFapmtkutn8haff2z1WuNo64J2w/Lml/4ETbJ0q6unSoXrLd+fldt3SWGIwUGBEjYoonR7/8FPU+QdoQuE7SlUzsRLNfuUjRC5Lm0XSkeR5dv8s6XYZs/2GZZH1zdXs49gy6tjSO8OTjGs4ldDzWHoI+GNi3vbd2wTw9J2mD1X2+1llMoywFRsSIGNEnRx8uHSD65jzgCmA58EThLIMwC7iHiXM+TIWTj9stYSfbXt0Zk6MHlWcADgXeAXzU9s2StgBqmwmxhObndarCsMoJ7aMuZzAiomqSng10pnlfafuuknmiN2rag98Lkj5o++Olc/SKpEuBV9nOQMyIIZQCIyKqJelA4FPAv9M8OXs5cJTtfy6ZK6ZP0nuBnwHnMnH720hutait4JJ0MvBrwDlM3BL2mWKh+qSro2G3FcBVwHE1NOCQtLXtGyRN+TNqe+mgM0V/ZYtURNTsWGBBZ9VC0kbAt4EUGMPvUZri8VjG35yN8laLms4kAPyo/RijGcZWs2/StNH+anv9RmA28GPgy4yfyxhm7wPezsQZGB1m4ta/qEBWMCKiWpKW235x1/UY8P3uezGc2rk1O9m+u3SWmaC2FYwOSbNtP1Q6Rz9N9XfXuTf5/2ERw2KsdICIiD46X9IFkg6RdAjwrzSHg2P43QhU/cbzSapqBUPSrpKuA25or7eT9LeFY/XLWpJ26lxIWgCs1V4+XiZSf0iaJel9ks6SdKakIyXNKp0rei8rGBFRNUkLgZe1l9+xfXbJPNEbks4GtgUWM/EMxuHFQvWBpONtHy1pke0zVvN1x9j+2CCz9ZOk7wJvAM7pDEyU9APbv142We+1BcUXgTk0heIDwO8D1wJ72z69YLyeknQ6sBL4Snvrd4F5theVSxX9kAIjIiKGjqSDp7pvu6rhke0B4PnAkhq3QK2KpO/a3rl7Iruk79vernS2fpG0HoDtFaWz9Iuk62xvs6Z7MfxyyDsiqjOiQwVHSm2FxGqcD9wHzJH0AO3PMPX/LP+PpN0AS1obOAK4vnCmvpC0DrCQdmik1Ox2s/2RgrH6ZamkXWxfASBpZ5puWVGZrGBERMTQkXQzUxSRtqvsIiXpG7Z/q3SOQZG0IXAC8Bqa86IXAEfU0LJ1Mknn07SlXULTTQoA21N1XBpKXa141wa2Av67vd4cuCErGPVJgREREUNH0jO7LmcBi4ANbH+oUKS+mzQ08ru2f1oyT/RGrWdLuknafHWft33roLLEYKSLVEREDB3b93R93G77s8DepXP1i6RFwJU0hdSBwJWS3lA2Vf9Ier6kf5H0U0l3SfqGpCpXp4DLJFXditb2rd0fwM9pVjA6H1GZrGBERMTQmTQReAx4KfDOWg8BS/o+sOfkoZEVf79XAH8D/FN7643Ae2zvXC5Vf7TteF8I3EzTEa1zvmZ+0WB9IGk/mmF7mwJ30WyRut72tkWDRc/lkHdERAyj7v3pjwO30DzZr9VYp7ho3UPduxBm2z6l6/orko4qlqa/Xlc6wAD9BbALTXG8g6Q9gN8rnCn6IAVGREQMHdt7lM4wYOdLuoDxJ/oHUffQyG9K+gBwGs0WmoOA8yRtAGD73pLhekHSXNsP0MyFGBWP2b5H0pikMduLJX22dKjovWyRioiIoSNpHvAW2taenfu1DdrrJukAYPf2suqhkW2XsFVxDd3CJJ1re5+ujmjd09ir+B4nk/Rt4LeBjwMb0myTWmB7t6LBoudSYERExNCRdBlwBbAceKJzf4TmY0wg6XLbu5bOMSiS9rR9Yekc8eRIegbwME0x9SZgPeDUGtsPj7oUGBERMXQkLR2lydZr0j3xehTU9Pcv6SLbr17TvYhhkjMYERExjE6R9DbgXJrOO0Ade/OfolF7Wqg1f8nMJmkWMBvYUNL6jH9Pc4HnFAvWB5JWMvXPaO0T6UdWCoyIiBhGjwKfAo5l/I2Lger2rceUaiio/gA4kqZl6xLGC4wHgL8uFaofbK9bOkMMVrZIRUTE0JF0E7CT7btLZ5kJskVqeEl6j+0TS+fop07HrE4XsMlGeOWxWjX30I6IiHrdCDxUOsQgSFpL0uI1fNmbBxJm5rildIAe+rGkdQEk/YmksyYNkqzBV9vXJcBV7euSruuoTFYwIiJi6Eg6G9gWWMzEMxhVtqmVdBFwgO0VpbMMgqRFwPm2V0r6E2BH4DjbSwtH6zlJ19ieL2l34DiarX8fqnFqeYyOnMGIiIhh9PX2Y1T8DFgu6ULgwc7NWgsq4E9tn9G+6X4NzZvuvwNqfNP9i/Z1b+AfbP+rpONKBuqn9kD7lsCszj3bl5RLFP2QAiMiIobOCM67OKv9GBWj9Kb7dkknAXsCx0tah0q3sEv6feAIYDNgGbALcDnwqpK5oveyRSoiIoaGpNNtHyhpOVN0ErI9v0CsgZD0dOC5tn9YOku/SToXuJ3mTfeOwM+BK21vVzRYH0iaDewFLLf9X5I2AV5s+1uFo/Vc++92AXCF7e0lbQ18zPYBhaNFj6XAiIiIoSFpE9t3Stp8qs/bvnXQmQZB0r7AXwK/YnsLSdsDH7G9X+FofTEKb7pHsbOSpO/ZXiBpGbCz7UckXWt729LZoreyRSoiIoaG7Tvb1yoLidX4MLAT8O8AtpdJqnnmxweBS4A74Jd/73cWTdR7XwX2oemkZCYOD6x1psttkubRnJ+6UNJ9wKj9Wx4JWcGIiIihI+kA4HjgWTRvzKqeCCzpCtu7dM+76HQfKp2tHyQdCrwc2BVYCXwHuMT2N4oGi56R9BvAejTdwh4tnSd6KwVGREQMHUk3Avvavr50lkGQ9AXgIuADwELgcGBt2+8oGqzPJG0MHAj8EbB+TROh1zTrotKWvH8FnGb7stJZor9SYERExNCR9B+2X1Y6x6C0ZxKOBX6TZrXmAuAvbD9cNFifSPo8sA3wE5rVi0uBpbYfLxqsh9YwPNG2q+usJOlg4CBgK+BsmmIjg/YqlAIjIiKGjqQTgI1p9nJ3D9qrupWrpLk0bz5Xls7ST+0gxU2B64CLabZH3VQ2VRmS9rR9YekcvdQebF8IvJGmM9qWhSNFj+WQd0REDKO5wEM0T/Q7TKWzIiQtAL4IrNterwAOs72kaLA+sb0/gKRfA14LLJa0lu3NyiYr4nigqgIDeCGwNbA5MBLbHEdNCoyIiBg6tg8tnWHAvgC8y/Z3ANoJ118Caj3kvQ/NIe9XAPOAf6PZKjWKtOYvGQ6SPgnsD/wIOI1mm9/9ZVNFP6TAiIiIoSHpj21/UtKJTD1o7/ACsQbhF53iAsD2pZKqOY8whb1oCooTbN9ROkxhNe1l/xGwG00L3nWA+ZKwfUnZWNFrKTAiImKYdLZTXEVdb7ym1NVp6GJJJwH/RPN9H0Q7E6NGtv+wHaa4DXBHO8X8abWfPRkBT9CsRm0GLAN2AS4HqjvQPupyyDsiIoZOeybhGOB5jD8sc21zIUax0xCApLcBbwc2sP0CSVsCf2/71YWj9ZykdWw/sqp7ks6yfUCZdL0laTmwALjC9vaStgY+Vsv3F+OyghEREcPoK8BRwHKap6JVsr1H6QyFvJtmcvl3AWz/l6RnlY3UN5cDk2di/PJeZW++H7b9sKROEXWDpK1Kh4reS4ERERHD6Ke2zykdYlAkzQPewsQVm5rPnDxi+1GpOd8s6WlUtiWuHSL4HODpknZg/DD3XGB2sWD9dVv7s/x14EJJ9wG3Fs4UfZACIyIihtGftcPYLmI05mCcB1xB5Ss2XS6WdAzNm+89gXcB/1I4U6+9FjiE5jzCpxkvMFbSbP+rTqf9MPDhdvvfesD5BSNFn+QMRkREDB1JX6Hpo38t42+4bfuwcqn6R9JS25O30VRL0hjwViZOLv+8K3zTImmh7TNL54jopRQYERExdCT90PbI7N2W9F7gZ8C5TFyxubdYqOgJSUfQzDRZCXyO5uzFB2x/q2iwiGkYKx0gIiLiKbhM0jalQwzQo8CnaA7/Lmk/riqaqA8knd6+Lpd0zeSP0vn65DDbD9Cs1jwTeDPwibKRIqYnZzAiImIY7QIsk3QzzRN9UWGb2i7vB15o++7SQfrsiPZ1n6IpBqtz9uL1wMm2r1XndHvEkEqBERERw2iv0gEG7EbgodIh+s32ne0fFwKnjcgU7yWSvgVsAXxQ0rqMxkH+qFgKjIiIGDq2R6215YM0KzaLmXgGo9Y2tevStDG9F/gacIbtnxTO1C9vBbYHbrL9kKRnAocWzhQxLTnkHRERMcNJOniq+7b/cdBZBknSfOAgmhWN22y/pnCkvpC0H/CK9vJi27W15I0RkxWMiIiIGa72QmI17gJ+DNwDVDnJW9IngAXAqe2twyXtarvKWRgxGrKCERERMcO1h9n/zy9s288vEKfvJL0LOBDYCDgDON32dWVT9UfbHWt720+012sBV1fcsCBGQFYwIiIiZr6Xdv15FrAI2KBQlkH4VeBI28tKBxmQeUBnpsl6JYNE9EJWMCIiIoaQpCW2X1I6R79I2h3Y0vaXJG0EzLF9c+lcvSbpd2jmXiymaVn7CppBe18rGixiGlJgREREzHCSduy6HKNZ0Xin7e0KReorSX9G8z1uZftFkjal6ST1ssLR+kLSJjTnMACutP3jknkipitbpCIiIma+TzN+BuNx4BaabVK12h/YAVgKYPuOdj5ErcaAu2nel71I0otsX1I4U8RTlgIjIiJi5nsdTavW5zH+u/uNwEdKBeqzR21bkgEkPaN0oH6RdDxNK95rGR+wZyAFRgytFBgREREz39eB+2me6D9cOEtfSRJwrqSTgHmS3gYcBnyubLK++W2arWCPrPErI4ZECoyIiIiZbzPbe5UOMQjtysUi4H3AA8BWwIdsX1g2Wd/cBKxN14T2iGGXAiMiImLmu0zSi20vLx1kQJYC99s+qnSQfpF0Is1WqIeAZZIuoqvIsH14qWwR05UuUhERETOcpOuAFwI307wJFc3D/iqHsUm6geb7vRV4sHO/pu9X0sGr+/wIT2+PCqTAiIiImOEkbT7Vfdu3DjrLIIza97s6ks60vbB0jognI1ukIiIiZrhRe2M9at/vGjy/dICIJ2usdICIiIiIWKVsNYmhkwIjIiIiIiJ6JgVGRERExMyl0gEinqwUGBEREREz19GlA0Q8WekiFRERETFgkpazmvMVNbXkjdGTLlIRERERg7dP+/ru9vWU9vVNBbJE9FRWMCIiIiIKkXS17R0m3Vtqe8dSmSKmK2cwIiIiIsqRpJd1XexG3p/FkMsWqYiIiIhy3gp8UdJ67fX9wGEF80RMW7ZIRURERBTWKTBsryidJWK6sgQXERERUYikZ0v6AnCa7RWStpH01tK5IqYjBUZEREREOV8GLgA2ba//EziyWJqIHkiBEREREVHOhrZPB54AsP048IuykSKmJwVGRERERDkPSnom7dA9SbsAOYcRQy1dpCIiIiLKeR9wDvACSf8BbAQsKhspYnrSRSoiIiKiEEnr0GyJ2goQ8ENgzPYjRYNFTEMKjIiIiIhCppranUneMeyyRSoiIiJiwCRtDDwHeLqkHWhWLwDmArOLBYvogRQYEREREYP3WuAQYDPgM133VwLHlAgU0SvZIhURERFRiKSFts8snSOil1JgRERERBQkaW9gW2BW557tj5RLFDE9mYMRERERUYikvwcOAt5Dcw5jEbB50VAR05QVjIiIiIhCJF1je37X6xzgm7ZfXjpbxFOVFYyIiIiIcn7evj4kaVPgMWCTgnkipi1dpCIiIiLKOVfSPOBTwFLAwOfLRoqYnmyRioiIiJgB2qnes2yvKJ0lYjpSYEREREQMmKQDVvd522cNKktEr2WLVERERMTg7buazxlIgRFDKysYERERERHRM1nBiIiIiChE0oemup9BezHMUmBERERElPNg159nAfsA1xfKEtET2SIVERERMUO0naQusP3K0lkinqoM2ouIiIiYOWYDm5UOETEd2SIVERERUYik5TRdowDWAjYCcv4ihlq2SEVEREQUImnzrsvHgZ/YfrxUnoheyBapiIiIiHI2Ae61favt24GnS9q5dKiI6cgKRkREREQhkq4GdnT7hkzSGHCV7R3LJot46rKCEREREVGO3PW01/YT5IxsDLkUGBERERHl3CTpcElrtx9HADeVDhUxHSkwIiIiIsp5B7AbcDtwG7Az8PaiiSKmKWcwIiIiIiKiZ7LHLyIiImLAJJ3I+PyL/8P24QOME9FTKTAiIiIiBu+q0gEi+iVbpCIiIiIiomeyghERERFRiKSNgKOBbYBZnfu2X1UsVMQ0pYtURERERDmnAtcDWwB/DtwCfK9koIjpyhapiIiIiEIkLbH9EknX2J7f3vue7QWls0U8VdkiFREREVHOY+3rnZL2Bu4ANiiYJ2LaUmBERERElHOcpPWA9wMnAnOBI8tGipienMGIiIiIKGcRzZb1H9jeA9gT2L9wpohpSYERERERUc582/d3LmzfC+xQME/EtKXAiIiIiChnTNL6nQtJG5At7DHk8gMcERERUc6ngcslndFeLwI+WjBPxLSlTW1EREREQZK2ATqD9f7N9nUl80RMVwqMiIiIiIjomZzBiIiIiIiInkmBERERERERPZMCIyIiIiIieiYFRkRERERE9EwKjIiIiIiI6Jn/BXoAaMt8cer0AAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 864x720 with 2 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "reviews per month and number of reviews are strongly correlated hence will drop  reviews per month\n",
        "\n",
        "the rest of the variables are not strongly correlated hence i will not drop any other columns"
      ],
      "metadata": {
        "id": "Md6q5gPmWM0P"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "df.drop(columns = ['reviews_per_month'], inplace = True)"
      ],
      "metadata": {
        "id": "od4MdD1WWdZl"
      },
      "execution_count": 31,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df.shape"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rF3hdBfDXA2_",
        "outputId": "d21d4e86-4a28-4fbf-f584-7a4fb664fea0"
      },
      "execution_count": 32,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(17075, 12)"
            ]
          },
          "metadata": {},
          "execution_count": 32
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "12 columns remaining"
      ],
      "metadata": {
        "id": "yOQ1zsrDXDrI"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# check VIF scores\n",
        "\n",
        "features = numerical_train.drop(['price'], axis =1 )\n",
        "features\n",
        "\n",
        "unit_train = features/(features.max())\n",
        "sorted_vars = unit_train.var().sort_values(ascending = False)\n",
        "print(sorted_vars)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "g6UObYwBXgWR",
        "outputId": "0075beb3-5de3-4e37-b665-57b63422c492"
      },
      "execution_count": 34,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "availability_365                  7.320372e-02\n",
            "id                                7.170868e-02\n",
            "host_id                           4.744645e-02\n",
            "calculated_host_listings_count    8.246591e-03\n",
            "number_of_reviews                 4.525346e-03\n",
            "reviews_per_month                 5.226424e-04\n",
            "minimum_nights                    2.436060e-04\n",
            "longitude                         5.022745e-05\n",
            "latitude                          9.661556e-08\n",
            "dtype: float64\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "We don't see any VIF score of 5 and above, which means our dataset does not have high levels of multicollinearity. We are, therefore, good to go."
      ],
      "metadata": {
        "id": "8Xlo8gjGX2fZ"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "UFT-K1wQBiU5"
      },
      "source": [
        "# <font color='#2F4F4F'>3. Data Analysis</font>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "T3ugplNYBiU5"
      },
      "source": [
        "## 3.1 Univariate Analysis "
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hMJPsYX_BiU6",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 390
        },
        "outputId": "46b939db-fb60-4b07-d98c-07b8ca5e294b"
      },
      "source": [
        "# getting the top 10 most common hosts\n",
        "plt.figure(figsize = (10, 6))\n",
        "df.host_name.value_counts()[:10].plot(kind = 'bar', rot = 0)\n",
        "plt.title(\"Top 10 Hosts\")\n",
        "plt.show()"
      ],
      "execution_count": 35,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlYAAAF1CAYAAAAqdaQaAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAbs0lEQVR4nO3debhsVX3m8e8LVwQhzDc0k14SUEMniHol2g4hatsYVEi0UeKAihLTTjGxlSR2i0MrRKOIido4cRWDMmigwaCIgjN6EWQQozQyT9cwRMQgwy9/7HW0OJ47cGqdc+rcfD/PU0/tvfa0Vu1dVW+tvasqVYUkSZLGt8FCV0CSJGl9YbCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJI0tyW0jt3uS/Gxk/LmdtnFAkq8nuT3JWTNM3zPJuW36uUn2XMO6zkrykmlleye5esw6LktSSZaMsx5Ji5fBStLYqmqzqRtwJfD0kbJPdNrMTcCRwOHTJyTZCDgZOBbYClgBnNzKJWneGKwkzZkk909yZJJr2+3IJPdv0/ZOcnWSv0ry4ySXr6l3q6q+UFXHA9fOMHlvYAlwZFXdUVVHAQGeOEbdd0hySpKbklya5KUj0/ZKsjLJvya5Icm72qQvt/tbWm/dY5LsmuTsJLe2dn5qtnWSNPkMVpLm0l8Djwb2BB4G7AW8YWT6fwK2BXYEDgKOTvKQWWznPwMX1L3/o+uCVj5bnwSuBnYAngW8LclUUHsP8J6q2hz4TeD4Vv6Edr9l6637BvAW4PMMPWk7Ae8do06SJpzBStJcei7w5qq6sapWAW8Cnj9tnv/VepnOBk4DDpjFdjYDbp1Wdivwa2tY5qgkt0zdgFOnJiTZGXgs8Pqq+reqOh/4EPCCNsudwK5Jtq2q26rqm2vYzp3Ag4Ad2rq+et+aJmkxMVhJmks7AFeMjF/RyqbcXFU/XcP0dXUbsPm0ss2Bn6xhmVdV1ZZTN+BpI9N2AG6qqtHlr2DoWQM4GHgw8P0k304yuux0r2M4LfmtJBcnefE6tEfSImWwkjSXrmXorZnyQO59jdRWSTZdw/R1dTGwR5KMlO3RymfjWmDrJKM9Xg8ErgGoqh9W1YHArwNHACe2dtT0FVXV9VX10qraAfgT4H1Jdp1lvSRNOIOVpLl0HPCGJEuTbAv8b4Zv7o16U5KNkjyeodfohJlWlGTDJBszXKS+QZKNk9yvTT4LuBt4Vbtg/hWt/IuzqXRVXQV8HXh7284eDL1Ux7a6PC/J0qq6B7ilLXYPsKrd/8ZIvf97kp3a6M0M4eue2dRL0uTzt1YkzaW3MpySu6CNn9DKplzPEDauBW4HXlZV31/Nup4PfHRk/GcMP6vwwqr6eZL9Ga6DOhy4BNi/qn4+Rt0PBD7Q6nYz8Maq+kKbtg/wriQPYDhF+Jyq+hlAkv8DfK2Fvn2ARwFHJtkCuAF4dVVdNka9JE2w3PtLNJI0P5LsDRxbVTutbV5JWiw8FShJktSJwUqSJKkTTwVKkiR1Yo+VJElSJwYrSZKkTibi5xa23XbbWrZs2UJXQ5Ikaa3OPffcH1fV0pmmTUSwWrZsGStXrlzoakiSJK1VkitWN81TgZIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUyZKFrsA4lh162rxu7/LD953X7UmSpMXFHitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjpZa7BK8pEkNya5aKRs6yRnJPlhu9+qlSfJUUkuTXJBkkfMZeUlSZImybr0WB0D7DOt7FDgzKraDTizjQM8Fdit3Q4B3t+nmpIkSZNvrcGqqr4M3DSteD9gRRteAew/Uv6xGnwT2DLJ9r0qK0mSNMlme43VdlV1XRu+HtiuDe8IXDUy39Wt7FckOSTJyiQrV61aNctqSJIkTY6xL16vqgJqFssdXVXLq2r50qVLx62GJEnSgpttsLph6hRfu7+xlV8D7Dwy306tTJIkab0322B1CnBQGz4IOHmk/AXt24GPBm4dOWUoSZK0XluythmSHAfsDWyb5GrgjcDhwPFJDgauAA5os38W+APgUuB24EVzUGdJkqSJtNZgVVUHrmbSk2aYt4CXj1spSZKkxchfXpckSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0sWegKaPWWHXravG7v8sP3ndftSZK0vrHHSpIkqZOxglWS1yS5OMlFSY5LsnGSXZKck+TSJJ9KslGvykqSJE2yWQerJDsCrwKWV9VvAxsCzwGOAN5dVbsCNwMH96ioJEnSpBv3VOASYJMkS4AHANcBTwRObNNXAPuPuQ1JkqRFYdbBqqquAd4JXMkQqG4FzgVuqaq72mxXAzuOW0lJkqTFYJxTgVsB+wG7ADsAmwL73IflD0myMsnKVatWzbYakiRJE2OcU4FPBn5UVauq6k7g08BjgS3bqUGAnYBrZlq4qo6uquVVtXzp0qVjVEOSJGkyjBOsrgQeneQBSQI8Cfge8CXgWW2eg4CTx6uiJEnS4jDONVbnMFyk/h3gwrauo4HXA3+e5FJgG+DDHeopSZI08cb65fWqeiPwxmnFlwF7jbNeSZKkxchfXpckSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqZKxfXpfGsezQ0+Z1e5cfvu+8bk+S9B+PPVaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUid8KlObA+v6Nx/W9fZI0W/ZYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUid+K1CSplnfv/W4vrdPWkj2WEmSJHVij5Ukab1ij5wWkj1WkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InfCpQkaZHwG4+Tzx4rSZKkTgxWkiRJnXgqUJIkTYT14VSnPVaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE7GClZJtkxyYpLvJ7kkyWOSbJ3kjCQ/bPdb9aqsJEnSJBu3x+o9wOlV9VDgYcAlwKHAmVW1G3BmG5ckSVrvzTpYJdkCeALwYYCq+nlV3QLsB6xos60A9h+3kpIkSYvBOD1WuwCrgI8mOS/Jh5JsCmxXVde1ea4Htptp4SSHJFmZZOWqVavGqIYkSdJkGCdYLQEeAby/qh4O/JRpp/2qqoCaaeGqOrqqllfV8qVLl45RDUmSpMkwTrC6Gri6qs5p4ycyBK0bkmwP0O5vHK+KkiRJi8Osg1VVXQ9cleQhrehJwPeAU4CDWtlBwMlj1VCSJGmRWDLm8q8EPpFkI+Ay4EUMYe34JAcDVwAHjLkNSZKkRWGsYFVV5wPLZ5j0pHHWK0mStBj5y+uSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqROxg5WSTZMcl6SU9v4LknOSXJpkk8l2Wj8akqSJE2+Hj1WrwYuGRk/Anh3Ve0K3Awc3GEbkiRJE2+sYJVkJ2Bf4ENtPMATgRPbLCuA/cfZhiRJ0mIxbo/VkcDrgHva+DbALVV1Vxu/GthxzG1IkiQtCrMOVkmeBtxYVefOcvlDkqxMsnLVqlWzrYYkSdLEGKfH6rHAM5JcDnyS4RTge4Atkyxp8+wEXDPTwlV1dFUtr6rlS5cuHaMakiRJk2HWwaqq/rKqdqqqZcBzgC9W1XOBLwHParMdBJw8di0lSZIWgbn4HavXA3+e5FKGa64+PAfbkCRJmjhL1j7L2lXVWcBZbfgyYK8e65UkSVpM/OV1SZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTmYdrJLsnORLSb6X5OIkr27lWyc5I8kP2/1W/aorSZI0ucbpsboL+Iuq2h14NPDyJLsDhwJnVtVuwJltXJIkab0362BVVddV1Xfa8E+AS4Adgf2AFW22FcD+41ZSkiRpMehyjVWSZcDDgXOA7arqujbpemC71SxzSJKVSVauWrWqRzUkSZIW1NjBKslmwEnAn1XVv45Oq6oCaqblquroqlpeVcuXLl06bjUkSZIW3FjBKsn9GELVJ6rq0634hiTbt+nbAzeOV0VJkqTFYZxvBQb4MHBJVb1rZNIpwEFt+CDg5NlXT5IkafFYMsayjwWeD1yY5PxW9lfA4cDxSQ4GrgAOGK+KkiRJi8Osg1VVfRXIaiY/abbrlSRJWqz85XVJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVInBitJkqRODFaSJEmdGKwkSZI6MVhJkiR1YrCSJEnqxGAlSZLUicFKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdWKwkiRJ6sRgJUmS1InBSpIkqRODlSRJUicGK0mSpE4MVpIkSZ0YrCRJkjoxWEmSJHVisJIkSerEYCVJktSJwUqSJKkTg5UkSVIncxKskuyT5J+TXJrk0LnYhiRJ0qTpHqySbAj8PfBUYHfgwCS7996OJEnSpJmLHqu9gEur6rKq+jnwSWC/OdiOJEnSRJmLYLUjcNXI+NWtTJIkab2Wquq7wuRZwD5V9ZI2/nzgd6vqFdPmOwQ4pI0+BPjnrhVZs22BH8/j9uab7Vu81ue2ge1b7Gzf4rU+tw3mv30PqqqlM01YMgcbuwbYeWR8p1Z2L1V1NHD0HGx/rZKsrKrlC7Ht+WD7Fq/1uW1g+xY727d4rc9tg8lq31ycCvw2sFuSXZJsBDwHOGUOtiNJkjRRuvdYVdVdSV4BfA7YEPhIVV3cezuSJEmTZi5OBVJVnwU+Oxfr7mRBTkHOI9u3eK3PbQPbt9jZvsVrfW4bTFD7ul+8LkmS9B+Vf2kjSZLUyaIMVkkqybEj40uSrEpy6n1cz7IkfzwyvjzJUW34GZP0dzxJ9m/tfuhC12WuJNkmyfntdn2Sa9rwbUnet9D1uy+S3LbQdehhDfvkliTfW+j6zZX1Zf/dV0nuHtnf50/Sa+C6SPLXSS5OckGr/+/OYh3HtJ8Nml6+Q5IT+9S0j47vhXvf12Xm0mJ//s3JNVbz4KfAbyfZpKp+BvxXZvhJhzVJsgRYBvwx8A8AVbUSWNmGT2Gyvs14IPDVdv/GBa7LnKiqfwH2BEhyGHBbVb1zQSu1SCRZUlV39V7v6vZJkmXAxLwQL5QkYbik4p6FrksnP6uqPRe6ErOR5DHA04BHVNUdSbYFNuq1/qq6FviVwLXAer0Xrtfm+3m6KHusms8C+7bhA4HjpiYk2SvJN5Kcl+TrSR7Syl+Y5JQkXwTOBA4HHt8+2bxmNLW3ef+uDR+T5Ki2rstm+jQzl5JsBjwOOJjh5yumPmGcleTEJN9P8ol28JDk8iRvSvKdJBdO9XIl2TTJR5J8qz02i+Kvhqbtl8OSrEjylSRXJPmjJH/T2nl6kvstdH2nJNksyZkj+2G/Vr5pktOSfDfJRUme3covH2nLt5Ls2sqXJjkpybfb7bGt/LAkH0/yNeDjC9DEDZN8sPUQfD7JJq1eeyb5Zus1+EySrVr5WUnenWRlkkuSPCrJp5P8MMlbp1aa5B+TnNvWe0gr27A9Dy9qj89r5qOBSf5ne8wvSPKmVrYsw5/Mfwy4CNg5yTtG6vbsdVj+kpkeu0mUZJ8kJ4yMjz4f39/258VT7VtA2wM/rqo7AKrqx1V1bZIntde7C9vr3/1h9c+35gnTX+/bfruoDW/Y9vnUvv2T+W7siB7vhYws86g2/2/OVwPWRZKnJzmn1e0LSbZr5Yclee3IfBe1fTXT83R+jteqWnQ34DZgD+BEYGPgfGBv4NQ2fXNgSRt+MnBSG34hw1/sbN3Gf7HM9PE279+14WOAExiC6O4M/4U4n+19LvDhNvx14JGtrrcy/ADrBsA3gMe1eS4HXtmG/wfwoTb8NuB5bXhL4AfApgu9P1fT5sOA186wXw5j6Lm7H/Aw4HbgqW3aZ4D9F7ruI8foEmDzNr4tcCkQ4JnAB0fm3WJkv/11G37BSJv/YWTfPhC4ZOSxOBfYZAH2yTLgLmDPNn78yLF1AfB7bfjNwJFt+CzgiDb8auBahjfD+7fn5TZt2tTzcxOGF8Rt2jF/xkhdtpyH/fcUhm8apT3HTgWe0Np+D/DoNu8zgTMYfl5mO+DK1q41LT/jY7fQN+BuhtfTqduz23F8Je21Anj/yL6e2lcbtv27xwLWfbNW5x8A7wN+j+H94SrgwW2ejwF/1oZX93w7hhle79t+u6gNHwK8oQ3fn+FMxy4L0Oau74XAf2F4TXngAh+Ht81QthW//MLdS4C/bcOH0V6X2vhFbV/d63k6n8frou0CrKoLMpyOOJBf/WmHLYAVSXYDiuFNeMoZVXXTLDb5jzV0I35vKinPowOB97ThT7bxU4FvVdXVAEnOZziQvtrm+3S7Pxf4ozb8FOAZI+l+Y9ob9VxWfg78U1XdmeRChifI6a38QobHYFIEeFuSJzA8wXdkeOO9EPjbJEcwvAB+ZWSZ40bu392GnwzsnqFDEmDzDL2YAKfUcApgIfyoqs5vw+cCy5JswRB6zm7lKxjepKZMnV6/ELi4qq4DSHIZwz82/AvwqiR/2ObbGdiN4S+vfiPJe4HTgM/PUZtGPaXdzmvjm7W6XAlcUVXfbOWPA46rqruBG5KcDTyKIUStbvlfeezmtinrbMZTgUlOB56e4RqjfYHXtUkHtF7FJQxhcneGYD3vquq2JI8EHg/8PvAp4O0Mj/UP2mwrgJcDR7bxmZ5vsPbX+6cAe+SXZy+2YNi3P+rVnnXV8b3wtxg+CDylhtOek2Yn4FNJtmc4xbsuj/Xo8xTm6XhdtMGqOQV4J0Pa3mak/C3Al6rqD9sBd9bItJ/Oclt3jAxntXN1lmRr4InA7yQphiBRDG8uo3W6m3vvzztmKA/wzKqaz/9lnAtTXf33JLmz2kcQhvAyScf0c4GlwCNbELwc2LiqfpDkEcAfAG9NcmZVvbktM/r7J1PDGzB86vq30ZW3oDXb47mH6cffupzOmlrmnmnL3wMsSbI3Q5B8TFXdnuQshsfs5iQPA/4b8DLgAODF41V/rQK8var+770Kh9eUdXnc17T8bB67hfRJ4BXATcDKqvpJkl2A1wKPavvnGIYPawumhduzgLPaB6+Xr22R1Qyv7fU+DGcFPjebes6BHu+F1zHsv4cz9CZPmvcC76qqU9rrxGGt/C7ufVnT6DH4izbO5/G6mK+xAvgI8KaqunBa+Rb88gK+F65h+Z8AvzYH9erpWcDHq+pBVbWsqnZmSOqPn8W6Pge8MvnFtVgP71hP/aotgBtbqPp94EEwfLsIuL2qjgXeATxiZJlnj9x/ow1/Hnjl1AxJJvbi4qq6Fbg5ydTx+Xzg7DUsMt0WwM0tVD0UeDRAhguRN6iqk4A3cO/HbK58DnjxVO9gkh2T/PoM830FeHa77mYpQ0/Vt+7D8ovB2QyP+UsZQhYMp5l+CtzaenWeukB1AyDJQ1rPzJQ9gf/P0JM6df3U9ONxpufbuvgc8Kdp13QmeXCSTWdX8y7GfS8EuIWhN/LtLbhMmtG2HDRSfjnt9aB9YN1lNcvP2/E6SZ/u77N2GuyoGSb9DUP35xsYenZW5wLg7iTfZTivft606ZPw66kHAkdMKzsJ+FOGF4374i0MXeAXJNmAIaA9bewa6l4yfMvmDuATwP9rn5xXAt9vs/wO8I4k9wB3MuzLKVsluaAtf2ArexXw9618CfBlhl6bSXUQ8IEkDwAuA150H5Y9HXhZkksYTv9NdePvCHy0HbcAf9mrstNN7b+q+nyS3wK+0T6L3AY8j6GHadRngMcA32V4zXhdVV0PXL+Oy0+STdplBVNOr6pDq+ruDBesv5D2plZV301yHsNxfRXwtXmv7b1tBrw3yZYMvRiXMlwLdRxwQtuv3wY+MLLMTM+3dfEhhtO332kfVFcB+4/dglnq8F44tZ4bkjwN+KckL66qczpXdV09IMnVI+PvYuihOiHJzcAX+WWAOgl4QZKLgXMYrrH7FfN5vPrL66uR5C8YLjxeL3/aQHOnnbL6YFXtdR+XuxxYXlU/npOKaZ3Mdv9pcfH5prmy2E8FzokkL2P4ZHbsWmaV7qUdO8cxnK7SIuP+kzQue6wkSZI6scdKkiSpE4OVJElSJwYrSZKkTgxWkiRJnRisJEmSOjFYSZIkdfLvjJkzv8mb/FwAAAAASUVORK5CYII=\n",
            "text/plain": [
              "<Figure size 720x432 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "The top host is Martijin"
      ],
      "metadata": {
        "id": "tGrH-Lv0cEn9"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "T_NepL5vBiU9",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 472
        },
        "outputId": "b6c77f70-4600-4ba0-f06a-a2a7737fa5bd"
      },
      "source": [
        "# getting the top 10 most common neighbourhoods\n",
        "plt.figure(figsize = (10, 6))\n",
        "df.neighbourhood.value_counts()[:10].plot(kind = 'bar', rot = 25)\n",
        "plt.xticks(ha = \"right\")\n",
        "plt.title(\"Top 10 Neighbourhoods\")\n",
        "plt.show()"
      ],
      "execution_count": 36,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAo8AAAHHCAYAAADec7LnAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nOzdebytc93/8deHYybjSYZTR5wSJfodolKiOFFpFAlJaaBoRrMmTRrupAGhRNMtxJ0kGm/DUSpD6sTpRuIYUhIZPr8/Pt/lLLt9jgvHXmvv/Xo+Hvux17rWtda+vnutdV3v6ztdkZlIkiRJXSw26A2QJEnS+GF4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSRpCEXFQRBzRcd33R8TXF/L43Ih41qLbuoVuy9ER8aEx+DtbRcRVD/XfkfSfDI+SxoWIuKXv5+6I+Fff/V0X0d/YKSJ+GRG3RsTZozy+cURc0B6/ICI2XshrnR0Rt0XEtL5lz4qIuV22JTM/kpmvfiDlkKSHkuFR0riQmcv3foD/A57Xt+y4RfRnbgQ+Axwy8oGIWBI4Cfg6sDJwDHBSW74g/wTes4i2behFxJRBb4Okh57hUdK4FhFLRcRnIuIv7eczEbFUe2yriLiqNQFf35pvF1hLmZk/ysxvAX8Z5eGtgCnAZzLz9sz8HBDA1gvZvM8Bu0TEugvY9jUj4rsRMS8iroiIN/U9dq+m6IjYPSL+HBE3RMR7RmmKXjIijo2If0TExRExc8Sf2zQiLomImyLiqxGxdN9rvyYi5kTEjRFxckSs2ZZPj4jsD4WtRvXV7fYrI+IXEfHpiLgBeH9bbeWIOLVty7n95Y+Ip0TE+RFxc/v9lBH/j5PbdsyJiNf0PbZMaxK/KSIuATYd8b98Z0Rc3f7mZRGxzQLfFUkPiuFR0nj3LmBzYGPgicBmwLv7Hn8EsBqwFrAH8OWIeOwD+DsbAr/Ne1/T9bdt+YJcDXwF+MDIByJiMeAU4Ddt27YB9o+I7UZZdwPgC8CuwBrAiu05/Z4PnACsBJwMfH7E47sC2wHrAo+h/Y8iYmvgo8BO7bX/3F6nqycDlwOrAx9uy3amyrwyMKe3PCJWAU6lQvWqwKHAqRGxanveCcBVwJrAS4CPtO0DeF/b9nVbOfbobUB7P/cFNs3MFdrjc+9HGSTdD4ZHSePdrsDBmXldZs6jQstuI9Z5T6st/AkVXnZ6AH9neeDmEctuBla4j+d9FHheRIwMmZsCUzPz4Mz8d2ZeTgXNnUd5jZcAp2TmzzPz38B7gRyxzs8z87TMvAv4GhWk+30+M6/MzBupMLdLW74rcFRm/iozbwcOBLaIiOn3Ua6ev2Tmf2XmnZn5r7bsxMw8LzPvBI6jgj3ADsAfM/Nrbf3jgd+3/8804KnAOzPztsy8EDgC2L09dyfgw5l5Y2ZeSQXQnruApYANImKJzJybmX/quP2S7ifDo6Txbk2qtqznz21Zz02Z+c+FPN7VLcDDRix7GPCPhT2pBdrPAwePeOhRwJoR8bfeD3AQVYM30prAlX2veStww4h1/tp3+1Zg6RF9EK/su93/P7jX/y8zb2mvPbJmc0GuHGXZyG1ZfrS/1bcta7XHbszMf4zyWO+5I8vQ2+Y5wP5Us/l1EXFCr+ld0qJneJQ03v2FCmI9j+TefRZXjojlFvJ4VxcDG0VE9C3bqC2/L58Angn8v75lVwJXZOZKfT8rZOb2ozz/GmDt3p2IWIZq9r0/pvXd7v8f3Ov/1/5Xq1JN7r3QvWzfcx8x4nVH1oAuzMj3qrctV7fHVomIFUZ5DOp/MLIM8zci8xuZ+bT2+gl87H5sl6T7wfAoabw7Hnh3REyNiNWoJt2Rcx5+ICKWjIgtgecC3x7thSJi8TaQZAqwWEQsHRFLtIfPpppH39QG6ezblv/4vjYwM/8GfAp4R9/i84B/tIEey7S//fiI2HSUl/gO1bT7lDa6+/3UYJ37Y5+IWLv1O3wX8M22/Hhgz6hpiJYCPgKc25p+51Hh7RVt+15F9Tl8oE4DHhMRL4+IKRHxMmAD4PutKfqXwEfb/30jYC/mv5ffAg6MiJUjYm3gjb0XjYjHRsTWbftvA/4F3P0gtlPSQhgeJY13HwJmU4NXfgf8qi3r+StwE1WzdRzwusz8/QJeazcqeBwObNlufwWg9TV8AdUH72/Aq4AXtOVdfJYKn7TXu4sKshsDVwDXU338Vhz5xMy8mApLJ1A1cLcA1wG3d/zbAN8AfkgNbvkT7X+UmT+iphP6bnvtdbl3v8vXAG+nmrI3pALeA5KZN1Blfmt7vXcAz83M69squwDTqffqROB9bfug+rL+mfpf/ZDq19mzFDW90vXU+/1wqu+mpIdA3HvgoCRNHBGxFfD1zFz7vtYdTyJieSrAzsjMKwa9PZImF2seJWkciIjnRcSyrU/iJ6la1rmD3SpJk5HhUZLGhx2p5ty/ADOAndOmI0kDYLO1JEmSOrPmUZIkSZ0ZHiVJktTZlPteRYvCaqutltOnTx/0ZkiSJN2nCy644PrMnDraY4bHMTJ9+nRmz5496M2QJEm6TxEx8lKi97DZWpIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnU2q8BgRS0fEeRHxm4i4OCI+0JavExHnRsSciPhmRCzZli/V7s9pj0/ve60D2/LLImK7wZRIkiRpbE2q8AjcDmydmU8ENgZmRcTmwMeAT2fmesBNwF5t/b2Am9ryT7f1iIgNgJ2BDYFZwBciYvExLYkkSdIATKrwmOWWdneJ9pPA1sB32vJjgBe02zu2+7THt4mIaMtPyMzbM/MKYA6w2RgUQZIkaaAmVXgEiIjFI+JC4DrgDOBPwN8y8862ylXAWu32WsCVAO3xm4FV+5eP8hxJkqQJa9KFx8y8KzM3BtamagvXf6j+VkTsHRGzI2L2vHnzHqo/I0mSNGYmXXjsycy/AWcBWwArRUTvUo1rA1e321cD0wDa4ysCN/QvH+U5/X/jy5k5MzNnTp066uUhJUmSxpVJFR4jYmpErNRuLwM8G7iUCpEvaavtAZzUbp/c7tMe/3FmZlu+cxuNvQ4wAzhvbEohSZI0OFPue5UJZQ3gmDYyejHgW5n5/Yi4BDghIj4E/Bo4sq1/JPC1iJgD3EiNsCYzL46IbwGXAHcC+2TmXWNcFkmSpDEXVZGmh9rMmTNz9uzZg94MSZKk+xQRF2TmzNEem2w1j+PO9ANOHdO/N/eQHcb070mSpPFlUvV5lCRJ0oNjeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeTKjxGxLSIOCsiLomIiyNiv7b8/RFxdURc2H6273vOgRExJyIui4jt+pbPasvmRMQBgyiPJEnSWJsy6A0YY3cCb83MX0XECsAFEXFGe+zTmfnJ/pUjYgNgZ2BDYE3gRxHxmPbwYcCzgauA8yPi5My8ZExKIUmSNCCTKjxm5jXANe32PyLiUmCthTxlR+CEzLwduCIi5gCbtcfmZOblABFxQlvX8ChJkia0SdVs3S8ipgObAOe2RftGxG8j4qiIWLktWwu4su9pV7VlC1ouSZI0oU3K8BgRywPfBfbPzL8DhwPrAhtTNZOfWkR/Z++ImB0Rs+fNm7coXlKSJGmgJl14jIglqOB4XGb+N0BmXpuZd2Xm3cBXmN80fTUwre/pa7dlC1p+L5n55cycmZkzp06duugLI0mSNMYmVXiMiACOBC7NzEP7lq/Rt9oLgYva7ZOBnSNiqYhYB5gBnAecD8yIiHUiYklqUM3JY1EGSZKkQZpUA2aApwK7Ab+LiAvbsoOAXSJiYyCBucBrATLz4oj4FjUQ5k5gn8y8CyAi9gVOBxYHjsrMi8eyIJIkSYMwqcJjZv4ciFEeOm0hz/kw8OFRlp+2sOdJkiRNRJOq2VqSJEkPjuFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktTZlEFvgCa36QecOqZ/b+4hO4zp35MkaaKx5lGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLU2aQKjxExLSLOiohLIuLiiNivLV8lIs6IiD+23yu35RERn4uIORHx24h4Ut9r7dHW/2NE7DGoMkmSJI2lSRUegTuBt2bmBsDmwD4RsQFwAHBmZs4Azmz3AZ4DzGg/ewOHQ4VN4H3Ak4HNgPf1AqckSdJENqnCY2Zek5m/arf/AVwKrAXsCBzTVjsGeEG7vSNwbJZzgJUiYg1gO+CMzLwxM28CzgBmjWFRJEmSBmJShcd+ETEd2AQ4F1g9M69pD/0VWL3dXgu4su9pV7VlC1ouSZI0oU3K8BgRywPfBfbPzL/3P5aZCeQi+jt7R8TsiJg9b968RfGSkiRJAzXpwmNELEEFx+My87/b4mtbczTt93Vt+dXAtL6nr92WLWj5vWTmlzNzZmbOnDp16qItiCRJ0gBMqvAYEQEcCVyamYf2PXQy0BsxvQdwUt/y3duo682Bm1vz9unAthGxchsos21bJkmSNKFNGfQGjLGnArsBv4uIC9uyg4BDgG9FxF7An4Gd2mOnAdsDc4BbgT0BMvPGiPggcH5b7+DMvHFsiiBJkjQ4kyo8ZubPgVjAw9uMsn4C+yzgtY4Cjlp0WydJkjT8JlWztSRJkh4cw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKmzSTXPozTWph9w6pj+vbmH7DCmf0+SNPlY8yhJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSepsUoXHiDgqIq6LiIv6lr0/Iq6OiAvbz/Z9jx0YEXMi4rKI2K5v+ay2bE5EHDDW5ZAkSRqUSRUegaOBWaMs/3Rmbtx+TgOIiA2AnYEN23O+EBGLR8TiwGHAc4ANgF3aupIkSRPelEFvwFjKzJ9GxPSOq+8InJCZtwNXRMQcYLP22JzMvBwgIk5o616yiDdXkiRp6Ey2mscF2TciftuatVduy9YCruxb56q2bEHLJUmSJjzDIxwOrAtsDFwDfGpRvXBE7B0RsyNi9rx58xbVy0qSJA3MpA+PmXltZt6VmXcDX2F+0/TVwLS+Vdduyxa0fLTX/nJmzszMmVOnTl30Gy9JkjTGJn14jIg1+u6+EOiNxD4Z2DkiloqIdYAZwHnA+cCMiFgnIpakBtWcPJbbLEmSNCiTasBMRBwPbAWsFhFXAe8DtoqIjYEE5gKvBcjMiyPiW9RAmDuBfTLzrvY6+wKnA4sDR2XmxWNcFEmSpIGYVOExM3cZZfGRC1n/w8CHR1l+GnDaItw0aVyafsCpY/r35h6yw5j+PUnSf5r0zdaSJEnqzvAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM4Mj5IkSerM8ChJkqTODI+SJEnqzPAoSZKkzgyPkiRJ6szwKEmSpM6mDHoDJGlYTT/g1DH7W3MP2WHM/pYkPRjWPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTOvbS1Jk9BYXrcbvHa3NJFY8yhJkqTODI+SJEnqzGZrSdKEY7O89NCx5lGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ0ZHiVJktSZ4VGSJEmdGR4lSZLUmeFRkiRJnRkeJUmS1JnhUZIkSZ1NqvAYEUdFxHURcVHfslUi4oyI+GP7vXJbHhHxuYiYExG/jYgn9T1nj7b+HyNij0GURZIkaRAmVXgEjgZmjVh2AHBmZs4Azmz3AZ4DzGg/ewOHQ4VN4H3Ak4HNgPf1AqckSdJEN6nCY2b+FLhxxOIdgWPa7WOAF/QtPzbLOcBKEbEGsB1wRmbemJk3AWfwn4FUkiRpQppU4XEBVs/Ma9rtvwKrt9trAVf2rXdVW7ag5ZIkSROe4bFPZiaQi+r1ImLviJgdEbPnzZu3qF5WkiRpYKYMegOGwLURsUZmXtOapa9ry68GpvWtt3ZbdjWw1YjlZ4/2wpn5ZeDLADNnzlxkoVSSNLlNP+DUMf17cw/ZYUz/noabNY9wMtAbMb0HcFLf8t3bqOvNgZtb8/bpwLYRsXIbKLNtWyZJkjThTaqax4g4nqo1XC0irqJGTR8CfCsi9gL+DOzUVj8N2B6YA9wK7AmQmTdGxAeB89t6B2fmyEE4kiRJE9KkCo+ZucsCHtpmlHUT2GcBr3MUcNQi3DRJkqRxwWZrSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnhkdJkiR1ZniUJElSZ4ZHSZIkdWZ4lCRJUmeGR0mSJHVmeJQkSVJnk+ryhJIkafhNP+DUMf17cw/ZYUz/3nhnzaMkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8NhExNyJ+FxEXRsTstmyViDgjIv7Yfq/clkdEfC4i5kTEbyPiSYPdekmSpLFheLy3Z2bmxpk5s90/ADgzM2cAZ7b7AM8BZrSfvYHDx3xLJUmSBmDKoDdgyO0IbNVuHwOcDbyzLT82MxM4JyJWiog1MvOagWylJEkaN6YfcOqY/a25h+ywyF/Tmsf5EvhhRFwQEXu3Zav3BcK/Aqu322sBV/Y996q2TJIkaUKz5nG+p2Xm1RHxcOCMiPh9/4OZmRGR9+cFWwjdG+CRj3zkottSSZKkAbHmscnMq9vv64ATgc2AayNiDYD2+7q2+tXAtL6nr92WjXzNL2fmzMycOXXq1Idy8yVJksaE4RGIiOUiYoXebWBb4CLgZGCPttoewEnt9snA7m3U9ebAzfZ3lCRJk4HN1mV14MSIgPqffCMzfxAR5wPfioi9gD8DO7X1TwO2B+YAtwJ7jv0mS5IkjT3DI5CZlwNPHGX5DcA2oyxPYJ8x2DRJkqShYrO1JEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8SpIkqTPDoyRJkjozPEqSJKkzw6MkSZI6MzxKkiSpM8OjJEmSOjM8PggRMSsiLouIORFxwKC3R5Ik6aFmeHyAImJx4DDgOcAGwC4RscFgt0qSJOmhZXh84DYD5mTm5Zn5b+AEYMcBb5MkSdJDyvD4wK0FXNl3/6q2TJIkacKKzBz0NoxLEfESYFZmvrrd3w14cmbu27fO3sDe7e5jgcvGcBNXA64fw7831izf+DaRyzeRywaWb7yzfOPXWJftUZk5dbQHpozhRkw0VwPT+u6v3ZbdIzO/DHx5LDeqJyJmZ+bMQfztsWD5xreJXL6JXDawfOOd5Ru/hqlsNls/cOcDMyJinYhYEtgZOHnA2yRJkvSQsubxAcrMOyNiX+B0YHHgqMy8eMCbJUmS9JAyPD4ImXkacNqgt2MBBtJcPoYs3/g2kcs3kcsGlm+8s3zj19CUzQEzkiRJ6sw+j5IkSerM8DgBREQMehskScMjIjy+j1MRsdygt+G++OEapyJi7YjYESAnYN+DiFgqIh7fRrJPWBN1Bx8RUyNiqUFvhx6YiFghIt4QETu0+xPuBHWifvd6MvNugIhYc9Dbsii1z+YjBr0dD5WI2BP47qC3475M6C/PRNS3w7sOeEdEvDoiPhYRjx/kdi0qfQeplYFnAi+KiFkRsdkAN2uRiojFW5mW7e3g2/KJdIDeHdgeICK2bL8nTPkmavDoK1cAqwBPh4l1ghoR60bE+hPtuzeyDBHx2Ig4DvhERCw9oM1aZPrKtyHwybbsWYPbokUrIqYAZOZXgfUi4nED3qSFmpA7wIkoIhaH+WeTwOrAqsCHgbMy86JBbduiEhHRd5C6E3g28Fng9dTlH8e1iFgsIhbLzLuArYAPR8R+EfEeGN8H6F7Z+hbNAb4eEb8GXjDivR2XImLTiPgu1PcwIqZFxHMnQu14r5a4b/9yG3AzMLV34jbeA1bf5/ORwJvaCdynYNx/93rHhuxb9lLg08DVmblrZt42qO1bFCJi8V75MvMcqlLhMmCXiHj4YLfugevfZ7bp/9aKiF2AvwP7tnWG8ntneBwnWuAgIl4fEV+lpll6H3AN8OP22OKD28IHrvflyMyMiGUj4p3AfwG3UGX7dGb+ZbzW9kRZLDPv7js4/xl4E7AJcPzgtm7R6JWt1eo8HXgY8H/AsZn51glycD4fmBkRT2sPvQl4bGb+e1h38F1ExOeAx/fd3wv4A/XZnAk8C8ZvwBrlxPty4MW0cNXWGbfvX9+xYd+I2Cci1qb2m7cBvabrcbfvHBGs7uodGyLie8APgVsyc6/MvG5wW/nA9B3zeu/PchExDTibupTxCcDeEfGoYf3ejbsP1GTQmjUXG7HsYRFxFrAFcExmXpGZ3wTOAQ6B+TuR8aaFxiUiYgZwGFUrt1tmvpz6Mu0YEcv1NzONJ1nujogZEfGVdnA+D/gBMDsz54y34D9yeyPikRFxLPA/wPTM/BrwDuDFrVZy3NbO9R2cVwW+CbwhIpahgtV32jpDuYNfkHZC03sPDwR+H9XPeBngBcBzMvNVwJHAOhHx/3rPG8wWP3B9799uEfEB4FHAV4CfZ+ahbZ1x8f6NeN96y9aNiB8Dj6PC8LlUcPwxcEdETGv7n3H13o3oVvAUYDawPLBvZr6A+lw+oT0+Lvaf/RUl7f6jI+Joqhl+Y+DUzHx/Zn4c+Bbwtv7nDRPD4xCJiGdD7ezal321iHhcO/CuRV0S8TPAb1qT2VLAl5jft2zViFhtUNv/QEXES4DPZ+YfqdrGuzLzzvbwHGAZqp8LEbHSYLayu9F2ZBGxGxU8LqF2EBcAH6SCyMPGS/Dv2/n1Dsi9sm4O3JGZj8nMY9s6pwDLAs/NzH+PfI1h1A7O0W4v1n4/LyI+CBwOfJEq60FU+L+q77lDfQDr/7+3E5q7IuJhVNA4E9g+M/8FrACs21b9PvBPxknfxwWEq0dGxPep2sZfZOZPgYOBdSNiu4hYovfcsd/ibnqfxb73bYW+hx9NHRc+BjwZWBJYmwqRywOb9Z47phv9ILT3cemI+HBUs/RcKvT/KjN737mjqfdx6CtOYvSuBbtS79uVmfl6YBrQP8r6E8ArImKVYXzvDI9DotW6fT7atbIj4hPAz4A3AIcCN1Cd2I8E3gv8qP2eC5wZERcCJwLrDGDz79PIHXNE9F/c/XLgsRHxSOr64JdHxJPbY78Ffg98NCJOB7YdWSs7DNoZ5Mpwr2C1SUSs11ZZgroa0RHAEhGxduu7cyXwkrb++u33UJVvZOhoy3aPiBOAt7dy3069h1+JiA9FxKER8Rjgo8C+EXFAO8Me2oNYVNeC7OtbdXd7L04CVsnMnTLzcuAo4J1Us+7nIuI5bf2hPIC1E9BPAuuPWP5q4F1U0+YJwLOimjxPYX7g+BMVTrbtfT6HWV+4WjoiprfFvcEiLwd+0Q7G/6bKuWNm3tFO4Ibuc9kXGnvNm8tG9dP8XUS8Jao2fAPqpOYoqp/qGpl5WetmcSOwZURMHUwJ7tsox4Y1gCmtn+YzqFaov1Anby/qW/X9wNYR8ZqIOK4dQ4dS3zHhJRHxzBYmf0N17/l7W+00YItotfzA36iT79eO9fZ24RVmBiRqZNWHgO9n5s8j4rHAftQO4DbgBZn5oajRZD8EngpcCCyWmf+M6le2M1WtvQQwMzPPHERZFibi3gMloppQroyIOcD7M/PrUXNavRe4Ay9GEfgAACAASURBVPgAFTguz8wvtOcsAewD/CHrkpBDJyJ+AFyWmftF9Yn7OHATNSr+61S4+iTV1zGAqVSt8R+obgfTgP8F9hqWg1hEPA94FVVbelFmHt+Wv4IaTf0xYH/gd8BxVG3HMtQO73HAtMx8ZUS8jgpaR2fm/455Qe6HiFgWOICqbftBZv4mIg6lvl9Pb+tMpbqL7ESV69nUe/qezLxsMFv+nyJiC2qfMoPazsdTtVKrZuaZbd/yMuCr1Ht8IhUm76D6HB9D2xdRNZP/3VfrMxQiYr3MnNNuL0btCz8MbEs14R4H/JLa1z6WavpcF7gMeAtwLLAi8Bjg6cNWvp6oQUubA/8AlgJ+AbyC2q98mjoJXa0FLtp37kfMf79/Nojtvj+iRoRvDLwG+Fpmnh3VGvcBYDtqn3kidWy8oj3nJcDWwJmZORTT27Qw3BsY2Vs2gwr4d1GtaRtk5lYR8V5qcOiXMvOGiHgX9X1digqWP6e+d0OzX7lHZvozhj/AUu33NOqgexK1U1uW6j/1DCoQHkf1Wfkh8Ly+568BvJTqW/Y1YMkRr7/4oMu4kLLvTtWcrgjsAvy4t83ApsBPgJWog/KRwCaD3uaFlGUT4FPUjhnqjPikdvtAYKt2+1zgG8BqwEpt2XJULci72v3HA08YdJn6yrYEdUA6p71nLwEuBV5N7dQ+B7y1rftYauDWXn3PXxn4PNU3CWpHOvByjSjjYrST575lO1Dh4r1UaJ7dvpcrArcCq/et+23gv9rt5YGHDbpMfdv2cKom8VzglVTN1DGtHAcB3+1b92PAAe32+4BPtNtbtM/3icBGgy7TiPItDXwEuIiaD++H1IkKwFOAE9rt51IH7Ne0fcwq7Wdd4HTq4DwNeD6w7KDL1bZ58RH316WaNn8AfAG4nqotpe0zT2vft0+3/cxH2n70jGHap9xXmYG3UjNrLEGdZO/D/Mqts4C92+3PUyehA9/uBZRlsb7bU/puzwIO77t/LtWNYnPqRG3btnwpqvXwAOAxgy7Pwn6GqnlsImt9OF5G62BP7QQuAn5FHZyXoWqptqDOKp8CHJSZ22bmKRGxcVTfxy2oD93nM3O37OtLBoNtOmtlHNkEsW1EvKHdPYc6y9omqxZrakQ8q23zHdTB7bXUjvJM4E8jXmuYPq+PoGp1Xt9qq/4CXNea26cC74mIc6mBMftn5vVU5/X1qAP4e6hwQmZelJm/G0QhFmBVYDp10nJsZn4HeDv1mdyRqi2NiFgi64x4eWDViFilnTmfC/yLqnElh3CgU9bo8IzqO/yotvh86iTgO9SgrfWoUHwzNSL+4L6XOIj6/gL8KzP/PvKzP0C3Aodm5pMz82jqgLx+K8f3gIyIrdu6PwOeHDWn3JHA9hHx/7JqiN+RmS/MzN8OoAwLsx/V/217at95CfDeqEEVa1HfP6gAdQqwERX8bwSeRoWxS4F/ZOaVmXlyZt46xmW4x4huIb3mzd4E+1tSJzJ7ZOYbqAGEa7THLgN+DbwxM99MBUiAD2Xms4dpnxIRL46Ig9t71DtWvATuKfMvgSdQ/W3PoQJUr/n2dOCA1gJ1BLWfHTmgdGDHhoh4ekS8EO7p6rJKRHwc+EnrrrMq1Wf/pr6nfRJ4S1bXpX9RXQuWyczbswbDHpKZfxjzwtwPw3QwntCyTitOBzaOiJdmdUz/A1WzcQnVf+OLwAvbjvtPwDMiYqOI6NVEPgX4XmbunJmnwnAEqohYPyIOAma0A/LKMX9gy2rMHy39B6rKfrMWhA8H9o+I7YHdqJ39LZn598z8Rmb+vf/vDDKEtL5Gv402uo8K/4dSB6u9qH6bKwD/pmoW51IDRd6YmddFxIZUDcGe7fFnZObpY1yMrp5C1cTMa8EY6rN7JdU0fTcVnp/ZHrsNuLsdnE8GnpiZb8/Mv43xdi/QKAebGRFxFHWicnREbJM15UevO8FxwN7Ay6MGlXwQeE3Mnw/xj5n5pXb7rvZ7KLobZOYtmXle36KX06bzok5yzqG6vEC1YGwC7JzVZPsOan800BPR0bTAsRw1yv0rmfl/7X/+Xur7txPVT+ySqEnAb4d7Jjv/V0TsRNVwHZuZ+w/6/WrlWax/OyJiz4i4APhsVN+/b1MVDM9pqxwL7BARa7X944+BrSLiEZl5fmYelJlnjHVZFiSqj98vqdrfO4BjImK1VuYvRcR2bdWLqc/dq6nPZFBzOa5N1TTfQR1fLszMd4w8Foz1sSHmD6Zbnvr+vKiFW6ga/BWpVpsZVDess4BtWpCEqiC6qZ04/JSqLR5Xc3EOPHhMVBGxVURs2nd/SjuYHgC8sPU3Opbq3Hwi1bT0VGqwyBrU2fXd1IirxwEvysyzc37H6Xt1pB6EvgPy4lSo2DoiPk3Vtn09qu/fWVSQ2rWteybV3LIlFR6/RdVq/YNqxj2s7/WHoian7eBvpcLt6yNiE+BaagfxYepAHFQT7pLM3/m9ICKeGBGnUDVVN1H94vbP4Z6b7Dxgw6iBBbdGTdB7B3Wy83gqWP2Jqu05neqP9AOAzPxdOzEaKn3fm6dGDXD5PHBTZm5INX2+tH0n1wBuaMH+POrAsEtmzgWempm3938uh+UzOpqYP+o4qM8rbR/0deCpEfEOKij/khYuM/PUYXn/ekG99z9ugWNV6oD8895jLURd0J62MjCPCvtQn9ebM/Mm4MTMfEZmfnvsSrFgWe6OGtyzX9RAiUdRJ9J3AZ/LzH9S79es9pyTqf3tju1l/hfYKTP/OvYlWLiomT9eB/woM2dl5gepeYl7gyU/SjVPQ9WWn0TtS+6mplKaTn0u5wFPysxL+l57INklatqxg4FvtBB8C1UbfBtVaz+F+ox+KWuw2euoPtHXUJ/Rj0S1xB0HnNM+A9/PzB8N+mTm/jI8LmLtwwP1JXhDOzOB2hlA9Uv5GVUDtTlwfkSsQvVV2YZqVnlEZl6cmZ+gQuNemXnZiOaNQYbGe01wmpkXU2eOT6X6dM6g+iG9jtrR/5Dqf0Rm/orqk/UCqinp2Mx8ZtbcVv9uZ+P3mgtriHyIqrnZr/1eg9pRfIUq3zVUDc73qB3+TCqknJp1lYd/DvJ961nYjrc9dj3V2f51bfEy7fefqDB1S2YeDrwR+HhmbpZDdIWjXo3OiGWbRMQ3qKs23EXt7HujcI+jjfinao4jIr5A9e38AvW/oLUI3OtzOYSf0Xv01RxuRwtbzWpUE+cjgAsy8+WZ+ZOx3r4FiZow+fXAm+FeI/wjM/+vrbZb+93b315KnWT/hOo7d0tEnE3VovfmcrxjTAqwAC149KaBiohYMWoKry8Az6P6vq3fQtK7gU2iZiz4UXvKC9tLHUeVLzLz1qwuMUOlbdv11An33yNig6guLWtTrW8rUZ/Bx0bEk7OmZlsMWJNqhv89NdPI4zLzsKxBovdMwTSo/Wj7u4+harkPjIgdMvM3VK3pNq0c04Cl2v/gDqqm/xXU4MKTqemUvpCZHxpEGRYVw+MilvPnJ/w2tXPeoC3Pvt/foKagOYT6skTWSOkjqLPKe3Yw7UvTu6zdUByo+nbm20XE89vi71ODXXrbeDhV2zGd2vktGzWdwmnU2fKR/WfLUROjRzsTG1g5RwtWrXZgsVZ7cSTV1eAgqtbmxdTApdupsq4XNe3Hj4E3Z+aWmfnFMSvAArSD1b2utBERL4yIJ/avl9UX8DaqnPtHNf/d0h5+KXBEzm+m/XUO2Qj/mD/dTv8EwxtTTUkrZ+YumflDqrZxsajmv5uofpvT22Ofo/rmvi8z39JqEMaliHgEta/5Q9T0Sj+j9js/amU7fLBbOF/fSeM/qelLpkc1W/ZOyntB8VCqtQLqfYI64VkFWDGrb+fe1Kjc52cbjT1oOb+f7VJtH/cU6nt2VmY+i9pn/j1qBPlN1En3Plm13r+larDIzOPaSfdQHA9goSekJ1KVCqdQl4XcEXgi9X1chjrmvTUi9gf2oAZ2/bo99+asaZd6x4Yx70bRX/vdF14/RHXh+QV13fAtqcGvS0bE46n+0W9m/lypfwPOzcx/Z9Xs75FDUvv9YDhVzyIWdYmhT1BfjMdSTV97tJ3GE6gzkCMz8w/tzPjpVN+409qBb+A1U/3aDj1agFq8fZmfQc0Dtys1B+MNmblPRLyRuub2kZl5RTvTfHxm7hI159qO1HQ2PxhMaUbXyjhyaoUXUtMF/WaU9R9F9QH8JhX0P5KZt0Vd9/g24LV9gWvgRn6uorpFHEjVcv+RmpLmq+2xPaga4Y9HxLupmsY7qc7rs6mRuXPHuAgLFdUl5M6++8tRffc2pKa5+EZEvIWq6d8vM69pgfJt1Lx4b6YmHD4/Mz89yusP3feyq6gpwC6lpvm6nBohPjS1jKNpLTF7UTWJZ2Vdraj32DKZ+a+IOI/qK/YNaqDhJ4FrM3O/QWxzF1GD6V5PfZ+OyMxzIuKH1HRtn2vBYw9gbmYeFhHrUKFkXeD2HKI+xD1dvhtR/eFXBt6d1e1jI2rw2cFUi9X21HHxa1mtNgPX9iG7Uycjh/Qtj3Ys/zHVqnQH1WL4COrzuAYVjA+mPr/rUAObXj+M79+DkkMw5Hsi/FBzbEGd8X6z3d6aGpG5EXWW+UNqYMzS7fFnUlNqPGXEa00Zq+2+jzLFKMumUqPDPtXur0XVsj6fmkz4WKopE6oG5y0LeO2hmL5l5HZQX/7PUZ3Uvwns2ffY7sA72+1XUTu+83qvASwx6PIspFxLUv1tf04NzNq/Ld+p3X8iNe/d/wJbtMcWp3b6L2MIp42gagu3BNZr96e0bf4WNZp9daq/7e5U+P0ssEPf/+P11Mjw06l5OVcYxs/og/wf9aaUGqrpdhayvS9s79nHqea+I6muIStQc+Ce1N7X9ajQfxJ1AnsgI6YtG9D2TwV2bbcX71u+JtV/71Vtu79JdSeYBfxvW2eJ9ln9OrB2W7b5oMvUsdx7UrWGW1A1/PfsD6nuO8cAW7b7U6juBest4LUG9r2j75hHVY58se+9mNL7jFHdDGa3/c3D2nt7NnXc2KCtsxHwyEG/Nw/Vj83Wi0DUFDy9EW5rUTs9spouz6N2iBdnTbvz/mwTuWbmWVkjp3/Z/3rZV4sy1vr7i2VmRsQyEXFgRHwnIrbNzHnUQXjN9pTrqSaJ3bOuvnEJdTWKM6id/tdGvP4wDfQhq0Z1yagpFX5OnTVenplPopo2nxw16OUtVNj4aXvqCVQz0++oHQg54D5V/fI/rwv7deqzuQcVFB/dHv4V9R5uk5mHZuYWOX8i77sz86bM/GYO0bQRfc1Ht1OTCr8xIo6jdvabUVPunEU1L/2D6ot6MVXOjSJipawprn5FHcS+mjWC8x/9f2eQn9FFJatrwVtziKbbaU3Q9zRTR418710d5MXUic07qBPtf1InCI+kLl26Z2Zem5lzsmqJX5eZ62fmR3PEtGUDsibwyajBFHf17WtmAX/PzKOAw6ia7tdmtcJMaX3n7qD2n+cAd7darnMGUIYFivl9+nv3l4yIw6l+fN+jaoz3hfn7w8ycDfyVOi58lho4ch5wTe8z0F7rXt1qBiF7CbJqv9ekTjKf2R67M6tf/rJZl169jbr6zd+pGQ1+RvV3fHhb/7c5v4/uhGN47CAito+IvSJig75lO0RdTg8qPC0VdfmuecDK7cMHNfJ2f9rcXNHXabrvtYbimrj9/cUi4mFRl537DHXGdTiwV0S8iaqu3yxqNO7t1FnXihExi+oQ/H7gxVmDROb1/41hOCAvimCVNfr6sKzBTEMTGvtFxEdb8+z1VPPJ5Vn99w4Gntbe7zlUk+YmrYnzngNEb0c6LPr6xPX6XN5BdcDfm5pr8Riqr9yB1OUDz87MJ2TmGe2E7TyqKWnD9pK9QLl11NUt9BBpAXFTuNfJcW8/+C7gVS1ozaNGSEOFqBuog/efMvNNmXljO8HtfRauGbNCdJDVzeX71GAyaCeWVC3VqhGxfAu51wK3R02F9V3m9+G8IDM/n5l/GZbvX0SsGxEfjIhVM/POiFghaiQ1VKhfkuomsgU1k8af+p7byxinUt1koGr/3541gLB/8NlQTA3Vuiz9iqpF3oCaCmnVVu6jgOOjptz5L+YP6vprZr4HWDMzzx7Qpo8pw+NCRM2xeC61c5sOfC8ieteZfC3wkqiJkm+lmsoOomraNgRe28Ll44D/o01cm63TdP/fGeSXJubPV9Xr17h61LySX6H6iC1LhavdqR3Fn7Lmg/s1NRoOqs/RCdRI60sy83tZkyYvFgOaUuG+PNhgBcMRrkY5EVm1bxuXoiaa/wPVtWBa+7z+DzU1Rm/E6u+pINULjQOr+V6YvlqBF0bEyVGd7L/I/KvhkDXyfw5wcmYe19Z/c8y/XNtHM/MXbd1bqJOdD/ZaA7RoRV3c4BTq//zeiPhyROwYNV3Jy9pqRzD/EornA2u2mru/Uc3Vm1P94vpPcAc9R+PC9mtHUdN0Ld13YvlXqu/p29r9lagm0luz+tTtAcOxT+np24+sSI3Q3zkiPkh9146OiIfTrp1NvW9/obq8fKNVPEAbQJmZPwVmZeZ+mXnVoI8ND7L2+1WZeUNmfhO4OmqcQ+8YOpQVCQ+FoTywD5GXUJdCemo7q9iTmgn+NVTz5tZUR1mo6RaeRk0A/R6qpvEU6ux6qxyya4vGiObjzMyoDtsXUWXai2rS25w6Mz6t1byd2mpKPwG8ue0g/52ZR2bmSX2vHy0oD3xKob77Ey5Y9QWqmRGxJ/NrUaHmUXtS1ACfM6gD8TbtsaOokx2yrnBzSAteQyHmX2Gjf9niEbEXNYXQF6nLfV0B/IZqjn5GW/XtwKyIOCFqYMU21GjHuzLz0vZavZqr32fmlWNQpMnq9cAvM/Nx1AnopVTLxdLAkwAy8+dUjfGmVB/UpYEvRA2424hq9Ti3rTvQlotey9HCtqO1TvyBNodh1EDD66iTnOdHxAnU/+BHrRJ1scz881hsfxd9343evu4iKhw+i+qPuCE10OxNVP/Tb1P9/D+TNS/s84Htogay9dcs3h7zZw4Z82PDIqz9viHahOCZuX1v/zFMwX8sGB4XblPgKrgnDP2C1leFqpG6lfkHY6iBJJ/Mmqfr7cCmmfmBzLxpGGrgWngaOV3Ls6MuGzUta66+c4DlWq3MVOC/gVPaWRYtOO+SmedSV8O5re/1++ehHPgXaaIFq4hYPmret/5lO7Sa4oOpfn53UjWnU7K6DHwfeHtm/poaiPA8gKy+V7uP5fZ3EXV1ondQB6peH9ydI2L1VkO/FVWmPwDrR1255/tUuddvNR7XUtd0Po6qJXhuK/89huHzOdFFTXq9MTVgB+BvWf0Uf0cNxCKqqwvUNZrfSI1e3Z/q7vNwapTq0Zl59Vhu+4Lk/Ol21o2Ir0bEa1oL08juR0fQruKT1ffxWVTN6k7Al4GZmXlEq0QdeFeefn37zS0j4vtUgP8lVVt6e1vt41ST7krUiPedI+JjEXEWNUflX0c70R5QaHwoar8nTQ3jggw80AyriFiTCoNz4V4Hm9lt2abUCLJZEfER6qzyaKpvB8AdWZ1re3NUDfqM+dHUZbyWbfeXjohjqM7NN1FfqlnUjn4zgHY2fASwU0QcFhGzqZ3fRe3xn/b/jUEekCdDsKLmsdsvIh4TEa+NiGWAj1Ghd9esKXS+TU1Y3rsM1q+oJrSVqQ7dF0dNwrxYOwEYCtG6BVBNRM+gBgy8jKpVnEXVcu9O1XjvTI0cfz31fVyHOjBsRTVZb5WZ/8jMUzLzohZAh6Jf8SRzHTXpeu9Spb334HjqIgG/owYTQnXtWY1672/JzK+2Js6BzrE58nMTEY+K6vf9LuokZQbV6jSy+9GZwLUtYP4PNWp8StZAnx/nAK+lPdJo341Wxk9QrWe/od6f71L9+ZfL6tt5JfCsdmK9FdWn+JNZFw04e4w2v4sJVfs9NHIIhnwP6w81emy/EcseTtVUrdPuP4kKWLsOens7lmnd9nt94GPt9oHUF+qV7f5s6so2veesDmxL1aQOvAwLKNcjqVGMj6FqhpehQu7/MH/qiN2pA9fqffevompBnk714VyOIZmihWpSGTnlzmzgauD0dn836kx5Sru/GBWKX0fNM3pAe3yHQZdnIeX8EnWAemK7/19UH+JXUtPxPIYalHXiyP9JW/e17fb03nvd/z8cdPkm60/bbxwGvKzd731Gl6cmvd6Gatk4l5rGbBf6prcZph/mT9fyZGq+zHe1+8u0sjyj3e+fnucV1DyqQ3dsAJYZZdlzqT76S1E1wY8a8fhT2vu5Y7v/DOpY+OhRXmso3kdqiq5zmT/FTm9u69OoS1h+guqLCdVN7eJ2LHkY1U3ts7Rjpj8j/reD3oBh/Ol98Klq6jOpJobeYytS88KtuYDnDvxgNXIbqPnDtqLOkn/TvhzrUTUDF1NXbHhk3/qvAi5a0GsPw45hZIhoyyZMsOp/D6kTlse0nfq7qemClut7/FLgmX33t6YmTb4KeCuw7KDLM6JsS7bP47R2f+/2Wfxsu78RNZ3Hte279nNg3xHv/a5Us/S51ET0/a+/+DB8Dyf7T3uf3kadHPR/Xnek+qtCXcv5OYPe1oWU4eXtGPBtqo/fFGoe2HdTAwShRhqf1G73n9gM5WewlaP/+/TK9n37NvCEtuwXwPPb7WXa71Xa+3kE8+e2XWPkez7o8o3YnmlUi8vD2/3esWA3quZ7d+o61FAtbte2x4aiAmGYfwa+AWNW0FHCxojHeoFxZPB6OzVw5ABqkMxlVJPFyPWGIVA9ldHPAjempoCAqnnbkwojR1KXv+p//jPb7bcxYrLyYdkxMEGD1cjPJxXy30ZNfXF23878eCpwrdjuvxM4ccRzl2SIJi0fsW1rUf1PP9jur0s1C32N6hYxi6oRuAA4bsRzZ7Xv61eAVw+6LP7c53u9JtWd5wRqFoqXUSdsbxj0tnXY9jWomrbpVHPmpVTt1NOo7kmPauutSF2CbpNBb/NCyrIe1by+EnVyNaW3n2zvz6wR6+8NfLvv/kZUH/gtqG4jSzI/QA7FcWEB5Z4wtd/D9jMpLk8YfZdQivmX2PuPyyq1QS0rZ42muueSZxExk2rWXB/4RGb+cazLcF+iLv+3CVVTcxcVjL6adSm2Z1E7h7dFxEupA/Q7qfIcTvUJnEXt3N+cmaePfQkWbuT71Tqp70T1Z7kSODQzT46I46n+jd/MzJsj4p3UVRpe2PfcJakumkPR6XkBn8VpVI3bCZn5zqhRxjOpeTfXoWpPX541unEp6ox5y8z83Rhv/gMSdanOr1G1IH+m+pv+lard2ITqK3cpdfL2BqoG4XXUDv59/e9d7zs9pgVQZxGxEjUf3hOoVpDPD8M+Ju7jggURsSvwIuok5qVUF5hDsqYh+zb1WTw6M++IiBdR39d5OUQH1f7vRkT8BPhMZp4YEV+nJtDfn6oU2YHq37gatT89GvgONVBmLap71j6ZecZ//JEh1gZxvpVqdXtL1nXTiYgdqWPi69ugyQ2yZtpQR5MiPAK96/m+BZiRmS8Y8dgU6sB0ADUP3GH38VqLUeFjkANE1qD69l0BHJ81OGc54DlUU/QbqH4br6MOvN/OzCe2554CfCMzj4+aJPsZ1EjIw0f8jRj0jnCiBquoCeWfQs1HeH1b9lxqJ3dSZl4e7VrZmblr28G9Crg5Mw+NiG9Sc1TuQA0++OcwntQsTNQ8jbOoudR2p05i7qCaOZ9JDaZYjPpMr0eFjrP6nj9urzk9GUXECjniKj7DoA2O3BL4YdbMGL3rF29I1fh/EfhA1gTZS1KfyR2p+QD3GsYyjRQRq1ODIW/PzL2iri99PLUPSurysnOp/c+zqabp31B9PB8FfLH/WDAMx4au2vv7EWoQzAepaXjeRlWufGGQ2zaeTbjR1gsYObYO1dn+Zqp/ysg5AFekDlpPX1hwbKM2e3NUDeSLExErRsRXqBrGpajmhY+3h2dQNTjrU2f611KjwG8G/hDz58H7H2D3qMu0/TLr0l6Ht9e/5/83wDKuHxGvalMl9GqMnxs12fOjs+bVmk1dXQRq8ufrqL6LP6Cmk/hERMylOoBvOizBMSKe0ML7V6nm2o0jYp2IOBJ4DdUk+8mI2IKaTugJUXNp/pm6dNm6EfE46uTg19RUJheOt+AIkJmfoboPbEaF/80z8waqRnJF4B1ZozYPyMwX94LjfdUYaTgNOmSNMnJ6uYg4DPgBVSt6z2VZ2ypXUscNWnB8KtXP9jlZU5e9fNBlGmmUMi4VEZ+nrgF+BbBbROyYdbnKK6j9x98z8+tZI47nUd+9y7Imwj4tMw9vYXrgx4YHIjP/QtWwXkaFx1cA7zY4PjgTIjxG34TCfVX0MyPiiW3xRtSB98h6KJ7Q//z2JflSq+35j8sH9q2XQ3DAejTVj+jTmXkgNTfakyPiYZl5IRUoNqNGEB9EzUV5DLVTuKm9xpeAA7PmsALudUAe5NVuJkOw2gs4J2vC9Xdl5o+ocl2XmTtSXQ42pfrq/IoqV+9SZxdS11Ndp31mj5gATS3/v707j5dzPP84/vlGEEuilqSCIraqFlGxq9qD2tdWVWhp/WpNUUtjDWptlaK1li62qq3WirWWWkOVkpbS2GLfg8T398d1P8mTcdKccJIzc871fr28nJl55skMmfNcc9/XcjrxJWgeSm9HR7P5rYgvRhOoCWbfptZVuzbMWO6ak2hdNtj2sPLFpX78W8CxRAP664i2WDfbnhBQTrcXPwWaOFK08T3OROROb+cYdHESE9sjHUf0Z+wlaXlFj8Y9ibGrz9XOPclY0FZk+w3bhwFDbG/SDGkTra7lg8ey1bdjFUAqmrdeQ1QQb1ZW6a4hcqnOIi5I1wMHNwaJZSm+01YV22kUUTG8NIDtB4mVxar59b1Eu5k1yi+3Q4gO+btVJ3BM2hhZP2mTXJC7dGAlaTki4fzn5Xb1TX4AMZHhceIXXrTYKgAAFctJREFU/cq2ryC2k84h8gKx/QRwqO1rp/drn1bK398/EMHjPJJ6l/uvtP18fXuslS9eafqS1L/6fFW/5yUNlnQzcLykNYm/c+OAyyUdpZhI9J3aOXrYfqr87tnL9upuSO3pTIqJKWvCxEBW0naSHgWGK5q0z00sIFTB5InEYsPXHVPPehKjEf8BfN/24MbfL01+PZwqzbZS3MpaMngs28fVmLkHbJ9FBEwQQdVpttcgPjTbEyt12zgmTexLfFi+1PihaIUPiWPyyyNAT0Wj6POI1cityuN3EdstX5U0vyNBeCjRFuWRznrdU9JNAquXiUKQ6u9q9fftdaI45EDb+9p+TtJ6xFbuCOCQsv2k8v+zyygX6OeIgrQd6r/cWymvKjUHSatIuoTo43eSpMXLluuqRJHgscQXzaOIitvjgCOIbd37iCECi8GkX6ibbPeisgOwsaTPl522c4gcxr2IlmU/cwwO6E2kNFFWV8dSRicSucbX2x5bvce2Ur9SatRywWO52Lj6puWoJt4LOKB8w9wa2E/SnURi7PK2n3VUxA2UdDDRBuR+NcHIwE/pUeAF4hfgv4j3vJ2kUxSV4TcTAUofANtjSkDSzO+3OwRWHxGB/9rldpUq8CDx//EgSXsrCmV+RrTi+dgxnu2DrhhIeeJs9ZGOvLIetce63PtN004JGi8lGsxvRHy+qtSHeYFXbd9o+3wiZ3w1YozedUSaS29gdtv/mu4vfirUdsxuIlYOlyJyvlcEnnNMsDkVmFWR534aMETSEZKOI7ob3KToKPKgG+Zq5wp/ao9mDiYmKCuNE5LkS6LzoZLOlzQH0QdvFmLV8XwisFjL9k62/ylpLUm9iG9l8wPbOoa4N8NW7RQ1Bn223yRaKFxOVOY+QlTdPkd0xB8J7Gv78YbnNfP77Q6B1RgiSX1tSbPWtppmJt7jcOICdoPtpcu2fbfS5H9HU3O7D3jK9h9tv0AEVlVuW0+iaHCh2rGbA+9K2p5Ig+lLmWnfzGq/6+4hUpLWsP0s8V5nKdc6iNz2YWU35miiJ+57RKHPmW6inM3Uepq+VY8m7dHYmwj+fkG0Efit7b9Lqjrfv0Z0/7+HqNh8mOgWvyDRD3BU9cFTE7TbKa9jsj3q2tq208Q+lf2I1i39be/d3uc3q/JtuurHNdRl9msJrLYl/t8uR+Q/ntlpL/QzUrSNOJpYYT2GWDXYnVj5GOom6T2ZUiuS9ArRZmZ5or3TnURF/+nEcIfHbZ8saSXiczeE6NrwVvlS3hKq3+2SBhNtds4D3ieufz+0/YSiaGY0kbJ1e8Pzm+L6l1pXUwaPtQ9G9e8FiSatKwJnEpW26xFbEeOJoe1rEd8kTyT6OW0EDCa+jZ1qe2x1buJ9d+oKh2pNyMvtXtVrbOPYtYHVbR/ZcP9mxGrrL22/Ufvv1ZJNk7tLYKVomrwX0VJpDiI3aUTnvqqUWp+kA4m+oUs5umfMS/z+WInod7sfcX1YgvidclVnvda2KNqTvTIVx89O5HK+a/vYkvf4FHCi7Q8kLVl233qUXbsMGlOHaKrgsa2gpwQUo4nE5p86uvv/mage+zewLLEatYWkE4l8jtMag0M1QUNhRXPrVR09wqr7NiECpgeAW0s+TvXYDMSEjcHExJRflfurIHEm2x9O1zcxjXWnwErS7I4CqJRSByhbti8RY1pfLfddB1xh+9eS+gJfdPQ0bBplUWNxIj9xf9sjG3bd2pyIVgLCTYH1iYWVPsRUnIMntxiRUkdoquCxImmj8uNdZUXtZuC/toeUx2fzxDFDsxOtd9Yh+lcNIoLHp8vjMwCd2n5H0gpETs1AosP/o5IWIaqgP0/k8PUiWglt5VpVtKQFbI+ewvk7PTDuaBlYpZQ+DUlnAuMdo+d2BnYCdrX9ZOe+srbVUpFE5D3b9iGTSVvaDnjJ9q214LHK1bzV0SM1pWmu0wpmShFMYzf81SWNILYq1wV+WR4aRkxOqYyTNK+k/YnK4ptsf0BsXy8NPF8d6Ohp2FmTUmaQ1IdoQTOn7QeIhObdiHY68wEz277HMUnjT8S3xnrT7tHVuSb353S1wBEmtCRKKaWpdQjwA0kPEaMtj2zWwBHiGlXyE/cAZgBWljRflboFIGnBsuO2E/BOeV7VqeBlok3ZhMCxscgypY7WKX/BNLHdTtUNv3odHxAf9G8QQ9s3UYxSuouolPu/ctw4IiBbHtjN9uHl/kHAbUQeZKdQTKjZQ9IdRN7eYrZPIfrYQWxNfI2YbnApMFox5xjgMiKB+xMBYSvmMKaU0vRm+yViKMKutrdtprSXcn3o0XDfbMDVxPXrFWLreYfqYQBHNfU+tje0fX/jed3Q/LorLiik5jLdtq0l9bM9pnZ7dmLO9ArEQPqqOfRXicq464j2Owvb/mbJDbzUdq9y3IQl/fqyfydvTy9GzM/8FXABUSXcB7iYyOM7mwhuDynHXVyOfcr2MEnrA9sBu2e+SkopdU0l/72n7adL5feJtr9WHtuYCH6H2H61MS2pVQsiU9cyTVcey7es3SQ9ApyiaNBdFUVcTjSC/iawi6LRN0Q7ln/YPoJot7OlpI1tXw0MkzRjQ+DYo/ogdXYFmaO57EtEccvfgAuJwp4Zife7laMdxANE9Z+JavDBki4k5o5ekYFjSim1Pkk7Sdq4tv08n6JX7SXAHpJ2pfQplrRwedooYsVx07bOmYFjagbTLHgsq3DjiGBwV2IE1NaSvmj7DeBbxEzbU4jh7d+VNCfwBjCfpG2J3MfriEao2D7R9kf1ILFZluc1cVziUUQBDMB/gP5EsPhXoI+k1YBbiJ5cmxBzqkcB1zkaQ189PV93SimljlXbmr6bWCCopsKsBVxiexWicfn3iFSmm4AflmNeIXbdhkiauVmucSnVTbPgsazCvQicUVbh5iSadlfFLO8SLWr+antxIlF4O2Im6fVE8vC9tjezfXd13uobXGdpq9AHJg6mt3068AVJ5xJ5LA8RDa5fAG4FdrT9Yrl/DeAt4J/AspL6T5c3kVJKqUOVtnLAJMUsTxDztLcvD60JfFvSjcAAYI9yfTsH2FbSSUSweR2wdykETanpTJPgsbYKdwxwkaRjiC3o/sBVkpYlgkkDd5RjxwC7AONs/8L2GrZ/U843IVhrgq3peqHPgPpjtfd9LDFven3bB9oeV6qH7wIWljQPcC/x/nsCVxHjsl6eTm8jpZRSB5H0FWJ3qbq9laQvl5tPARsoJqE9RDQrH2p7U9v3S1rG9ihgdeBRojDmBNsPT+e3kVK7faaCmbIKOCHncDLHPEe00ql6NB5HjI36NnAYsa09J7F9e63tB6qcxmZIDJY0l+3XardnIopfvk/8sngSOKEU7NS7+I8BlrH9fNl6+EAxam9W269LGgpsBmyQOY4ppdRaVJvWUq6FlxBbzvMQc6TfIHbSziZWE48ldtz2pVzviJGJCxOrjP9pOH/LjJdN3U+HVVtLGuDSmLvc7ml7nKTDgBVL+x0kzQ2MBL5I5P3tDIy0/WCHvJAOUFY69yQC3H8BjwFX2n5E0qpE4cu+ktYl2utsbfsv1XNLIPkrYEnba7b1S6Dxv1dKKaXWMJluH+sDvyfax11Wbu9GjEtchZiGNhRYlcj5H0TkOv6spDJ94twpNaupCh4/4yrckkQfx5OBN4Efe9LZzs0yc/oHxIf9j8C5QG8iF3Md20tK2p4YBdWbmK39G9tn1Z5fve85iFYLp0zv95BSSqljNQZ1khYHfkTktJ9LDKm4H/i97ePLNWBXotvGqcRAi4NsjyjXuxldxstmwJhazRRzHhVTUvaRdB9wmqRDJC1THh4E9Le9BFE5fRCwNkTCcPlG9jHRz3AMcA1RRHNkY+BYcgmboarsQ2K01Z62H7J9u+3dASR9i1gtXYZYiVzN9lmS+in6VtYTpd/MwDGllFqbJk77qgeOqwG/AEYQW9WnEAskwylTwkpbtj7AeyXn/TLi+lHlzn9Yrq8ZOKaW8z+Dx7IKNxpYlFhdPINYbbukHLIwMHfpW3UEsF+1fVtUH4gDgf2AdW3/xDGvekLVdDN9cGyfB3xcthyQ1Ks8dDyRq3IDkQDdV1JvSTsQuSsrtXW+zq4OTyml9OlVCwKSVpO0Rbl7AaJ7xjPAFkRQ+CaxQPI5SSdIWq889kI5z3GOaWn1c3fa+NyUPov/uW2tGCo/3PYCDff/kwgWxxLTUk62fUF5rB8Tv2m1dc4JScYd8xY6nqQfAdvYXqVetCPpGSJI7EfkQy5PbMWf4JhNnVJKqUVNJj99e2Kk7BeI/P1+knYDDiDaz51k+47q+cA+wDDgTOBW2zfUzjXJtJiUWtUUcx4lPQvsYvtGSb1sj5X0XaKh6RrEGL67iQ/KZsQH5wC3MU+0lZbnJb0CbGj7vnJ7LWJb/tuOQfSfGLmYUkqp9Uwu517SosDviOEP75Sf9yRWE38AnGn7nlIIujdwPjFlbF5Hr+MJ52+Va19K7dGePo8nE6uMAB8B2D4X6EvkcxxJrMRdTlSQ7ddW4Fie10ofnjOJ7XYkLUQMqr+hFjjK9hiFTzQNTyml1BqqnHtJs0jaRdKC5aE1gb/Zvsb2bcD+wOGOwRd3E2N3zya2sPsDr9p+pwoc28qXTKkraFe1dXdchSu5ju8SOSz9iZYKw22/16kvLKWU0mfSuH2saOC9PrA5sCDROeQPRDHMZbYHlNXJvkTO+8a2b5U0EFgKuLnebielrq69E2a63Sqco3H34cQkmFVtH5SBY0optb5aEUw1FWxHIlg83vaqxOSz7R39h8dI2rOsHi5FTAPbt5xnpO0/2H5RUg9NnGmdUpfW3pXHbr8KV4Lij3P7IaWUWksbK42rED0YXwDOsD1a0mvA5rZvl7Q0sDtwBdFebk9ghXL8+cSs6h1d+h5nTmPqbtrdJFzSIUTrneNsfzRNX1UTaYXq8JRSSu0jaW0id/HnREC4PDHpbH9gWdublL692wAbEkHiWEmL2x4l6VBgJtvDOuktpNTp2r3Ebnu47aNsf1Q1Np2WL6xZ2M7VxpRSaiGN1ydJfSUdXdKuFgeuBsYT08NeKj8fA6wiaaHSau4fwN+APoppagtJegJYiJhXnVK31XPKh0xUW4UbP41eT0oppTTV6lvH1b8l9bH9FrAI0afxbWA2Iof/z0Re46OaOJ96BHASsDVwv+17a+d/Ali9yvVPqTubqtnWKaWUUjNpq0djqZ7eC5jb9p6SZiEaeq9ODHrYCDitBI6LAUOItnQflec8XTtXNvZOqUFWhqWUUmo5kr4Ek/RonFfSEWWE4BvEON3VJe1g+33gRmBVouDzMeA8Sb8H/kjswr0DvG376YbxuRk4ptQgVx5TSim1FEmbAKfYHlBuDwM2BS4EVgT+bXuYpMHAxkQw2QO4sTT7RtJSwDLAlSW4TCm1U648ppRSamqSeksaVH7uYftq4AVJ25ZDbiYqo0cAiwJbSBpU5kqfCgwiBlsMqM5p+zHbF9l+vzsVgabUETJ4TCml1Oy+D+wsaUBtG/lqohcjtu8iWuucDOxDVElvK6mX7SeB44iejU9/4szx/PHZVSOl9svgMaWUUlOqrQbeDrwHLCZpiTJPeitgOUnrlWMGAheVQPJJopH3lwFs32p7y2rLOqX02WTwmFJKqWnURgZOaLlj+z7gZeCnRIHLSNuDgP2APcrho4ANJA0nKqrPpmGlsauMz02ps2XBTEoppU5V8hnnLjmKlNY6M9l+s9aDcQViTODFtq8px/UCRhKrjA8DBxMjdE+ot9tJKXWsXHlMKaXUKSRtUH7cBFinTIKZEfgtsBpEPmI55mFidXGgpHnKY2OJYpl9St7icNs/rNrtlMEWKaUOlh+slFJK042k2STNKqkvMH+5+0ZgVmLO9ArErti1tefI9ofAPcA85ZjKUGCX+rGlItvZozGlaSODx5RSStNcmQ8NMRpwxTLm7xJJO9u+k5gxvTSwOXBOec7MMDH3kQgeARas5S9+aPvDapUxg8aUpr3MeUwppTRNSdoQGG57UAn6FgGeIfounkvkMgo4lFhVvAU42PYztXPItiX1t/3CdH8TKaUJMnhMKaXU4RpnTkt6DVjX9oOSbgFutj1c0oHA/GUG9VHAXMCzwAbAaOAO279u6/zZmzGlzpHb1imllDpUPeew1nrnTOCY8vOxwDfKz9cCi0paAvgLMB64DVgbOA+4s60/IwPHlDpPBo8ppZQ6VAkae0vaE9i63H0YsIqkRUpLnjdLvuMjwEPAECJQfB+Y3fbHtkfYfrRT3kRKabIyeEwppfSpSZpf0koN9w0m5kzPBawr6WjbHwAXAEeVw84Fdio//xlYjti+/rHtv9TOlTOnU2oyGTymlFKaarUeigKOkTRQ0lBJnwO+ABwJnESMCFxK0pzAcGIKzFy2Lwb6StrA9t3A34kAsn7u3J5OqQll8JhSSqndqhY5tXY4MwCLA9cRIwRnABYFTiVWFE+3vYXt122PIdrtnFyeu6Xt6yWtCGxKzKSunzul1ISy2jqllNJUk7Q5sAQRNG4DbFTmTSNpGNAPONz2a6XH4zdtXyBpIeAr1YjBcvzCwKy2H5vObyOl9Clk8JhSSqlNJd+wR21EIGUyzMXAWGKM4GWlSfe1wNW2z5D0VWAHYkXyNmA74N/AbsCbuRWdUmvL4DGllNIUSZrN9rslMNwaOMX2i5Jmtf2epK2B/WyvLKkX0BtYi2j6faHtBzvx5aeUOlAGjymllIDYPrb9n9rtmYB9gF2Bu4Hbyz8HE8UttwBfB84ALgSuAMYR+fR72H6idq5JmoanlFpXzykfklJKqasqlc1Dge8Bz0i6F7jG9r3AmkSz7pWBhYHzgQeJ+dS9iAKZbYFlgfeAPYBVgCttv1r/M0rQmKsVKXUBGTymlFL3dgARHFYTX3YEfidpIDGD+pESCL4q6SpgK9s/kTQ7sCQwGBhb8iIfL//UA8asnk6pi8lWPSml1E1J6gesA+xv+2ngGdtHAE8TeY29AEuaqzzlcmKlESLIPBEYYXunhvPm9nRKXVgGjyml1H29DszBxGvBDOXfvwa+Q1RVLw7sLGlmYHng0nLMRbbXsn0WZGPvlLqTDB5TSqn76kUUwqxebo8DsP0noofjjMDxwAJEccyWwEXlmNegzabhKaUuLnMeU0qpm7L9tqRRwEBJfW2/DCBpEaIwZrzteyTdD8xre3Qb5xjfeF9KqWvLlceUUureLiUWEk6SNFdpAv4T4L+2nyvHjLc9WmGGyZ4ppdQtZJ/HlFLq5kpBzGnEgsJXgBuAw2y/3akvLKXUlDJ4TCmlBICkBYHnbY8rt5XFLymlRhk8ppRSmkTZmv44A8eUUlsyeEwppZRSSu2WBTMppZRSSqndMnhMKaWUUkrtlsFjSimllFJqtwweU0oppZRSu2XwmFJKKaWU2i2Dx5RSSiml1G4ZPKaUUkoppXb7f4Z6lQPOtzizAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 720x432 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "The top neighbourhood is De Baarsjes"
      ],
      "metadata": {
        "id": "V_qsFQnqcKCO"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "336tKm-eBiVB",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "37452676-5585-4432-8cc1-0447c03e18c6"
      },
      "source": [
        "df.room_type.value_counts()"
      ],
      "execution_count": 37,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Entire home/apt    13308\n",
              "Private room        3497\n",
              "Hotel room           232\n",
              "Shared room           38\n",
              "Name: room_type, dtype: int64"
            ]
          },
          "metadata": {},
          "execution_count": 37
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Most rented room type is the entire home or apartment"
      ],
      "metadata": {
        "id": "uKNNUC7kcQYL"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "KLmzCtedBiVE",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 357
        },
        "outputId": "0016863c-702e-453b-b4d6-7b75ad0094ef"
      },
      "source": [
        "# getting the most common room types\n",
        "plt.figure(figsize = (6, 6))\n",
        "labels = ['Entire home/apt', 'Private room', 'Hotel room', 'Shared room']\n",
        "df.room_type.value_counts().plot(kind = 'pie', autopct = '%0.1f%%', labels = labels)\n",
        "plt.show()"
      ],
      "execution_count": 38,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZwAAAFUCAYAAAAQ+orgAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3deXxcdb3/8ddnZtJ0b+lKC8i07NACsilcNjfAO+AGiIiCclVwAdTr1bnXLa53FP2h6FUQF1BEQFBAR2QRwbJD2cq+ThdauneaNmmWOd/fH+ekTUvTpMmc+c7yfj4eeSSZnJnzTqB553vO93yPOecQERGJW8J3ABERaQwqHBERqQgVjoiIVIQKR0REKkKFIyIiFaHCERGRilDhiIhIRahwRESkIlQ4IiJSESocERGpCBWOiIhUhApHREQqQoUjIiIVocIREZGKUOGIiEhFqHBERKQiVDgiIlIRKhwREakIFY6IiFSECkdERCpChSMiIhWhwhERkYpQ4YiISEWocEREpCJUOCIiUhEqHBERqQgVjoiIVIQKR0REKkKFIyIiFaHCERGRilDhiIhIRahwRESkIlQ4IiJSESocERGpCBWOiIhUhApHREQqQoUjIiIVocIREZGKSPkOIBKndDafBKYDu0RvU4CRwIjora+Pk0DHFm9tQCuwNnprBZYDC4EFwNJCLuMq9K2J1BxzTv8+pHals/kEsAewH/AGNhVLz9uOhOVRCR3AIsLy6XmbH71/tpDLLKxQDpGqpMKRmpHO5puBWcAbe73tD4zymWs7rAAeBeYCjwCPFHKZl/xGEqkcFY5UpXQ2b8Bs4BjgYMJy2Qdo8pkrBmuAxwgLaC5wZyGXWew3kkg8VDhSNdLZ/EzgHcBbgWMJz7c0oieBW6K3OYVcZoPnPCJlocIRb9LZ/HDCYnln9LaH10DVqR24i6iACrnMM57ziAyaCkcqKiqZdwEfBI4jnBEmA7cQuBm4hvDwW+A5j8iAqXAkdtFMsrcCZwDvA8b6TVQ3lgDXAlcXcpn7fYcR6Y8KR2KTzuYPJiyZDwDTPMepdy8CVwBXaPq1VCsVjpRVOpufDHwc+DCwt+c4jSgA/gn8BriukMt0eM4jspEKR8oinc3vC3wO+BAw3HMcCS0Ffgr8rJDLrPIdRkSFI0OSzuaPIyya4wHzHEe2rg24HLiokMu86DmLNDAVjmy36Ir/MwiLZpbnODJwAXAT8INCLnOP7zDSeFQ4MmDpbH4McAHwGWCq5zgyNA8APwSu19RqqRQVjvQrnc0PAz4JfAWY5DmOlNcTwJcKuczffQeR+qfCkT5F65l9EPgWMMNzHInXP4AvFnKZR3wHkfqlwpGtiiYD5AgXzZTG4IA/AF8u5DIFz1mkDqlwZDPpbP4g4HvA231nEW86gJ8B39Z0aiknFY4AkM7mpwI/IJx9punNAuGtE75LOJ2623cYqX0qnAYXnaf5OOGoZrznOFKdHgfO1vkdGSoVTgNLZ/P7AZcC/+Y7i1S9EuE06q/r/jwyWCqcBpTO5puA/wG+TP3dQVPi9TzwsUIuM8d3EKk9KpwGk87mDyRc5uQAz1GkdjngEsLrd1p9h5HaocJpEOlsPgV8DfhvIOU5jtSHBcC5hVzmZt9BpDaocBpAOpvfmfAOkUf4ziJ16VLgszq3I/1R4dS5dDb/TuB3wETfWaSuPQG8v5DLPOc7iFQvFU6dSmfzScIlabLouhqpjHXAJwu5zJW+g0h1UuHUoXQ2P41wiZJjfGeRhvQL4LxCLtPpO4hUFxVOnUln828FrkK3DxC/HgROLuQyi3wHkeqhwqkT0YoBXwFagITfNCIALAc+UMhl7vAdRKqDCqcORPeruRw43XMUkS2VgM8UcplLfAcR//SXcI1LZ/PjgL+jspHqlAR+ns7mv+U7iPinEU4Ni66v+Rsw23cWkQH4NXCOVp5uXCqcGpXO5mcBNwM7+84ish3+Rni9znrfQaTyVDg1KJ3NHwvcAIzzHEVkMB4CMoVcZrnvIFJZ/Z7DMbOSmT3W6y3bz/bHmtkRvT4/18zOHGxAM7vczE4Z7PMHuc8mMxvUvT/M7CNmNr3cmXqks/nTgFtQ2UjtOhS4N53Nz/QdRCprIJMG2p1zB/Z6y/Wz/bH0WrPLOXeJc+63W25kZtW8gOSRwD2DfO5HgFgKJ53Nf5rwgs5hcby+SAXtDtwX3dJcGsSgZ6mZWcHMvmFmj5jZPDPb28zSwLnA56LR0FFm1mJmX4iec6eZ/cjMHgYuMLODzewuM5trZreY2bQ+dne0md1rZi/3jHYsdKGZPRnt/7To8WOj17wx2j5nZmeY2YPRdrtF2002s+vN7KHorfdNyE4gPD+Cmd0Q5XvKzD7R6/tfZ2YXRY//I3q9U4BDgN9H3/+Iwf58t5TO5s8BfoqWqZH6MQW4PZ3N61YZDWIghTNii0Nqp/X62grn3EHAz4EvOOcKhPfJuCgaDW3tJk3DnHOHABcDPwFOcc4dTDiD5Tt9ZJhGOOo4EegZYb0POJDwvi5vBy7sVVgHEBbfPsCHgT2dc4cBvwTOi7b5cZTzUODk6Gs93gLcGX18dpTvEOB8M+tZBHMU8LBzbj/gLuDrzrnrgIeBM6Lvv72P72e7pLP5jxD+jEXqzQ7Abelsfh/fQSR+Azms1e6cO7CPr/0pej+XsAAG4pro/V7ALOA2M4Nwvv6SPp5zg3MuAJ42s54lW44E/uCcKwFLzewuwmPDa4GHnHNLAMzsJeDW6DnzCMsEwpLaN9o3wFgzG014bmSVc64tevx8M3tv9PEuwB7ASiDo9b1c2etnUVbpbP504FdoZCP1azLwj3Q2f3Qhl3nRdxiJz1DPo3RE70vb8Vo90yENeMo5d/h27KfneduzfdDr84BNORPAm51zm93DIxrB3RJ9fCxhMR3unGszszuB4X3ss+zT/dLZ/PuA36ILdKX+TSMsnaMKucwC32EkHnH8ImsFxgxgu+eAyWZ2OGycGbbfduxnDnCamSXNbDJwNOGCgQN1K5sOr2FmPaO4jedvCEc7q6Oy2Rt4c6/nJ4Ce2XMfBO6OPh7o979N6Wz+ROBqdHdOaRxvAO5IZ/OxzfIUvwZzDqe/WWp/Ad7bM2mgr42cc52Ev7C/Z2aPA4+xfXek/DPhTZ8eB+4Avuice207nn8+cIiZPWFmTwPnmlkS2N0592y0zd+BlJk9Q3ju6P5ez18PHGZmTwJvBb4ZPX45cMlQJg2ks/l3ANcBTYN5vkgN241wIsFk30Gk/HThZy9mdiTwIefcuQPYdp1zbnS5M6Sz+SMJR19lm+EmUoMeB95SyGVW+w4i5aPCGaQ4Ciedze9BOIqaUM7XFalRdwHvKOQyXb6DSHnoZPQgxVA2E4A8KhuRHscQXjohdUKFUwWi+9n8mXDKtYhsck60wobUARVOdbiEcJadiLzej6Jbp0uN0zkcz9LZ/PmEqx6ISN9WAYcVcpmXfAeRwVPheBT91XYLutZGZCCeBt5cyGVafQeRwdEhNU/S2fwM4FpUNiIDtS9wVTqb1++tGqX/cB5EkwSuByb2t62IbOZE+l7kV6qcCseP7wBv9B1CpEZ9KZ3NH+87hGw/ncOpsHQ2/zbgNrT6s8hQLAUOKOQyS30HkYHTCKeCoos7r0BlIzJUU4HfpLN5/VuqISqcyroU2Ml3CJE68U7gAt8hZOB0SK1C0tn8Rwnvaioi5dMBHFTIZZ72HUT6p8KpgHQ2vxvh7RfKvrq0iDCX8Pqcbt9BZNt0SC1m6Ww+RXgLapWNSDwOBr7sO4T0T4UTvyyb3ylURMrvK+ls/mDfIWTbdEgtRtFqAk+hm6mJVMJcwvXWAt9BZOs0wonXj1DZiFTKwcDHfYeQvmmEE5N0Nv/vhDdUE5HKWQnsWchlVvkOIq+nEU4M0tl8M3Cx7xwiDWgiWmutaqlw4vFFYDffIUQa1CfS2bzWKqxCOqRWZulsPk143w6duxHx517gyEIuo19wVUQjnPLTRAER/44AzvQdQjanEU4ZpbP5dwJ/851DRIBwRek9C7nMWt9BJKQRTplEq9Z+33cOEdloKvBV3yFkExVO+ZwCzPIdQkQ286l0Nj/FdwgJqXDKIBrdfM13DhF5nZHAf/kOISEVTnlodCNSvT6ZzuYn+w4hKpwh0+hGpOqNAv7TdwhR4ZSDRjci1e/T6Wx+ou8QjU6FMwQa3YjUjNHA532HaHQqnKHR6Eakdnwmnc3v4DtEI0v5DlCranF007VyEctv+t7Gz7vXvMb4Iz9Ex+Jn6Vq1CIBgw3oSw0cx/aM/ed3z1z58I+sevwUcjD7geMYe+m4AVt/5G9pfnsuwKTOYdGJ4qHzdU/8kaFu7cRuRKjAW+Bw19u+2nqhwBu8Eamx00zRx541F4oISi352FiP3PHyzUlh1xy9JNI963XM7lxdY9/gt7Hjm/8OSTSy79muM2P1QkiPH0fnaS0w/+6esvPliOpcXSI2fxvp5tzHl1G9W7HsTGaDz09n89wu5zDrfQRqRDqkN3md8BxiKDfMfp2n8NFLjNl0T55yj7dm7GbXP0a/bvmvlIoZN24tE03AskaR5l1m0PX8vYLigG+ccQVcHlkiy9sE/Meagk7Ck/p6RqjMOON13iEalwhmEdDa/G+EIp2atf+ZfjNyiWDoWPUVy1HiaJuz0uu2HTdqVjkVPUWpfS9C1gfaXH6a0dgWJ5pGM2O0Qllx+PsnRO2DNo+hc8jwj9zy8Ut+KyPY6x3eARqU/QQfnU9RwWbtSF+0vPsgOx5y12ePrn75rq6MbgKZJuzD2Taew7JqvYk3DGTZlJlj4Ixj3plMY96ZTAFh588WMO/IMWh+/hQ2vPErTlDTjj/hAvN+QyPY5OJ3NH1zIZeb6DtJoavaXpi/pbH4EcLbvHEPR/vJchk3djeSoTRN2XFCi7fn7GLn31gsHYMwBxzHtIz9mxzO+R2L46NeNhDqXvoRzjqYJO9P27N1Mfk+W7tWv0bXq1di+F5FB0ijHAxXO9jsVGO87xFBsbSSzofAYTRN3JjV2Up/PK61fA0D32mW0PX8fo/Y9ZrOvr5lzJeOP+hAE3eCC8EEzXHdHeb8BkaE7PZ3Nj/EdotHokNr2+5jvAEMRdG5gQ+ExJp6w+ZyH9c/863Ul1N26kpV/v5ipp34DgOU3fJegvRUSSSa841wSw0dv3Lbt+fsYtuPupMaEF3MPmzKTxb/6NE1T0uHhN5HqMho4A7jEd5BGohuwbYd0Nr838IzvHCJSFo8Vcpk3+g7RSHRIbfvU9OhGRDZzYDqbP8x3iEaiwhmgdDafIByCi0j9+ITvAI1EhTNwRwA7+g4hImV1cjqbb/IdolGocAbufb4DiEjZjQfe7jtEo1DhDNx7fQcQkVic6jtAo9AstQFIZ/MHAboqWaQ+rQKmFnKZbt9B6p1GOAOjw2ki9WsC8FbfIRqBCmdgVDgi9e0k3wEagQqnH9HFnvv4ziEisVLhVIAKp38a3YjUv13T2fz+vkPUOxVO/97jO4CIVIRGOTFT4WxDOpsfBxzsO4eIVERN31SxFqhwtu0I9DMSaRSHprP5Zt8h6pl+mW7bUb4DiEjFNAOH+A5Rz1Q426bCEWksR/oOUM9UOH2IhtaH+s4hIhWlwomRCqdvhxEOsUWkcRyRzubNd4h6pcLpmw6niTSeCehC79iocPqmwhFpTDqsFhMVzlZEd/c8wncOEfFChRMTFc7W7QuM9R1CRLz4N98B6pUKZ+v28x1ARLyZmc7mx/gOUY9iLxwzGxn3PmKwt+8AIuKVfgfEILbCMbMjzOxp4Nno8wPM7Gdx7a/MNEtFpLGpcGIQ5wjnIuB4YCWAc+5x4OgY91dOKhyRxraX7wD1KNZDas65hVs8VIpzf+UQzVDb03cOEfFKI5wYpGJ87YVmdgTgzKwJuAB4Jsb9lUsaGO47hIh4pRFODOIc4ZwLfBrYCVgMHBh9Xu10OE1E9oiOdkgZxTbCcc6tAM6I6/VjpKG0iDQTHu142XOOuhLnLLWZZvYXM1tuZsvM7EYzmxnX/spIIxwRAf3xWXZxDhmvAq4FpgHTgT8Cf4hxf+Wym+8AIlIVdB6nzOIsnJHOud8557qjtyupjZPx03wHEJGqMN13gHoT5yy1m80sC1wNOOA04G9mNgHAObcqxn0PxY6+A4hIVZjoO0C9ibNw3h+9P2eLxz9AWEBVdz4nnc0PB8b5ziEiVWGS7wD1Js5ZajPieu0YaXQjIj00wimzOGepzTWzT5nZ+Lj2EYPJvgOISNXQCKfM4pw0cBrhRZ8Pm9nVZna8mVX7vcIn+A4gIlVDhVNmsRWOc+5F59yXCdcluwr4NTDfzL7RM3GgClVrLhGpvPFabaC8Yv1hmtn+wA+BC4HrgVOBtcAdce53CHbwHUBEqkYC/RFaVrFNGjCzucAa4FdA1jnXEX3pATOr1lu46n8uEeltIrDCd4h6Eee06FOdc5utQ2RmM5xzrzjn3hfjfodilO8AIlJVNFOtjOI8pHbdAB+rJjpeKyK91cLqKDWj7CMcM9sb2A8YZ2a9RzJjqf7/eNU+i06k4tpfnsuqf/wCgoDRBxzHuDefutnX1z74Z9Y9cSskkiRHjmXiOz9LatwUulYuYsVfLsQFJSYe/2mad9oHF5RYdu3XmHzyV0k0VfuvAwCSg3mSmX0Z+CDhTScD4Bzn3ANmVgAOiVbTj42Z3Ql8wTn3cJz72V5xHFLbCzgRGA+c1OvxVuDjMeyvnFQ4Ir24oMSq237OlNO+TWrMRJZc8TlG7P4mhk16w8Zthk3djR3PuohE03BaH/0bq+/8DZPf/SVaH7uZHd7+CVJjp7L6H79g8nv3ofXRvzFqv7fUStnAIArHzA4n/B14kHOuw8wmAcOGGsTMUs657qG+Tq/XSzrnKnoX5rIfQnLO3eic+yhwonPuo73eznfO3duznZn9d7n3XQYqHJFeOpc8T2r8NJrG74glmxi1z9G0v3D/ZtsM33X/jQXSPH0vSq3hH++WTOG6OnDdHZBIEmxYR/uLDzJq1lsr/n0MwWBGONOAFT0TpZxzK5xzi3t9/Twze8TM5kVHhDCzw8zsPjN71MzuNbO9osc/YmY3mdkdwD/MbJSZ/drMHoy2fXe03YjoesdnzOzPwIitBTOzgpl9z8weAU41s9OjHE+a2fd6bdfX4+vM7EIze8rMbo9y32lmL5vZu/r7wcS5tM19/WxyKvC/ce1/kFQ4QjOdGw5JPjpvcWIYq8xcgFmqBMkAkiVIOkiUjJTr9Vjgwo8DRzIwkoEjEUAqcJYMIOFcTf6/9cJLj+ywOOgce8zCR+YDPNu2csLylYtGH7Xz7gu2tv2c+65/w+5jJ3QdsvCRJWun7DzsX7dfOqMrKNmxh500/4W/XjjxiF33Le6y6LHWyn4Xg9eeag4gs71PuxX4mpk9D9wOXOOcu6vX11c45w4ys08BXwA+BjwLHOWc6zaztwPfBU6Otj8I2N85t8rMvgvc4Zw7O1rF5UEzu51wzco259w+0eUoj2wj38po/9OB+4GDgdXArWb2HuBB4HtbPu6cu4FwYtUdzrn/iort28A7gH2BK4CbtvWDiXOWWn+q8R9gNWaSCgtIJK5M/fhAM5ocuNWJxKpXh6dWLWxKFec3pTYsaGrqfjWVTCxLppqLycSodrMdSjAZs74PmzjnkgGlhKM7GVBKljZ+HCSD8H0ioJQKCJIlSsmAUjLAhdu6IBkQpAJcqkQQPd9F2xK9D1Jh+QWpsPxcsgSpEi4Z4KKvuWRAT3m6ZID1ek8icJYKsEQAyQBLOOyWFWu6fv/aitF/uqblgLGpZNf7p05Y8sy6ds555ipLOBIJR8IcZo7kxUuWTX55xarJLdN3fO29j1014aUNHc1Prl/RXHLOjp731+mdra0jsm5N82l3X73HgSNGBJ+bPLk0Y1hz0gZ5nqRChsEXt+sJzrl1ZnYwcBTwFuAaM8s65y6PNvlT9H4u0HOeexxwhZntQbi4cVOvl7yt1+r6xwHvMrMvRJ8PB94AHA1cHO3/CTN7YhsRr4neHwrc6ZxbDmBmv49ex/Xx+A1AJ/D36PnzgA7nXJeZzSO8Q+o2+Swc53HffVHhCF2khm1g2PMj6NzTwCYEwcQJnZ0TZ3d29vmcnmJanEqtXNCUWrugKdW+INVUerUpybJksnlNIjmqPWETumByV8q28wSGv/8t214cSevvm5h+1nQWXbYoddVhzIQRfOLE1GbrDrbOa2XBT1Yzct+R/OotTTted2iKJX9YztgPTGfYpGF85VsvjZ/xlRm8+3eLm0ccvwML3zohecZ1S5O7nLsLAInABYmA7o2FHL0lwvdB9Hl3MizcsIBLPV9zPZ+7nqKOitlFjwUbi7cEqZJz0Wv0FDKvK+FS+H7VGNoHcwvg6NzIncCd0S/js4DLoy/3XJNYYtPv4G8B/3TOvdfM0tFze6zv9bEBJzvnnuu9v+1cNWx9/5v0qcs51/O7OyD6XpxzgZn12yca4WyuGjOJB/Pd1GV728I9B7p9VEwTJnR2Tpi1jWICWJ1IrF6cSq1Y2JRqnd+UaluQSpVeTaVYlgqLqS2xccTUPORvZIhGzBhB97pugo4A5xzFB4rsfO7Om23TPr+dRZcuYtIJk+ha2bXxcUsaQWfAumfXkRiWIDUmRceSDiafNBkMgs5g47ZBwhJBgmEM6uR6rP9sc+dv5xOi8y+Bc+6F6KEDgfn9PG0c8Gr08Ue2sd0thOeAznPOOTN7o3PuUeBfhLPi7jCzWcD+A4j6IHBxNKlhNXA68JNtPD5kPgvnjx733RcVjgDwcLBnae/Ewlhee4cg2GGHzs4d9uunmNYkEmteDYupOD+V2rCgKdX1aiqVWJZKNq1JJEe3J2x8d1hMsU35sqQx/UPTWXTZIrpWdzHl3VMYvtNwlv5pKSNmjGDsG8ey5MollNpLtD7aSueqTja8uoFxh45jwtsmsPDShXQs7GDXz+7KspuWMeW9U3jtD6/hSo7pZ9XEDTW7+t/kdUYTnlt5DugGXiQsgp9u4znfB64zs28TLgPWl28Bc4DFZrYKeIVwRtzPgd+Y2TPAM4SH67bJObckuknmPwl/9+WdczcC9PX4UNmm0VF5mdkM4DzC43obi8051+9MBl/S2fyFhCfxpMEdn3josUuHXXSg7xwDUUwk1ryaSq5clEoV5zc1tS9oSnUt2lhMidFticS4qJi2OnNpIDqXdzL/R/PZ4zt7vO5rC366gEknTGLk7iNZdNkixhw4hnGHbn4fw46lHSy9finTz5jOkquX4EqOqe+bSvOO3gdx/Tly3lnz7tneJ5nZOufc6F6ff4Tw+pvPbOM5lwN/dc5t8wJ5M2sB1jnnfrCNbco6hbpc4hzh3EC4jtpfCI/11YJqve21VNgDwd67+s4wUOOCYPy4zmD8vp1dQHuf2xUTVlycSq3YspiWhsU0qi2RGD+YYmovtLPw5+FosLSuROsTrVjCGHvw2I3bLL1+KVPfN5WVt61kwjETaJrUxNLrltJzDqeKlX1GXXSO5teEtz9YDnwU2Bl4F3CMmX2FTTPU/o/wPl1twMedc89u43UvBzYAbwTuMbPfApcAI4GXgLOdc6vN7MA+Hr8TeJRwssMo4Ezgv4HZhDPtvjLU7z3OwtngnLs4xtePgwpHAFjDmB26XWJxyoKaOO4zEOMCN25cZ9e4ffovprVLUqnlC1OptQuamtrmN6W6n2oNhi/qDPYfWyo935ZI7NANkzAbCbDXD/ba+NyeEU7vsln/7HqaxjfRvGNzeN7GeN05nCq2bpDPG2Fmj/X6fAKbpgz/BLjCOXeFmZ0NXOyce4+Z3USvEY6Z/QM41zn3gpm9CfgZ0N9FTDsDRzjnStFMtfOcc3eZ2TeBrwOfBX7bx+MAnc65Q8zsAuBGwqnRq4CXzOwi59zKQf48gHgL58dm9nXCOek9szJwzm1rfrhvQ/phSn1Zyg6LdmJl3RTOQI0L3NhxnV1j946K6fTr27i3UKKzzTH/s88e8I1jm+kKYJ1jw0lHjFq8MJyVt35+U1P35a1de49v7SyOKZXa2xKJ8Z3OTVr2l2WjdvlkOJLZ4dgdWHTpolo6h7N2kM9rd85tPCTbc0gt+vRwNk2H/h3h+ZvNmNlo4Ajgj71moA3k+OMfo7IZB4zvdf3PFdFrbfXxXs/vKcV5wFPOuSVRnpeBXRji78g4C2c28GHCRu75U8bRf0P7pBGObDQvmNG+U1J/g/zh5JF9fWk4XV0z9+radF79G+9NAu1TWfDqxsdaT021LlmzfMXC9ak184en2hf8545di5pSLE0mm1aXSqPaEolxXeGhvGpcrX2Np/0mgDW9S2uAhjLlGTYNDoJeH/d8PuS+iPX2BMBM59y2p+JUF/12kY3uCWY3n5CsqrUPa9IY58aM6eoas2fXtid8rTNrXdIzKy+cLh4VU6ppdTIxan0iMTYqptHbfKHyWTfvrHlxnHi/F/gA4ejmDMJZZxCeLxoD4Jxba2avmNmpzrk/WjjM2d859/hAduCcK5rZajM7yjk3h/CP/7v6erzM31+f4iycJwkX8FwW4z7KTSMc2eieYL+aOOZTL0Y7N2aPrq4xe/RTTOvN1i1JpVYsakqtmZ9Ktc1vCovptbCYRq4PR0yTMBszxEjLh/j8vpxHOIX5v9g0aQDgauAyMzsfOIWwjH4eTSJoir4+oMKJnAVcYuG5tpd77aevx2MX57ToOwkvPnqIzc/hVPO06JEMfUgqdcO5V5rPaDVjbP/bSrVZb7butVRyxcJUUzE8x5TqWpRK8Voq1bQ6mRixLpEY3wUTMevrv+99886ad0RFQ9e5OEc4X4/xtWNRyGXa0tn8Bqr/vj1SEWZFRhXGs34gV21LlRnl3OjdurpH79bVva1JebSZrQ+LKVVc0NS0Liom156weZVL2xjiXC36LjObSrhAHMCDzrlaOLy2CtChFAHgBbfzmkPtuf43lJo10rlRM7u6R83s6ob2Db2/9KSvTPUqtlsqm9n7CdfkORV4P/CAmZ0S1/7K6NX+N5FGcV+wj2473ri2egsGGbw4/zF9GTjUOXeWc+5M4DDgqzHur1ye9x1AqsfdpdkTfWcQb5/He/cAABP6SURBVOJZTK+BxVk4iS0Ooa2MeX/losKRjR53u81wjqpbk0oqQoVTZnFOGvi7md0C/CH6/DTgbzHur1xUOLJRB8OGd9D04nC6dvedRSpOhVNmsY04nHP/BVxKODV6f+AXzrkvxbW/MtIZYtnMQjelFia7SHmtBxb5DlFv4r4fzj2E95NwhBMIaoFGOLKZucGeXXskNJekwTxJS7EmVhetJZWYpXYKNTRLrZDLrAcW+84h1WNOMHuoV6xL7XnCd4B6FOcIp2eW2jIAM5sM3A5s8+ZCVeI5dC2ORO4P9nmD7wxScduzhIwMkGapbZ0Oq8lGKxk3qeTsNd85pKJUODGIZYQTrWz6UI3OUgNNHJAtLGf8oh1ZvaPvHFIxOqQWg1hGHC5cEfQwanOWGuivG9nCk8EMLeraOAq0FAd74zXZhjjP4cwFFjrnPh/jPuLyEOENh2rlEKDE7O5g1rC3J6v5ZrVSRvqDMyZx/kJ9E3Cfmb1kZk/0vMW4v7Ip5DKtwDO+c0j1uDfYb5rvDFIxNfF7qhbFOcI5PsbXroQHgP18h5Dq8ILb6Q3Osc6MSt1tUvzRCCcmcd6eYH5cr10hDwBn+w4h1cGRSLQy8pWxtM32nUVi95DvAPVK5yj6drfvAFJdXnTT1/jOILF7kZaibksQExVOHwq5zNPEd09zqUH3B/v6jiDxu913gHqmwtk2jXJkoznB7Am+M0jsVDgxUuFs2798B5Dq8Wiw+0znKPnOIbEJgDt8h6hnKpxtu9N3AKkeG2ge0Umq1ifDSN/m0lJc7TtEPVPhbNvjgNall40WuclLfWeQ2OhwWsxUONtQyGUccJPvHFI9Hgn26PSdQWKjwomZCqd/N/gOINVjTjBbF37Wp3bCG0ZKjFQ4/fsnUPQdQqqD7o1Tt+bQUuzwHaLeqXD6UchluoCbfeeQ6rCMCZNLznR9Vv35u+8AjUCFMzA6rCYbrWSsrkSvLwFwje8QjUCFMzA3AzpZLAA8FaTX+c4gZfVPWoqLfYdoBCqcASjkMmsJz+WIcE8wq8l3Bimr3/sO0ChUOAOnw2oCwD3BLN1qun5sAK73HaJRqHAG7s9Al+8Q4t9zbpddnaPddw4pi7xuJ105KpwBKuQyS4G/+M4h/gUkkusZ/orvHFIWOpxWQSqc7fML3wGkOrzkpq/0nUGGbA3wN98hGokKZ/vcBhR8hxD/Hgj2cb4zyJBdp4s9K0uFsx0KuUwA/Mp3DvFP98apCzqcVmEp3wFq0K+Br6OfXUN7JNgj7RzODPOZY2Ex4Mwb2lm6zmEGnzioiQve3Myqdsdp17VRWONIjzeuPWUkO4x4fdTkN9cye0r4d+cbxiW46fSRAJzxpzbmLQ04cc8U333bcAC+/a8OZk1J8J6962JW+EvoflcVpxHOdirkMouBvO8c4td6RozuIul9xYFUAn543HCe/vRo7v+PUfzfQ108vbxE7u4O3jYjxQvnjeZtM1Lk7t76kaMRKXjs3NE8du7ojWXzxNISI1LGE58czUOLSxQ3OJa0BjzwaqleygbgR7QUA98hGo0KZ3Au8x1A/FvsJi3xnWHamAQHTUsCMKbZ2GdyglfXOm58rpuzDgjL4awDmrjhue4Bv2ZTAtq7HYFzdJUgmYCv/bODbxzbHMv34MFq4De+QzQiFc7g3Aws9B1C/HrU7V5VJ5wLawIeXVLiTTsnWbouYNqY8J/3jqONpeu2/sf8hm445BfrePMv13PDs+FlZvtMTjJ5ZIKDLl3PSXumeHFVQODYWGx14FJaiut9h2hEOg8xCIVcJkhn85cC3/adRfyZU5o98r3J6riFyrpOx8nXtvGjE4YztnnzczVmhvVxpmn+Z0ez09gEL68OeOsV65k9JcluExL86IThG7c56Q9tXHricL7zrw4eX1riHTNTfPzgYXF+O3HqAn7iO0Sj0ghn8P4P0BXKDez+YN+dfWcA6CqFZXPG7Cbet094GG3q6ARLWsNRzZLWgCmjtv5Pfaex4eMzd0hwbDrFo6+VNvv6jc92cfC0BOs6HS+tDrj21JFc90wXbV01Oyv8ai3U6Y8KZ5AKucwa9JdSQ1vMpGmBM68XgDrn+I+bNrDPpCSfP3zTOZZ37ZniisfDQ2RXPN7Fu/d6/cGM1e2Oju6wOFa0BdyzsMS+kzf9SugqOX70QCdf/Ldm2rvYOB2vFEBn6XUvVyt+6DtAI9MhtaG5CLgA0G2HG9QqxiyYxNqJvvZ/z8ISv3uii9lTEhx4SXjXhO++rZnskcN4/3Xt/OrRLnYdZ1x7ajgD7eHFJS55uJNfvmsEz6wocc5fN5AwCBxk/20Y+07edJ7m/x7q5KwDmhjZZOw/NUFbt2P2z9fx77unGD/c62zwwbqDluLjvkM0MnOuZofGVSGdzX8f+C/fOcSP3zb9711HJ+cd4zuHDEiGlqKWsvFIh9SG7oeglYMb1b3BfnVzYUqdewbdKt47Fc4QRatIa1HPBnV3MGuK7wwyIF+lpajDOZ6pcMrj+0BVXZMhlfGM2zXtnP7bV7l7aSnqJmtVQIVTBtFyN7/2nUMqr0Qy1Uaz7o1T3XSOtUqocMonR3i7Wmkwr7hpK3xnkD79mZbivb5DSEiFUyaFXGYB4TRpaTAPBntrEcjq1A1kfYeQTVQ45fVd4DXfIaSy5gSzx/vOIFt1GS3F532HkE1UOGVUyGXWAV/2nUMq66Fgr7RzaAZUdWkFWnyHkM2pcMrvcuAR3yGkctYxcmw3yUW+c8hmLqSluMx3CNmcCqfMottQfwb0F28jWeImaEHI6rEErZlWlVQ4MSjkMvehGzw1lMfc7pqhWD0uoKXY5juEvJ4KJz5fAlb5DiGVcXcwa4TvDALA9bQU/+g7hGydCicmhVxmBfA/vnNIZdwX7LeT7wzCKuDTvkNI31Q48boMuMt3CInfQjdlp8CxxneOBvdZWopLfYeQvqlwYhRNIDgL3Rm0IaxhTMF3hgaWp6X4O98hZNtUODEr5DLzgfN955D4PRvsUvSdoUEVgXN8h5D+qXAqoJDLXAFotdo6d2+wn+6g68cXaCm+6juE9E+FUznnoGVv6trdwexJvjM0oNtpKf7SdwgZGBVOhRRymZXA2b5zSHyecumZztHlO0cDaQU+7juEDJwKp4IKuczNwCW+c0g8ukg1tTNM98apnI/SUiz4DiEDp8KpvP8EXvAdQuJRcDsu952hQfxAd/GsPSqcCivkMm3A6ehmbXXpoWCvku8MDeAudJ+bmqTC8aCQy8wFPuY7h5Tf3cHssb4z1LnFwGm0FFXsNUiF40khl/k9cKHvHFJeDwZ7p31nqGNdwKlaTaB2qXD8ygI3+w4h5VNk9Phul9A1IfH4Ai3Fe32HkMFT4XgULX1zOvCc7yxSPq8xQYVTflfRUrzYdwgZGhWOZ4Vcpgi8m3B5DqkDTwQz231nqDNPAZ/wHUKGToVTBQq5zHOEI53AdxYZuruDWcN9Z6gjrwEn0VJc7zuIDJ0Kp0pEF4VqqmcduDfYb7rvDHWiFfh3Woq6mLZOqHCqSCGXuRD4ie8cMjQFt+POzukQ6RB1ASfTUnzUdxApHxVO9bkA+I3vEDIUZmsYNd93ihrmgLNpKd7mO4iUlwqnyhRyGUd4Uei1vrPI4D3vdtHdPwfvc7QUr/QdQspPhVOFounSHwL+6juLDM59wb76tzU4X6el+GPfISQe+kdRpQq5THhVNdzhO4tsv7tLsyf6zlCDfkhL8Zu+Q0h8VDhVrJDLbADeBejq6hrzhJs50zm6feeoIb+gpfgF3yEkXiqcKlfIZdYD/w5otk4N6aSpeQNNms47MD8Czh3sk82sZGaPmdmTZvZHMxvZx3aD+sPNzNJm9sHB5pNNVDg1IFqN4Dhgru8sMnAL3NRlvjPUgK/SUvwcLUU3hNdod84d6JybBXSyRXmZWQrAOXfEIF8/DQy6cCyk37WocGpGIZdZAbwFuNNzFBmgh4M9dUitbwHwKVqK3y7z684BdjezY81sjpndBDwNYGbrovdXm1mm5wlmdrmZnRKNZOaY2SPRW09B5YCjolHU58wsaWYXmtlDZvaEmZ2zZYjotZ4zs98CTwK7RM950szmmdlp0XbWx+PHmtldZnajmb1sZjkzO8PMHoy2263MP7eKUOHUkEIu0wqcANzoO4v0b04we4zvDFWqCziDluLPy/mi0UjmncC86KGDgAucc3tusek1wPuj5wwD3gbkgWXAO5xzBwGnAT2LhWaBOdEo6iLgP4Cic+5Q4FDg42Y2YyuR9gB+5pzbDzgEOBA4AHg7cKGZTQPe18fjRI+dC+wDfBjY0zl3GPBL4LxB/Ii8U+HUmEIu0wGcjC4OrXoPBnvv6jtDFWoD3k1L8eoyvuYIM3sMeBhYAPwqevxB59zWzqPdDLzFzJoJC+pfzrl2oAm4zMzmAX8E9u1jf8cBZ0b7fACYSFguW5rvnLs/+vhI4A/OuZJzbinhXUsP3cbjAA8555Y45zqAl4Bbo8fnER7mqzkp3wFk+xVymRJwdjqbXwh8zXce2bpVjJtYconXkhbs6DtLlVgDnEhL8Z4yv267c+7A3g+YGcBWF/x0zm0wszuB4wlHMj3l9zlgKeHIIkHft4E34Dzn3C395BrqgqMdvT4Oen0eUKO/uzXCqWGFXObrhMN7nSuoUssYv9B3hirxGnBMDGUzWNcAHwWOAv4ePTYOWOKcCwgPYSWjx1uB3odHbwE+aWZNAGa2p5mN6md/c4DTovM/k4GjgQe38XhdUuHUuEIu82vgRMJ/FFJlnghmtPnOUAUeBA6lpfiE7yC93AocA9zunOuMHvsZcJaZPQ7szaYRyhNAycweN7PPEZ5DeRp4xMyeBC6l/xHHn6PXeZzwYu4vOude28bjdcmcG8psRKkW6Wx+H+B6whOMUiXOTN5y3zebrjjcdw6PLgPOo6XY0e+WUvc0wqkThVzmGeAwNh2PlirQwPfG6QA+RkvxEyob6aERTh1KZ/PnAT8knHUjXjn3SvMZ680Y7TtJBS0kvJfNQ76DSHXRCKcOFXKZnxAen17kO4uYrWVkIy1xcwdwsMpGtkaFU6cKucx9hBe+3e47S6N7we282neGCvk+cBwtxeW+g0h1UuHUsUIus5zwWoNvE95FUTy4P9jHfGeI2QrCQ2hfoqVY8h1GqpcKp84VcpmgkMt8FXgr4dXKUmF3B7Pq+d441wP70VL8k+8gUv00aaCBpLP5kcB3gPPRHxsVM5yO9meaPzrMbOOFhPVgOfAZWoq6FboMmAqnAaWz+cMJ15vSNTsV8lzzWS81W1dNrvC7FX8EPq1zNbK99FduA4omFLwR+F+0LE5FLHSTl/rOUAbLgFNpKb5fZSODocJpUIVcpqOQy/wP8CbCZTUkRnODPTr736qqXUN4ruY630GkdqlwGlwhl3mEcDn0LwPrPMepW3fX7r1xngVOoqX4AVqKK3yHkdqmcziyUTqbnwp8A/gY1NUJbu8msWb5w8M/Ndl3ju2wDGgBLqOlqMOuUhYqHHmdaCHQ7wEn+c5ST15qPmNZ0twU3zn60Q5cBORoKWoFcikrFY70KZ3NHwv8ADjYc5S68EDzpx6eamsO8Z2jDw74HfBlWopaEklioXM40qdCLnMn4fmdM4D5ftPUvieDGUO9A2RcetY/O0tlI3FS4cg2FXIZV8hlrgL2Ai4gXAlYBuGeYFa1rd59J/BOWopvo6X4qO8wUv90SE22SzqbbyIc8XyJ8K6IMkB724JX/t6cneE5Ronwws0f0FKc6zmLNBgVjgxKOps34D3A54EjPcepCUYQvNz8oQ1mjPSw+3WEq0tcREtRh0fFCxWODFk6mz8U+CxwKrrp2zbNa/6Pp8ZY+34V3OUS4GLgElqKayq4X5HXUeFI2aSz+Z2Ac4EPA7t6jlOV/jzsa3PemHjxqArs6kHgEuD3tBRrfZUDqRMqHCm76HDb0cCZwCnAWL+Jqkc2ddW/zk399eiYXv5l4PfAlbQUn49pHyKDpsKRWKWz+RHAuwnL5zgafAWDIxPznrxy2P/OKuNLriJc5+xKWor3lvF1RcpOhSMVk87mdwROJzzk9kbPcbwYyYb1TzWfPcJsSJckdAB/Aa4E/kZLsas86UTipcIRL9LZ/M7ACdHb24FxfhNVzvPNZ74yzLq3d3r0AuBW4DbgFlqKxfInE4mXCke8S2fzKeDNbCqggwDzGipGdwz7/H0zE68d3s9mrYQXZt4K3KpzMlIPVDhSddLZ/BTC8z1vI1xaZ2/q6NzPD5t+fufJyTnHbvFwCXiYcARzK3C/DpVJvVHhSNVLZ/MjgQOBQwgXEj2EsIRqcmmmkxL3PviTYT8dAcyN3h4GHqel2O43mUi8VDhSk9LZ/Cg2ldAsYDdgJrAL1VNEG4BXgeeAJ6O3ecAzhVymw2cwER9UOFJX0tn8MMKLTtPAzlu8TQJGAaN7vR++nbvoJCySDcBKYBFhqSza8q2Qy6wc2ncjUl9UONLQ0tl8kteXkLGpVDZ7K+QygaeoIjVPhSMiIhVRLce6RUSkzqlwRESkIlQ4IiJSESocERGpCBWOiIhUhApHREQqQoUjIiIVocIREZGKUOGIiEhFqHBERKQiVDgiIlIRKhwREakIFY6IiFSECkdERCpChSMiIhWhwhERkYpQ4YiISEWocEREpCJUOCIiUhEqHBERqQgVjoiIVIQKR0REKkKFIyIiFaHCERGRilDhiIhIRahwRESkIlQ4IiJSESocERGpCBWOiIhUhApHREQqQoUjIiIVocIREZGKUOGIiEhFqHBERKQiVDgiIlIRKhwREakIFY6IiFSECkdERCri/wOmiFy2xNXJhwAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 432x432 with 1 Axes>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ffYLNxWmBiVI",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 337
        },
        "outputId": "a780289e-65d2-4026-ac80-5043e5e13745"
      },
      "source": [
        "# distribution of price\n",
        "plt.figure(figsize = (10,4))\n",
        "sns.distplot(df['price'])\n",
        "plt.show()"
      ],
      "execution_count": 39,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).\n",
            "  warnings.warn(msg, FutureWarning)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAm0AAAEICAYAAAAN2sPKAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3de5Scd33f8fd3Zy/SSrZkywpgySC1lk0FgZoIQ5pLT+MYm5CgtDFFTiBujhuniZ2Qy0lqc1qHuPEp7gVCG6A42IlxILJRSKoSBwMxSUMSZMlgApZRvfFVxoCsmy+SVjuz3/7xPCOPVnt5VtpnViO/X+f4aOY3v+fZ3+yckT7+XSMzkSRJ0smtb74bIEmSpJkZ2iRJknqAoU2SJKkHGNokSZJ6gKFNkiSpBxjaJEmSekCtoS0iLo2IHRExEhHXTvL6UETcUb6+JSJWdbx2XVm+IyIuKcvOj4j7O/57JiJ+uc73IEmSdDKIuvZpi4gG8P+Ai4GdwFbg8szc3lHnF4DXZOa/i4gNwL/MzLdHxFrgj4ALgbOBzwPnZWZrwv2fBN6QmY9N15azzjorV61aNafvT5IkqQ733Xff05m5fGJ5f40/80JgJDMfBoiIjcB6YHtHnfXAe8rHm4DfjYgoyzdm5ijwSESMlPf7u45rLwL+YabABrBq1Sq2bdt2gm9HkiSpfhExabapc3h0BfBEx/OdZdmkdTKzCewHllW8dgNFb9ykIuKqiNgWEdt27dp1XG9AkiTpZNGTCxEiYhB4K/DJqepk5s2ZuS4z1y1ffkwPoyRJUk+pM7Q9CZzT8XxlWTZpnYjoB5YAuytc+2bgy5n57TlusyRJ0kmpztC2FVgTEavLnrENwOYJdTYDV5SPLwPuyWJlxGZgQ7m6dDWwBri347rLmWZoVJIk6VRT20KEzGxGxDXA3UADuDUzH4iIG4BtmbkZuAW4vVxosIci2FHWu5Ni0UITuLq9cjQiFlGsSP25utouSZJ0sqlty4+Tybp169LVo5IkqRdExH2ZuW5ieU8uRJAkSXqxMbRJkiT1AENbF/2vv/oHrrj13pkrSpIkTWBo66JvPPUMX3ty/3w3Q5Ik9SBDWxeNNsc5eLg1c0VJkqQJDG1dNNoc5+BYi/HxU3/FriRJmluGti46NFb0sh1q2tsmSZJmx9DWRaPNcQAOOEQqSZJmydDWRaNlD5vz2iRJ0mwZ2rpodKzoaTs4ZmiTJEmzY2jrIodHJUnS8TK0dVF7ePTA4eY8t0SSJPUaQ1sXHSqHRw85PCpJkmbJ0NZFL/S0GdokSdLsGNq6JDOd0yZJko6boa1LxlpJlgchuOWHJEmaLUNbl4x2nILglh+SJGm2DG1d0h4aBYdHJUnS7BnauqQztB10yw9JkjRLhrYu6dzmw542SZI0W4a2LmkfYQXOaZMkSbNnaOuSoxYi2NMmSZJmqdbQFhGXRsSOiBiJiGsneX0oIu4oX98SEas6XruuLN8REZd0lC+NiE0R8Y2IeDAivrfO9zBXXIggSZJORG2hLSIawAeBNwNrgcsjYu2EalcCezPzXOD9wE3ltWuBDcCrgEuBD5X3A/gA8JnMfCXwWuDBut7DXGqHtsH+PnvaJEnSrNXZ03YhMJKZD2fmYWAjsH5CnfXAbeXjTcBFERFl+cbMHM3MR4AR4MKIWAL8IHALQGYezsx9Nb6HOTNazmM7Y3iAA2OuHpUkSbNTZ2hbATzR8XxnWTZpncxsAvuBZdNcuxrYBfx+RHwlIj4aEYsm++ERcVVEbIuIbbt27ZqL93NCDpU9bWcMD9rTJkmSZq3XFiL0A68DPpyZFwDPA8fMlQPIzJszc11mrlu+fHk32zipdk/b0uEBQ5skSZq1OkPbk8A5Hc9XlmWT1omIfmAJsHuaa3cCOzNzS1m+iSLEnfRGO3raDrjlhyRJmqU6Q9tWYE1ErI6IQYqFBZsn1NkMXFE+vgy4JzOzLN9Qri5dDawB7s3MbwFPRMT55TUXAdtrfA9zph3alg4PunpUkiTNWn9dN87MZkRcA9wNNIBbM/OBiLgB2JaZmykWFNweESPAHopgR1nvTopA1gSuzsx20vlF4ONlEHwY+Jm63sNcau/TtnR4gMPNcVrjSaMv5rlVkiSpV9QW2gAy8y7grgll13c8PgS8bYprbwRunKT8fmDd3La0fu0TEZYuHACKUxEWD9X665ckSaeQXluI0LNGm+MM9vcxXAa1Ax4aL0mSZsHQ1iWHxloM9fcxPFDsEewKUkmSNBuGti4ZbY6zYKDBwsEytLmCVJIkzYKhrUtGm0VPWzu0uYJUkiTNhqGtS0ab4w6PSpKk42Zo65LRsXGG+hsMD7YXIhjaJElSdYa2Lhltthga6GPhYPErd06bJEmaDUNblxQ9bX0sLHvaDrrlhyRJmgVDW5cUCxEaR+a0OTwqSZJmw9DWJcWWH64elSRJx8fQ1iXF6tEGQ/19RBSb7UqSJFVlaOuS0fJEhIhgeKBhT5skSZoVQ1uXjDbHGRooft0LB/sNbZIkaVYMbV3SHh4FGB5suHpUkiTNiqGtS9oHxgMsHGi4T5skSZoVQ1sXNFvjNMeTBeV2HwsHndMmSZJmx9DWBYdb4wBHetqK4VFDmyRJqs7Q1gWjY0eHtoWuHpUkSbNkaOuC0WYZ2jqGR92nTZIkzYahrQtGm0VA6xwetadNkiTNhqGtCw4dGR5tb/nRzwG3/JAkSbNgaOuCiT1tC9zyQ5IkzVKtoS0iLo2IHRExEhHXTvL6UETcUb6+JSJWdbx2XVm+IyIu6Sh/NCK+FhH3R8S2Ots/V9pz2tpbfgwPNhhrJWPlqlJJkqSZ9Nd144hoAB8ELgZ2AlsjYnNmbu+odiWwNzPPjYgNwE3A2yNiLbABeBVwNvD5iDgvM9vdU/8iM5+uq+1z7cjq0YEX5rQBHBxrMdCws1OSJM2szsRwITCSmQ9n5mFgI7B+Qp31wG3l403ARRERZfnGzBzNzEeAkfJ+PWni8OjCdmhzMYIkSaqoztC2Anii4/nOsmzSOpnZBPYDy2a4NoHPRsR9EXHVVD88Iq6KiG0RsW3Xrl0n9EZO1JEtP8qFCAvLYVJXkEqSpKp6cWzu+zPzdcCbgasj4gcnq5SZN2fmusxct3z58u62cILJtvwAe9okSVJ1dYa2J4FzOp6vLMsmrRMR/cASYPd012Zm+8/vAH9CDwybHpowp23hYDGV8OCY235IkqRq6gxtW4E1EbE6IgYpFhZsnlBnM3BF+fgy4J7MzLJ8Q7m6dDWwBrg3IhZFxGkAEbEIeBPw9Rrfw5wYHWv3tL2wehQcHpUkSdXVtno0M5sRcQ1wN9AAbs3MByLiBmBbZm4GbgFuj4gRYA9FsKOsdyewHWgCV2dmKyJeAvxJsVaBfuATmfmZut7DXHlhy48Xzh4FQ5skSaquttAGkJl3AXdNKLu+4/Eh4G1TXHsjcOOEsoeB1859S+vVDm2DjaNXj3r+qCRJqqoXFyL0nNFmi/6+oL9x9EIEe9okSVJVhrYuGB0bP7JyFGB4oOjgNLRJkqSqDG1dcKjZYqicxwYvrCJ1eFSSJFVlaOuCiT1tQ/19RLywqlSSJGkmhrYuGG0eHdoigqH+Pg41PTBekiRVY2jrgtFmiwUdw6MACwYanoggSZIqM7R1wcSeNij2anNOmyRJqsrQ1gXFnLZje9ocHpUkSVUZ2rpgtNk6smK0bai/z542SZJUmaGtCw6NHTs8usDhUUmSNAuGti4YbbaOGR51TpskSZoNQ1sXjDbHjxkeXTDQx6Ex57RJkqRqDG1dUKwenWQhgj1tkiSpIkNbF4yOtSaf09Y0tEmSpGoMbV0w1fDowcMOj0qSpGoMbTXLzCmHRz17VJIkVWVoq9louYGuw6OSJOlEGNpqNmVo628w1kqaLYdIJUnSzAxtNRste9OOPTC++NV7lJUkSarC0Faz0bHJe9oWDhYhzm0/JElSFYa2mrWHRwcnGR4FQ5skSarG0Fazw0fmtB09PNreAsRTESRJUhW1hraIuDQidkTESERcO8nrQxFxR/n6lohY1fHadWX5joi4ZMJ1jYj4SkR8us72z4WxVrunLY4qb89xs6dNkiRV0V+lUkR8CrgF+PPMrNQ1FBEN4IPAxcBOYGtEbM7M7R3VrgT2Zua5EbEBuAl4e0SsBTYArwLOBj4fEedlZjvhvAt4EDi9Slvmwye2PA7AY7ufB+CvH3qab+0fPfL6Q99+FjC0SZKkaqr2tH0I+EngoYh4b0ScX+GaC4GRzHw4Mw8DG4H1E+qsB24rH28CLoqIKMs3ZuZoZj4CjJT3IyJWAm8BPlqx7fOqOZ4ANPqO7mnrbzg8KkmSqqsU2jLz85n5U8DrgEcper7+NiJ+JiIGprhsBfBEx/OdZdmkdTKzCewHls1w7e8AvwFMm3Yi4qqI2BYR23bt2jXDO6xPqwxt/XF0aBtoFM/taZMkSVVUntMWEcuAfwP8W+ArwAcoQtznamnZ5G34UeA7mXnfTHUz8+bMXJeZ65YvX96F1k2udaSn7ehf9UC7p81TESRJUgVV57T9CXA+cDvwY5n5VPnSHRGxbYrLngTO6Xi+siybrM7OiOgHlgC7p7n2rcBbI+JHgAXA6RHxh5n5jirvYz60phgeHXB4VJIkzULVnrbfy8y1mfmf24EtIoYAMnPdFNdsBdZExOqIGKRYWLB5Qp3NwBXl48uAezIzy/IN5erS1cAa4N7MvC4zV2bmqvJ+95zMgQ2mC23F84MOj0qSpAqqhrbfnqTs76a7oJyjdg1wN8VKzzsz84GIuCEi3lpWuwVYFhEjwK8C15bXPgDcCWwHPgNc3bFytKfM1NM2amiTJEkVTDs8GhEvpVgAsDAiLgDayeN0YHimm2fmXcBdE8qu73h8CHjbFNfeCNw4zb3/EvjLmdow36YKbf0uRJAkSbMw05y2SygWH6wE3tdR/izw7pradEpp5uShrRFB4Jw2SZJUzbShLTNvA26LiJ/IzD/uUptOKUe2/JgQ2iKCgf4+57RJkqRKZhoefUdm/iGwKiJ+deLrmfm+SS5Th6mGRwEG+sLhUUmSVMlMw6OLyj8X192QU1VrvBj+nDS0NfocHpUkSZXMNDz6kfLP3+pOc049rfEkgL44NrT1N/rcXFeSJFVSacuPiPgvEXF6RAxExF9ExK6IOKn3RztZtMZz0l42gMFGuOWHJEmqpOo+bW/KzGeAH6U4e/Rc4NfratSppDlNaOtvuBBBkiRVUzW0tYdR3wJ8MjP319SeU850PW0DjXBOmyRJqqTS2aPApyPiG8BB4OcjYjlwqL5mnTpa43nMdh9txUIEe9okSdLMKvW0Zea1wD8D1mXmGPA8sL7Ohp0qputp6ze0SZKkiqr2tAG8kmK/ts5rPjbH7TnlFHPaJs/Gg41gr8OjkiSpgkqhLSJuB/4xcD/Q7hpKDG0zmm541J42SZJUVdWetnXA2szyIE1VNu1CBE9EkCRJFVVdPfp14KV1NuRU1crpVo/2cajp8KgkSZpZ1Z62s4DtEXEvMNouzMy31tKqU8i0PW39fbTGk7HWOAONqvlZkiS9GFUNbe+psxGnstZ4Mtg/eSAbKMPcwbGWoU2SJE2rUmjLzL+KiFcAazLz8xExDDTqbdqpoTWeNCY5dxSKhQgAh8ZanL5goJvNkiRJPabq2aM/C2wCPlIWrQD+tK5GnUqmPxGh+PWPuu2HJEmaQdUxuauB7wOeAcjMh4DvqqtRp5Lpzh4daBTlriCVJEkzqRraRjPzcPtJucGu239U0Bofn/YYK8BD4yVJ0oyqhra/ioh3Awsj4mLgk8D/qa9Zp44qw6MeGi9JkmZSNbRdC+wCvgb8HHAX8B9muigiLo2IHRExEhHXTvL6UETcUb6+JSJWdbx2XVm+IyIuKcsWRMS9EfHViHggIn6rYvvnzfShzeFRSZJUTdXVo+MR8afAn2bmrirXREQD+CBwMbAT2BoRmzNze0e1K4G9mXluRGwAbgLeHhFrgQ3Aq4Czgc9HxHkUe8T9UGY+FxEDwBcj4s8z80vV3m73Tbe5bufqUUmSpOlM29MWhfdExNPADmBHROyKiOsr3PtCYCQzHy7nw20E1k+osx64rXy8CbgoIqIs35iZo5n5CDACXJiF58r6A+V/J/Xcuko9bZ6KIEmSZjDT8OivUKwafX1mnpmZZwJvAL4vIn5lhmtXAE90PN9Zlk1aJzObwH5g2XTXRkQjIu4HvgN8LjO3TPbDI+KqiNgWEdt27arUOViLSnPaDtvTJkmSpjdTaHsncHnZ2wVAZj4MvAP46TobNpXMbGXmPwVWAhdGxKunqHdzZq7LzHXLly/vbiNL45mMJzOHtqahTZIkTW+m0DaQmU9PLCzntc20hf+TwDkdz1eWZZPWKbcRWQLsrnJtZu4DvgBcOkM75k1rvBi57Z/iRIT2MVbOaZMkSTOZKbQdPs7XALYCayJidUQMUiws2DyhzmbgivLxZcA9mZll+YZydelqYA1wb0Qsj4ilABGxkGKRwzdmaMe8aYe2mRciOKdNkiRNb6bVo6+NiGcmKQ9gwXQXZmYzIq4B7qY4p/TWzHwgIm4AtmXmZuAW4PaIGAH2UAQ7ynp3AtuBJnB1ZrYi4mXAbeXK1D7gzsz8dOV322UzhbZGXzDQCHvaJEnSjKYNbZl5QofCZ+ZdFHu6dZZd3/H4EPC2Ka69EbhxQtnfAxecSJu66YXQNnWH5oL+hiciSJKkGVXdXFfHYaaeNoChgYbDo5IkaUaGthpVCW0LB/sYtadNkiTNwNBWo2bOHNoW9Dfc8kOSJM3I0FajVqvc8mO60DbQ4KCb60qSpBkY2mrUGi/mqk3b0zbQ55w2SZI0I0NbjSoNjw44PCpJkmZmaKvRkRMRZgpt9rRJkqQZGNpqVGX16IKBhqtHJUnSjAxtNaoU2vr73FxXkiTNyNBWoyOhbYoD46E9PGpokyRJ0zO01aja5rrOaZMkSTMztNWoSmgbHizOHm3XlSRJmoyhrUbNCqFt6cIBAJ45ONaVNkmSpN5kaKvRC1t+TP1rXjo8CMA+Q5skSZqGoa1GVYZHlwwXPW37DhzuSpskSVJvMrTVqFXhRIT28Oi+A/a0SZKkqRnaatTuaZsms3UMj9rTJkmSpmZoq1FrPGn0BTHNPm32tEmSpCoMbTVqh7bpnG5okyRJFRjaatQcz2lPQ4BivtvpC/rZ7+pRSZI0DUNbjVrjSf8MPW1QzGtz9agkSZqOoa1GVYZHAZYOD7hPmyRJmlatoS0iLo2IHRExEhHXTvL6UETcUb6+JSJWdbx2XVm+IyIuKcvOiYgvRMT2iHggIt5VZ/tPVGt8vFJoW7JwwDltkiRpWrWFtohoAB8E3gysBS6PiLUTql0J7M3Mc4H3AzeV164FNgCvAi4FPlTerwn8WmauBd4IXD3JPU8a1XvaBp3TJkmSplVnT9uFwEhmPpyZh4GNwPoJddYDt5WPNwEXRbE/xnpgY2aOZuYjwAhwYWY+lZlfBsjMZ4EHgRU1vocTUjW0nTE84Jw2SZI0rTpD2wrgiY7nOzk2YB2pk5lNYD+wrMq15VDqBcCWyX54RFwVEdsiYtuuXbuO+02ciFZWXIiwcID9B8cYLzfjlSRJmqgnFyJExGLgj4FfzsxnJquTmTdn5rrMXLd8+fLuNrDUrNjTtmR4kPGEZ0ebXWiVJEnqRXWGtieBczqeryzLJq0TEf3AEmD3dNdGxABFYPt4Zn6qlpbPkcpz2soNdve7GEGSJE2hztC2FVgTEasjYpBiYcHmCXU2A1eUjy8D7snMLMs3lKtLVwNrgHvL+W63AA9m5vtqbPucmM2WH+D5o5IkaWr9dd04M5sRcQ1wN9AAbs3MByLiBmBbZm6mCGC3R8QIsIci2FHWuxPYTrFi9OrMbEXE9wPvBL4WEfeXP+rdmXlXXe/jRBShbeZc3A5te+1pkyRJU6gttAGUYequCWXXdzw+BLxtimtvBG6cUPZFYOauq5NE5TltCwcBXEEqSZKm1JMLEXpF9WOsyjlt7tUmSZKmYGirUavCgfFQnIgAeCqCJEmakqGtRlUXIgw0+lg81G9okyRJUzK01ahqaIPy/FFXj0qSpCkY2mo0m9C2dHjAfdokSdKUDG01mm1o2+dCBEmSNAVDW00yk1bOIrQtHHTLD0mSNCVDW01aWRz+XmXLD4AlwwNu+SFJkqZkaKtJa7wIbdV72gbYd2CMLMOeJElSJ0NbTWYd2oYHaI4nzx9u1dksSZLUowxtNZl9aPMoK0mSNDVDW02OhLYKJyJAMTwKnoogSZImZ2iryfH3tBnaJEnSsQxtNWkex5w2wFMRJEnSpAxtNWn3tFXd8sPhUUmSNB1DW01mOzx6ehna3KtNkiRNpn++G3CqeiG0TZ+LP7Hl8SOPh/r7+OuHnuaMcn5bp598w8vntoGSJKmn2NNWk/aJCFV72gCWLR5k93OjdTVJkiT1MENbTWY7pw3grMVD7H7ehQiSJOlYhraazHZOGxShbe/zh2m2xutqliRJ6lGGtprMdssPgGWLBklgj71tkiRpAkNbTY63pw3g6ecMbZIk6Wi1hraIuDQidkTESERcO8nrQxFxR/n6lohY1fHadWX5joi4pKP81oj4TkR8vc62n6gTCW27n3cxgiRJOlptoS0iGsAHgTcDa4HLI2LthGpXAnsz81zg/cBN5bVrgQ3Aq4BLgQ+V9wP4g7LspHY8oW3hYINFgw2edgWpJEmaoM6etguBkcx8ODMPAxuB9RPqrAduKx9vAi6KiCjLN2bmaGY+AoyU9yMz/y+wp8Z2z4nWeLGYoL/igfFtZy0ecnhUkiQdo87QtgJ4ouP5zrJs0jqZ2QT2A8sqXjutiLgqIrZFxLZdu3bNsukn7ngWIgAsWzxkT5skSTrGKbsQITNvzsx1mblu+fLlXf/5xzM8CnDW4kGePdRktNmqo1mSJKlH1RnangTO6Xi+siybtE5E9ANLgN0Vrz2ptUNb36xDW7kYwSFSSZLUoc7QthVYExGrI2KQYmHB5gl1NgNXlI8vA+7JzCzLN5SrS1cDa4B7a2zrnGuNJ30Bfccxpw1wiFSSJB2lttBWzlG7BrgbeBC4MzMfiIgbIuKtZbVbgGURMQL8KnBtee0DwJ3AduAzwNWZ2QKIiD8C/g44PyJ2RsSVdb2HE9Eaz1kPjQKcuag4LN7QJkmSOvXXefPMvAu4a0LZ9R2PDwFvm+LaG4EbJym/fI6bWYtmHl9oG+zvY8nCAVeQSpKko5yyCxHmW9HTdny/3rMWD7LbnjZJktTB0FaT1njSfxw9bVDMa9v13CjF9D5JkiRDW22Od04bFKHt0Ng4z40257hVkiSpVxnaatIaTxqzXDnatmLpQgB27j04l02SJEk9zNBWkxPpaVtxxkL6Ah7fc2COWyVJknqVoa0mzfHx4w5tA40+zl660NAmSZKOMLTV5JmDTRYPHf+OKuecOczOvQeOnKwgSZJe3AxtNchM9jx/mGWLB4/7Hi8/Y5ixVvKtZw7NYcskSVKvMrTV4OnnDnO4NX7kdIPj8fIzhwHntUmSpIKhrQaP7X4egGUnENqWDg9w2lA/TxjaJEkShrZaPLa7CFpnLho67ntEBOecOWxPmyRJAgxttXhszwECOGN44ITu8/Izh9nz/GE32ZUkSYa2Ojy++3mWDA/Q3zixX297XptDpJIkydBWg8f2HDihRQht7U12H336+TlolSRJ6mWGtho8tvvACS1CaBto9HH+S07jS4/s5vHd9rZJkvRiZmibY88eGiv2aDuBRQidfuy1Z9MXwa9v+irjbrQrSdKLlqFtjr2wcvTEe9oAlg4P8pbvfhlbHtnD7V96bE7uKUmSeo+hbY61t+iYq9AG8D2vOIN/ft5y3vvn3+Chbz87Z/eVJEm9w9A2xx6dg411J4oIbvqJ17BoqJ+f/dg29h04PGf3liRJvcHQNsce332AsxYPMjTQmNP7vnTJAj7yztfxzX2HuOYTX6HZGp/T+0uSpJOboW2OPbb7wJH91eba97ziTH77x1/NF0ee5vLf+xL//bM7+MzXv8XhpgFOkqRTXf98N+BU8/ieA1y4+sw5v+8ntjx+5PGbX/1S7ntsL/c9tpfxLObPXbz2JXz3iiW8442vmPOfLUmS5l+toS0iLgU+ADSAj2bmeye8PgR8DPgeYDfw9sx8tHztOuBKoAX8UmbeXeWe82m02eKb+w/W1tPW9gNrlvMDa5Yz1hrnH77zHJ/d/m3u2PoEn33gW9z7yB5es3IJr1m5lFevOJ3hQXO5JEmngtr+RY+IBvBB4GJgJ7A1IjZn5vaOalcCezPz3IjYANwEvD0i1gIbgFcBZwOfj4jzymtmuue82H9gjC+OPE0mrDprmIOH6x+yHGj08cqXnc55Lz2Nrz6xj+1PPcO2R/ew+avfBKAvYM13nVaGuCUsGuqnWe71dtpQP4uG+nnm0Bjf3HeQfQfGOHvpQl5+5jCnLxwgM4kIFg81WDw0wK5nR7n/ib3s+PazfNdpC/hHyxexatkiXnL6ApYtGqSvL45qW2YynjCeSWbRlr4IIoqFFZIkaXbq7Ia5EBjJzIcBImIjsB7oDFjrgfeUjzcBvxvFv+jrgY2ZOQo8EhEj5f2ocM+u+1cf+hu+/Pg+oAgna1+2hPse29u1n98XwQUvP4MLXn4GUGzw++Teg+zcd5Cdew/wZ197ik/et3PaewRQZeveof4+RifMoesL6G/0HQlqrRk2AY4ywPWVAa5vkgwXxDHXTGyvJEndtGCgwX3/8eJ5+/l1hrYVwBMdz3cCb5iqTmY2I2I/sKws/9KEa1eUj2e6JwARcRVwVfn0uYjYcRzv4bi8shiwPQt4uls/U3PKz653+dn1Lj+73vWi+uzi+q78mEknqJ+yE54y82bg5vn6+RGxLTPXzdfP1/Hzs+tdfna9y8+ud/nZdU+dW348CZzT8XxlWTZpnYjoB5ZQLEiY6toq95QkSTrl1BnatgJrImJ1RAxSLCzYPKHOZuCK8vFlwD2ZmWX5hogYiojVwBrg3or3lCRJOuXUNjxazlG7BribYnuOWzPzgYi4AdiWmZuBW4Dby1L8ZH0AAAWNSURBVIUGeyhCGGW9OykWGDSBqzOzBTDZPet6Dydo3oZmdcL87HqXn13v8rPrXX52XRJFx5YkSZJOZh5jJUmS1AMMbZIkST3A0DbHIuLSiNgRESMRce18t0cQEedExBciYntEPBAR7yrLz4yIz0XEQ+WfZ5TlERH/o/wM/z4iXtdxryvK+g9FxBVT/UzNrYhoRMRXIuLT5fPVEbGl/IzuKBcmUS5euqMs3xIRqzrucV1ZviMiLpmfd/LiEhFLI2JTRHwjIh6MiO/1e9cbIuJXyr8vvx4RfxQRC/zezT9D2xzqOLrrzcBa4PLySC7Nrybwa5m5FngjcHX5uVwL/EVmrgH+onwOxee3pvzvKuDDUIQ84DcpNnS+EPjN9j84qt27gAc7nt8EvD8zzwX2UhyJBx1H4wHvL+sx4Wi8S4EPld9X1esDwGcy85XAayk+Q793J7mIWAH8ErAuM19NsfCvfdSk37t5ZGibW0eO7srMw0D7mC3No8x8KjO/XD5+luIfjhUUn81tZbXbgB8vH68HPpaFLwFLI+JlwCXA5zJzT2buBT5H8ReRahQRK4G3AB8tnwfwQxRH38Gxn137M90EXFTWP3I0XmY+AnQejacaRMQS4AcpdgkgMw9n5j783vWKfmBhuYfqMPAUfu/mnaFtbk12dNeKKepqHpTd9hcAW4CXZOZT5UvfAl5SPp7qc/TznR+/A/wG0D70dhmwLzOb5fPOz+Goo/GAzqPx/Oy6azWwC/j9cmj7oxGxCL93J73MfBL4b8DjFGFtP3Affu/mnaFNLxoRsRj4Y+CXM/OZztfKTZ3d/+YkExE/CnwnM++b77Zo1vqB1wEfzswLgOd5YSgU8Ht3siqHn9dTBO+zgUXYu3lSMLTNLY/ZOklFxABFYPt4Zn6qLP52OfxC+ed3ynKPUTt5fB/w1oh4lGK6wQ9RzJNaWg7bwNGfw2yPxlN9dgI7M3NL+XwTRYjze3fy+2HgkczclZljwKcovot+7+aZoW1ueczWSaicW3EL8GBmvq/jpc5j1K4A/ndH+U+Xq9neCOwvh3PuBt4UEWeU/yf6prJMNcnM6zJzZWauovg+3ZOZPwV8geLoOzj2s5vN0XiqSWZ+C3giIs4viy6iOOXG793J73HgjRExXP792f7s/N7Ns9qOsXoxmurornlulor/Q3wn8LWIuL8sezfwXuDOiLgSeAz41+VrdwE/QjFp9gDwMwCZuSci/hNFOAe4ITP3dOctaIJ/D2yMiN8GvkI52Z3jOBpPtfpF4OPl/8Q+TPFd6sPv3UktM7dExCbgyxTfl69QHFX1Z/i9m1ceYyVJktQDHB6VJEnqAYY2SZKkHmBokyRJ6gGGNkmSpB5gaJMkSeoBhjZJmqWIuCEifni+2yHpxcUtPyRpFiKi4V5TkuaDPW2SVIqIVRHxjYj4eEQ8GBGbyl3hH42ImyLiy8DbIuIPIuKy8prXR8TfRsRXI+LeiDgtIhoR8V8jYmtE/H1E/Nw8vzVJpwBDmyQd7XzgQ5n5T4BngF8oy3dn5usyc2O7YrnT/x3AuzLztRRnNh4ErqQ4hun1wOuBny2P8ZGk42Zok6SjPZGZf1M+/kPg+8vHd0xS93zgqczcCpCZz2Rmk+J8zJ8uj03bAiyjOHdRko6bZ49K0tEmTvRtP39+FvcI4Bcz04PNJc0Ze9ok6Wgvj4jvLR//JPDFaeruAF4WEa8HKOez9QN3Az8fEQNl+XkRsajORks69RnaJOloO4CrI+JB4Azgw1NVzMzDwNuB/xkRXwU+BywAPgpsB74cEV8HPoIjG5JOkFt+SFIpIlYBn87MV89zUyTpGPa0SZIk9QB72iRJknqAPW2SJEk9wNAmSZLUAwxtkiRJPcDQJkmS1AMMbZIkST3g/wMQ/AZk4DHX9gAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 720x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Price paid for rooms mostly lies below 2000"
      ],
      "metadata": {
        "id": "6l0S3PGccm7U"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Y_YnBZ0RBiVL",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 320
        },
        "outputId": "c05a87b5-5b88-4cab-c998-6bf79e26c5e4"
      },
      "source": [
        "# getting the top 10 most common minimum number of nights to spend\n",
        "plt.figure(figsize = (10, 5))\n",
        "df.minimum_nights.value_counts()[:10].plot(kind = 'bar', rot = 0)\n",
        "plt.show()"
      ],
      "execution_count": 40,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlwAAAEvCAYAAACQQh9CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAW0UlEQVR4nO3dbYyd5X3n8e+vOGm7tIpNmHqR7azRxiKilXjoyBClirawGANVzIsUEe0GC7nyvqBVoo3UOn2xVqFZOW9Kg7RFQsGN6WZDKG2EFVDoyKGqKi0P5jEBB3lCzdoWYDc2pC1qKtL/vpjL6QQ8mRl8rnNmTr4f6ejc9/++zrn/l2Sf+el+OCdVhSRJkvr5mVE3IEmSNO4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktTZilE38JOce+65tX79+lG3IUmSNK8nn3zy76tq4nTblnTgWr9+Pfv37x91G5IkSfNK8vJc2+Y9pZjkgiTPzHp8P8mnk5yTZCrJwfa8qo1PkjuSTCd5Lsmls95raxt/MMnWwUxPkiRpaZs3cFXVi1V1cVVdDPwq8CbwNWAHsK+qNgD72jrANcCG9tgO3AmQ5BxgJ3AZsBHYeSqkSZIkjbPFXjR/JfDdqnoZ2ALsafU9wPVteQtwT814FFiZ5DzgamCqqk5U1UlgCth8xjOQJEla4hYbuG4EvtKWV1fVK235VWB1W14DHJ71miOtNlddkiRprC04cCV5L/Ax4M/fvq1mfgF7IL+CnWR7kv1J9h8/fnwQbylJkjRSiznCdQ3wVFW91tZfa6cKac/HWv0osG7W69a22lz1H1NVd1XVZFVNTkyc9s5KSZKkZWUxgesT/NvpRIC9wKk7DbcCD8yq39TuVrwceKOdenwY2JRkVbtYflOrSZIkjbUFfQ9XkrOBq4D/Nqu8C7gvyTbgZeCGVn8IuBaYZuaOxpsBqupEktuAJ9q4W6vqxBnPQJIkaYnLzOVXS9Pk5GT5xaeSJGk5SPJkVU2ebpu/pShJktSZgUuSJKmzJf1biu/W+h0PDnV/h3ZdN9T9SZKk5cUjXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSpMwOXJElSZwYuSZKkzgxckiRJnRm4JEmSOjNwSZIkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjpbUOBKsjLJ/Um+k+RAkg8nOSfJVJKD7XlVG5skdySZTvJckktnvc/WNv5gkq29JiVJkrSULPQI1xeAb1TVh4CLgAPADmBfVW0A9rV1gGuADe2xHbgTIMk5wE7gMmAjsPNUSJMkSRpn8wauJO8DPgrcDVBV/1JVrwNbgD1t2B7g+ra8BbinZjwKrExyHnA1MFVVJ6rqJDAFbB7obCRJkpaghRzhOh84DvxpkqeTfDHJ2cDqqnqljXkVWN2W1wCHZ73+SKvNVZckSRprCwlcK4BLgTur6hLgn/i304cAVFUBNYiGkmxPsj/J/uPHjw/iLSVJkkZqIYHrCHCkqh5r6/czE8Bea6cKac/H2vajwLpZr1/banPVf0xV3VVVk1U1OTExsZi5SJIkLUnzBq6qehU4nOSCVroSeAHYC5y603Ar8EBb3gvc1O5WvBx4o516fBjYlGRVu1h+U6tJkiSNtRULHPc7wJeTvBd4CbiZmbB2X5JtwMvADW3sQ8C1wDTwZhtLVZ1IchvwRBt3a1WdGMgsJEmSlrAFBa6qegaYPM2mK08ztoBb5nif3cDuxTQoSZK03PlN85IkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSpMwOXJElSZwYuSZKkzgxckiRJnRm4JEmSOjNwSZIkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktTZggJXkkNJvpXkmST7W+2cJFNJDrbnVa2eJHckmU7yXJJLZ73P1jb+YJKtfaYkSZK0tCzmCNevV9XFVTXZ1ncA+6pqA7CvrQNcA2xoj+3AnTAT0ICdwGXARmDnqZAmSZI0zs7klOIWYE9b3gNcP6t+T814FFiZ5DzgamCqqk5U1UlgCth8BvuXJElaFhYauAr4qyRPJtneaqur6pW2/Cqwui2vAQ7Peu2RVpurLkmSNNZWLHDcr1XV0SS/BEwl+c7sjVVVSWoQDbVAtx3gAx/4wCDeUpIkaaQWdISrqo6252PA15i5Buu1dqqQ9nysDT8KrJv18rWtNlf97fu6q6omq2pyYmJicbORJElaguYNXEnOTvKLp5aBTcC3gb3AqTsNtwIPtOW9wE3tbsXLgTfaqceHgU1JVrWL5Te1miRJ0lhbyCnF1cDXkpwa/3+q6htJngDuS7INeBm4oY1/CLgWmAbeBG4GqKoTSW4Dnmjjbq2qEwObiSRJ0hI1b+CqqpeAi05T/x5w5WnqBdwyx3vtBnYvvk1JkqTly2+alyRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1tmLUDWjx1u94cKj7O7TruqHuT5KkceMRLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1tuDAleSsJE8n+XpbPz/JY0mmk3w1yXtb/Wfb+nTbvn7We3y21V9McvWgJyNJkrQULeYI16eAA7PWPw/cXlUfBE4C21p9G3Cy1W9v40hyIXAj8MvAZuBPkpx1Zu1LkiQtfQsKXEnWAtcBX2zrAa4A7m9D9gDXt+UtbZ22/co2fgtwb1X9oKr+DpgGNg5iEpIkSUvZQo9w/THwu8C/tvX3A69X1Vtt/Qiwpi2vAQ4DtO1vtPE/qp/mNZIkSWNr3sCV5DeAY1X15BD6Icn2JPuT7D9+/PgwdilJktTVQo5wfQT4WJJDwL3MnEr8ArAyyYo2Zi1wtC0fBdYBtO3vA743u36a1/xIVd1VVZNVNTkxMbHoCUmSJC018wauqvpsVa2tqvXMXPT+zar6L8AjwMfbsK3AA215b1unbf9mVVWr39juYjwf2AA8PrCZSJIkLVEr5h8yp98D7k3yh8DTwN2tfjfwZ0mmgRPMhDSq6vkk9wEvAG8Bt1TVD89g/5IkScvCogJXVf018Ndt+SVOc5dhVf0z8JtzvP5zwOcW26QkSdJy5jfNS5IkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSpMwOXJElSZwYuSZKkzgxckiRJnRm4JEmSOjNwSZIkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmfzBq4kP5fk8STPJnk+yR+0+vlJHksyneSrSd7b6j/b1qfb9vWz3uuzrf5ikqt7TUqSJGkpWcgRrh8AV1TVRcDFwOYklwOfB26vqg8CJ4Ftbfw24GSr397GkeRC4Ebgl4HNwJ8kOWuQk5EkSVqK5g1cNeMf2+p72qOAK4D7W30PcH1b3tLWaduvTJJWv7eqflBVfwdMAxsHMgtJkqQlbEHXcCU5K8kzwDFgCvgu8HpVvdWGHAHWtOU1wGGAtv0N4P2z66d5jSRJ0thaUOCqqh9W1cXAWmaOSn2oV0NJtifZn2T/8ePHe+1GkiRpaBZ1l2JVvQ48AnwYWJlkRdu0Fjjalo8C6wDa9vcB35tdP81rZu/jrqqarKrJiYmJxbQnSZK0JC3kLsWJJCvb8s8DVwEHmAleH2/DtgIPtOW9bZ22/ZtVVa1+Y7uL8XxgA/D4oCYiSZK0VK2YfwjnAXvaHYU/A9xXVV9P8gJwb5I/BJ4G7m7j7wb+LMk0cIKZOxOpqueT3Ae8ALwF3FJVPxzsdCRJkpaeeQNXVT0HXHKa+kuc5i7Dqvpn4DfneK/PAZ9bfJuSJEnLl980L0mS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnC/nxammo1u94cKj7O7TruqHuT5L008cjXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSpMwOXJElSZwYuSZKkzgxckiRJnc0buJKsS/JIkheSPJ/kU61+TpKpJAfb86pWT5I7kkwneS7JpbPea2sbfzDJ1n7TkiRJWjoWcoTrLeAzVXUhcDlwS5ILgR3AvqraAOxr6wDXABvaYztwJ8wENGAncBmwEdh5KqRJkiSNs3kDV1W9UlVPteV/AA4Aa4AtwJ42bA9wfVveAtxTMx4FViY5D7gamKqqE1V1EpgCNg90NpIkSUvQoq7hSrIeuAR4DFhdVa+0Ta8Cq9vyGuDwrJcdabW56pIkSWNtwYEryS8AfwF8uqq+P3tbVRVQg2goyfYk+5PsP378+CDeUpIkaaQWFLiSvIeZsPXlqvrLVn6tnSqkPR9r9aPAulkvX9tqc9V/TFXdVVWTVTU5MTGxmLlIkiQtSQu5SzHA3cCBqvqjWZv2AqfuNNwKPDCrflO7W/Fy4I126vFhYFOSVe1i+U2tJkmSNNZWLGDMR4BPAt9K8kyr/T6wC7gvyTbgZeCGtu0h4FpgGngTuBmgqk4kuQ14oo27tapODGQWkiRJS9i8gauq/hbIHJuvPM34Am6Z4712A7sX06AkSdJy5zfNS5IkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1tmLUDUg/bdbveHCo+zu067qh7k+S9E4e4ZIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSps3kDV5LdSY4l+fas2jlJppIcbM+rWj1J7kgyneS5JJfOes3WNv5gkq19piNJkrT0LOQI15eAzW+r7QD2VdUGYF9bB7gG2NAe24E7YSagATuBy4CNwM5TIU2SJGnczRu4qupvgBNvK28B9rTlPcD1s+r31IxHgZVJzgOuBqaq6kRVnQSmeGeIkyRJGkvv9hqu1VX1Slt+FVjdltcAh2eNO9Jqc9UlSZLG3hlfNF9VBdQAegEgyfYk+5PsP378+KDeVpIkaWTebeB6rZ0qpD0fa/WjwLpZ49a22lz1d6iqu6pqsqomJyYm3mV7kiRJS8e7DVx7gVN3Gm4FHphVv6ndrXg58EY79fgwsCnJqnax/KZWkyRJGnsr5huQ5CvAfwLOTXKEmbsNdwH3JdkGvAzc0IY/BFwLTANvAjcDVNWJJLcBT7Rxt1bV2y/ElyRJGkvzBq6q+sQcm648zdgCbpnjfXYDuxfVnSRJ0hjwm+YlSZI6m/cIlyQt1PodDw51f4d2XTfU/UnSu+URLkmSpM4MXJIkSZ0ZuCRJkjozcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTODFySJEmdGbgkSZI6M3BJkiR1ZuCSJEnqzMAlSZLUmYFLkiSpMwOXJElSZytG3YAkLRfrdzw41P0d2nXdUPcnqR+PcEmSJHVm4JIkSerMwCVJktSZgUuSJKkzA5ckSVJnBi5JkqTO/FoISRLg115IPXmES5IkqTMDlyRJUmcGLkmSpM6GHriSbE7yYpLpJDuGvX9JkqRhG+pF80nOAv4XcBVwBHgiyd6qemGYfUiSfvqM+00B4z6/5W7YdyluBKar6iWAJPcCWwADlyRJOq1xCJPDPqW4Bjg8a/1Iq0mSJI2tVNXwdpZ8HNhcVb/V1j8JXFZVvz1rzHZge1u9AHhxaA3CucDfD3F/w+b8lrdxnt84zw2c33Ln/JavYc/tP1TVxOk2DPuU4lFg3az1ta32I1V1F3DXMJs6Jcn+qpocxb6Hwfktb+M8v3GeGzi/5c75LV9LaW7DPqX4BLAhyflJ3gvcCOwdcg+SJElDNdQjXFX1VpLfBh4GzgJ2V9Xzw+xBkiRp2Ib+W4pV9RDw0LD3u0AjOZU5RM5veRvn+Y3z3MD5LXfOb/laMnMb6kXzkiRJP438aR9JkqTODFxAknVJHknyQpLnk3xq1D0NUpKfS/J4kmfb/P5g1D0NUpLdSY4l+faoe+klyVlJnk7y9VH3MmhJDiX5VpJnkuwfdT+DlOSCNq9Tj+8n+fSo+xqkJCuT3J/kO0kOJPnwqHs6Ez/p8yTJZ5JUknNH0duZOt3ckpyTZCrJwfa8apQ9nom5/ta1G/Ueaz8p+NV2097QGbhmvAV8pqouBC4Hbkly4Yh7GqQfAFdU1UXAxcDmJJePuKdB+hKwedRNdPYp4MCom+jo16vq4qVy+/agVNWLbV4XA78KvAl8bcRtDdoXgG9U1YeAi1j+/06/xGk+T5KsAzYB/2/YDQ3Ql3jn3HYA+6pqA7CvrS9Xc/2t+zxwe1V9EDgJbBtFcwYuoKpeqaqn2vI/MPOBMTbfgF8z/rGtvqc9xubivar6G+DEqPvoJcla4Drgi6PuRWfkSuC7VfXyqBsZlCTvAz4K3A1QVf9SVa+Ptqsz8xM+T24Hfpdl/Nk5x9y2AHva8h7g+qE2NUA/4W/dFcD9rT6yORq43ibJeuAS4LHRdjJY7ZTUM8AxYKqqxmp+Y+6Pmfmg/9dRN9JJAX+V5Mn2SxPj6kbgK6NuYsDOB44Df9pOeX8xydmjbmrQkmwBjlbVs6PupYPVVfVKW34VWD3KZs7U2//WAd8FXq+qt9qQkf2koIFrliS/APwF8Omq+v6o+xmkqvphO62xFtiY5FdG3ZPml+Q3gGNV9eSoe+no16rqUuAaZk7nf3TUDQ1au2bkY8Cfj7qXAVsBXArcWVWXAP/E8j4l9Q5J/h3w+8D/GHUvvdXM1xYs2yN48M6/dcCHRtzSjxi4miTvYSZsfbmq/nLU/fTSDvc/wvhf8zQuPgJ8LMkh4F7giiT/e7QtDVZVHW3Px5i5vmnjaDvq4hrgqap6bdSNDNgR4MisI+b3MxPAxsl/ZOZI3rPt/+Fa4Kkk/36kXQ3Oa0nOA2jPx0bcz0DM+lv3YWBlklPfO/qOnxQcFgMXkCTMXINwoKr+aNT9DFqSiSQr2/LPA1cB3xltV1qIqvpsVa2tqvXMnJL6ZlX91xG3NTBJzk7yi6eWmbkoeRzvNv0E43c6kap6FTic5IJWuhJ4YYQtDVxVfauqfqmq1rf/h0eAS9vcx8FeYGtb3go8MMJezsgcf+sOMBO8Pt6GjWyOBq4ZHwE+yczRg1O3b1876qYG6DzgkSTPMfN7llNVNTZfL5DkK8D/BS5IciTJSO5A0buyGvjbJM8CjwMPVtU3RtzTQLUgeRUwrkfOfwf4cvt8uRj4nyPu54yM8+fJHHPbBVyV5CDwn9v6cjXX37rfA/57kmng/bSbPIbNb5qXJEnqzCNckiRJnRm4JEmSOjNwSZIkdWbgkiRJ6szAJUmS1JmBS5IkqTMDlyRJUmcGLkmSpM7+P5QH/lj9I35LAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 720x360 with 1 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "most customers spend 2 nights "
      ],
      "metadata": {
        "id": "ZrlAFtWFcvKO"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "OeZUEETkBiVO"
      },
      "source": [
        "## 3.2 Bivariate Analysis"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ONWbn9UqBiVP",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 388
        },
        "outputId": "e27af219-2475-47c4-ae56-71067eecfce1"
      },
      "source": [
        "# price by room type\n",
        "df.hist('price', by = 'room_type', rot = 0, figsize = (10, 6))\n",
        "plt.show()"
      ],
      "execution_count": 41,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAnUAAAFzCAYAAABYRv/UAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3de7hdVX3v//dHIqhoJUBKw82goi31VKQRsFprRblphZ7HY6EeCdQaW7HVtudRqG1Rqz3osbV6qlgsUWwRpF5qCihG1PrraUGCInIREzFIYiARBLxVRb+/P+bYuNjsHfbOvqy9Zt6v51nPmnOMMef6zjX3Gvu75phzrlQVkiRJGm0PGnYAkiRJmjmTOkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAZM6SZKkHjCp03ZL8p0kj56ldb03yRtmY12S1EdJXpvkn4YdhxYuk7odSJINSb7fkrGxx99NcdnPJPndwbKqenhV3TQ30Q5XkhuTPG6G67ADlnqs9anPGld2cpJ/n+LyfpnVrFo07AA0736jqj451y+SZKeq+vFcv85cSPIYYKeq+sqwY5Gk7ZFkUVXdM+w4NL88Uifgp98uk7wlybeSfC3JMa3ujcCvAn83eHQvSSV5bJt+b5KzklyS5LvAryfZO8mHkmxt6/vDBwhjcZKLk3w7yRUtuRqL71eSXJnkrvb8KwN1n0nyhiT/0eL71yR7JDkvyd2t/bKB9j+fZE2SO9oRuReMi+M5wCWt7XOSfKGt55Ykrx1Yz7L2HqxM8o0km5P8r1Z3NPCnwG+1mL44rR0iqReS/ELro+5Mcl2S57XylcALgVeN9VutfLr95tjrPCPJxiSvTnIr8J4kuyT529Y/faNN7zKwzEuSrG994eokew/UVZKXJVnX+uS/TPKY1s/eneTCJDvP6pulGTOp06DDgBuBPYE3A+ckSVW9Bvj/gJe3IdeXT7L8bwNvBB4B/Afwr8AXgX2AI4BXJjlqG69/AvA6YDGwvq2LJLsDFwNvB/YA/ga4OMke45Z9UXutxwD/CbwH2B24ATijrWtXYA3wfuBn23LvTHLQwLqOba8H8F3gJGA3umTv95McPy7uXwcOBI4EXp3kWVX1ceCvgA+09+yJ29huST2U5MF0/eAn6PqbPwDOS/L4qjobOA94c+sjfiPJg5h+vzno5+j6vEcBK4HXAIcDBwNPBA4F/qzF9kzgfwMvAJYCNwMXjFvfUcAvt3W8Cjgb+J/AfsATgBOn835o7pnU7Xj+pX1jHHu8ZKDu5qp6dxs2PZfug77XNNb90ar6f1X1E+C/AUuq6vVV9cN27t276ZKoyXykqj7XhgzOo+uIoEum1lXVP1bVPVV1PvBl4DcGln1PVX21qu4CPgZ8tao+2db1z8CTWrvnAhuq6j1tXV8APgT8D4AkDwOeDHwGoKo+U1VfqqqfVNU1wPnAr42L+3VV9d2q+hJdImlHJ+047tOnAu8cqDsceDhwZusHPwVcxOR9xJOZfr856CfAGVX1g6r6Pt2RwNdX1Zaq2kr3pflFre0LgVVV9fmq+gFwOvCUwVENuoTz7qq6DrgW+ERV3TTQzz4JLSieU7fjOX4b59TdOjZRVd9LAl2HNFW3DEw/Cti7dXJjdqI74jeZWwemvzfw2nvTfYscdDPdN9kxtw1Mf3+C+bF1PQo4bFxci4B/bNNHAP/ROjmSHAacSfetdGdgF7okcdDgdt9Ml9BK2jHcp09NcjIwdlHZ3sAt7YvumPF916Dt6TcHba2q/xqYH9933tzKxuo+P1ZRVd9JcnuLbUMrfqB+9eemGJfmiUmdpqqm2eYW4GtVdeAsvPY36Dq7QfsDH9+Odd0C/FtVPXuS+mNp59M17wf+Djimqv4ryd/SDU8P2o/uyOFYXN9o01N5zyT11zeA/ZI8aCCx2x8YuwhrfB8x035z/PrG+s7rBl77G+PqgHtPTdkD2LSdr60FwOFXTdVtwHTuSfc54NvtpN2HJtkpyROSPHk7XvsS4HFJfjvJoiS/BRxEN4wxXRe1db0oyYPb48lJfqHVH8NPz6eD7vzAO1pCdyjdeYPj/XmShyX5ReAU4AOt/DZgWTtPRtKO5wq6UYdXtb7mGXSnjYyduza+X53NfhO600X+LMmSJHsCfwH800DdKUkObhdP/BVwRVVt2M7X0gLgP5sdz7/mvvep+8gUl3sb8Px0V8a+/YEat/Pynkt3XtzXgG8C/wA8croBV9XtbV1/AtxOd8Luc6vqm9uxrm/TXdBwAt031VuBNwG7JHkC8J2q+vrAIi8DXp/k23Qd4oUTrPbf6C7suAx4S1V9opWPDdPenuTzEywnqceq6od0SdwxdH3gO4GTqmrsyP45wEHtfLx/mc1+s3kDsBa4BvgS3XDrG1psnwT+nO6c4s10F5hN9dw9LVCpcoRIAkjyKmDPqnrVFNsvo+t4H+z9oCRJw+Y5ddJPbaC7nYAkSSPHI3XSdvJInSRpITGpkyRJ6gEvlJAkSeoBkzpJmgdJViXZkuTagbLd0/0O8br2vLiVJ8nb2+9yXpPkkOFFLmlUjOzw65577lnLli0bdhiS5tBVV131zapaMuw4ZkOSpwPfAd5XVU9oZW+muw/imUlOAxZX1auTHEv3O6HH0v0m89uq6rBtrd8+UdoxbKtfHNmrX5ctW8batWuHHYakOZRk/M/Djayq+uy439UEOA54Rps+l+43h1/dyt9X3bfuy5PslmRpVW2ebP32idKOYVv9osOvkjQ8ew0karcCe7XpfbjvbwpvZILfC02yMsnaJGu3bt06t5FKWvBM6iRpAWhH5aZ1PkxVnV1Vy6tq+ZIlvRilljQDJnWSNDy3JVkK0J63tPJNwH4D7fbFH1qX9ABM6iRpeFYDK9r0CuCjA+UntatgDwfu2tb5dJIEI3yhxHQsO+3iOVv3hjOfM2frltQfSc6nuyhizyQbgTOAM4ELk7wYuBl4QWt+Cd2Vr+uB7wGnzHvAMzBXfa79rbRtO0RSJ0nDVlUnTlJ1xARtCzh1biOS1DcOv0qSJPXAAyZ1k9wF/f8k+XK70/lHkuzWypcl+X6Sq9vjXQPL/HKSL7U7pL89SVr5hHdUlyRJ0tRN5Ujde4Gjx5WtAZ5QVb8EfAU4faDuq1V1cHv83kD5WcBLgAPbY2ydpwGXVdWBwGVtXpIkSdPwgEldVX0WuGNc2Seq6p42eznd5faTapfq/0xVXd7OFXkfcHyrPo7uTuq05+MnWIUkSZK2YTbOqfsd4GMD8wck+UKSf0vyq61sH7o7oo8ZvDv6ZHdUlyRJ0hTN6OrXJK8B7gHOa0Wbgf2r6vYkvwz8S5JfnOr6qqqSTHpH9SQrgZUA+++///YHLkmS1DPbfaQuycnAc4EXtiFVquoHVXV7m74K+CrwOLo7oQ8O0Q7eHX2yO6rfjz+JI0mSNLHtSuqSHA28CnheVX1voHxJkp3a9KPpLoi4qQ2v3p3k8HbV60nc987pE91RXZIkSVP0gMOvk9wF/XRgF2BNuzPJ5e1K16cDr0/yI+AnwO9V1dhFFi+ju5L2oXTn4I2dhzfZHdUlSZI0RQ+Y1E1yF/RzJmn7IeBDk9StBZ4wQfntTHBHdUmSJE2dvyghSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSUOW5I+SXJfk2iTnJ3lIkgOSXJFkfZIPJNl52HFKWthM6iRpiJLsA/whsLyqngDsBJwAvAl4a1U9FvgW8OLhRSlpFJjUSdLwLQIemmQR8DBgM/BM4IOt/lzg+CHFJmlEmNRJ0hBV1SbgLcDX6ZK5u4CrgDur6p7WbCOwz3AilDQqTOokaYiSLAaOAw4A9gZ2BY6e4rIrk6xNsnbr1q1zGKWkUWBSJ0nD9Szga1W1tap+BHwYeCqwWxuOBdgX2DR+wao6u6qWV9XyJUuWzF/EkhYkkzpJGq6vA4cneViSAEcA1wOfBp7f2qwAPjqk+CSNiEUP3ESSNFeq6ookHwQ+D9wDfAE4G7gYuCDJG1rZObP5ustOu3g2VydpATCpk6Qhq6ozgDPGFd8EHDqEcCSNqCkNvyZZlWRLkmsHynZPsibJuva8uJUnydvbDTOvSXLIwDIrWvt1SVYMlP9yki+1Zd7ehiAkSZI0RVM9p+693P9qrNOAy6rqQOCyNg9wDHBge6wEzoIuCaT7JnoY3bfPM8YSwdbmJQPLTenKL0mSJHWmlNRV1WeBO8YVH0d3Q0y4740xjwPeV53L6a7gWgocBaypqjuq6lvAGuDoVvczVXV5VRXwPrzJpiRJ0rTM5OrXvapqc5u+FdirTe8D3DLQbuymmdsq3zhB+f14TyZJkqSJzcotTdoRtpqNdT3A63hPJkmSpAnMJKm7rQ2d0p63tPJNwH4D7cZumrmt8n0nKJckSdIUzSSpW013Q0y4740xVwMntatgDwfuasO0lwJHJlncLpA4Eri01d2d5PB21etJeJNNSZKkaZnSfeqSnA88A9gzyUa6q1jPBC5M8mLgZuAFrfklwLHAeuB7wCkAVXVHkr8ErmztXl9VYxdfvIzuCtuHAh9rD0mSJE3RlJK6qjpxkqojJmhbwKmTrGcVsGqC8rXAE6YSiyRJku7P336VJEnqAZM6SZKkHjCpkyRJ6gGTOkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAZM6SRqyJLsl+WCSLye5IclTkuyeZE2Sde158bDjlLSwmdRJ0vC9Dfh4Vf088ETgBuA04LKqOhC4rM1L0qRM6iRpiJI8Eng6cA5AVf2wqu4EjgPObc3OBY4fToSSRoVJnSQN1wHAVuA9Sb6Q5B+S7ArsVVWbW5tbgb2GFqGkkWBSJ0nDtQg4BDirqp4EfJdxQ63tN7Vr/IJJViZZm2Tt1q1b5yVYSQuXSZ0kDddGYGNVXdHmP0iX5N2WZClAe94yfsGqOruqllfV8iVLlsxbwJIWJpM6SRqiqroVuCXJ41vREcD1wGpgRStbAXx0COFJGiHbndQleXySqwcedyd5ZZLXJtk0UH7swDKnJ1mf5MYkRw2UH93K1ifxCi9JO5o/AM5Lcg1wMPBXwJnAs5OsA57V5iVpUou2d8GqupGu8yHJTsAm4CPAKcBbq+otg+2THAScAPwisDfwySSPa9XvAJ5NNwxxZZLVVXX99sYmSaOkqq4Glk9QdcR8xyJpdG13UjfOEcBXq+rmJJO1OQ64oKp+AHwtyXrg0Fa3vqpuAkhyQWtrUidJkjRFs3VO3QnA+QPzL09yTZJVA3dB3we4ZaDNxlY2WbkkSZKmaMZJXZKdgecB/9yKzgIeQzc0uxn465m+xsBrefm+JEnSBGbjSN0xwOer6jaAqrqtqn5cVT8B3s1Ph1g3AfsNLLdvK5us/H68fF+SJGlis5HUncjA0OvYfZWa3wSubdOrgROS7JLkAOBA4HPAlcCBSQ5oR/1OaG0lSZI0RTO6UKL9lM2zgZcOFL85ycF0dz/fMFZXVdcluZDuAoh7gFOr6sdtPS8HLgV2AlZV1XUziUuSJGlHM6Okrqq+C+wxruxF22j/RuCNE5RfAlwyk1gkSZJ2ZP6ihCRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJA1Zkp2SfCHJRW3+gCRXJFmf5ANJdh52jJIWPpM6SRq+VwA3DMy/CXhrVT0W+Bbw4qFEJWmkmNRJ0hAl2Rd4DvAPbT7AM4EPtibnAscPJzpJo8SkTpKG62+BVwE/afN7AHdW1T1tfiOwzzACkzRaZpzUJdmQ5EtJrk6ytpXtnmRNknXteXErT5K3t/NErklyyMB6VrT265KsmGlckrTQJXkusKWqrtrO5VcmWZtk7datW2c5OkmjZraO1P16VR1cVcvb/GnAZVV1IHBZmwc4BjiwPVYCZ0GXBAJnAIcBhwJnjCWCktRjTwWel2QDcAHdsOvbgN2SLGpt9gU2TbRwVZ1dVcuravmSJUvmI15JC9hcDb8eR3ceCNz3fJDjgPdV53K6jmspcBSwpqruqKpvAWuAo+coNklaEKrq9Krat6qWAScAn6qqFwKfBp7fmq0APjqkECWNkNlI6gr4RJKrkqxsZXtV1eY2fSuwV5veB7hlYNmxc0UmK5ekHdGrgT9Osp7uHLtzhhyPpBGw6IGbPKCnVdWmJD8LrEny5cHKqqokNQuvQ0saVwLsv//+s7FKSVoQquozwGfa9E10p6JI0pTN+EhdVW1qz1uAj9B1RLe1YVXa85bWfBOw38DiY+eKTFY+/rU8f0SSJGkCM0rqkuya5BFj08CRwLXAarrzQOC+54OsBk5qV8EeDtzVhmkvBY5MsrhdIHFkK5MkSdIUzHT4dS/gI929MlkEvL+qPp7kSuDCJC8GbgZe0NpfAhwLrAe+B5wCUFV3JPlL4MrW7vVVdccMY5MkSdphzCipa+d9PHGC8tuBIyYoL+DUSda1Clg1k3gkSZJ2VP6ihCRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1wGzcfFiSpDm37LSL52zdG858zpytW5ovHqmTJEnqAZM6SZKkHjCpkyRJ6gGTOkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAZM6SRqiJPsl+XSS65Ncl+QVrXz3JGuSrGvPi4cdq6SFzaROkobrHuBPquog4HDg1CQHAacBl1XVgcBlbV6SJmVSJ0lDVFWbq+rzbfrbwA3APsBxwLmt2bnA8cOJUNKo2O6kbhtDBq9NsinJ1e1x7MAypydZn+TGJEcNlB/dytYn8duopB1SkmXAk4ArgL2qanOruhXYa0hhSRoRM/nt17Ehg88neQRwVZI1re6tVfWWwcZtOOEE4BeBvYFPJnlcq34H8GxgI3BlktVVdf0MYpOkkZLk4cCHgFdW1d1J7q2rqkpSEyyzElgJsP/++89XqJIWqO0+UreNIYPJHAdcUFU/qKqvAeuBQ9tjfVXdVFU/BC5obSVph5DkwXQJ3XlV9eFWfFuSpa1+KbBl/HJVdXZVLa+q5UuWLJm/gCUtSLNyTt24IQOAlye5JsmqgSu29gFuGVhsYyubrHyi11mZZG2StVu3bp2N0CVpqNIdkjsHuKGq/magajWwok2vAD4637FJGi0zTurGDxkAZwGPAQ4GNgN/PdPXGOO3Ukk99FTgRcAzx52LfCbw7CTrgGe1eUma1EzOqZtwyKCqbhuofzdwUZvdBOw3sPi+rYxtlEtSr1XVvwOZpPqI+YxF0mibydWvEw4ZjJ0D0vwmcG2bXg2ckGSXJAcABwKfA64EDkxyQJKd6S6mWL29cUmSJO2IZnKkbmzI4EtJrm5lfwqcmORgoIANwEsBquq6JBcC19NdOXtqVf0YIMnLgUuBnYBVVXXdDOKSJEna4Wx3UreNIYNLtrHMG4E3TlB+ybaWkyRJ0rb5ixKSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDM/pFCUmS+mDZaRfP2bo3nPmcOVv3KPK9njseqZMkSeoBj9RJkjSHPDKl+eKROkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAZM6SZKkHlgwSV2So5PcmGR9ktOGHY8kDZv9oqTpWBC3NEmyE/AO4NnARuDKJKur6vrhRiZJw2G/qGGay9uwjKq5ek9m87Y0C+VI3aHA+qq6qap+CFwAHDfkmCRpmOwXJU3LgjhSB+wD3DIwvxE4bHyjJCuBlW32O0lunOL69wS+OaMIJ5E3zcVat8ucbeMC4jb2w3S28VFzGcgC94D94jT7xIX2t2U82zaleObxf9BIvD9D/J+83e/PdsQ8ab+4UJK6Kamqs4Gzp7tckrVVtXwOQlow3MZ+cBs1HdPpExfa+24822Y822Y8E1sow6+bgP0G5vdtZZK0o7JflDQtCyWpuxI4MMkBSXYGTgBWDzkmSRom+0VJ07Ighl+r6p4kLwcuBXYCVlXVdbP4EtMesh1BbmM/uI0C5qRfXGjvu/Fsm/Fsm/FMIFU17BgkSZI0Qwtl+FWSJEkzYFInSZLUA71P6kb1Z3aS7Jfk00muT3Jdkle08t2TrEmyrj0vbuVJ8va2ndckOWRgXSta+3VJVgxrmyaTZKckX0hyUZs/IMkVbVs+0E4SJ8kubX59q182sI7TW/mNSY4azpZMLMluST6Y5MtJbkjylL7txyR/1P5Or01yfpKH9G0/jrL57gdns/+a5bhm3NfMYiyz0i/MYjyz8hmeYQyrkmxJcu1A2dD6ykni+T9tn12T5CNJdhuom7D/mtfPX1X19kF3cvFXgUcDOwNfBA4adlxTjH0pcEibfgTwFeAg4M3Aaa38NOBNbfpY4GNAgMOBK1r57sBN7Xlxm1487O0bt61/DLwfuKjNXwic0KbfBfx+m34Z8K42fQLwgTZ9UNu3uwAHtH2+07C3a2D7zgV+t03vDOzWp/1Id5PcrwEPHdh/J/dtP47qYxj94Gz1X3MQ14z6mlmOZcb9wizGMiuf4VmI4+nAIcC1A2VD6ysniedIYFGbftNAPBP2X/P9+ZuTlS6UB/AU4NKB+dOB04cd13Zuy0fpfgPyRmBpK1sK3Nim/x44caD9ja3+RODvB8rv027YD7p7b10GPBO4qH1Avznwobl3H9JdBfiUNr2otcv4/TrYbtgP4JGts8y48t7sR376ywe7t/1yEXBUn/bjKD8WQj+4vf3XLMcw475mFmOZlX5hFuOZlc/wLMWyjPsmUUPtK8fHM67uN4Hz2vSE/dd8f/76Pvw60c/s7DOkWLZbO7T9JOAKYK+q2tyqbgX2atOTbetCfw/+FngV8JM2vwdwZ1Xd0+YH4713W1r9Xa39Qt7GA4CtwHvasM8/JNmVHu3HqtoEvAX4OrCZbr9cRb/24ygb6vs6w/5rNs1GXzNbZqtfmBWz+BmeCwu5r/wduqOFCyWe3id1Iy/Jw4EPAa+sqrsH66pL+0f2njRJngtsqaqrhh3LHFpEd/j+rKp6EvBduiGEe/VgPy6m+6H5A4C9gV2Bo4calBaEhdJ/LcC+ZkH1C6PyGV5IfWWS1wD3AOcNO5ZBfU/qRvpndpI8mK5DPK+qPtyKb0uytNUvBba08sm2dSG/B08FnpdkA3AB3bDI24DdkozdGHsw3nu3pdU/Eridhb2NG4GNVXVFm/8gXWfep/34LOBrVbW1qn4EfJhu3/ZpP46yobyvs9R/zZbZ6mtmy2z1C7Nltj7Dc2HB9ZVJTgaeC7ywJZpDjWdQ35O6kf2ZnSQBzgFuqKq/GahaDYxdzbOC7lyVsfKT2hVBhwN3tUPWlwJHJlncvo0d2cqGrqpOr6p9q2oZ3b75VFW9EPg08PzWbPw2jm3781v7auUntCuyDgAOBD43T5uxTVV1K3BLkse3oiOA6+nRfqQbsjk8ycPa3+3YNvZmP464ee8HZ7H/mhWz2NfMVjyz1S/Mltn6DM+FBdVXJjmabhj/eVX1vXFxTtR/ze/nb65O1lsoD7orZL5Cd/XJa4YdzzTifhrdYeZrgKvb41i68xYuA9YBnwR2b+0DvKNt55eA5QPr+h1gfXucMuxtm2R7n8FPr0h7dPswrAf+GdillT+kza9v9Y8eWP41bdtvBI4Z9vaM27aDgbVtX/4L3RVZvdqPwOuALwPXAv9IdwVYr/bjKD/mux+czf5rDmKbUV8zi3HMSr8wi/HMymd4hjGcT3dO34/ojma+eJh95STxrKc7R27s7/pdA+0n7L/m8/Pnz4RJkiT1QN+HXyVJknYIJnWSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSZLUAyZ1kiRJPWBSJ0mS1AMmdZIkST1gUidJktQDJnWSJEk9YFInSZLUAyZ1mhVJvpPk0cOOQ5LmW5KTk/z7EF9/Q5JnDev1tXCY1GlCrZP4fkvWbkvy3iQPn6x9VT28qm6ahdetJI+d6XokaTYleVqS/0hyV5I7kvy/JE8edlzSIJM6bctvVNXDgUOA5cCfjW+QZNG8RzVFCzk2SaMjyc8AFwH/F9gd2Ad4HfCDOXitOe23kuw0l+vXcJnU6QFV1SbgY8AT4N6jaacmWQesGyh7bJLDktw62HEk+c0k17TpQ5P8Z5I7k2xO8ndJdm51n22LfLEdIfytVv7cJFe3Zf4jyS9NFusksb0kyfr27Xp1kr0H2v9Kkivbt+8rk/zKQN1nkryhveZ3kvxrkj2SnJfk7tZ+2Sy8xZIWtscBVNX5VfXjqvp+VX2iqq4ZbJTkLUm+leRrSY4ZKD8lyQ1Jvp3kpiQvHah7RpKNSV6d5FbgPUkelOS0JF9NcnuSC5PsPrDMi5Lc3Opes63A2yjLWUkuSfJd4NeT/ELr3+5Mcl2S5w20f2SS9yXZ2l7jz5I8qNWd3I5QvrUte1PrQ09OckuSLUlWzPTN1vYzqdMDSrIfcCzwhYHi44HDgIMG21bVFcB3gWcOFP828P42/WPgj4A9gacARwAva8s+vbV5YhvO/UCSJwGrgJcCewB/D6xOsss2Qr43tiTPBP438AJgKXAzcEHbrt2Bi4G3t3X/DXBxkj0G1nUC8CK6b+aPAf4TeA/dt/UbgDO2EYekfvgK8OMk5yY5JsniCdocBtxI17e9GTgnSVrdFuC5wM8ApwBvTXLIwLI/R9enPApYCfwBXT/2a8DewLeAdwAkOQg4i65f2puu79r3AeL/beCNwCOAK4B/BT4B/Gx7rfOSPL61/b/AI4FHt9c/qcU8uJ3XtNd9P11/+mTgscD/BP5uW6fqaI5VlQ8f93sAG4DvAHfSJULvBB7a6gp45rj2BTy2Tb8BWNWmH0GX5D1qktd5JfCRidbT5s8C/nLcMjcCvzbJ+u4TG3AO8OaB+YcDPwKW0XWKnxu3/H8CJ7fpzwCvGaj7a8pDC8AAABNYSURBVOBjA/O/AVw97H3lw4ePuX8AvwC8F9gI3AOsBvZqdScD6wfaPqz1RT83ybr+BXhFm34G8EPgIQP1NwBHDMwvbf3WIuAvgAsG6nZtyz9rktd6L/C+gflfBW4FHjRQdj7wWmCntq6DBupeCnxmYDvXDdT9t7adew2U3Q4cPOz9taM+PFKnbTm+qnarqkdV1cuq6vsDdbdsY7n3A/+9HU3778Dnq+pmgCSPS3JRG6K9G/grum+2k3kU8CftUP+dSe4E9qP7hjqZwdj2pktKAaiq79B1OvuMr2tubnVjbhuY/v4E834jlXYAVXVDVZ1cVfvSnYqyN/C3A01uHWj7vTb5cIB2dO/ydgrInXQjH4P93taq+q+B+UcBHxno826gG+XYq73uvX1cVX2Xrk/blvF94i1V9ZOBsrF+b0/gwdy3X3ygPpGqsl9cIEzqtL1q0oqq6+k6gmO479ArdEfevgwcWFU/A/wpkPut5KduAd7Yksuxx8Oq6vwpxvYNug4SgCS70g0bbBpf1+zf6iRpQlX1ZbojYE94oLbty+2HgLfQHdHaDbiE+/Z74/vTW4BjxvV7D6nu/ObNdF9sx9b/MLo+bZshD0x/A9hv7Dy5Zqzf+ybdEcFHTVCnEWBSp7nyfuAVwNOBfx4ofwRwN/CdJD8P/P645W6jO5djzLuB30t3AUaS7JrkOUkeMcU4zgdOSXJw61z/CriiqjbQdayPS/LbSRaluzDjILqr3CQJgCQ/n+RPkuzb5vcDTgQun8LiOwO7AFuBe9oFFEc+wDLvAt6Y5FHt9ZYkOa7VfRB4brpbrOwMvJ7p/S+/Avge8KokD07yDLpTSS6oqh8DF7bXfkR7/T8G/mka69cQmdRprpxPd5Ltp6rqmwPl/4vu6N236RK2D4xb7rXAuW3Y4QVVtRZ4CfB3dCcLr6c7r2NKquqTwJ/TfVPeTHexwwmt7na6k5f/hG744lXAc8fFK0nfprtA4Ip2BenlwLV0fcc2VdW3gT+kS5a+Rdf/rX6Axd7W2nwiybfb6x3W1ncdcCrdF+fNbZ0bp7ohVfVDuiTuGLojc+8ETmpHH6G7cOK7wE3Av7fXWTXV9Wu4UjXpKJokSZJGhEfqJEmSesCkTpIkqQdM6iRJknrApE6SJKkHRvYHz/fcc89atmzZsMOQNIeuuuqqb1bVkmHHMQrsE6Udw7b6xZFN6pYtW8batWuHHYakOZRk/C9+aBL2idKOYVv9osOvkiRJPWBSJ0mS1AMmdZIkST1gUidJktQDI3uhxHQsO+3iOVv3hjOfM2frlqS5Yr8o9Y9H6iRJknrApE6SJKkHTOokSZJ6wKROkiSpB0zqJEmSesCkTpIkqQdM6iRJknrApE6SJKkHTOokSZJ6wKROkiSpB0zqJEmSesCkTpIkqQdM6iRJknpgRkldkock+VySLya5LsnrWvkBSa5Isj7JB5Ls3Mp3afPrW/2ygXWd3spvTHLUTOKSJEna0cz0SN0PgGdW1ROBg4GjkxwOvAl4a1U9FvgW8OLW/sXAt1r5W1s7khwEnAD8InA08M4kO80wNkmSpB3GjJK66nynzT64PQp4JvDBVn4ucHybPq7N0+qPSJJWfkFV/aCqvgasBw6dSWySJEk7khmfU5dkpyRXA1uANcBXgTur6p7WZCOwT5veB7gFoNXfBewxWD7BMpLUW0lWJdmS5NqBstcm2ZTk6vY4dpgxShoNM07qqurHVXUwsC/d0bWfn3FUk0iyMsnaJGu3bt06Vy8jSfPpvXSnnYz31qo6uD0umeeYJI2gWbv6taruBD4NPAXYLcmiVrUvsKlNbwL2A2j1jwRuHyyfYJnB1zi7qpZX1fIlS5bMVuiSNDRV9VngjmHHIWn0zfTq1yVJdmvTDwWeDdxAl9w9vzVbAXy0Ta9u87T6T1VVtfIT2tWxBwAHAp+bSWySNOJenuSaNjy7eNjBSFr4Znqkbinw6STXAFcCa6rqIuDVwB8nWU93ztw5rf05wB6t/I+B0wCq6jrgQuB64OPAqVX14xnGJkmj6izgMXR3FdgM/PVEjTwlRdKgRQ/cZHJVdQ3wpAnKb2KCq1er6r+A/zHJut4IvHEm8UhSH1TVbWPTSd4NXDRJu7OBswGWL19e8xOdpIXKX5SQpAUmydKB2d8Erp2srSSNmdGROknSzCQ5H3gGsGeSjcAZwDOSHEx3388NwEuHFqCkkWFSJ0lDVFUnTlB8zgRlkrRNDr9KkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg8sGnYAkqR+WXbaxXOy3g1nPmdO1iv1xXYfqUuyX5JPJ7k+yXVJXtHKd0+yJsm69ry4lSfJ25OsT3JNkkMG1rWitV+XZMXMN0uSJGnHMpPh13uAP6mqg4DDgVOTHAScBlxWVQcCl7V5gGOAA9tjJXAWdEkgcAZwGHAocMZYIihJkqSp2e6krqo2V9Xn2/S3gRuAfYDjgHNbs3OB49v0ccD7qnM5sFuSpcBRwJqquqOqvgWsAY7e3rgkSZJ2RLNyoUSSZcCTgCuAvapqc6u6FdirTe8D3DKw2MZWNlm5JPVeklVJtiS5dqBswtNYJGlbZpzUJXk48CHglVV192BdVRVQM32NgddamWRtkrVbt26drdVK0jC9l/uPTkx2GoskTWpGSV2SB9MldOdV1Ydb8W1tWJX2vKWVbwL2G1h831Y2Wfn9VNXZVbW8qpYvWbJkJqFL0oJQVZ8F7hhXPNlpLJI0qZlc/RrgHOCGqvqbgarVwNgVrCuAjw6Un9Sugj0cuKsN014KHJlkcRtiOLKVSdKOarLTWO7D0QtJg2Zyn7qnAi8CvpTk6lb2p8CZwIVJXgzcDLyg1V0CHAusB74HnAJQVXck+Uvgytbu9VU1/lurJO2QqqqSTHgaS1WdDZwNsHz58lk71UXSaNrupK6q/h3IJNVHTNC+gFMnWdcqYNX2xiJJPXNbkqVVtXncaSySNCl/JkySFp7JTmORpEmZ1EnSECU5H/hP4PFJNrZTV84Enp1kHfCsNi9J2+Rvv0rSEFXViZNU3e80FknaFo/USZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIPmNRJkiT1gEmdJElSD8woqUuyKsmWJNcOlO2eZE2Sde15cStPkrcnWZ/kmiSHDCyzorVfl2TFTGKSJEnaEc30SN17gaPHlZ0GXFZVBwKXtXmAY4AD22MlcBZ0SSBwBnAYcChwxlgiKEk7siQbknwpydVJ1g47HkkL24ySuqr6LHDHuOLjgHPb9LnA8QPl76vO5cBuSZYCRwFrquqOqvoWsIb7J4qStKP69ao6uKqWDzsQSQvbXJxTt1dVbW7TtwJ7tel9gFsG2m1sZZOV30+SlUnWJlm7devW2Y1akiRphM3phRJVVUDN4vrOrqrlVbV8yZIls7VaSVqoCvhEkquSrBx2MJIWtrlI6m5rw6q05y2tfBOw30C7fVvZZOWStKN7WlUdQndO8qlJnj5Y6eiFpEFzkdStBsauYF0BfHSg/KR2FezhwF1tmPZS4Mgki9sFEke2MknaoVXVpva8BfgI3cVkg/WOXki616KZLJzkfOAZwJ5JNtJdxXomcGGSFwM3Ay9ozS8BjgXWA98DTgGoqjuS/CVwZWv3+qoaf/GFJO1QkuwKPKiqvt2mjwReP+SwJC1gM0rqqurESaqOmKBtAadOsp5VwKqZxCJJPbMX8JEk0PXV76+qjw83JEkL2YySOknS3Kiqm4AnDjsOSaPDnwmTJEnqAZM6SZKkHjCpkyRJ6gGTOkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAZM6SZKkHvDmw5IkSQ9g2WkXz8l6N5z5nFlbl0fqJEmSesCkTpIkqQdM6iRJknrApE6SJKkHTOokSZJ6wKROkiSpB7yliSRpJMzVLSVgdm8rMd6oxq3R45E6SZKkHjCpkyRJ6gGTOkmSpB4wqZMkSeoBkzpJkqQeMKmTJEnqAW9pIkna4c3lbUc0f3b0/eiROkmSpB4wqZMkSeqBBZPUJTk6yY1J1ic5bdjxSNKw2S9Kmo4FkdQl2Ql4B3AMcBBwYpKDhhuVJA2P/aKk6VoQSR1wKLC+qm6qqh8CFwDHDTkmSRom+0VJ07JQkrp9gFsG5je2MknaUdkvSpqWkbqlSZKVwMo2+50kN05x0T2Bb85JTG+ai7Vu05xtyzzry3aA2zKXHjXsABayB+gTF9q+nApjnqbt/B80au/zqMUL04h5O/bhpP3iQknqNgH7Dczv28ruo6rOBs6e7sqTrK2q5dsf3sLRl23py3aA26I584D94rb6xFHcl8Y8P0Yt5lGLF4YX80IZfr0SODDJAUl2Bk4AVg85JkkaJvtFSdOyII7UVdU9SV4OXArsBKyqquuGHJYkDY39oqTpWhBJHUBVXQJcMkern/aQ7QLWl23py3aA26I5MsN+cRT3pTHPj1GLedTihSHFnKoaxutKkiRpFi2Uc+okSZI0A71O6kbhJ3aS7Jfk00muT3Jdkle08t2TrEmyrj0vbuVJ8va2TdckOWRgXSta+3VJVgxpe3ZK8oUkF7X5A5Jc0eL9QDvhmyS7tPn1rX7ZwDpOb+U3JjlqSNuxW5IPJvlykhuSPGWE98kftb+ta5Ocn+Qho7pfNDULte9LsirJliTXDpRN+3M1j/HOWv88jzE/JMnnknyxxfy6Vj7tz/w8xz3j/x1DiHlDki8luTrJ2lY23L+Nqurlg+7E4q8CjwZ2Br4IHDTsuCaIcylwSJt+BPAVup8EejNwWis/DXhTmz4W+BgQ4HDgila+O3BTe17cphcPYXv+GHg/cFGbvxA4oU2/C/j9Nv0y4F1t+gTgA236oLavdgEOaPtwpyFsx7nA77bpnYHdRnGf0N2s9mvAQwf2x8mjul98TGmfL9i+D3g6cAhw7UDZtD5X8xzvrPTP8xxzgIe36QcDV7RYpvWZH0LcM/rfMaSYNwB7jisb6t/GUN6IeXqznwJcOjB/OnD6sOOaQtwfBZ4N3AgsbWVLgRvb9N8DJw60v7HVnwj8/UD5fdrNU+z7ApcBzwQuan+83wQWjd8ndFf0PaVNL2rtMn4/Dbabx+14JF0ilHHlo7hPxn6VYPf2Pl8EHDWK+8XHlPf5gu77gGXcN6mb1udqyLFvV/88xHgfBnweOGy6n/l5jnPG/zuG9P5u4P5J3VD/Nvo8/DpyP7HTDiM/ie6b1V5VtblV3Qrs1aYn266FsL1/C7wK+Emb3wO4s6rumSCme+Nt9Xe19gthOw4AtgLvacMB/5BkV0Zwn1TVJuAtwNeBzXTv81WM5n7R1Izavpru52ooZtg/z6s2lHk1sAVYQ3fkdrqf+fk0G/87hqGATyS5Kt2vu8CQ/zb6nNSNlCQPBz4EvLKq7h6sqy6tX9CXKSd5LrClqq4adiyzYBHdENFZVfUk4Lt0h9HvNQr7BKCdz3EcXaK6N7ArcPRQg5ImsVA/V6PWP1fVj6vqYLojYIcCPz/kkCY14v87nlZVhwDHAKcmefpg5TD+Nvqc1E3pp8cWgiQPpuswzquqD7fi25IsbfVL6b5xweTbNeztfSrwvCQbgAvoDqO/Ddgtydj9EAdjujfeVv9I4HaGvx3QfYPaWFVXtPkP0iV5o7ZPAJ4FfK2qtlbVj4AP0+2rUdwvmppR21fT/VzNq1nqn4eiqu4EPk03fDndz/x8ma3/HfOujYRQVVuAj9Al0EP92+hzUjcSP7GTJMA5wA1V9TcDVauBsaslV9CdyzFWflK7kuZw4K52qPdS4Mgki9vRmSNb2byoqtOrat+qWkb3Xn+qql5I16E8f5LtGNu+57f21cpPaFc4HQAcCHxunjYDgKq6FbglyeNb0RHA9YzYPmm+Dhye5GHtb21sW0Zuv2jKRqLvGzDdz9W8mcX+ed4kWZJktzb9ULpzAG9g+p/5eTGL/zvmVZJdkzxibJquf7+WYf9tDOPkwvl60F1t8hW68wleM+x4JonxaXSHZ68Brm6PY+nOEbgMWAd8Eti9tQ/wjrZNXwKWD6zrd4D17XHKELfpGfz0CqZH0/3zXw/8M7BLK39Im1/f6h89sPxr2vbdCBwzpG04GFjb9su/0F29OpL7BHgd8GW6Ducf6a5gHcn94mPK+3xB9n3A+XTndv6I7oj4i7fnczWP8c5a/zyPMf8S8IUW87XAX7TyaX/mhxD7jP53zHOsj6a7svyLwHVjn7Nh/234ixKSJEk90OfhV0mSpB2GSZ0kSVIPmNRJkiT1gEmdJElSD5jUSZIk9YBJnSRJUg+Y1EmSJPWASZ0kSVIP/P/fDfhBR1S1BgAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 720x432 with 4 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "hotel and shared rooms have a wider distribution for their prices "
      ],
      "metadata": {
        "id": "VMkRnAdwc8BP"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "1_r0mB2YBiVT",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "cfaf8aee-2905-455d-aee5-5b8360840eeb"
      },
      "source": [
        "# average price by neighbourhood\n",
        "df.groupby('neighbourhood')['price'].mean().sort_values(ascending = False)"
      ],
      "execution_count": 42,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "neighbourhood\n",
              "Centrum-West                              203.653397\n",
              "Centrum-Oost                              190.534247\n",
              "Zuid                                      178.813243\n",
              "Oud-Noord                                 168.763566\n",
              "De Pijp - Rivierenbuurt                   166.601787\n",
              "IJburg - Zeeburgereiland                  157.723077\n",
              "Westerpark                                151.241140\n",
              "De Baarsjes - Oud-West                    149.376228\n",
              "Oud-Oost                                  144.606957\n",
              "Watergraafsmeer                           141.199125\n",
              "Buitenveldert - Zuidas                    137.690355\n",
              "Oostelijk Havengebied - Indische Buurt    135.101163\n",
              "Noord-Oost                                130.495833\n",
              "Noord-West                                126.318885\n",
              "Bos en Lommer                             122.525304\n",
              "De Aker - Nieuw Sloten                    121.268908\n",
              "Slotervaart                               119.791549\n",
              "Geuzenveld - Slotermeer                   113.937143\n",
              "Osdorp                                    103.418182\n",
              "Gaasperdam - Driemond                      96.317757\n",
              "Bijlmer-Centrum                            91.434343\n",
              "Bijlmer-Oost                               89.696629\n",
              "Name: price, dtype: float64"
            ]
          },
          "metadata": {},
          "execution_count": 42
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "centrum west is highest priced neighbourhool while biljmer oost is the chepeast neighborhood"
      ],
      "metadata": {
        "id": "PgjVtCQ2dQUr"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "icZWqXs3BiVd",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "2a3955ec-1c12-4e2e-9000-68a6f77e60bc"
      },
      "source": [
        "# average price by number of nights\n",
        "df.groupby('minimum_nights')['price'].mean().sort_values(ascending = False)"
      ],
      "execution_count": 43,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "minimum_nights\n",
              "365     3000.000000\n",
              "200      999.000000\n",
              "99       999.000000\n",
              "52       429.000000\n",
              "30       331.551020\n",
              "222      300.000000\n",
              "27       275.000000\n",
              "48       250.000000\n",
              "31       243.750000\n",
              "150      203.000000\n",
              "21       201.761905\n",
              "15       197.888889\n",
              "1000     185.000000\n",
              "240      180.000000\n",
              "28       175.900000\n",
              "7        174.760526\n",
              "300      170.500000\n",
              "180      169.250000\n",
              "3        166.936544\n",
              "14       163.476923\n",
              "38       159.000000\n",
              "4        158.828311\n",
              "45       157.500000\n",
              "5        155.676190\n",
              "1        154.149670\n",
              "60       152.071429\n",
              "2        151.557365\n",
              "24       150.000000\n",
              "22       150.000000\n",
              "6        146.276923\n",
              "59       146.250000\n",
              "40       139.000000\n",
              "9        136.250000\n",
              "41       131.000000\n",
              "20       130.185185\n",
              "1001     130.000000\n",
              "16       129.666667\n",
              "100      127.000000\n",
              "90       126.250000\n",
              "10       125.709677\n",
              "18       125.000000\n",
              "8        120.730769\n",
              "999      120.000000\n",
              "29       120.000000\n",
              "25       118.555556\n",
              "12       118.083333\n",
              "500      110.000000\n",
              "50       110.000000\n",
              "17       109.500000\n",
              "95       105.000000\n",
              "13       104.750000\n",
              "120      104.500000\n",
              "186      100.000000\n",
              "37        95.000000\n",
              "19        93.000000\n",
              "70        90.000000\n",
              "23        89.000000\n",
              "11        83.333333\n",
              "89        77.000000\n",
              "35        45.000000\n",
              "Name: price, dtype: float64"
            ]
          },
          "metadata": {},
          "execution_count": 43
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "most gains seens for rooms that are booked for 365 days and the least being 35 days "
      ],
      "metadata": {
        "id": "vOHP5sCCeO54"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "RAMIxPNBBiVh"
      },
      "source": [
        "## 3.3 Feature Engineering"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "amDK304_BiVi",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 374
        },
        "outputId": "34562298-3f95-4bef-94af-b9646b30b366"
      },
      "source": [
        "# getting the average price per room type\n",
        "\n",
        "avg_price_per_room = df.groupby('room_type')['price'].mean().to_dict()\n",
        "\n",
        "# adding to our dataset\n",
        "\n",
        "df['avg_price_per_room'] = df['room_type'].map(avg_price_per_room)\n",
        "\n",
        "# previewing our modified dataset\n",
        "\n",
        "df.head()"
      ],
      "execution_count": 44,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-ed92e64a-491d-41f3-bcf0-a1d10b527c15\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "      <th>avg_price_per_room</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>3159</td>\n",
              "      <td>Daniel</td>\n",
              "      <td>Oostelijk Havengebied - Indische Buurt</td>\n",
              "      <td>52.36575</td>\n",
              "      <td>4.94142</td>\n",
              "      <td>Private room</td>\n",
              "      <td>59</td>\n",
              "      <td>3</td>\n",
              "      <td>278</td>\n",
              "      <td>2020-02-14</td>\n",
              "      <td>1</td>\n",
              "      <td>169</td>\n",
              "      <td>109.421504</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>59484</td>\n",
              "      <td>Alexander</td>\n",
              "      <td>Centrum-Oost</td>\n",
              "      <td>52.36509</td>\n",
              "      <td>4.89354</td>\n",
              "      <td>Private room</td>\n",
              "      <td>100</td>\n",
              "      <td>1</td>\n",
              "      <td>340</td>\n",
              "      <td>2020-04-09</td>\n",
              "      <td>2</td>\n",
              "      <td>106</td>\n",
              "      <td>109.421504</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>56142</td>\n",
              "      <td>Joan</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.37297</td>\n",
              "      <td>4.88339</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>125</td>\n",
              "      <td>14</td>\n",
              "      <td>5</td>\n",
              "      <td>2020-02-09</td>\n",
              "      <td>1</td>\n",
              "      <td>132</td>\n",
              "      <td>169.179967</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>97647</td>\n",
              "      <td>Flip</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.38761</td>\n",
              "      <td>4.89188</td>\n",
              "      <td>Private room</td>\n",
              "      <td>155</td>\n",
              "      <td>2</td>\n",
              "      <td>217</td>\n",
              "      <td>2020-03-02</td>\n",
              "      <td>1</td>\n",
              "      <td>172</td>\n",
              "      <td>109.421504</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>124245</td>\n",
              "      <td>Edwin</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.36719</td>\n",
              "      <td>4.89092</td>\n",
              "      <td>Private room</td>\n",
              "      <td>75</td>\n",
              "      <td>2</td>\n",
              "      <td>332</td>\n",
              "      <td>2020-03-16</td>\n",
              "      <td>3</td>\n",
              "      <td>210</td>\n",
              "      <td>109.421504</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-ed92e64a-491d-41f3-bcf0-a1d10b527c15')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-ed92e64a-491d-41f3-bcf0-a1d10b527c15 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-ed92e64a-491d-41f3-bcf0-a1d10b527c15');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "   host_id  host_name                           neighbourhood  latitude  \\\n",
              "0     3159     Daniel  Oostelijk Havengebied - Indische Buurt  52.36575   \n",
              "1    59484  Alexander                            Centrum-Oost  52.36509   \n",
              "2    56142       Joan                            Centrum-West  52.37297   \n",
              "3    97647       Flip                            Centrum-West  52.38761   \n",
              "4   124245      Edwin                            Centrum-West  52.36719   \n",
              "\n",
              "   longitude        room_type  price  minimum_nights  number_of_reviews  \\\n",
              "0    4.94142     Private room     59               3                278   \n",
              "1    4.89354     Private room    100               1                340   \n",
              "2    4.88339  Entire home/apt    125              14                  5   \n",
              "3    4.89188     Private room    155               2                217   \n",
              "4    4.89092     Private room     75               2                332   \n",
              "\n",
              "  last_review  calculated_host_listings_count  availability_365  \\\n",
              "0  2020-02-14                               1               169   \n",
              "1  2020-04-09                               2               106   \n",
              "2  2020-02-09                               1               132   \n",
              "3  2020-03-02                               1               172   \n",
              "4  2020-03-16                               3               210   \n",
              "\n",
              "   avg_price_per_room  \n",
              "0          109.421504  \n",
              "1          109.421504  \n",
              "2          169.179967  \n",
              "3          109.421504  \n",
              "4          109.421504  "
            ]
          },
          "metadata": {},
          "execution_count": 44
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6DxMshHtBiVm",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 374
        },
        "outputId": "5d10763f-2b8b-412b-fae9-ff0fdd9dcc5e"
      },
      "source": [
        "# getting the average price per neighbourhood\n",
        "\n",
        "avg_price_per_neighbourhood = df.groupby('neighbourhood').price.transform('mean')\n",
        "\n",
        "# adding to our dataset\n",
        "\n",
        "df['avg_price_per_neighbourhood'] = avg_price_per_neighbourhood\n",
        "\n",
        "# previewing our modified dataset\n",
        "\n",
        "df.head()"
      ],
      "execution_count": 45,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-154ba30c-ae00-4e86-8c61-9680c013e1bd\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "      <th>avg_price_per_room</th>\n",
              "      <th>avg_price_per_neighbourhood</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>3159</td>\n",
              "      <td>Daniel</td>\n",
              "      <td>Oostelijk Havengebied - Indische Buurt</td>\n",
              "      <td>52.36575</td>\n",
              "      <td>4.94142</td>\n",
              "      <td>Private room</td>\n",
              "      <td>59</td>\n",
              "      <td>3</td>\n",
              "      <td>278</td>\n",
              "      <td>2020-02-14</td>\n",
              "      <td>1</td>\n",
              "      <td>169</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>135.101163</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>59484</td>\n",
              "      <td>Alexander</td>\n",
              "      <td>Centrum-Oost</td>\n",
              "      <td>52.36509</td>\n",
              "      <td>4.89354</td>\n",
              "      <td>Private room</td>\n",
              "      <td>100</td>\n",
              "      <td>1</td>\n",
              "      <td>340</td>\n",
              "      <td>2020-04-09</td>\n",
              "      <td>2</td>\n",
              "      <td>106</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>190.534247</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>56142</td>\n",
              "      <td>Joan</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.37297</td>\n",
              "      <td>4.88339</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>125</td>\n",
              "      <td>14</td>\n",
              "      <td>5</td>\n",
              "      <td>2020-02-09</td>\n",
              "      <td>1</td>\n",
              "      <td>132</td>\n",
              "      <td>169.179967</td>\n",
              "      <td>203.653397</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>97647</td>\n",
              "      <td>Flip</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.38761</td>\n",
              "      <td>4.89188</td>\n",
              "      <td>Private room</td>\n",
              "      <td>155</td>\n",
              "      <td>2</td>\n",
              "      <td>217</td>\n",
              "      <td>2020-03-02</td>\n",
              "      <td>1</td>\n",
              "      <td>172</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>124245</td>\n",
              "      <td>Edwin</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.36719</td>\n",
              "      <td>4.89092</td>\n",
              "      <td>Private room</td>\n",
              "      <td>75</td>\n",
              "      <td>2</td>\n",
              "      <td>332</td>\n",
              "      <td>2020-03-16</td>\n",
              "      <td>3</td>\n",
              "      <td>210</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-154ba30c-ae00-4e86-8c61-9680c013e1bd')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-154ba30c-ae00-4e86-8c61-9680c013e1bd button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-154ba30c-ae00-4e86-8c61-9680c013e1bd');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "   host_id  host_name                           neighbourhood  latitude  \\\n",
              "0     3159     Daniel  Oostelijk Havengebied - Indische Buurt  52.36575   \n",
              "1    59484  Alexander                            Centrum-Oost  52.36509   \n",
              "2    56142       Joan                            Centrum-West  52.37297   \n",
              "3    97647       Flip                            Centrum-West  52.38761   \n",
              "4   124245      Edwin                            Centrum-West  52.36719   \n",
              "\n",
              "   longitude        room_type  price  minimum_nights  number_of_reviews  \\\n",
              "0    4.94142     Private room     59               3                278   \n",
              "1    4.89354     Private room    100               1                340   \n",
              "2    4.88339  Entire home/apt    125              14                  5   \n",
              "3    4.89188     Private room    155               2                217   \n",
              "4    4.89092     Private room     75               2                332   \n",
              "\n",
              "  last_review  calculated_host_listings_count  availability_365  \\\n",
              "0  2020-02-14                               1               169   \n",
              "1  2020-04-09                               2               106   \n",
              "2  2020-02-09                               1               132   \n",
              "3  2020-03-02                               1               172   \n",
              "4  2020-03-16                               3               210   \n",
              "\n",
              "   avg_price_per_room  avg_price_per_neighbourhood  \n",
              "0          109.421504                   135.101163  \n",
              "1          109.421504                   190.534247  \n",
              "2          169.179967                   203.653397  \n",
              "3          109.421504                   203.653397  \n",
              "4          109.421504                   203.653397  "
            ]
          },
          "metadata": {},
          "execution_count": 45
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "5cE9g8rHBiVp",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "faec84f5-e9ef-4a46-a50d-fdf608dd55fb"
      },
      "source": [
        "# encoding 'room_type'\n",
        "# YOUR CODE HERE\n",
        "# trying nominal encoding\n",
        "# sort the dictionary of average price per room type based on values\n",
        "sorted(avg_price_per_room.items(), key=lambda x: x[1])"
      ],
      "execution_count": 46,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "[('Private room', 109.42150414641121),\n",
              " ('Shared room', 123.0),\n",
              " ('Entire home/apt', 169.17996693718064),\n",
              " ('Hotel room', 245.85344827586206)]"
            ]
          },
          "metadata": {},
          "execution_count": 46
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# assign the numbers based on the average values\n",
        "room_type_map = {'Private room':1,'Shared room':2,'Entire home/apt':3,'Hotel room':4}\n",
        "\n",
        "# create a new column in the dataframe\n",
        "df['room_type_encode'] = df['room_type'].map(room_type_map)\n",
        "df.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 374
        },
        "id": "YkSo-OpNFP76",
        "outputId": "be374506-9bb2-4a59-8760-159bcaaed2da"
      },
      "execution_count": 47,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-b6836144-1f3e-412a-9481-ba18f248f42e\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>host_id</th>\n",
              "      <th>host_name</th>\n",
              "      <th>neighbourhood</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>room_type</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>last_review</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "      <th>avg_price_per_room</th>\n",
              "      <th>avg_price_per_neighbourhood</th>\n",
              "      <th>room_type_encode</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>3159</td>\n",
              "      <td>Daniel</td>\n",
              "      <td>Oostelijk Havengebied - Indische Buurt</td>\n",
              "      <td>52.36575</td>\n",
              "      <td>4.94142</td>\n",
              "      <td>Private room</td>\n",
              "      <td>59</td>\n",
              "      <td>3</td>\n",
              "      <td>278</td>\n",
              "      <td>2020-02-14</td>\n",
              "      <td>1</td>\n",
              "      <td>169</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>135.101163</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>59484</td>\n",
              "      <td>Alexander</td>\n",
              "      <td>Centrum-Oost</td>\n",
              "      <td>52.36509</td>\n",
              "      <td>4.89354</td>\n",
              "      <td>Private room</td>\n",
              "      <td>100</td>\n",
              "      <td>1</td>\n",
              "      <td>340</td>\n",
              "      <td>2020-04-09</td>\n",
              "      <td>2</td>\n",
              "      <td>106</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>190.534247</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>56142</td>\n",
              "      <td>Joan</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.37297</td>\n",
              "      <td>4.88339</td>\n",
              "      <td>Entire home/apt</td>\n",
              "      <td>125</td>\n",
              "      <td>14</td>\n",
              "      <td>5</td>\n",
              "      <td>2020-02-09</td>\n",
              "      <td>1</td>\n",
              "      <td>132</td>\n",
              "      <td>169.179967</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>97647</td>\n",
              "      <td>Flip</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.38761</td>\n",
              "      <td>4.89188</td>\n",
              "      <td>Private room</td>\n",
              "      <td>155</td>\n",
              "      <td>2</td>\n",
              "      <td>217</td>\n",
              "      <td>2020-03-02</td>\n",
              "      <td>1</td>\n",
              "      <td>172</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>124245</td>\n",
              "      <td>Edwin</td>\n",
              "      <td>Centrum-West</td>\n",
              "      <td>52.36719</td>\n",
              "      <td>4.89092</td>\n",
              "      <td>Private room</td>\n",
              "      <td>75</td>\n",
              "      <td>2</td>\n",
              "      <td>332</td>\n",
              "      <td>2020-03-16</td>\n",
              "      <td>3</td>\n",
              "      <td>210</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-b6836144-1f3e-412a-9481-ba18f248f42e')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-b6836144-1f3e-412a-9481-ba18f248f42e button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-b6836144-1f3e-412a-9481-ba18f248f42e');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "   host_id  host_name                           neighbourhood  latitude  \\\n",
              "0     3159     Daniel  Oostelijk Havengebied - Indische Buurt  52.36575   \n",
              "1    59484  Alexander                            Centrum-Oost  52.36509   \n",
              "2    56142       Joan                            Centrum-West  52.37297   \n",
              "3    97647       Flip                            Centrum-West  52.38761   \n",
              "4   124245      Edwin                            Centrum-West  52.36719   \n",
              "\n",
              "   longitude        room_type  price  minimum_nights  number_of_reviews  \\\n",
              "0    4.94142     Private room     59               3                278   \n",
              "1    4.89354     Private room    100               1                340   \n",
              "2    4.88339  Entire home/apt    125              14                  5   \n",
              "3    4.89188     Private room    155               2                217   \n",
              "4    4.89092     Private room     75               2                332   \n",
              "\n",
              "  last_review  calculated_host_listings_count  availability_365  \\\n",
              "0  2020-02-14                               1               169   \n",
              "1  2020-04-09                               2               106   \n",
              "2  2020-02-09                               1               132   \n",
              "3  2020-03-02                               1               172   \n",
              "4  2020-03-16                               3               210   \n",
              "\n",
              "   avg_price_per_room  avg_price_per_neighbourhood  room_type_encode  \n",
              "0          109.421504                   135.101163                 1  \n",
              "1          109.421504                   190.534247                 1  \n",
              "2          169.179967                   203.653397                 3  \n",
              "3          109.421504                   203.653397                 1  \n",
              "4          109.421504                   203.653397                 1  "
            ]
          },
          "metadata": {},
          "execution_count": 47
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZQkBcgN9BiVr",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 288
        },
        "outputId": "e8d49d35-1ab0-4eb6-cfec-a10b54b079c4"
      },
      "source": [
        "# dropping columns not required in preparation for modeling\n",
        "# YOUR CODE HERE\n",
        "df.drop(columns=['host_id','host_name','neighbourhood','room_type','last_review'],inplace=True)\n",
        "print(df.shape)\n",
        "df.head()"
      ],
      "execution_count": 48,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "(17075, 10)\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "\n",
              "  <div id=\"df-05eb7e23-b2f2-4897-86f6-d5983e660a07\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>price</th>\n",
              "      <th>minimum_nights</th>\n",
              "      <th>number_of_reviews</th>\n",
              "      <th>calculated_host_listings_count</th>\n",
              "      <th>availability_365</th>\n",
              "      <th>avg_price_per_room</th>\n",
              "      <th>avg_price_per_neighbourhood</th>\n",
              "      <th>room_type_encode</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>52.36575</td>\n",
              "      <td>4.94142</td>\n",
              "      <td>59</td>\n",
              "      <td>3</td>\n",
              "      <td>278</td>\n",
              "      <td>1</td>\n",
              "      <td>169</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>135.101163</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>52.36509</td>\n",
              "      <td>4.89354</td>\n",
              "      <td>100</td>\n",
              "      <td>1</td>\n",
              "      <td>340</td>\n",
              "      <td>2</td>\n",
              "      <td>106</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>190.534247</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>52.37297</td>\n",
              "      <td>4.88339</td>\n",
              "      <td>125</td>\n",
              "      <td>14</td>\n",
              "      <td>5</td>\n",
              "      <td>1</td>\n",
              "      <td>132</td>\n",
              "      <td>169.179967</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>52.38761</td>\n",
              "      <td>4.89188</td>\n",
              "      <td>155</td>\n",
              "      <td>2</td>\n",
              "      <td>217</td>\n",
              "      <td>1</td>\n",
              "      <td>172</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>52.36719</td>\n",
              "      <td>4.89092</td>\n",
              "      <td>75</td>\n",
              "      <td>2</td>\n",
              "      <td>332</td>\n",
              "      <td>3</td>\n",
              "      <td>210</td>\n",
              "      <td>109.421504</td>\n",
              "      <td>203.653397</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-05eb7e23-b2f2-4897-86f6-d5983e660a07')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-05eb7e23-b2f2-4897-86f6-d5983e660a07 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-05eb7e23-b2f2-4897-86f6-d5983e660a07');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ],
            "text/plain": [
              "   latitude  longitude  price  minimum_nights  number_of_reviews  \\\n",
              "0  52.36575    4.94142     59               3                278   \n",
              "1  52.36509    4.89354    100               1                340   \n",
              "2  52.37297    4.88339    125              14                  5   \n",
              "3  52.38761    4.89188    155               2                217   \n",
              "4  52.36719    4.89092     75               2                332   \n",
              "\n",
              "   calculated_host_listings_count  availability_365  avg_price_per_room  \\\n",
              "0                               1               169          109.421504   \n",
              "1                               2               106          109.421504   \n",
              "2                               1               132          169.179967   \n",
              "3                               1               172          109.421504   \n",
              "4                               3               210          109.421504   \n",
              "\n",
              "   avg_price_per_neighbourhood  room_type_encode  \n",
              "0                   135.101163                 1  \n",
              "1                   190.534247                 1  \n",
              "2                   203.653397                 3  \n",
              "3                   203.653397                 1  \n",
              "4                   203.653397                 1  "
            ]
          },
          "metadata": {},
          "execution_count": 48
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "10 columns remaining"
      ],
      "metadata": {
        "id": "x9pXgVdAfR0P"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "l1ciT2WtBiVv"
      },
      "source": [
        "# <font color='#2F4F4F'>4. Data Modeling</font>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "p5etKU12BiVv"
      },
      "source": [
        "# split into features (X) and label (Y)\n",
        "# YOUR CODE HERE\n",
        "X = df.drop('price',axis=1).values\n",
        "y = df['price'].values"
      ],
      "execution_count": 49,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6HBMvY_IBiVy",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "4653aa4c-f953-4998-f083-62acb5d27471"
      },
      "source": [
        "# split into 70-30 train and test sets\n",
        "# YOUR CODE HERE\n",
        "from sklearn.model_selection import train_test_split\n",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)\n",
        "\n",
        "#confirm size of datasets\n",
        "print(df.shape)\n",
        "print(X_train.shape)\n",
        "print(X_test.shape)\n",
        "print(y_train.shape)\n",
        "print(y_test.shape)"
      ],
      "execution_count": 50,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "(17075, 10)\n",
            "(11952, 9)\n",
            "(5123, 9)\n",
            "(11952,)\n",
            "(5123,)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "FYjh75alBiV0"
      },
      "source": [
        "# scaling our features\n",
        "\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "scaler = StandardScaler()\n",
        "scaler.fit(X_train)\n",
        "X_train = scaler.transform(X_train)\n",
        "X_test = scaler.transform(X_test)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "hxoyP6JvBiV3"
      },
      "source": [
        "For purposes of simplicity, we will work with the following regressors:\n",
        "- Decision Tree Regressor\n",
        "- Random Forest Regressor"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "es4RooNMBiV4"
      },
      "source": [
        "## 4.1 Normal Modeling"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "9oqDHFgQBiV4",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "69fd2a4b-bc0a-427c-fc1e-493b445bed92"
      },
      "source": [
        "# loading our regressors\n",
        "\n",
        "from sklearn.tree import DecisionTreeRegressor\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "\n",
        "# import the scoring metrics\n",
        "from sklearn.metrics import mean_squared_error, r2_score\n",
        "\n",
        "# instantiating our regressors\n",
        "\n",
        "dt_model = DecisionTreeRegressor(random_state=1)\n",
        "rf_model = RandomForestRegressor(random_state=1)\n",
        "\n",
        "# fitting to our training data\n",
        "\n",
        "dt_model.fit(X_train, y_train)\n",
        "rf_model.fit(X_train, y_train)\n",
        "\n",
        "# making predictions\n",
        "\n",
        "dt_pred = dt_model.predict(X_test)\n",
        "rf_pred = rf_model.predict(X_test)\n",
        "\n",
        "# evaluating the RMSE and R2 scores\n",
        "\n",
        "# calculate RMSE\n",
        "dt_rmse = np.sqrt(mean_squared_error(y_test,dt_pred))\n",
        "rf_rmse = np.sqrt(mean_squared_error(y_test,rf_pred))\n",
        "print('Decision Tree RMSE:', dt_rmse)\n",
        "print('Random Forest RMSE:', rf_rmse)\n",
        "\n",
        "# calculate R2 Score\n",
        "dt_r2 = r2_score(y_test,dt_pred)\n",
        "rf_r2 = r2_score(y_test,rf_pred)\n",
        "print('Decision Tree R2 Score:', dt_r2)\n",
        "print('Random Forest R2 Score:', rf_r2)"
      ],
      "execution_count": 51,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree RMSE: 183.24351617182066\n",
            "Random Forest RMSE: 144.758329103297\n",
            "Decision Tree R2 Score: -0.501366651685627\n",
            "Random Forest R2 Score: 0.06304948360548057\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "r2 score is far from 1 hence this models need improvement \n",
        "\n",
        "Random forest has a lower RMSE hence a better fit"
      ],
      "metadata": {
        "id": "CdWYZ83qfqB6"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ePws3a5SBiV8",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "e0646e0b-7b7f-4b32-c5de-f23ed33df1aa"
      },
      "source": [
        "# 10% of target variable's mean\n",
        "\n",
        "mean_price = y.mean()\n",
        "mean_price * 0.1"
      ],
      "execution_count": 53,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "15.788029282576867"
            ]
          },
          "metadata": {},
          "execution_count": 53
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "- Both models give an RMSE that is lower than 10% of the mean price indicating lower accuracy\n"
      ],
      "metadata": {
        "id": "OUQQ3_5YNGis"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Vk7x7utuBiV_"
      },
      "source": [
        "## 4.2 Modeling with Grid Search"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "QPm9K21BBiWA",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "cbd504ba-2204-4ba8-e92c-c65f7b439582"
      },
      "source": [
        "# setting our grid parameters\n",
        "\n",
        "from sklearn.model_selection import GridSearchCV\n",
        "dt_model = DecisionTreeRegressor(random_state=42)\n",
        "rf_model = RandomForestRegressor(random_state=42)\n",
        "\n",
        "# grid parameters for decision trees\n",
        "dt_grid_param = {\n",
        "    'max_depth': [10, 20, 30, 40, 50, None],\n",
        "    'min_samples_leaf': [10, 20, 30, 40, 50]\n",
        "}\n",
        "\n",
        "# grid parameters for random forest\n",
        "rf_grid_param = {\n",
        "    'max_depth': [10, 20, 30, 40, 50,None],\n",
        "    \"n_estimators\": [10, 20, 30, 40, 50],\n",
        "    'min_samples_leaf': [10, 20, 30, 40, 50]\n",
        "}\n",
        "# setting up the Grid Search with our regressors with cv = 5 and n_jobs = -1\n",
        "\n",
        "# decision tree Grid Search\n",
        "gd_sr_dt = GridSearchCV(estimator = dt_model,\n",
        "                     param_grid = dt_grid_param,\n",
        "                     scoring = ['neg_root_mean_squared_error','r2'],\n",
        "                     cv = 5,\n",
        "                     refit = 'neg_root_mean_squared_error',\n",
        "                     verbose = 2,\n",
        "                     n_jobs =-1)\n",
        "# Random forest Grid Search\n",
        "gd_sr_rf = GridSearchCV(estimator = rf_model,\n",
        "                     param_grid = rf_grid_param,\n",
        "                     scoring = ['neg_root_mean_squared_error','r2'],\n",
        "                     cv = 5,\n",
        "                     refit = 'neg_root_mean_squared_error',\n",
        "                     verbose = 2,\n",
        "                     n_jobs =-1)\n",
        "# fitting to training data\n",
        "\n",
        "gd_sr_dt.fit(X_train, y_train)\n",
        "gd_sr_rf.fit(X_train, y_train)\n",
        "\n",
        "# getting the best parameters\n",
        "\n",
        "best_parameters_dt = gd_sr_dt.best_params_\n",
        "best_parameters_rf = gd_sr_rf.best_params_\n",
        "print('Decision Tree Best Parameters')\n",
        "print(best_parameters_dt)\n",
        "print('Random Forest Best Parameters')\n",
        "print(best_parameters_rf)"
      ],
      "execution_count": 54,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Fitting 5 folds for each of 30 candidates, totalling 150 fits\n",
            "Fitting 5 folds for each of 150 candidates, totalling 750 fits\n",
            "Decision Tree Best Parameters\n",
            "{'max_depth': 10, 'min_samples_leaf': 40}\n",
            "Random Forest Best Parameters\n",
            "{'max_depth': 10, 'min_samples_leaf': 10, 'n_estimators': 20}\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# get the score for decision tree\n",
        "best_result_dt = gd_sr_dt.best_score_\n",
        "print(best_result_dt)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "owCIfq6UG_Bz",
        "outputId": "79c89fbc-0503-4bf5-85da-0449e8590e77"
      },
      "execution_count": 55,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "-149.2102154887103\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "The RMSE from decision tree reduced from 183.24 to 149.21 after Grid Search modelling"
      ],
      "metadata": {
        "id": "HoNBKO8FQvKN"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# get the score for random forest\n",
        "best_result_rf = gd_sr_rf.best_score_\n",
        "print(best_result_rf)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Sa8tfNP_HJzg",
        "outputId": "971adc79-bc8c-4fdb-8b37-f027d8021223"
      },
      "execution_count": 56,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "-146.07574069462765\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Random forest RMSE increased slightly from 144.47 to 146.07 after Grid search tuning, however random forest remaining the better model"
      ],
      "metadata": {
        "id": "Py5-FGnHQ3wl"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "khsTTDq0BiWD",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "952ee63b-95fc-4625-a72f-376e7a4867b3"
      },
      "source": [
        "# implementing this recommendation\n",
        "\n",
        "# instantiating our regressors with the recommended parameters\n",
        "# YOUR CODE HERE\n",
        "dt_model = DecisionTreeRegressor(random_state=1,max_depth=10, min_samples_leaf=40)\n",
        "rf_model = RandomForestRegressor(random_state=1,max_depth=20, min_samples_leaf=50, n_estimators=20)\n",
        "\n",
        "# fitting to our training data\n",
        "# YOUR CODE HERE\n",
        "dt_model.fit(X_train, y_train)\n",
        "rf_model.fit(X_train, y_train)\n",
        "\n",
        "# making predictions\n",
        "# YOUR CODE HERE\n",
        "dt_pred = dt_model.predict(X_test)\n",
        "rf_pred = rf_model.predict(X_test)\n",
        "\n",
        "# evaluating the RMSE and R2 scores\n",
        "# YOUR CODE HERE\n",
        "# calculate RMSE\n",
        "dt_rmse = np.sqrt(mean_squared_error(y_test,dt_pred))\n",
        "rf_rmse = np.sqrt(mean_squared_error(y_test,rf_pred))\n",
        "print('Decision Tree RMSE:', dt_rmse)\n",
        "print('Random Forest RMSE:', rf_rmse)\n",
        "\n",
        "# calculate R2 Score\n",
        "dt_r2 = r2_score(y_test,dt_pred)\n",
        "rf_r2 = r2_score(y_test,rf_pred)\n",
        "print('Decision Tree R2 Score:', dt_r2)\n",
        "print('Random Forest R2 Score:', rf_r2)"
      ],
      "execution_count": 57,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree RMSE: 146.32654059404936\n",
            "Random Forest RMSE: 143.60690636194903\n",
            "Decision Tree R2 Score: 0.042638976484545954\n",
            "Random Forest R2 Score: 0.07789540772411063\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Random forest RMSE reduced from 146.07 to 143.60 after using the the best parameters from the Grid search tuning"
      ],
      "metadata": {
        "id": "D4-5LaUo3Tcz"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The RMSE from decision tree reduced from 183.24 to 146.32 after using the the best parameters from the Grid search tuning"
      ],
      "metadata": {
        "id": "ktS4ID3H3iXV"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "YuFQMJceBiWF"
      },
      "source": [
        "## 4.3 Modeling with Random Search"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Tht4XME9BiWF",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "dc5ebda6-35d8-4171-f33f-fc77862e40e5"
      },
      "source": [
        "# setting up our parameters and the respective distributions to sample from\n",
        "# YOUR CODE HERE\n",
        "from scipy.stats import randint as sp_randint\n",
        "# grid parameters for decision trees\n",
        "dt_random_param = {\n",
        "    'max_depth': [10, 20, 30, 40, 50, None],\n",
        "    'min_samples_leaf': sp_randint(1, 50)\n",
        "}\n",
        "# grid parameters for random forest\n",
        "rf_random_param = {\n",
        "    'max_depth': [10, 20, 30, 40, 50,None],\n",
        "    \"n_estimators\": sp_randint(1, 50),\n",
        "    'min_samples_leaf': sp_randint(1, 50)\n",
        "}\n",
        "\n",
        "# setting up Randomized Search for each regressor   with cv = 5\n",
        "# YOUR CODE HERE\n",
        "from sklearn.model_selection import RandomizedSearchCV \n",
        "dt_model = DecisionTreeRegressor(random_state=42)\n",
        "rf_model = RandomForestRegressor(random_state=42)\n",
        "\n",
        "random_dt = RandomizedSearchCV(dt_model, \n",
        "                               dt_random_param, \n",
        "                               cv = 5,\n",
        "                               scoring = ['neg_root_mean_squared_error','r2'],\n",
        "                               refit = 'neg_root_mean_squared_error',\n",
        "                               n_jobs=-1,\n",
        "                               random_state=1\n",
        "                               )\n",
        "random_rf = RandomizedSearchCV(rf_model,                                \n",
        "                               rf_random_param, \n",
        "                               cv = 5,\n",
        "                               scoring = ['neg_root_mean_squared_error','r2'],\n",
        "                               refit = 'neg_root_mean_squared_error',\n",
        "                               n_jobs=-1,\n",
        "                               random_state=1\n",
        "                               )\n",
        "\n",
        "# fitting to training data\n",
        "# YOUR CODE HERE\n",
        "random_dt.fit(X_train, y_train)\n",
        "random_rf.fit(X_train, y_train)\n",
        "\n",
        "# getting the best parameters\n",
        "# YOUR CODE HERE\n",
        "best_parameters_dt = random_dt.best_params_\n",
        "print('Decision Tree Best Parameters (Random Search): ',best_parameters_dt)\n",
        "\n",
        "best_parameters_rf = random_rf.best_params_\n",
        "print('Random Forest Best Parameters (Random Search): ',best_parameters_rf)\n",
        "\n",
        "# And lastly obtaining our accuracy\n",
        "best_result_dt = random_dt.best_score_\n",
        "print('Decision Tree Accuracy (Random Search): ',best_result_dt)\n",
        "\n",
        "best_result_rf = random_rf.best_score_\n",
        "print('Random Forest Accuracy (Random Search): ',best_result_rf)"
      ],
      "execution_count": 58,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree Best Parameters (Random Search):  {'max_depth': None, 'min_samples_leaf': 44}\n",
            "Random Forest Best Parameters (Random Search):  {'max_depth': 10, 'min_samples_leaf': 10, 'n_estimators': 12}\n",
            "Decision Tree Accuracy (Random Search):  -149.8100962302653\n",
            "Random Forest Accuracy (Random Search):  -146.56249890207636\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Random forest RMSE increased from 146.07 to 146.56 after tuning using Random Search"
      ],
      "metadata": {
        "id": "9O8h9Owt6gZu"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The RMSE from decision tree reduced from 183.24 to 149.81 after tuning using Random Search"
      ],
      "metadata": {
        "id": "F-PudhbQ6zn2"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "oc55zVBiBiWI",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "3e042081-1e70-4e76-fa82-2436c1736ccc"
      },
      "source": [
        "# implementing this recommendation\n",
        "\n",
        "# instantiating our regressors with the recommended parameters\n",
        "# YOUR CODE HERE\n",
        "dt_model = DecisionTreeRegressor(random_state=1,max_depth=None, min_samples_leaf=44)\n",
        "rf_model = RandomForestRegressor(random_state=1,max_depth=50, min_samples_leaf=43, n_estimators=29)\n",
        "\n",
        "# fitting to our training data\n",
        "# YOUR CODE HERE\n",
        "dt_model.fit(X_train, y_train)\n",
        "rf_model.fit(X_train, y_train)\n",
        "\n",
        "# making predictions\n",
        "# YOUR CODE HERE\n",
        "dt_pred = dt_model.predict(X_test)\n",
        "rf_pred = rf_model.predict(X_test)\n",
        "\n",
        "# evaluating the RMSE and R2 scores\n",
        "# YOUR CODE HERE\n",
        "# calculate RMSE\n",
        "dt_rmse = np.sqrt(mean_squared_error(y_test,dt_pred))\n",
        "rf_rmse = np.sqrt(mean_squared_error(y_test,rf_pred))\n",
        "print('Decision Tree RMSE after Random Search:', dt_rmse)\n",
        "print('Random Forest RMSE after Random Search:', rf_rmse)\n",
        "\n",
        "# calculate R2 Score\n",
        "dt_r2 = r2_score(y_test,dt_pred)\n",
        "rf_r2 = r2_score(y_test,rf_pred)\n",
        "print('Decision Tree R2 Score after Random Search:', dt_r2)\n",
        "print('Random Forest R2 Score after Random Search:', rf_r2)"
      ],
      "execution_count": 59,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree RMSE after Random Search: 146.7108481231787\n",
            "Random Forest RMSE after Random Search: 143.48160498167485\n",
            "Decision Tree R2 Score after Random Search: 0.03760360564608134\n",
            "Random Forest R2 Score after Random Search: 0.07950383415138562\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Random forest RMSE reduced from 144.47 to 143.48 after using the the best parameters from the Random search tuning"
      ],
      "metadata": {
        "id": "7GQEc2WH7SFK"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The RMSE from decision tree reduced from 183.24 to 146.71 after using the the best parameters from the Random search tuning"
      ],
      "metadata": {
        "id": "gYK6GQmr7ViH"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "H4FCkA4HBiWN"
      },
      "source": [
        "## 4.4 Modeling with Bayesian Optimization"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "17VcumC_BiWO",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "acf9d165-0c34-47f3-efbb-a6a5e3a2e365"
      },
      "source": [
        "# importing the hyperopt library and cross_val_score\n",
        "# YOUR CODE HERE\n",
        "from hyperopt import hp, fmin, tpe, STATUS_OK\n",
        "\n",
        "# setting up a space dictionary\n",
        "# YOUR CODE HERE\n",
        "dt_space = {'max_depth': hp.quniform('max_depth', 10, 1200, 10), \n",
        "        'min_samples_leaf': hp.uniform ('min_samples_leaf', 0, 0.5)}\n",
        "def dt_objective(space): \n",
        "    model = DecisionTreeRegressor(max_depth = space['max_depth'],\n",
        "                                 min_samples_leaf = space['min_samples_leaf'])\n",
        "    # print(classifier)\n",
        "    model.fit(X_train, y_train) \n",
        "    y_pred = model.predict(X_test) \n",
        "    rmse = np.sqrt(mean_squared_error(y_test,y_pred=y_pred))\n",
        "    # We aim to maximize accuracy; in this case we return it as a negative value\n",
        "    return {'loss': -rmse, 'status': STATUS_OK }\n",
        "\n",
        "# 3. Running our bayesian optimizer\n",
        "# ---\n",
        "#\n",
        "best_dt = fmin(fn= dt_objective,                        # the objective function to miminize / the loss function to minimize\n",
        "            space = dt_space,                        # the range of input values to test during optimisation\n",
        "            algo= tpe.suggest,                    # the search algorithm to use\n",
        "            max_evals = 80,                       # the no. of iteration to perform\n",
        "            rstate=np.random.RandomState(42))     # the randomstate for reproducability / to get the same result when we run the code\n",
        "\n",
        "# printing out our outcome\n",
        "best_dt"
      ],
      "execution_count": 60,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "100%|██████████| 80/80 [00:01<00:00, 57.81it/s, best loss: -149.53870223767646]\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "{'max_depth': 370.0, 'min_samples_leaf': 0.4978237863008366}"
            ]
          },
          "metadata": {},
          "execution_count": 60
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# importing the hyperopt library and cross_val_score\n",
        "# YOUR CODE HERE\n",
        "from hyperopt import hp, fmin, tpe, STATUS_OK\n",
        "\n",
        "# setting up a space dictionary\n",
        "# YOUR CODE HERE\n",
        "rf_space = {'max_depth': hp.quniform('max_depth', 10, 1200, 10), \n",
        "        'min_samples_leaf': hp.uniform ('min_samples_leaf', 0, 0.5),\n",
        "        \"n_estimators\": hp.choice ('n_estimators', range(10,1200))\n",
        "        }\n",
        "def rf_objective(space): \n",
        "    model = RandomForestRegressor(max_depth = space['max_depth'],\n",
        "                                 min_samples_leaf = space['min_samples_leaf'],\n",
        "                                  n_estimators = space['n_estimators'])\n",
        "    # print(classifier)\n",
        "    model.fit(X_train, y_train) \n",
        "    y_pred = model.predict(X_test) \n",
        "    rmse = np.sqrt(mean_squared_error(y_test,y_pred=y_pred))\n",
        "    # We aim to maximize accuracy; in this case we return it as a negative value\n",
        "    return {'loss': -rmse, 'status': STATUS_OK }\n",
        "\n",
        "# 3. Running our bayesian optimizer\n",
        "# ---\n",
        "#\n",
        "best_rf = fmin(fn= rf_objective,                        # the objective function to miminize / the loss function to minimize\n",
        "            space = rf_space,                        # the range of input values to test during optimisation\n",
        "            algo= tpe.suggest,                    # the search algorithm to use\n",
        "            max_evals = 80,                       # the no. of iteration to perform\n",
        "            rstate=np.random.RandomState(42))     # the randomstate for reproducability / to get the same result when we run the code\n",
        "\n",
        "# printing out our outcome\n",
        "best_rf"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "aMAeNLkiGKuv",
        "outputId": "e25f760c-88b8-4345-b70a-77eafd8113d1"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "100%|██████████| 80/80 [02:48<00:00,  2.10s/it, best loss: -149.56256628445828]\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "{'max_depth': 430.0,\n",
              " 'min_samples_leaf': 0.3750836823856944,\n",
              " 'n_estimators': 14}"
            ]
          },
          "metadata": {},
          "execution_count": 47
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "PMtZPGJLBiWU",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "b27bb7be-5cdc-4b4a-e6fa-ac4d69b0847e"
      },
      "source": [
        "# implementing this recommendation\n",
        "\n",
        "# instantiating our regressors with the recommended parameters\n",
        "# YOUR CODE HERE\n",
        "dt_model = DecisionTreeRegressor(random_state=1,max_depth=370, min_samples_leaf=0.50)\n",
        "rf_model = RandomForestRegressor(random_state=1,max_depth=650, min_samples_leaf=0.33, n_estimators=123)\n",
        "\n",
        "# fitting to our training data\n",
        "# YOUR CODE HERE\n",
        "dt_model.fit(X_train, y_train)\n",
        "rf_model.fit(X_train, y_train)\n",
        "\n",
        "# making predictions\n",
        "# YOUR CODE HERE\n",
        "dt_pred = dt_model.predict(X_test)\n",
        "rf_pred = rf_model.predict(X_test)\n",
        "\n",
        "# evaluating the RMSE and R2 scores\n",
        "# YOUR CODE HERE\n",
        "# calculate RMSE\n",
        "dt_rmse = np.sqrt(mean_squared_error(y_test,dt_pred))\n",
        "rf_rmse = np.sqrt(mean_squared_error(y_test,rf_pred))\n",
        "print('Decision Tree RMSE after Bayesian Optimization:', dt_rmse)\n",
        "print('Random Forest RMSE after Bayesian Optimization:', rf_rmse)\n",
        "\n",
        "# calculate R2 Score\n",
        "dt_r2 = r2_score(y_test,dt_pred)\n",
        "rf_r2 = r2_score(y_test,rf_pred)\n",
        "print('Decision Tree R2 Score after Bayesian Optimization:', dt_r2)\n",
        "print('Random Forest R2 Score after Bayesian Optimization:', rf_r2)"
      ],
      "execution_count": 61,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree RMSE after Bayesian Optimization: 149.55682362293263\n",
            "Random Forest RMSE after Bayesian Optimization: 149.5587488222559\n",
            "Decision Tree R2 Score after Bayesian Optimization: -9.670713776532835e-05\n",
            "Random Forest R2 Score after Bayesian Optimization: -0.0001224551825498299\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Random forest RMSE increased from 144.47 to 149.55 after using the the best parameters from the Bayesian Optimization"
      ],
      "metadata": {
        "id": "iXp6iKl5Jfw6"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The RMSE from decision tree reduced from 183.24 to 149.55 after using the the best parameters from the Bayesian Optimization"
      ],
      "metadata": {
        "id": "phbgAfi3Jq-F"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "YFoZdpZaBiWX"
      },
      "source": [
        "# <font color='#2F4F4F'>5. Summary of Findings</font>\n",
        "\n",
        "Summarize your findings."
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Our best model is Random Forest that has been optimized using Random Search with an RMSE of 143.48"
      ],
      "metadata": {
        "id": "UL8Y7iQ8J9G-"
      }
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8l8X81g0BiWY"
      },
      "source": [
        "# <font color='#2F4F4F'>6. Recommendations</font>\n",
        "\n",
        "The Airbnb should use random forest predictions to predict rental prices"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "YQD7_7o8BiWZ"
      },
      "source": [
        "# <font color='#2F4F4F'>7. Challenging your Solution</font>\n",
        "\n",
        "### a) Did we have the right question?\n",
        "Yes\n",
        "\n",
        "### b) Did we have the right data?\n",
        "The data was relevant in answering the question \n",
        "\n",
        "### c) What can be done to improve the solution?\n",
        "More hyperparameter tuning can be done on the models to improve on the performance. \n",
        "\n",
        "Alternatively, we can try out other regression analysis models."
      ]
    }
  ]
}

NameError: ignored